core-java-modules/core-java-lang-4/pom.xml
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/compiletimeconstants/Annotations.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/compiletimeconstants/ClassConstants.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/compiletimeconstants/CompileTimeVariables.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/compiletimeconstants/RuntimeVariables.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/compiletimeconstants/SwitchStatement.java

commit 2347e8b21b0d33391e9cb4e79e146756cadfe322
Author: ashleyfrieze <ashley@incredible.org.uk>
Date:   Tue Apr 27 21:40:33 2021 +0100
Minor tweak to pom
commit 0497a9e3e88e9000d335976f311b5e8c1e10675b
Merge: a7cf36704b 58c06a67e3
Author: Daniel Strmecki <daniel.strmecki@gmail.com>
Date:   Mon Apr 26 20:27:13 2021 +0200
Merge branch 'master' into feature/BAEL-4502-compile-time-const
commit a7cf36704bbf94a0afa5a9f46969f8e9774ca683
Author: Daniel Strmecki <daniel.strmecki@gmail.com>
Date:   Mon Apr 26 20:25:47 2021 +0200
BASE-4502: Update POM
commit 86bfe45c4850c31d1505f4bb7a638a3f06621062
Author: Daniel Strmecki <daniel.strmecki@gmail.com>
Date:   Sun Apr 25 20:32:35 2021 +0200
BASE-4502: Revert POM changes and comment out JDK9+ code
commit b538d1cc19c54c0b9ad9022b94fd066603836e26
Author: …

BAEL-4502 - attempt merge of failing PR

---

spring-boot-modules/spring-boot-properties-3/src/main/resources/application.yml
spring-boot-modules/spring-boot-properties-3/src/test/java/com/baeldung/boot/properties/multidocument/StagingMultidocumentFilesIntegrationTest.java

JIRA: http://team.baeldung.com/browse/JAVA-4892

[JAVA-4892] Update Using application.yml vs application.properties in Spring Boot article

---

spring-boot-modules/spring-boot-mvc-3/README.md
spring-boot-modules/spring-boot-mvc-3/src/main/java/com/baeldung/filtersinterceptors/FilterInterceptorApp.java
spring-boot-modules/spring-boot-mvc-3/src/main/java/com/baeldung/filtersinterceptors/HelloConroller.java
spring-boot-modules/spring-boot-mvc-3/src/main/java/com/baeldung/filtersinterceptors/LogFilter.java
spring-boot-modules/spring-boot-mvc-3/src/main/java/com/baeldung/filtersinterceptors/LogInterceptor.java
spring-boot-modules/spring-boot-mvc-3/src/main/java/com/baeldung/filtersinterceptors/WebMvcConfig.java
spring-boot-modules/spring-boot-mvc-3/src/main/resources/templates/hello.html

Pull request for: http://jira.baeldung.com/browse/BAEL-4564

BAEL-4564 - Difference between Interceptor and Filter in Spring MVC

---

core-java-modules/core-java-string-conversions-2/src/test/java/com/baeldung/stringtobigdecimal/StringToBigDecimalConversionUnitTest.java

Adding junit for Converting String to BigDecimal in Java

Code commit for "Converting String to BigDecimal in Java" - Article

---

maven-modules/maven-printing-plugins/pom.xml

Fixes according to the Jira comment.

BAEL-4796 How to display a message in Maven - improvement

---

spring-boot-modules/spring-boot-keycloak/src/main/java/com/baeldung/keycloak/WebController.java
spring-boot-modules/spring-boot-keycloak/src/main/resources/templates/customers.html

As title. I think this is a very valuable addition to the tutorial, since this has been one of the most troublesome things in the past.

Implement a functional logout for spring-boot-keycloak

---

libraries-data-3/README.md
libraries-data-3/log4j.properties
libraries-data-3/pom.xml
libraries-data-3/src/test/java/com/baeldung/kafka/streams/KafkaStreamsLiveTest.java

- Add Kafka Streams vs Kafka Consumer source code

[BAEL-4907] - Kafka Streams vs Kafka Consumer

---

logging-modules/log4j/README.md

BAEL-4724: add link back to article

---

core-java-modules/core-java-regex/src/test/java/com/baeldung/ignore/pattern/metacharacters/IgnoringPatternMetacharactersUnitTest.java

Unit test method names simplified according to Editor's suggestion.

BAEL-4881 - Update IgnoringPatternMetacharactersUnitTest.java

---

core-java-modules/core-java/src/main/java/com/baeldung/uuid/UUIDGenerator.java
core-java-modules/core-java/src/test/java/com/baeldung/uuid/UUIDGeneratorUnitTest.java

Added a new method to generate UUID identifiers for version 5.

[uuid] diegotorres/dtorres.py@gmail.com Added method to generate UUID identifiers for version 5

---

spring-kafka/pom.xml
spring-kafka/src/main/java/com/baeldung/monitoring/LagAnalyzerApplication.java
spring-kafka/src/main/java/com/baeldung/monitoring/Makefile
spring-kafka/src/main/java/com/baeldung/monitoring/README.md
spring-kafka/src/main/java/com/baeldung/monitoring/docker-compose.yml
spring-kafka/src/main/java/com/baeldung/monitoring/service/LagAnalyzerService.java
spring-kafka/src/main/java/com/baeldung/monitoring/service/LiveLagAnalyzerService.java
spring-kafka/src/main/java/com/baeldung/monitoring/simulation/ConsumerSimulator.java
spring-kafka/src/main/java/com/baeldung/monitoring/simulation/KafkaConsumerConfig.java
spring-kafka/src/main/java/com/baeldung/monitoring/simulation/KafkaProducerConfig.java
spring-kafka/src/main/java/com/baeldung/monitoring/simulation/ProducerSimulator.java
spring-kafka/src/main/java/com/baeldung/monitoring/util/MonitoringUtil.java
spring-kafka/src/main/resources/application.properties
spring-kafka/src/test/java/com/baeldung/monitoring/LiveLagAnalyzerServiceLiveTest.java
spring-kafka/src/test/resources/application.yml

Monitor Kafka Consume Lag in Java
- [BAEL-4855](http://jira.baeldung.com/browse/BAEL-4855)

BAEL-4855 | Monitor the Kafka Consume Lag in Java

---

core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/privateconstructors/Employee.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/privateconstructors/PrivateConstructorClass.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/privateconstructors/SingletonClass.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/privateconstructors/StringUtils.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/privateconstructors/ValueTypeClass.java

http://jira.baeldung.com/browse/BAEL-4986

BAEL-4986: Private constructors in Java

---

maven-modules/maven-builder-plugin/pom.xml
maven-modules/maven-builder-plugin/src/main/java/com/baeldung/maven/plugin/MainApp.java
maven-modules/maven-builder-plugin/src/main/newsrc/com/baeldung/database/DataConnection.java
maven-modules/pom.xml

Extra Source Directory in Maven using the build-helper-maven plugin.

Extra source Directory in Maven by sgrverma23

---

core-java-modules/core-java-16/README.md
core-java-modules/core-java-16/pom.xml
core-java-modules/core-java-16/src/test/java/com/baeldung/streams/StreamToImmutableUnitTest.java

BAEL-4969: Improvement: Streams to Immutable Collections

---

core-java-modules/core-java-annotations/src/main/java/com/baeldung/annotations/ClassWithSuppressWarningsNames.java

sample usages of @SuppressWarnings warning names

BAEL-4143: sample usages of @SuppressWarnings warning names

---

core-java-modules/core-java-networking-3/pom.xml
core-java-modules/core-java-networking-3/src/main/java/com/baeldung/ipingivenrange/IPWithGivenRangeCheck.java
core-java-modules/core-java-networking-3/src/test/java/com/baeldung/ipingivenrange/IPWithGivenRangeCheckUnitTest.java

Initial PR : https://github.com/eugenp/tutorials/pull/11009

[BAEL-4478] IP address is in given range or not using java

---

maven-modules/host-maven-repo-example/pom.xml
maven-modules/host-maven-repo-example/src/java/com/baeldung/maven/plugin/MainApp.java
maven-modules/pom.xml

http://jira.baeldung.com/browse/BAEL-4353
Changes done.

Changes for hosting maven repo on github by sgrverma23

---

persistence-modules/core-java-persistence-2/src/main/java/com/baeldung/jdbcautocommit/Person.java
persistence-modules/core-java-persistence-2/src/test/java/com/baeldung/jdbcautocommit/AutoCommitUnitTest.java

Hi @JonCook ,
Please will you review my code for the first draft of : 
JIRA: [[BAEL-4122] - A Quick Guide to Autocommit in JDBC](http://jira.baeldung.com/browse/BAEL-4122)
IP: https://drafts.baeldung.com/wp-admin/post.php?post=110029&action=edit
Thanks
Glen
email: glenjohnsoneng@gmail.com

First Draft - [BAEL-4122] - A Quick Guide to Autocommit in JDBC

---

core-java-modules/core-java-12/pom.xml
core-java-modules/core-java-12/src/main/java/com/baeldung/file/content/comparison/CompareFileContents.java
core-java-modules/core-java-12/src/test/java/com/baeldung/file/content/comparison/CampareFileContentsApacheIOUnitTest.java
core-java-modules/core-java-12/src/test/java/com/baeldung/file/content/comparison/CompareByMemoryMappedFilesUnitTest.java
core-java-modules/core-java-12/src/test/java/com/baeldung/file/content/comparison/CompareFileContentsByBytesUnitTest.java
core-java-modules/core-java-12/src/test/java/com/baeldung/file/content/comparison/CompareFileContentsByLinesUnitTest.java
core-java-modules/core-java-12/src/test/java/com/baeldung/newfeatures/CompactNumbersUnitTest.java
core-java-modules/core-java-12/src/test/java/com/baeldung/newfeatures/FileMismatchUnitTest.java
core-java-modules/core-java-12/src/test/java/com/baeldung/newfeatures/StringUnitTest.java
core-java-modules/core-java-12/src/test/java/com/baeldung/newfeatures/TeeingCollectorUnitTest.java
patterns/simplehexagonalexample/pom.xml
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/DailyQuoteMain.java
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/controller/QuoteCliController.java
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/controller/QuoteRestController.java
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/domain/QuoteOfTheDay.java
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/domain/repository/QuoteOfTheDayFromProvider.java
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/domain/service/QuoteAggregator.java
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/domain/service/QuoteService.java
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/repository/primary/quoteadapter/ProviderQuote.java
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/repository/primary/quoteadapter/ProviderQuoteAdapter.java
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/repository/primary/quoteadapter/ProviderQuoteEnvelope.java
patterns/simplehexagonalexample/src/main/java/com/baeldung/simplehexagonalex/reposity/mock/quoteadapter/MockQuoteAdapter.java
patterns/simplehexagonalexample/src/main/resources/application.properties
patterns/simplehexagonalexample/src/test/java/com/baeldung/simplehexagonalex/repository/primaryQuoteProvider/MockAccessProviderUnitTest.java
patterns/simplehexagonalexample/src/test/java/com/baeldung/simplehexagonalex/repository/primaryQuoteProvider/PrimaryAccessProviderIntegrationTest.java
patterns/simplehexagonalexample/src/test/java/com/baeldung/simplehexagonalex/repository/primaryQuoteProvider/QuoteRequestIntegrationTest.java
patterns/simplehexagonalexample/src/test/resources/application.properties

Hello Grzegorz,
Please review.
Thanks,
M

Core java 12 improvements

---

spring-boot-modules/spring-boot-keycloak/pom.xml

JAVA-5892: Upgrade spring-boot-keycloak to the latest Spring Boot

---

core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/constructors/exception/Animal.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/constructors/exception/Bird.java
core-java-modules/core-java-lang-oop-constructors/src/test/java/com/baeldung/constructors/exception/AnimalUnitTest.java

Draft - https://drafts.baeldung.com/wp-admin/post.php?post=100843&action=edit

[BAEL-4990] Throwing exceptions in constructor

---

spring-boot-modules/spring-boot-security/src/main/java/com/baeldung/annotations/globalmethod/AnnotationSecuredApplication.java
spring-boot-modules/spring-boot-security/src/main/java/com/baeldung/annotations/globalmethod/AnnotationSecuredController.java
spring-boot-modules/spring-boot-security/src/main/java/com/baeldung/annotations/globalmethod/AnnotationSecuredStaticResourceConfig.java
spring-boot-modules/spring-boot-security/src/main/java/com/baeldung/annotations/globalmethod/DifferentClass.java
spring-boot-modules/spring-boot-security/src/main/java/com/baeldung/annotations/websecurity/ConfigSecuredApplication.java
spring-boot-modules/spring-boot-security/src/main/java/com/baeldung/annotations/websecurity/ConfigSecuredController.java
spring-boot-modules/spring-boot-security/src/main/java/com/baeldung/annotations/websecurity/CustomWebSecurityConfig.java
spring-boot-modules/spring-boot-security/src/main/resources/public/hello/baeldung.txt
spring-boot-modules/spring-boot-security/src/test/java/com/baeldung/annotations/globalmethod/GlobalMethodSpringBootIntegrationTest.java
spring-boot-modules/spring-boot-security/src/test/java/com/baeldung/annotations/websecurity/WebSecuritySpringBootIntegrationTest.java

@ashleyfrieze here's the PR for the security annotations article.

BAEL-4914 Code for EnableGlobalMethodSecurity vs EnableWebSecurity

---

spring-cloud/spring-cloud-ribbon-retry/ribbon-client-service/src/test/java/com/baeldung/spring/cloud/ribbon/retry/RibbonRetryFailureManualTest.java
spring-cloud/spring-cloud-ribbon-retry/ribbon-client-service/src/test/java/com/baeldung/spring/cloud/ribbon/retry/RibbonRetrySuccessManualTest.java

expected at live running server to connect to

JAVA-6216 Renamed spring-cloud-ribbon-retry to *ManualTest as they both

---

spring-security-modules/spring-security-web-react/pom.xml

JAVA-6216 Updating frontend maven plugin and removing manually

---

maven-modules/maven-parent-pom-resolution/README.md
maven-modules/maven-parent-pom-resolution/pom.xml
maven-modules/maven-parent-pom-resolution/project-a/pom.xml
maven-modules/maven-parent-pom-resolution/project-a/project-b/pom.xml
maven-modules/maven-parent-pom-resolution/project-a/project-c/pom.xml
maven-modules/maven-parent-pom-resolution/project-a/project-c/project-d/pom.xml
maven-modules/pom.xml

I added some Maven projects (just POMs) that inherit from each other

BAEL-5083: add Maven parent POM resolution samples

---

maven-modules/maven-parent-pom-resolution/aggregator/module1/pom.xml
maven-modules/maven-parent-pom-resolution/aggregator/module2/module3/pom.xml
maven-modules/maven-parent-pom-resolution/aggregator/module2/pom.xml
maven-modules/maven-parent-pom-resolution/aggregator/pom.xml
maven-modules/maven-parent-pom-resolution/pom.xml

This is a second pull request for the JIRA ticket because of the editor's feedback

BAEL-5083: Rename projects to make the example simpler

---

persistence-modules/spring-data-jpa-repo/src/test/java/com/baeldung/boot/daos/InventoryRepositoryIntegrationTest.java

[BAEL-4681] Update "Spring Data – CrudRepository save() Method" article

---

apache-kafka/pom.xml
apache-kafka/src/main/java/com/baeldung/kafka/dto/MessageDto.java
apache-kafka/src/main/java/com/baeldung/kafka/serdes/CustomDeserializer.java
apache-kafka/src/main/java/com/baeldung/kafka/serdes/CustomSerializer.java
apache-kafka/src/test/java/com/baeldung/kafka/serdes/KafkaSerDesLiveTest.java

- Add the dto (including the lombok dependency) and the custom serializers and deserializers

[BAEL-4854] - Custom Serializers in Apache Kafka

---

spring-security-modules/spring-security-saml/src/main/java/com/baeldung/saml/config/SamlSecurityConfig.java
spring-security-modules/spring-security-saml/src/main/resources/application.properties

Added comments to Spring SAML configuration file 
Correction to loading of sso.xml file.

Spring Security SAML - Minor documentation update & File Load Improvement

---

core-java-modules/core-java-os/src/test/java/com/baeldung/example/soundapi/AppUnitTest.java

BAEL 4293 

---

persistence-modules/spring-data-cassandra-reactive/pom.xml
persistence-modules/spring-data-cassandra-reactive/src/main/resources/application.properties

PR for http://team.baeldung.com/browse/JAVA-2801

JAVA-2801: Upgrade spring-data-cassandra-reactive to the latest Spring Boot version

---

persistence-modules/spring-boot-persistence/src/main/resources/persistence-generic-entity.properties

- Added spring.jpa.defer-datasource-initialization so that data creation
can be enabled using data.sql files

JAVA-6454 Changes done as per Spring Boot 2.5 release

---

persistence-modules/spring-data-arangodb/src/live-test/resources/Dockerfile
persistence-modules/spring-data-arangodb/src/live-test/resources/arangodb-setup.js
persistence-modules/spring-data-arangodb/src/live-test/resources/live-test-setup.sh
persistence-modules/spring-data-arangodb/src/main/java/com/baeldung/arangodb/configuration/ArangoDbConfiguration.java
persistence-modules/spring-data-arangodb/src/main/resources/arangodb.properties
persistence-modules/spring-data-arangodb/src/test/java/com/baeldung/arangodb/ArticleRepositoryLiveTest.java

Updating the database user from root to baeldung in ArangoDB Java configuration and properties file.

fix: updating database username to be in sync with the article

---

java-collections-maps-3/src/test/java/com/baeldung/map/hashing/HashMapUpdateUnitTest.java

BAEL-5161 Added tests for updating the value of a key in a HashMap

---

spring-security-modules/spring-security-web-mvc-custom/pom.xml
spring-security-modules/spring-security-web-mvc-custom/src/main/java/com/baeldung/web/interceptor/LoggerInterceptor.java
spring-security-modules/spring-security-web-mvc-custom/src/main/java/com/baeldung/web/interceptor/SessionTimerInterceptor.java
spring-security-modules/spring-security-web-mvc-custom/src/main/java/com/baeldung/web/interceptor/UserInterceptor.java

BAEL-5111: Improve the HandlerInterceptor Article

---

core-java-modules/core-java-string-operations-3/pom.xml
core-java-modules/core-java-string-operations-3/src/test/java/com/baeldung/multipledelimiterssplit/MultipleDelimitersSplitUnitTest.java

BAEL-5195 split string by multiple delimiters

---

core-java-modules/core-java-jndi/pom.xml
core-java-modules/core-java-jndi/src/test/java/com/baeldung/jndi/ldap/auth/JndiLdapAuthManualTest.java
core-java-modules/core-java-jndi/src/test/resources/logback.xml
core-java-modules/core-java-jndi/src/test/resources/users.ldif

Hi Adam Meszaros,
Please will you review this pull request. It contains the code exactly as it was from the previous pull request, but now with the POM.xml indentation problem and conflict with upstream fixed.
JIRA Ticket :
[BAEL-4451] - LDAP Authentication using Pure Java
http://jira.baeldung.com/plugins/servlet/mobile#issue/BAEL-4451
IP : https://drafts.baeldung.com/wp-admin/post.php?post=116422&action=edit
Thanks
Glen Johnson

For 3rd PR (POM fixed) - [BAEL-4451] LDAP Authentication using Pure Java

---

core-java-modules/core-java-string-operations-3/src/test/java/com/baeldung/multipledelimiterssplit/MultipleDelimitersSplitUnitTest.java

BAEL-5195 changed the pattern (removed the OR operator)

BAEL-5195 Modified the regex pattern

---

core-java-modules/core-java-string-algorithms-2/src/test/java/com/baeldung/isuppercase/StringFirstCharacterUppercase.java

BAEL-5227 check if a first letter of a string is uppercase

---

persistence-modules/spring-boot-persistence/src/test/resources/dsrouting-db.sql

http://team.baeldung.com/browse/JAVA-2592

JAVA-2592: Add DROP TABLE IF EXIST clause to avoid SQL exception

---

testing-modules/testing-assertions/src/test/java/com/baeldung/optional/OptionalUnitTest.java

A few tests on how to test a Java Optional

[BAEL-5211] - How to test a Java Optional

---

core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/abstractconstructors/defaultconstructor/AbstractClass.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/abstractconstructors/defaultconstructor/ConcreteClass.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/abstractconstructors/noargs/AbstractClass.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/abstractconstructors/noargs/ConcreteClassA.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/abstractconstructors/noargs/ConcreteClassB.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/abstractconstructors/noargs/Counter.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/abstractconstructors/noargs/SimpleCounter.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/abstractconstructors/parametrized/Car.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/abstractconstructors/parametrized/ElectricCar.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/abstractconstructors/parametrized/FuelCar.java
core-java-modules/core-java-lang-oop-constructors/src/test/java/com/baeldung/abstractconstructors/noargs/AbstractClassUnitTest.java
core-java-modules/core-java-lang-oop-constructors/src/test/java/com/baeldung/abstractconstructors/noargs/CounterUnitTest.java
core-java-modules/core-java-lang-oop-constructors/src/test/java/com/baeldung/abstractconstructors/parametrized/CarUnitTest.java

Adding examples for Abstract class constructors

BAEL-5132 Abstract class constructors examples

---

apache-poi/src/main/java/com/baeldung/poi/excel/cellstyle/CellBordersHandler.java
apache-poi/src/test/java/com/baeldung/poi/excel/cellstyle/CellBorderHandlerUnitTest.java

Excel cell border handling code. Tested with JUnit.

BAEL-5199: Excel Cell Border Example

---

lombok/src/main/java/com/baeldung/lombok/valvar/ValExample.java
lombok/src/main/java/com/baeldung/lombok/valvar/VarExample.java
lombok/src/main/java/com/baeldung/lombok/valvar/lombok.config
lombok/src/test/java/com/baeldung/lombok/valvar/ValExampleUnitTest.java
lombok/src/test/java/com/baeldung/lombok/valvar/VarExampleUnitTest.java

- Add val and var examples
- Add unit tests
- Include lombok config to demonstrate flagUsage

[BAEL-5137]-Declaring-val-var-lombok

---

core-java-modules/core-java-string-conversions-2/README.md
core-java-modules/core-java-string-conversions-2/src/test/java/com/baeldung/bytebuffertostring/ByteArrayToStringUnitTest.java

BAEL-5147 : convert ByteBuffer to String

---

core-java-modules/core-java-regex/src/test/java/com/baeldung/regex/matcher/MatcherUnitTest.java

BAEL-4882: pattern.matcher() vs pattern.matches()

---

spring-boot-rest-2/src/main/java/com/baeldung/unsupportedmediatype/UnsupportedMediaTypeApplication.java
spring-boot-rest-2/src/main/java/com/baeldung/unsupportedmediatype/User.java
spring-boot-rest-2/src/main/java/com/baeldung/unsupportedmediatype/UserController.java
spring-boot-rest-2/src/test/java/com/baeldung/unsupportedmedia/ApplicationTest.java
spring-boot-rest-2/src/test/java/com/baeldung/unsupportedmediatype/ApplicationUnitTest.java

1. Basic user controller added
2. POST API explains the how to support differnet content-type formats

415 Unsupported Media Type

---

spring-websockets/pom.xml
spring-websockets/src/main/java/com/baeldung/debugwebsockets/StockTicksController.java
spring-websockets/src/main/java/com/baeldung/debugwebsockets/StompClientSessionHandler.java
spring-websockets/src/main/java/com/baeldung/debugwebsockets/StompWebSocketClient.java
spring-websockets/src/main/java/com/baeldung/debugwebsockets/WebsocketApplication.java
spring-websockets/src/main/java/com/baeldung/debugwebsockets/WebsocketConfiguration.java
spring-websockets/src/test/java/com/baeldung/debugwebsockets/WebSocketIntegrationTest.java
spring-websockets/src/test/java/com/baeldung/debugwebsockets/WebsocketIntegrationTest.java

Added code for BAEL-4648: How to debug Websockets.
Includes an integration test

BAEL-4648: How to debug Websockets

---

apache-poi-2/README.md
apache-poi/README.md

Add README for new apache-poi-2 module and update README for previous apache-poi module

Add and update README files

---

spring-boot-modules/spring-boot-swagger/pom.xml
spring-boot-modules/spring-boot-swagger/src/main/java/com/baeldung/swagger2pdf/controller/UserController.java
spring-boot-modules/spring-boot-swagger/src/main/java/com/baeldung/swagger2pdf/objects/User.java

Generating PDF from Swagger doc

BAEL-5032 Swagger to PDF

---

spring-swagger-codegen/custom-validations-opeanpi-codegen/src/main/java/com/baeldung/openapi/petstore/validation/Capitalized.java
spring-swagger-codegen/custom-validations-opeanpi-codegen/src/main/java/com/baeldung/openapi/petstore/validation/CapitalizedValidator.java
spring-swagger-codegen/custom-validations-opeanpi-codegen/src/main/resources/openapi/templates/api.mustache
spring-swagger-codegen/custom-validations-opeanpi-codegen/src/main/resources/openapi/templates/model.mustache
spring-swagger-codegen/custom-validations-opeanpi-codegen/src/main/resources/petstore.yml

The tests and the implementation demo a capitalized word. I named it accordingly.

Update annotation name

---

core-java-modules/core-java-datetime-string/src/test/java/com/baeldung/datetime/DateTimeFormatterUnitTest.java

BAEL-3763: Improvement: Add a section about the ISO_INSTANT formatter

---

core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/implicitsuperconstructorundefined/Employee.java
core-java-modules/core-java-lang-oop-constructors/src/main/java/com/baeldung/implicitsuperconstructorundefined/Person.java

draft article link : https://drafts.baeldung.com/wp-admin/post.php?post=122611&action=edit

Bael-5125 Java implicit super constructor is undefined error

---

core-java-modules/core-java-concurrency-advanced-4/src/main/java/com/baeldung/volatilekeywordthreadsafety/VolatileVarNotThreadSafe.java
core-java-modules/core-java-concurrency-advanced-4/src/test/java/com/baeldung/volatilekeywordthreadsafety/VolatileVarNotThreadSafeUnitTest.java

BAEL-5185 article to show when volatile variables are not thread safe in java

initial commit for BAEL-5185

---

core-java-modules/core-java-string-operations-4/src/main/java/com/baeldung/split/SplitStringEveryNthChar.java
core-java-modules/core-java-string-operations-4/src/test/java/com/baeldung/split/SplitStringEveryNthCharUnitTest.java

BAEL-5278 : Java - split a String every n characters

---

core-java-modules/core-java-string-operations-4/src/main/java/com/baeldung/endswithpattern/StringEndsWithPattern.java
core-java-modules/core-java-string-operations-4/src/test/java/com/baeldung/endswithpattern/StringEndsWithPatternUnitTest.java

BAEL-5276: Java - check if a String ends with a certain pattern

---

core-java-modules/core-java-15/pom.xml
core-java-modules/core-java-15/src/main/java/com/baeldung/hidden/classes/HiddenClass.java
core-java-modules/core-java-15/src/test/java/com/baeldung/hidden/classes/HiddenClassUnitTest.java

[BAEL-5077] Hidden Classes

---

core-java-modules/core-java-11-2/src/test/java/com/baeldung/reflection/OperationsUnitTest.java

BAEL-4586: Improve the Reflective Method Call Article

---

core-java-modules/core-java-15/README.md
core-java-modules/core-java-17/README.md
core-java-modules/core-java-string-algorithms-3/README.md
gradle/maven-to-gradle/README.md
persistence-modules/java-cassandra/README.md
testing-modules/junit-5-advanced/README.md

BAEL-47433 - add links to github-baeldung articles

---

core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/threads/name/CustomThreadName.java

draft article link :https://drafts.baeldung.com/wp-admin/post.php?post=122960&action=edit

BAEL-5271 set custom thread name

---

persistence-modules/java-mongodb/src/main/java/com/baeldung/mongo/objectid/RetrieveIdExample.java

code used to illustrate the article about retrieving the MongoDB ID

Example class for BAEL-4888

---

feign/src/main/java/com/baeldung/feign/retry/Custom5xxErrorDecoder.java
feign/src/main/java/com/baeldung/feign/retry/NaiveRetryer.java
feign/src/main/java/com/baeldung/feign/retry/ResilientFeignClientBuilder.java
feign/src/test/java/com/baeldung/feign/retry/Custom5xxErrorDecoderUnitTest.java

http://jira.baeldung.com/browse/BAEL-5301
https://drafts.baeldung.com/wp-admin/post.php?post=125475&action=edit

BAEL-5301 Retrying Feign Calls

---

persistence-modules/core-java-persistence-2/src/main/java/com/baeldung/connectionstatus/ConnectionValidation.java
persistence-modules/core-java-persistence-2/src/test/java/com/baeldung/connectionstatus/ConnectionValidationUnitTest.java

JDBC Connection validation examples

BAEL-4498 JDBC Connection Status

---

javaxval/pom.xml
javaxval/src/main/java/com/baeldung/javaxval/container/validation/Customer.java

Reverts the [previously commented @NotBlank annotation](https://github.com/eugenp/tutorials/pull/11673/commits/be439c7571a30ee3cf0a98dc03ee0fc8b2428b9f). See [related JIRA thread](http://jira.baeldung.com/browse/BAEL-5123).

Bael 5123: uncomment @NotBlank annotation

---

spring-5-autowiring-beans/pom.xml
spring-5-autowiring-beans/src/main/java/com/baeldung/autowiring/App.java
spring-5-autowiring-beans/src/main/java/com/baeldung/autowiring/controller/CorrectController.java
spring-5-autowiring-beans/src/main/java/com/baeldung/autowiring/controller/FlawedController.java
spring-5-autowiring-beans/src/main/java/com/baeldung/autowiring/service/MyComponent.java
spring-5-autowiring-beans/src/main/java/com/baeldung/autowiring/service/MyService.java
spring-5-autowiring-beans/src/main/java/com/baeldung/autowiring/service/MyServiceConfiguration.java
spring-5-autowiring-beans/src/test/java/com/baeldung/autowiring/controller/CorrectControllerIntegrationTest.java
spring-5-autowiring-beans/src/test/java/com/baeldung/autowiring/controller/FlawedControllerIntegrationTest.java

Ticket : http://jira.baeldung.com/browse/BAEL-5336

Code for the Spring @Autowired Field Null – Common Causes and Solutions article

---

apache-shiro/pom.xml
logging-modules/log-mdc/pom.xml
logging-modules/log4j/pom.xml
logging-modules/log4j2/pom.xml
spring-4/pom.xml
spring-boot-modules/spring-boot-1/pom.xml
spring-cloud/spring-cloud-archaius/zookeeper-config/pom.xml
testing-modules/junit-5/pom.xml
testing-modules/junit5-annotations/pom.xml
testing-modules/test-containers/pom.xml

JAVA-9825: Upgrade log4j version for modules that use log4j-core library

---

gradle/gradle-source-vs-target-compatibility/build.gradle
gradle/gradle-source-vs-target-compatibility/src/main/java/com/baeldung/helloworld/HelloWorldApp.java
gradle/settings.gradle

Draft url: https://drafts.baeldung.com/wp-admin/post.php?post=126456 
Jira link: http://jira.baeldung.com/browse/BAEL-4513

BAEL-4513 Gradle source vs target compatibility

---

jta/pom.xml
maven-modules/maven-generate-war/pom.xml
patterns/enterprise-patterns/pom.xml
persistence-modules/spring-data-dynamodb/pom.xml
quarkus-vs-springboot/spring-project/pom.xml
spring-5-data-reactive/pom.xml
spring-activiti/pom.xml
spring-boot-modules/spring-boot-2/pom.xml
spring-boot-modules/spring-boot-logging-log4j2/pom.xml
spring-boot-modules/spring-boot-mvc-birt/pom.xml
spring-boot-modules/spring-boot-react/pom.xml
spring-boot-modules/spring-boot-swagger-keycloak/pom.xml
spring-boot-modules/spring-boot-testing/pom.xml
spring-cloud/spring-cloud-contract/pom.xml
spring-cloud/spring-cloud-eureka-self-preservation/pom.xml
spring-cloud/spring-cloud-eureka/pom.xml
spring-cloud/spring-cloud-load-balancer/pom.xml
spring-cloud/spring-cloud-stream-starters/twitterhdfs/pom.xml
spring-cloud/spring-cloud-zuul-eureka-integration/eureka-client/pom.xml
spring-cloud/spring-cloud-zuul-eureka-integration/eureka-server/pom.xml
spring-cloud/spring-cloud-zuul-eureka-integration/zuul-server/pom.xml
spring-cloud/spring-cloud-zuul/spring-zuul-rate-limiting/pom.xml
spring-di-2/pom.xml
spring-di-3/pom.xml
spring-native/pom.xml
spring-roo/pom.xml
spring-security-modules/spring-5-security-oauth/pom.xml
spring-security-modules/spring-security-legacy-oidc/pom.xml
spring-swagger-codegen/custom-validations-opeanpi-codegen/pom.xml
spring-web-modules/spring-boot-jsp/pom.xml

JAVA-9824: Identify boot modules not using parent-boot-2 as parent and

---

spring-security-modules/spring-security-web-boot-3/src/main/java/com/baeldung/logging/LoggingController.java
spring-security-modules/spring-security-web-boot-3/src/main/java/com/baeldung/logging/SecurityConfig.java
spring-security-modules/spring-security-web-boot-3/src/main/java/com/baeldung/logging/SecurityLoggingApplication.java
spring-security-modules/spring-security-web-boot-3/src/main/resources/application-logging.properties

How to enable debug logging with Spring Security

[ BAEL-5337 ] - Enable Logging for Spring Security

---

core-java-modules/core-java-collections-maps-4/README.md
core-java-modules/core-java-concurrency-advanced-4/README.md
core-java-modules/core-java-exceptions-4/README.md
docker/README.md
javax-servlets-2/README.md
maven-modules/maven-classifier/README.md
spring-cloud/spring-cloud-gateway/README.md
spring-security-modules/spring-security-web-boot-3/README.md

added links back to the articles

Updated README.md files

---

spring-security-modules/spring-5-security-oauth/src/main/java/com/baeldung/oauth2resttemplate/AppController.java
spring-security-modules/spring-5-security-oauth/src/main/java/com/baeldung/oauth2resttemplate/GithubRepo.java
spring-security-modules/spring-5-security-oauth/src/main/java/com/baeldung/oauth2resttemplate/SecurityConfig.java
spring-security-modules/spring-5-security-oauth/src/main/java/com/baeldung/oauth2resttemplate/SpringSecurityOauth2ClientApplication.java
spring-security-modules/spring-5-security-oauth/src/main/resources/application-oauth2-rest-template.properties
spring-security-modules/spring-5-security-oauth/src/main/resources/templates/oauth2resttemplate/error.html
spring-security-modules/spring-5-security-oauth/src/main/resources/templates/oauth2resttemplate/home.html
spring-security-modules/spring-5-security-oauth/src/main/resources/templates/oauth2resttemplate/index.html
spring-security-modules/spring-5-security-oauth/src/main/resources/templates/oauth2resttemplate/repositories.html

Basic Spring Web Application to make use of OAuth2RestTemplate

BAEL-5335: Introduction to OAuth2RestTemplate

---

httpclient-2/README.md
httpclient-simple/README.md
libraries-testing/README.md

Fixed link for Introduction to Awaitility, from https://www.baeldung.com/awaitlity-testing to https://www.baeldung.com/awaitility-testing

Updated README.md

---

nginx-forward-proxy/forward
nginx-forward-proxy/package-lock.json
nginx-forward-proxy/package.json
nginx-forward-proxy/proxytest.js

ADDED FORWARD PROXY CONFIGURATION AND CLIENT

BAEL-5224 Nginx Forward Proxy Jira issue 

---

spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/config/ExceptionMessage.java
spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/config/FeignSupportConfig.java
spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/config/RetreiveMessageErrorDecoder.java
spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/controller/FileController.java
spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/service/UploadClient.java
spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/service/UploadService.java

Changes to fetch the original message

Changes to fetch the Original Message

---

jakarta-ee/pom.xml
jakarta-ee/src/main/java/com/baeldung/eclipse/krazo/User.java
jakarta-ee/src/main/java/com/baeldung/eclipse/krazo/UserApplication.java
jakarta-ee/src/main/java/com/baeldung/eclipse/krazo/UserController.java
jakarta-ee/src/main/webapp/WEB-INF/beans.xml
jakarta-ee/src/main/webapp/WEB-INF/views/success.jsp
jakarta-ee/src/main/webapp/WEB-INF/views/user.jsp
jakarta-ee/src/main/webapp/styles.css
jakarta-ee/src/test/java/com/baeldung/eclipse/krazo/AppTest.java
jakarta-ee/src/test/java/com/baeldung/eclipse/krazo/UserControllerTest.java
jakarta-ee/src/test/java/com/baeldung/eclipse/krazo/UserControllerUnitTest.java
pom.xml

Added code for BAEL-1355 Eclipse Krazo (Formerly, Ozark)

Added code for BAEL-1355

---

core-java-modules/core-java-string-operations-4/src/main/java/com/baeldung/split/SplitStringEveryNthChar.java

[BAEL-5278]: Quick fix to improve splitting a given String using a pattern

---

persistence-modules/core-java-persistence-2/src/main/java/com/baeldung/resultsetrowcount/RowCounterApp.java
persistence-modules/core-java-persistence-2/src/main/java/com/baeldung/resultsetrowcount/ScrollableRowCounter.java
persistence-modules/core-java-persistence-2/src/main/java/com/baeldung/resultsetrowcount/StandardRowCounter.java
persistence-modules/core-java-persistence-2/src/test/java/com/baeldung/resultsetrowcount/ScrollableRowCounterUnitTest.java
persistence-modules/core-java-persistence-2/src/test/java/com/baeldung/resultsetrowcount/StandardRowCounterUnitTest.java

JIRA: https://jira.baeldung.com/browse/BAEL-5156
Draft: https://drafts.baeldung.com/wp-admin/post.php?post=130406&action=edit
The article is missing the link to GitHub since it's not available yet.

Example code for Get the Number of Rows in a ResultSet

---

core-java-modules/core-java-datetime-string/src/test/java/com/baeldung/formatinstant/FormatInstantUnitTest.java

BAEL-5386: Format Instant to String in Java

---

core-java-modules/core-java-lang-4/src/main/java/com/baeldung/implementsvsextends/Main.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/implementsvsextends/media/model/AudioMedia.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/implementsvsextends/media/model/Media.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/implementsvsextends/media/model/VideoMedia.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/implementsvsextends/media/player/AdvancedPlayerOptions.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/implementsvsextends/media/player/MediaPlayer.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/implementsvsextends/media/player/impl/AudioMediaPlayer.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/implementsvsextends/media/player/impl/CustomMediaPlayer.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/implementsvsextends/media/player/impl/MultiMediaPlayer.java
core-java-modules/core-java-lang-4/src/main/java/com/baeldung/implementsvsextends/media/player/impl/VideoMediaPlayer.java
core-java-modules/core-java-lang-4/src/test/java/com/baeldung/implementsvsextends/model/AudioMediaUnitTest.java
core-java-modules/core-java-lang-4/src/test/java/com/baeldung/implementsvsextends/model/VideoMediaUnitTest.java
core-java-modules/core-java-lang-4/src/test/java/com/baeldung/implementsvsextends/player/impl/AudioMediaPlayerUnitTest.java
core-java-modules/core-java-lang-4/src/test/java/com/baeldung/implementsvsextends/player/impl/MultiMediaPlayerUnitTest.java
core-java-modules/core-java-lang-4/src/test/java/com/baeldung/implementsvsextends/player/impl/VideoMediaPlayerUnitTest.java

BAEL-5417 - implements vs extends
https://drafts.baeldung.com/wp-admin/post.php?post=130235

BAEL-5417 - implements vs extends

---

persistence-modules/spring-boot-persistence-mongodb/src/main/java/com/baeldung/projection/model/InStock.java
persistence-modules/spring-boot-persistence-mongodb/src/main/java/com/baeldung/projection/model/Inventory.java
persistence-modules/spring-boot-persistence-mongodb/src/main/java/com/baeldung/projection/model/Size.java
persistence-modules/spring-boot-persistence-mongodb/src/main/java/com/baeldung/projection/repository/InventoryRepository.java
persistence-modules/spring-boot-persistence-mongodb/src/test/java/com/baeldung/logging/LoggingUnitTest.java
persistence-modules/spring-boot-persistence-mongodb/src/test/java/com/baeldung/projection/AbstractTestProjection.java
persistence-modules/spring-boot-persistence-mongodb/src/test/java/com/baeldung/projection/MongoTemplateProjectionUnitTest.java
persistence-modules/spring-boot-persistence-mongodb/src/test/java/com/baeldung/projection/RepositoryProjectionUnitTest.java

Field projection with tests for MongoTemplate and MongoRepository

BAEL-5400 - Return Only Specific Fields for a Query in Spring Data MongoDB

---

jersey/src/main/java/com/baeldung/jersey/exceptionhandling/ExceptionHandlingConfig.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/data/Stock.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/data/Wallet.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/repo/Db.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/repo/Identifiable.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/rest/StocksResource.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/rest/WalletsResource.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/rest/exceptions/IllegalArgumentExceptionMapper.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/rest/exceptions/InvalidTradeException.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/rest/exceptions/RestErrorResponse.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/rest/exceptions/ServerExceptionMapper.java
jersey/src/main/java/com/baeldung/jersey/exceptionhandling/service/Repository.java
jersey/src/test/java/com/baeldung/jersey/exceptionhandling/rest/StocksResourceIntegrationTest.java

First draft:
https://drafts.baeldung.com/wp-admin/post.php?post=131880&action=edit

BAEL-5157 - Exception Handling with Jersey

---

core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/stopexecution/FixedTimeTask.java
core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/stopexecution/LongRunningTask.java
core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/stopexecution/Step.java
core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/stopexecution/SteppedTask.java
core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/stopexecution/StoppingExecution.java
core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/stopexecution/TimeOutTask.java
core-java-modules/core-java-concurrency-basic-2/src/test/java/com/baeldung/concurrent/stopexecution/FixedTimeTaskUnitTest.java
core-java-modules/core-java-concurrency-basic-2/src/test/java/com/baeldung/concurrent/stopexecution/LongRunningTaskUnitTest.java
core-java-modules/core-java-concurrency-basic-2/src/test/java/com/baeldung/concurrent/stopexecution/SteppedTaskUnitTest.java
core-java-modules/core-java-concurrency-basic-2/src/test/java/com/baeldung/concurrent/stopexecution/TimeOutTaskUnitTest.java

New sample classes and improvements

BAEL-4559 Stop Execution After Certain Time improvements

---

spring-boot-modules/pom.xml

JAVA-8271 Uncommenting spring-boot-keycloak module

---

spring-boot-modules/pom.xml

This reverts commit 61d687d50f51315f89a7e1082fad0b922fde8d0c.

Revert "JAVA-8271 Uncommenting spring-boot-keycloak module"

---

core-java-modules/core-java-lang-5/README.md
core-java-modules/core-java-lang-5/pom.xml
core-java-modules/core-java-lang-5/src/test/java/com/baeldung/nullchecks/NullChecksUnitTest.java
core-java-modules/pom.xml

(cherry picked from commit 2268039035ec1ef23b68d9239fc921fe84b14b14)

BAEL 5414 - Java null check why use == instead of .equals()

---

spring-boot-modules/pom.xml
spring-boot-modules/spring-boot-keycloak/pom.xml

Lets experiment with older version

 JAVA-8271 Lets try different jaxb2-maven-plugin version

---

core-java-modules/core-java-concurrency-advanced-4/src/main/java/com/baeldung/setvslazyset/Application.java

JIRA: https://jira.baeldung.com/browse/BAEL-4034
Draft: https://drafts.baeldung.com/wp-admin/post.php?post=133468&action=edit

Example code for Java atomic variable set vs lazySet

---

java-numbers-4/pom.xml
java-numbers-4/src/main/java/com/baeldung/booleantoint/BooleanToInt.java
java-numbers-4/src/test/java/com/baeldung/booleantoint/BooleanToIntUnitTest.java

- added class for Article examples
- created unit tests
- modified pom in order to call Apache Commons outside test

BAEL-5521 Convert boolean to int in Java

---

spring-boot-modules/spring-boot-di/src/main/java/com/baeldung/componentscan/springapp/SpringComponentScanApp.java

BAEL-5448: Improvement: Scan Multiple Paths using the @ComponentScan Annotation

---

resteasy/pom.xml
resteasy/src/test/java/com/baeldung/server/RestEasyClientLiveTest.java

[BAEL-5342] Update RESTEasy Client Article

---

core-java-modules/core-java-networking-3/src/main/java/com/baeldung/http/JavaHttpClientTimeout.java
core-java-modules/core-java-networking-3/src/test/java/com/baeldung/http/JavaHttpClientTimeoutIntegrationTest.java

JAVA-5484: Added JavaHttpClientTimeout class

---

libraries-data/pom.xml

JAVA-12081 Reverting hazelcast back to previous version

---

testing-modules/junit-5-basics/src/test/java/com/baeldung/assertexception/ExceptionAssertionUnitTest.java

After this statement "This means that if we pass Exception as the expected exception type, any exception thrown will make the assertion succeed since Exception is the super-type for all exceptions." it would be a good idea to insert an exception hierarchy image e.g.

JUnit5 conventions + code rearrangement 

---

core-java-modules/core-java-uuid/src/main/java/com/baeldung/uuid/UUIDGenerator.java

- Remove unused imports
- Code cleaning using IDE's code inspection tool

Remove unused imports

---

javax-servlets-2/pom.xml
javax-servlets-2/src/main/java/com/baeldung/servlets/UserServlet.java
javax-servlets-2/src/test/java/com/baeldung/servlets/TestUtil.java
javax-servlets-2/src/test/java/com/baeldung/servlets/UserServletUnitTest.java

Hello Saajan,
Hope you are doing good!
I have completed the draft and created a PR:
Draft Link: https://drafts.baeldung.com/wp-admin/post.php?post=135610&action=edit
Palani

BAEL-5524: Mock HttpServletRequest + tests

---

testing-modules/mockito-2/src/test/java/com/baeldung/mockito/additionalanswers/BookServiceUnitTest.java

BAEL-4469: Update Introduction to Mockito AdditionalAnswers

---

spring-security-modules/spring-security-core-2/src/main/java/com/baeldung/global/exceptionhandler/Application.java
spring-security-modules/spring-security-core-2/src/main/java/com/baeldung/global/exceptionhandler/controller/LoginController.java
spring-security-modules/spring-security-core-2/src/main/java/com/baeldung/global/exceptionhandler/handler/DefaultExceptionHandler.java
spring-security-modules/spring-security-core-2/src/main/java/com/baeldung/global/exceptionhandler/handler/RestError.java
spring-security-modules/spring-security-core-2/src/main/java/com/baeldung/global/exceptionhandler/handler/RestResponse.java
spring-security-modules/spring-security-core-2/src/main/java/com/baeldung/global/exceptionhandler/security/CustomAuthenticationEntryPoint.java
spring-security-modules/spring-security-core-2/src/main/java/com/baeldung/global/exceptionhandler/security/CustomSecurityConfig.java
spring-security-modules/spring-security-core-2/src/main/java/com/baeldung/global/exceptionhandler/security/DelegatedAuthenticationEntryPoint.java
spring-security-modules/spring-security-core-2/src/main/java/com/baeldung/global/exceptionhandler/security/DelegatedSecurityConfig.java
spring-security-modules/spring-security-core-2/src/test/java/com/baeldung/global/exceptionhandler/DelegatedSecurityConfigUnitTest.java
spring-security-modules/spring-security-core-2/src/test/java/com/baeldung/global/exceptionhandler/SecurityConfigUnitTest.java

Draft - https://drafts.baeldung.com/wp-admin/post.php?post=137238&action=edit

BAEL-5533: Spring security exceptions

---

spring-vault/pom.xml
spring-vault/src/main/java/com/baeldung/springvault/Credentials.java
spring-vault/src/main/java/com/baeldung/springvault/CredentialsRepository.java
spring-vault/src/main/java/com/baeldung/springvault/CredentialsService.java
spring-vault/src/test/java/com/baeldung/springvault/VaultIntegrationTest.java

BAEL-3598: Improvement: Spring Vault @Secret Annotation

---

spring-web-modules/spring-thymeleaf/pom.xml
spring-web-modules/spring-thymeleaf/src/main/java/com/baeldung/thymeleaf/controller/FunctionCallController.java
spring-web-modules/spring-thymeleaf/src/main/webapp/WEB-INF/js/functionCall.js
spring-web-modules/spring-thymeleaf/src/main/webapp/WEB-INF/views/functionCall.html
spring-web-modules/spring-thymeleaf/src/test/java/com/baeldung/thymeleaf/controller/FunctionCallIntegrationTest.java

See https://jira.baeldung.com/browse/BAEL-3825

BAEL-3825: Javascript function call with Thymeleaf

---

core-java-modules/core-java-jar/README.md
core-java-modules/core-java-numbers-5/README.md
persistence-modules/hibernate-exceptions/README.md
persistence-modules/java-mongodb-3/README.md
persistence-modules/spring-boot-persistence-mongodb-2/README.md
spring-web-modules/spring-thymeleaf/README.md

added links back to the articles

Updated README.mds

---

core-java-modules/core-java-streams-4/pom.xml
core-java-modules/core-java-streams-4/src/test/java/splitting/Article.java
core-java-modules/core-java-streams-4/src/test/java/splitting/StreamSplittingUnitTest.java
core-java-modules/pom.xml
pom.xml

https://jira.baeldung.com/browse/BAEL-5557

BAEL-5557 Split a stream into parts

---

core-java-modules/core-java-string-operations-4/src/main/java/com/baeldung/truncate/TruncateString.java
core-java-modules/core-java-string-operations-4/src/test/java/com/baeldung/truncate/TruncateStringUnitTest.java

BAEL-5550: Trim a string based on the string length

---

core-java-modules/core-java-jar/src/main/java/com/baeldung/jar/MySampleGUIAppn.java
core-java-modules/core-java-jar/src/test/java/com/baeldung/jar/MySampleGUIAppnUnitTest.java

[BAEL-5421] by @opokharel

---

docker-modules/docker-compose/Dockerfile
docker-modules/docker-compose/depends-on_vs_links/docker-compose-depends-on.yml
docker-modules/docker-compose/depends-on_vs_links/docker-compose-links.yml
docker-modules/docker-compose/depends-on_vs_links/docker-compose-network.yml
docker-modules/docker-compose/pom.xml

YAML examples for depends-on, links, and network over deprecated links

[ BAEL-5503 ] - Difference Between links and depends_on in Docker-Compose

---

javaxval/pom.xml
javaxval/src/main/java/com/baeldung/javaxval/notnull/NotNullMethodParameter.java
javaxval/src/main/java/com/baeldung/javaxval/notnull/ValidatingComponent.java
javaxval/src/test/java/com/baeldung/javaxval/notnull/NotNullMethodParameterUnitTest.java
javaxval/src/test/java/com/baeldung/javaxval/notnull/ValidatingComponentIntegrationTest.java

The integration test in this PR is Spring Boot, but the current pom in this javaxval project is Spring only. I haven't added spring boot to the pom, for fear of interfering with the other articles/tests. So, we'll need to consider where to put this for its final resting place.

BAEL-5642 Using @NotNull as a method parameter

---

docker-modules/docker-compose/two-compose-share-same-network/create-network-from-service/docker-compose-my-app-service.yaml
docker-modules/docker-compose/two-compose-share-same-network/create-network-from-service/docker-compose-redis-service.yaml
docker-modules/docker-compose/two-compose-share-same-network/join-existing-network/docker-compose-my-app-service.yaml
docker-modules/docker-compose/two-compose-share-same-network/join-existing-network/docker-compose-redis-service.yaml

two or more services are using the same network

[ BAEL-5498 ] - Communication Between Multiple Docker Compose Projects

---

spring-boot-modules/spring-boot-libraries-2/pom.xml
spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/SampleAnnotatedClass.java
spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/SampleAnnotation.java
spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/SampleAnnotationScanner.java
spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/ScanNotSupportedException.java
spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/UnexpectedScanException.java
spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/jandexlib/JandexScannerService.java
spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/javareflectionlib/JavaReflectionsScannerService.java
spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/reflectionslib/ReflectionsScannerService.java
spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/springcontextlib/SpringBeanAnnotationScannerService.java
spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/springcorelib/SpringCoreAnnotationScannerService.java
spring-boot-modules/spring-boot-libraries-2/src/test/java/com/baeldung/annotation/scanner/SampleAnnotationScannerUnitTest.java

Annotation scanners using Spring context, Spring core, reflections, java reflection, and Jandex libraries are implemented

BAEL-5645 - Scanning Java Annotations at Runtime

---

core-java-modules/core-java-17/README.md
persistence-modules/hibernate-exceptions/README.md
quarkus-modules/quarkus/README.md

Updated links titles

---

core-java-modules/core-java-concurrency-advanced-4/src/main/java/com/baeldung/atomicvsvolatile/SafeAtomicCounter.java
core-java-modules/core-java-concurrency-advanced-4/src/main/java/com/baeldung/atomicvsvolatile/UnsafeCounter.java
core-java-modules/core-java-concurrency-advanced-4/src/main/java/com/baeldung/atomicvsvolatile/UnsafeVolatileCounter.java
core-java-modules/core-java-concurrency-advanced-4/src/test/java/com/baeldung/atomicvsvolatile/SafeAtomicCounterUnitTest.java

An example for the article about the usage of atomic values and the volatile keyword.

BAEL-5682 - Atomic vs Volatile

---

algorithms-modules/algorithms-miscellaneous-4/pom.xml
algorithms-modules/algorithms-miscellaneous-4/src/main/java/com/baeldung/algorithms/stringpermutation/ArrayHelper.java
algorithms-modules/algorithms-miscellaneous-4/src/main/java/com/baeldung/algorithms/stringpermutation/StringPermutationsApache.java
algorithms-modules/algorithms-miscellaneous-4/src/main/java/com/baeldung/algorithms/stringpermutation/StringPermutationsCombinatoricsLib.java
algorithms-modules/algorithms-miscellaneous-4/src/main/java/com/baeldung/algorithms/stringpermutation/StringPermutationsGuava.java
algorithms-modules/algorithms-miscellaneous-4/src/test/java/com/baeldung/algorithms/stringpermutation/StringPermutationsApacheUnitTest.java
algorithms-modules/algorithms-miscellaneous-4/src/test/java/com/baeldung/algorithms/stringpermutation/StringPermutationsCombinatoricsLibUnitTest.java
algorithms-modules/algorithms-miscellaneous-4/src/test/java/com/baeldung/algorithms/stringpermutation/StringPermutationsGuavaUnitTest.java

Examples for an article about String permutations

BAEL-5646: String permutation examples

---

.gitignore
docker-modules/docker-compose/multiple-mounts/bind_mount_and_volume.yml
docker-modules/docker-compose/multiple-mounts/init.sql
docker-modules/docker-compose/multiple-mounts/multiple_bind_mounts.yml
docker-modules/docker-compose/multiple-mounts/multiple_volumes.yaml

Multiple mount examples with docker compose

[ BAEL 5508 ] - Mounting Multiple Volumes on a Docker Container

---

algorithms-modules/algorithms-miscellaneous-4/src/main/java/com/baeldung/algorithms/stringpermutation/Helper.java
algorithms-modules/algorithms-miscellaneous-4/src/main/java/com/baeldung/algorithms/stringpermutation/StringPermutationsApache.java
algorithms-modules/algorithms-miscellaneous-4/src/main/java/com/baeldung/algorithms/stringpermutation/StringPermutationsCombinatoricsLib.java
algorithms-modules/algorithms-miscellaneous-4/src/main/java/com/baeldung/algorithms/stringpermutation/StringPermutationsGuava.java
algorithms-modules/algorithms-miscellaneous-4/src/test/java/com/baeldung/algorithms/stringpermutation/HelperUnitTest.java
algorithms-modules/algorithms-miscellaneous-4/src/test/java/com/baeldung/algorithms/stringpermutation/StringPermutationsApacheUnitTest.java
algorithms-modules/algorithms-miscellaneous-4/src/test/java/com/baeldung/algorithms/stringpermutation/StringPermutationsCombinatoricsLibUnitTest.java
algorithms-modules/algorithms-miscellaneous-4/src/test/java/com/baeldung/algorithms/stringpermutation/StringPermutationsGuavaUnitTest.java

String permutation improvements

BAEL-5646: String permutation improvements

---

core-java-modules/core-java-collections-list-4/pom.xml
core-java-modules/core-java-collections-list-4/src/test/java/com/baeldung/list/creation/ArraysAsListUnitTest.java
core-java-modules/core-java-collections-list-4/src/test/java/com/baeldung/list/creation/ListOfUnitTest.java
core-java-modules/pom.xml
pom.xml

Added compatibility to the latest LTS Java 17

JAVA-5683: Difference Between List.of and Arrays.asList

---

core-java-modules/core-java-concurrency-advanced-4/src/main/java/com/baeldung/ownablesynchronizers/Application.java

Title: What is “Locked ownable synchronizers” in thread dump?
JIRA ticket: https://jira.baeldung.com/browse/BAEL-4500
Draft link: https://drafts.baeldung.com/wp-admin/post.php?post=141658&action=edit

[BAEL-4500] Add locked ownable synchronizers example code

---

core-java-modules/core-java-io-apis/src/test/java/com/baeldung/scanner/JavaScannerUnitTest.java

BAEL-4623: Add a new section for Scanner article

---

axon/README.md
axon/pom.xml
axon/src/main/java/com/baeldung/axon/coreapi/queries/OrderUpdatesQuery.java
axon/src/main/java/com/baeldung/axon/coreapi/queries/TotalProductsShippedQuery.java
axon/src/main/java/com/baeldung/axon/gui/OrderRestEndpoint.java
axon/src/main/java/com/baeldung/axon/querymodel/InMemoryOrdersEventHandler.java
axon/src/main/java/com/baeldung/axon/querymodel/LegacyQueryHandler.java
axon/src/main/java/com/baeldung/axon/querymodel/OrderQueryService.java
axon/src/main/java/com/baeldung/axon/querymodel/OrderResponse.java
axon/src/main/java/com/baeldung/axon/querymodel/OrderStatusResponse.java
axon/src/main/java/com/baeldung/axon/querymodel/OrdersEventHandler.java
axon/src/main/resources/order-api.http
axon/src/test/java/com/baeldung/axon/querymodel/AbstractOrdersEventHandlerUnitTest.java
axon/src/test/java/com/baeldung/axon/querymodel/InMemoryOrdersEventHandlerUnitTest.java
axon/src/test/java/com/baeldung/axon/querymodel/OrderQueryServiceIntegrationTest.java
axon/src/test/resources/application.properties
axon/start_axon_server.sh

As per commits, added:
- update to latest and adding script to start axon server
- implement the two other kinds of query
- add unit and integration tests

BAEL-4769 Additions for 'Querying the Query Model in Axon'

---

persistence-modules/spring-boot-persistence-mongodb-2/src/main/java/com/baeldung/boot/collection/name/SpringBootCollectionNameApplication.java
persistence-modules/spring-boot-persistence-mongodb-2/src/main/java/com/baeldung/boot/composite/key/SpringBootCompositeKeyApplication.java
persistence-modules/spring-boot-persistence-mongodb-2/src/main/java/com/baeldung/boot/count/SpringBootCountApplication.java
persistence-modules/spring-boot-persistence-mongodb-2/src/main/java/com/baeldung/boot/unique/field/SpringBootUniqueFieldApplication.java
persistence-modules/spring-boot-persistence-mongodb-2/src/test/java/com/baeldung/boot/collection/name/service/MusicStoreServiceIntegrationTest.java
persistence-modules/spring-boot-persistence-mongodb-2/src/test/java/com/baeldung/boot/composite/key/CustomerServiceIntegrationTest.java
persistence-modules/spring-boot-persistence-mongodb-2/src/test/java/com/baeldung/boot/count/service/CountCarServiceIntegrationTest.java
persistence-modules/spring-boot-persistence-mongodb-2/src/test/java/com/baeldung/boot/unique/field/UniqueFieldIntegrationTest.java

add embedded properties to failing integration tests

[ BAEL-5397 fix 3 ] add embedded properties to tests

---

core-java-modules/core-java-string-operations-4/src/main/java/com/baeldung/stringbuilder/RemoveLastChar.java
core-java-modules/core-java-string-operations-4/src/test/java/com/baeldung/stringbuilder/RemoveLastCharTest.java
core-java-modules/core-java-string-operations-4/src/test/java/com/baeldung/stringbuilder/RemoveLastCharUnitTest.java

- Added initial code with main method test
- Added initial tests for each method article is going to be written on

BAEL-5614 Remove Last Char from String Builder

---

core-java-modules/core-java-collections-list-3/README.md
core-java-modules/core-java-collections-list-4/README.md
core-java-modules/core-java-collections-list-4/src/test/java/com/baeldung/list/listofhashmaps/ListOfHashMapsUnitTest.java

Move https://www.baeldung.com/java-hashmap-inside-list code to core-java-collections-list-4

BAEL-5634: move the code to a different module

---

axon/pom.xml
axon/src/main/java/com/baeldung/axon/gui/OrderRestEndpoint.java
axon/src/main/java/com/baeldung/axon/querymodel/InMemoryOrdersEventHandler.java
axon/src/main/java/com/baeldung/axon/querymodel/OrderQueryService.java
axon/src/main/java/com/baeldung/axon/querymodel/OrdersEventHandler.java
axon/src/main/resources/order-api.http
axon/src/test/java/com/baeldung/axon/querymodel/AbstractOrdersEventHandlerUnitTest.java
axon/src/test/java/com/baeldung/axon/querymodel/OrderQueryServiceIntegrationTest.java

Update to 4.6.0 where streaming queries are introduced. See https://jira.baeldung.com/browse/BAEL-5807

BAEL-5807 Add streaming query

---

persistence-modules/hibernate-enterprise/src/main/java/com/baeldung/hibernate/exception/Product.java
persistence-modules/hibernate-enterprise/src/test/java/com/baeldung/hibernate/exception/HibernateExceptionUnitTest.java

BAEL-5697: Add new section in Hibernate Exceptions article

---

core-java-modules/core-java-concurrency-advanced-4/src/main/java/com/baeldung/threadparking/Application.java

JIRA: https://jira.baeldung.com/browse/BAEL-4038

Example code for BAEL-4038 Understanding java.lang.Thread.State: WAITING (parking)

---

core-java-modules/core-java-collections-list-4/src/test/java/com/baeldung/list/tostring/ListToStringUnitTest.java

* adapting code to the article based on changes after user feedback: https://www.baeldung.com/wp-admin/edit-comments.php?s=143.255.84.196&mode=detail

bael-5754 - quick fix

---

spring-caching-2/src/main/java/com/baeldung/caching/ttl/service/HotelService.java

Using variable instead of fixed value.

bael-5696 quick fix

---

core-java-modules/core-java-numbers-5/src/main/java/com/baeldung/uniquerng/BigUniqueRng.java
core-java-modules/core-java-numbers-5/src/main/java/com/baeldung/uniquerng/UniqueRng.java
core-java-modules/core-java-numbers-5/src/test/java/com/baeldung/uniquerng/RngUtilsUnitTest.java

Ready for review.
Draft: https://drafts.baeldung.com/wp-admin/post.php?post=142886&action=edit

BAEL-5678 - Creating Random Numbers With No Duplicates in Java

---

core-java-modules/core-java-collections-maps-4/pom.xml
core-java-modules/core-java-collections-maps-4/src/test/java/com/baeldung/multivaluedmap/MultivaluedMapUnitTest.java

Jira: https://jira.baeldung.com/browse/BAEL-5888

HashMap vs MultivaluedMap in Java

---

spring-security-modules/spring-security-oauth2-sso/spring-security-sso-kerberos/src/main/java/com/baeldung/intro/config/WebSecurityConfig.java
spring-security-modules/spring-security-oauth2-sso/spring-security-sso-kerberos/src/main/java/kerberos/server/config/WebSecurityConfig.java

 JAVA-14890 Update spring-security-oauth2-sso module under spring-security-modules to remove usage of deprecated WebSecurityConfigurerAdapter

---

patterns-modules/design-patterns-creational/src/main/java/com/baeldung/factorygeneric/DateNotifier.java
patterns-modules/design-patterns-creational/src/main/java/com/baeldung/factorygeneric/Main.java
patterns-modules/design-patterns-creational/src/main/java/com/baeldung/factorygeneric/Notifier.java
patterns-modules/design-patterns-creational/src/main/java/com/baeldung/factorygeneric/NotifierFactory.java
patterns-modules/design-patterns-creational/src/main/java/com/baeldung/factorygeneric/Record.java
patterns-modules/design-patterns-creational/src/main/java/com/baeldung/factorygeneric/StringNotifier.java
patterns-modules/design-patterns-creational/src/test/java/com/baeldung/factorygeneric/FactoryGenericUnitTest.java

Fixing package names in source code.

bael-5851 - quick fix - Factory Pattern with Generics in Java

---

persistence-modules/pom.xml
persistence-modules/spring-boot-persistence-mongodb-2/README.md
persistence-modules/spring-boot-persistence-mongodb-3/README.md
persistence-modules/spring-boot-persistence-mongodb-3/pom.xml
persistence-modules/spring-boot-persistence-mongodb-3/src/main/java/com/baeldung/boot/hashmap/SpringBootHashMapApplication.java
persistence-modules/spring-boot-persistence-mongodb-3/src/main/resources/application.properties
persistence-modules/spring-boot-persistence-mongodb-3/src/test/java/com/baeldung/boot/hashmap/MongoDbHashMapIntegrationTest.java
persistence-modules/spring-boot-persistence-mongodb-3/src/test/resources/embedded.properties
persistence-modules/spring-boot-persistence-mongodb-3/src/test/resources/logback-test.xml

Draft: https://drafts.baeldung.com/wp-admin/post.php?post=146749&action=edit

bael-5848 - How to Insert a HashMap Into MongoDB With Java

---

core-java-modules/core-java-collections-maps-2/pom.xml

pom.xml - update streamex dependency so MergeMaps compiles on java 17

---

spring-security-modules/spring-security-web-boot-4/src/main/java/com/baeldung/enablemethodsecurity/EnableMethodSecurityApplication.java
spring-security-modules/spring-security-web-boot-4/src/main/java/com/baeldung/enablemethodsecurity/authentication/CustomUserDetailService.java
spring-security-modules/spring-security-web-boot-4/src/main/java/com/baeldung/enablemethodsecurity/authorization/CustomAuthorizationManager.java
spring-security-modules/spring-security-web-boot-4/src/main/java/com/baeldung/enablemethodsecurity/configuration/SecurityConfig.java
spring-security-modules/spring-security-web-boot-4/src/main/java/com/baeldung/enablemethodsecurity/controller/ResourceController.java
spring-security-modules/spring-security-web-boot-4/src/main/java/com/baeldung/enablemethodsecurity/services/Policy.java
spring-security-modules/spring-security-web-boot-4/src/main/java/com/baeldung/enablemethodsecurity/services/PolicyEnum.java
spring-security-modules/spring-security-web-boot-4/src/main/java/com/baeldung/enablemethodsecurity/services/PolicyService.java
spring-security-modules/spring-security-web-boot-4/src/main/java/com/baeldung/enablemethodsecurity/user/SecurityUser.java
spring-security-modules/spring-security-web-boot-4/src/test/java/com/baeldung/enablemethodsecurity/EnableMethodSecurityIntegrationTest.java
spring-security-modules/spring-security-web-boot-4/src/test/java/com/baeldung/enablemethodsecurity/EnableMethodSecurityTest.java

spring security using @EnableMethodSecurity with a custom authorization manager

[ BAEL-5804 ] Spring @EnableMethodSecurity annotation

---

core-java-modules/core-java-exceptions-4/src/main/java/com/baeldung/exception/exceptions_vs_errors/CheckedExceptionExcample.java
core-java-modules/core-java-exceptions-4/src/main/java/com/baeldung/exception/exceptions_vs_errors/ErrorExample.java
core-java-modules/core-java-exceptions-4/src/main/java/com/baeldung/exception/exceptions_vs_errors/RuntimeExceptionExample.java
core-java-modules/core-java-exceptions-4/src/test/java/com/baeldung/exception/exceptions_vs_errors/ErrorExampleUnitTest.java
core-java-modules/core-java-exceptions-4/src/test/java/com/baeldung/exception/exceptions_vs_errors/RuntimeExceptionExampleUnitTest.java

JIRA: https://jira.baeldung.com/browse/BAEL-6008

Added the code for "Errors and Exceptions in Java".

---

core-java-modules/core-java-collections-array-list/src/main/java/com/baeldung/defaultarraylistcapacity/DefaultArrayListCapacity.java
core-java-modules/core-java-collections-array-list/src/test/java/com/baeldung/defaultarraylistcapacity/DefaultArrayListCapacityUnitTest.java

BAEL-5931: Default Capacity of ArrayList

---

testing-modules/selenium-junit-testng/pom.xml
testing-modules/selenium-junit-testng/src/main/java/com/baeldung/selenium/config/SeleniumConfig.java
testing-modules/selenium-junit-testng/src/main/java/com/baeldung/selenium/tabs/TabHelper.java
testing-modules/selenium-junit-testng/src/test/java/com/baeldung/selenium/clickusingjavascript/SeleniumJavaScriptClickLiveTest.java
testing-modules/selenium-junit-testng/src/test/java/com/baeldung/selenium/cookies/SeleniumCookiesJUnitLiveTest.java
testing-modules/selenium-junit-testng/src/test/java/com/baeldung/selenium/screenshot/TakeScreenShotSeleniumLiveTest.java
testing-modules/selenium-junit-testng/src/test/java/com/baeldung/selenium/tabs/SeleniumBaseTest.java
testing-modules/selenium-junit-testng/src/test/java/com/baeldung/selenium/tabs/SeleniumTabsLiveTest.java
testing-modules/selenium-junit-testng/src/test/java/com/baeldung/selenium/tabs/SeleniumTestBase.java

https://jira.baeldung.com/browse/BAEL-4555
Upgraded Selenium to 4.6.0 because version >= 4.0 supports opening new tabs.

Bael 4555 selenium tab switching

---

core-java-modules/core-java-collections-4/src/main/java/com/baeldung/collections/stackreversal/ReverseStackUsingQueue.java
core-java-modules/core-java-collections-4/src/main/java/com/baeldung/collections/stackreversal/ReverseStackUsingRecursion.java
core-java-modules/core-java-collections-4/src/main/java/com/baeldung/collections/toarraycomparison/ToArrayBenchmark.java
core-java-modules/core-java-collections-4/src/test/java/com/baeldung/stackreversal/StackReversalUnitTest.java

- Contains two classes, for the algorithms discussed
- Unit Test case

[JAVA-6029] reversing a stack

---

core-java-modules/core-java-lambdas/src/main/java/com/baeldung/anonymousclass/EmailSenderService.java
core-java-modules/core-java-lambdas/src/main/java/com/baeldung/anonymousclass/Sender.java
core-java-modules/core-java-lambdas/src/main/java/com/baeldung/anonymousclass/SenderService.java
core-java-modules/core-java-lambdas/src/main/java/com/baeldung/anonymousclass/SmsSenderService.java
core-java-modules/core-java-lambdas/src/test/java/com/baeldung/anonymousclass/AnonymousClassToLambdaIntegrationTest.java

BAEL-5844: Convert Anonymous Class into Lambda in Java

---

testing-modules/assertion-libraries/src/main/java/com/baeldung/assertj/extracting/Address.java
testing-modules/assertion-libraries/src/main/java/com/baeldung/assertj/extracting/Person.java
testing-modules/assertion-libraries/src/main/java/com/baeldung/assertj/extracting/ZipCode.java
testing-modules/assertion-libraries/src/test/java/com/baeldung/assertj/extracting/AssertJExtractingUnitTest.java

JIRA: https://jira.baeldung.com/browse/BAEL-5976

[BAEL-5976]: Extract Values using AssertJ in Java

---

persistence-modules/hibernate-enterprise/src/main/java/com/baeldung/hibernate/exception/HibernateUtil.java
persistence-modules/hibernate-enterprise/src/main/java/com/baeldung/hibernate/exception/ProductEntity.java
persistence-modules/hibernate-enterprise/src/test/java/com/baeldung/hibernate/exception/HibernateExceptionUnitTest.java

BAEL-6018: HibernateSystemException: ids for this class must be manually assigned before calling save()

---

core-java-modules/core-java-string-operations-5/src/test/java/com/baeldung/splitstring/SplitStringUnitTest.java

- Using split() method of String class
- Using StringTokenizer class
- Using split() utility method of the StringUtils class

BAEL-6015: Split String by Whitespace in Java

---

core-java-modules/core-java-perf/src/main/java/com/baeldung/jmxshell/JmxCalculatorMain.java
core-java-modules/core-java-perf/src/main/java/com/baeldung/jmxshell/bean/Calculator.java
core-java-modules/core-java-perf/src/main/java/com/baeldung/jmxshell/bean/CalculatorMBean.java
core-java-modules/core-java-perf/src/main/java/com/baeldung/jmxshell/custom/JmxConnectionWrapper.java
core-java-modules/core-java-perf/src/main/java/com/baeldung/jmxshell/custom/JmxInvoker.java
core-java-modules/core-java-perf/src/main/resources/jmxshell/jmx-invoker.sh
core-java-modules/core-java-perf/src/main/resources/jmxshell/jmxclient.sh
core-java-modules/core-java-perf/src/main/resources/jmxshell/jmxterm.pl
core-java-modules/core-java-perf/src/main/resources/jmxshell/jmxterm.sh
core-java-modules/core-java-perf/src/test/java/com/baeldung/jmxshell/custom/JmxInvokerLiveTest.java

Draft: https://drafts.baeldung.com/wp-admin/post.php?post=147805&action=edit

BAEL 5842 - Calling JMX MBean Method from a Shell Script

---

core-java-modules/core-java-optional/src/main/java/com/baeldung/optionaluses/UserFoundException.java
core-java-modules/core-java-optional/src/main/java/com/baeldung/optionaluses/UserRepositoryWithOptional.java
core-java-modules/core-java-optional/src/test/java/com/baeldung/optionaluses/UsesForOptionalUnitTest.java

BAEL-6023: Throwing an Exception If an Optional Is Present

---

logging-modules/logback/pom.xml

Added logbak-core-1.3.5 to pom
Updated logback.version to 1.3.5
Added slf4j - 2.0.4 to pom
Updated javax.mail from 1.4.7 to com.sun.mail 1.6.2 
Updated javax.activation to javax.activation 1.2.0
Ran both mvn clean verify and
mvn exec:java -Dexec.mainClass="com.baeldung.logback.Example" without errors using jdk 1.8

Update Logback Article

---

core-java-modules/core-java/src/main/java/com/baeldung/anonymousclass/AnonymousClassExample.java
core-java-modules/core-java/src/main/java/com/baeldung/lambdaexpression/LambdaExpressionExample.java

BAEL-5929 added example for anonymous class and lambda expression

added an example of anonymous class and lambda expression

---

json-modules/json-2/src/main/java/com/baeldung/jsonvalidation/JacksonValidator.java

see https://github.com/FasterXML/jackson/discussions/143#discussioncomment-4479800

need to handle trailing tokens

---

core-java-modules/core-java-collections-array-list/pom.xml
core-java-modules/core-java-collections-array-list/src/main/java/com/baeldung/listofobjectstolistofstring/Node.java
core-java-modules/core-java-collections-array-list/src/main/java/com/baeldung/listofobjectstolistofstring/User.java
core-java-modules/core-java-collections-array-list/src/test/java/com/baeldung/listofobjectstolistofstring/ConvertObjectListToStringListUnitTest.java
core-java-modules/pom.xml
pom.xml

[JAVA-5730] convert list of objects to list of strings

---

persistence-modules/scylladb/pom.xml
persistence-modules/scylladb/src/main/java/com/baeldung/scylladb/ScylladbApplication.java
persistence-modules/scylladb/src/main/java/com/baeldung/scylladb/model/User.java
persistence-modules/scylladb/src/main/resources/application.yml
persistence-modules/scylladb/src/test/java/com/baeldung/scylladb/ScyllaDBApplicationLiveTest.java
persistence-modules/scylladb/src/test/java/com/baeldung/scylladb/ScylladbApplicationTest.java
persistence-modules/scylladb/src/test/resources/application.yml

Ticket : https://jira.baeldung.com/browse/BAEL-6073

BAEL-6073 added scylladb code

---

core-java-modules/core-java-exceptions-4/src/main/java/com/baeldung/exception/noenumconst/Priority.java
core-java-modules/core-java-exceptions-4/src/main/java/com/baeldung/exception/noenumconst/PriorityUtils.java
core-java-modules/core-java-exceptions-4/src/test/java/com/baeldung/exception/noenumconst/PriorityUtilsUnitTest.java

BAEL-6044: Fix the IllegalArgumentException: No enum const class

---

core-java-modules/core-java-lang-3/src/main/java/com/baeldung/transientkw/Book.java
core-java-modules/core-java-lang-3/src/test/java/com/baeldung/transientkw/TransientUnitTest.java

Add a new example for transient keyword for Strings when using **new** operator.

JAVA-17420 Update The transient Keyword in Java Article

---

core-java-modules/core-java-jvm-3/src/test/java/com/baeldung/inmemorycompilation/InMemoryCompilationUnitTest.java

Inverting condition to match the article.

BAEL-5999 - Compiling and Executing Code From a String in Java - quick fix

---

core-java-modules/core-java-networking-2/pom.xml
core-java-modules/core-java-networking-2/src/main/java/com/baeldung/mail/EmailService.java
core-java-modules/core-java-networking-2/src/main/java/com/baeldung/mail/mailwithattachment/MailWithAttachmentService.java
core-java-modules/core-java-networking-2/src/test/java/com/baeldung/download/FileDownloadIntegrationTest.java
core-java-modules/core-java-networking-2/src/test/java/com/baeldung/mail/EmailServiceLiveTest.java
core-java-modules/core-java-networking-2/src/test/java/com/baeldung/mail/mailwithattachment/MailWithAttachmentServiceLiveTest.java
core-java-modules/core-java-networking-3/pom.xml
core-java-modules/core-java-networking-3/src/main/java/com/baeldung/downloadattachments/DownloadEmailAttachments.java
logging-modules/logback/pom.xml

Upgrade javamail to the angus mail which is a successor of JavaMail/Jakarta Mail

JAVA-17293 Update Java Mail articles

---

core-java-modules/core-java-streams-4/src/main/java/com/baeldung/streams/streamtoiterable/StreamToIterable.java
core-java-modules/core-java-streams-4/src/test/java/com/baeldung/streams/streamtoiterable/StreamToIterableUnitTest.java

[JAVA-5783] stream to iterable

---

testing-modules/testing-libraries/pom.xml

Adding findbugs maven plugin dependencies

JAVA-16890 GitHub Issue: FindBugs should be SpotBugs

---

spring-5-webflux-2/src/main/java/com/baeldung/webflux/caching/ItemService.java
spring-5-webflux-2/src/test/java/com/baeldung/webflux/caching/MonoFluxResultCachingLiveTest.java

Replace the CacheMono with other implementation since, this will be removed in the [next release](https://projectreactor.io/docs/extra/snapshot/api/index.html?reactor/cache/CacheMono.html).

Java 16681

---

core-java-modules/core-java/src/main/java/com/baeldung/anonymousclass/AnonymousClassExample.java

BAEL-5929 - Lambda Expression vs. Anonymous Inner Class - quick fix

---

core-java-modules/core-java-time-measurements/src/main/java/com/baeldung/timer/NewsletterTask.java
core-java-modules/core-java-time-measurements/src/test/java/com/baeldung/timer/NewsletterTaskUnitManualTest.java
core-java-modules/core-java-time-measurements/src/test/java/com/baeldung/timer/NewsletterTaskUnitTest.java

Improvements to better understand the concept of `schedule` and `scheduleAtFixedRate`.

JAVA-17333 Update Java Timer Article

---

persistence-modules/spring-jdbc/src/main/java/com/baeldung/spring/jdbc/template/testing/EmployeeDAO.java
persistence-modules/spring-jdbc/src/test/java/com/baeldung/spring/jdbc/template/testing/EmployeeDAOUnitTest.java

BAEL-5742: Fix EmptyResultDataAccessException when using Jdbctemplate

---

spring-roo/pom.xml

Adding a note in the pom.xml regarding unsupported spring-roo

JAVA-17327 Fix and enable spring-roo module

---

.gitignore
apache-cxf-modules/cxf-aegis/src/test/java/com/baeldung/cxf/aegis/BaeldungIntegrationTest.java
jmeter/pom.xml

Cleanup files that are generated during build

JAVA-17765 Cleanup un-committed or un-ignored artifacts - Week 6 - 2023

---

core-java-modules/core-java-collections-maps-6/pom.xml
core-java-modules/core-java-collections-maps-6/src/main/java/com/baeldung/map/hashmapcopy/CopyingAHashMapToAnother.java
core-java-modules/core-java-collections-maps-6/src/test/java/com/baeldung/map/hashmapcopy/CopyHashMapIntoAnotherUnitTest.java
core-java-modules/pom.xml

[JAVA-6143] java copy from one hashmap to another

---

apache-libraries/src/main/java/com/baeldung/avro/util/serialization/AvroDeSerializer.java
apache-libraries/src/main/java/com/baeldung/avro/util/serialization/AvroSerializer.java
apache-libraries/src/test/java/com/baeldung/avro/util/serialization/AvroSerializerDeSerializerIntegrationTest.java

fix: Typos in Avro module

---

core-java-modules/core-java-17/src/main/java/com/baeldung/java8to17/Address.java
core-java-modules/core-java-17/src/main/java/com/baeldung/java8to17/Circle.java
core-java-modules/core-java-17/src/main/java/com/baeldung/java8to17/Person.java
core-java-modules/core-java-17/src/main/java/com/baeldung/java8to17/Rectangle.java
core-java-modules/core-java-17/src/main/java/com/baeldung/java8to17/Shape.java
core-java-modules/core-java-17/src/main/java/com/baeldung/java8to17/Student.java
core-java-modules/core-java-17/src/test/java/com/baeldung/java17/Java8to17ExampleUnitTest.java

Hello Saajan,
Hope you are doing well!
I have completed the draft and created the PR:
Draft Link: https://drafts.baeldung.com/wp-admin/post.php?post=143326&action=edit
Palani

BAEL-6154: Migrate from Java 8 to Java 17 + tests

---

core-java-modules/core-java-annotations/src/main/java/com/baeldung/annotations/ClassWithSuppressWarningsNames.java

BAEL-4143 - quick fix - @SuppressWarnings("deprecation")

---

spring-web-modules/spring-mvc-basics-4/src/main/java/com/baeldung/config/WebConfig.java
spring-web-modules/spring-mvc-basics-4/src/test/java/com/baeldung/controller/PassParametersControllerIntegrationTest.java
spring-web-modules/spring-mvc-basics-4/src/test/java/com/baeldung/optionalpathvars/ArticleViewerControllerWithRequiredAttributeIntegrationTest.java

Add some improvements to the migration mvc to spring boot

JAVA-14723 Some additional improvements

---

pom.xml

JAVA-18133 Upgrade drools module to JDK 11

---

feign/src/main/java/com/baeldung/core/client/FormClient.java
feign/src/main/java/com/baeldung/core/defaulterrorhandling/model/FormData.java
feign/src/test/java/com/baeldung/core/client/FormClientUnitTest.java

Ticket : https://jira.baeldung.com/browse/BAEL-5294

BAEL-5294 added form-url-encoded data code

---

jackson-modules/jackson-exceptions/src/main/java/com/baeldung/exceptions/Contact.java
jackson-modules/jackson-exceptions/src/main/java/com/baeldung/exceptions/Person.java
jackson-modules/jackson-exceptions/src/main/java/com/baeldung/exceptions/PersonContact.java
jackson-modules/jackson-exceptions/src/test/java/com/baeldung/exceptions/JacksonExceptionsUnitTest.java

BAEL-6076: Resolving Jackson JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token

---

core-java-modules/core-java-reflection-private-constructor/README.md
core-java-modules/core-java-reflection-private-constructor/pom.xml
core-java-modules/core-java-reflection-private-constructor/src/main/java/com/baeldung/reflection/PrivateConstructorClass.java
core-java-modules/core-java-reflection-private-constructor/src/test/java/com/baeldung/reflection/PrivateConstructorUnitTest.java

Pull request for https://jira.baeldung.com/browse/BAEL-5788

[BAEL-5788] Accessing Private Constructor

---

persistence-modules/spring-persistence-simple/src/main/resources/com/baeldung/spring/jndi/datasource/mock/datasource.properties
persistence-modules/spring-persistence-simple/src/test/java/com/baeldung/spring/jndi/datasource/mock/SimpleJNDIUnitTest.java

BAEL-3830 - Test a Mock JNDI Datasource with Spring - quick fix

---

spring-cloud-modules/spring-cloud-kubernetes/kubernetes-guide/client-service/Dockerfile
spring-cloud-modules/spring-cloud-kubernetes/kubernetes-guide/travel-agency-service/Dockerfile

JAVA-13609: fix jar version

---

libraries-2/pom.xml
libraries-2/src/main/resources/com/baeldung/process/helloworld.bpmn
libraries-2/src/test/java/com/baeldung/jbpm/WorkflowEngineIntegrationTest.java

Fixing failed Integration test

JAVA-18149 Fixing failed integration test

---

core-java-modules/core-java-streams-4/src/main/java/com/baeldung/streams/parallelstream/Book.java
core-java-modules/core-java-streams-4/src/main/java/com/baeldung/streams/parallelstream/BookSpliterator.java
core-java-modules/core-java-streams-4/src/main/java/com/baeldung/streams/parallelstream/MyBookContainer.java
core-java-modules/core-java-streams-4/src/main/java/com/baeldung/streams/parallelstream/ParallelStreamApplication.java
core-java-modules/core-java-streams-4/src/main/java/com/baeldung/streams/parallelstream/ParallelStreamDifferences.java
core-java-modules/core-java-streams-4/src/test/java/parallelstream/ParallelStreamUnitTest.java

[JAVA-6173] Difference Between parallelStream() and stream().parallel() 

---

spring-kafka/pom.xml
spring-kafka/src/main/java/com/baeldung/monitoring/LagAnalyzerApplication.java
spring-kafka/src/main/java/com/baeldung/monitoring/service/LagAnalyzerService.java
spring-kafka/src/main/java/com/baeldung/monitoring/service/LiveLagAnalyzerService.java
spring-kafka/src/main/java/com/baeldung/monitoring/simulation/ConsumerSimulator.java
spring-kafka/src/main/java/com/baeldung/monitoring/simulation/KafkaConsumerConfig.java
spring-kafka/src/main/java/com/baeldung/monitoring/simulation/ProducerSimulator.java
spring-kafka/src/main/resources/application.properties

Expose Kafka Consumer Metrics via Actuator Endpoint
[BAEL-5170](https://jira.baeldung.com/browse/BAEL-5170)

BAEL-5170: Expose Kafka Consumer Metrics via Actuator Endpoint

---

jackson-modules/jackson-core/src/main/java/com/baeldung/jackson/deserialization/jsongeneric/JsonResponse.java
jackson-modules/jackson-core/src/main/java/com/baeldung/jackson/deserialization/jsongeneric/User.java
jackson-modules/jackson-core/src/test/java/com/baeldung/jackson/deserialization/jsongeneric/GenericTypeDeserializerUnitTest.java

Title: Deserialize Generic Type with Jackson
JIRA ticket: https://jira.baeldung.com/browse/BAEL-6203
Draft link: https://drafts.baeldung.com/wp-admin/post.php?post=158960&action=edit

[BAEL-6203] Deserialize Generic Type with Jackson

---

core-java-modules/core-java-19/src/main/java/com/baeldung/highcpu/Application.java

Title: What is “Possible Root Causes for High CPU Usages in Java"
JIRA ticket: https://jira.baeldung.com/browse/BAEL-4496
Draft link: https://drafts.baeldung.com/wp-admin/post.php?post=159706&action=edit

Add application file for BAEL-4496

---

jackson-modules/jackson-conversions/pom.xml
jackson-modules/jackson-conversions/src/main/java/com/baeldung/jackson/map/Fruit.java
jackson-modules/jackson-conversions/src/test/java/com/baeldung/jackson/map/MapWithJsonKeyValueUnitTest.java

Introduce @JsonKey annotation for Map serialization
[BAEL-6370](https://jira.baeldung.com/browse/BAEL-6307)

BAEL-6370: Introduce @JsonKey annotation for Map serialization

---

mapstruct/src/main/java/com/baeldung/dto/ArticleDTO.java
mapstruct/src/main/java/com/baeldung/entity/Article.java
mapstruct/src/main/java/com/baeldung/mapper/ArticleMapper.java
mapstruct/src/main/java/com/baeldung/mapper/ArticleUsingPersonMapper.java
mapstruct/src/test/java/com/baeldung/mapper/ArticleMapperUnitTest.java

https://jira.baeldung.com/browse/BAEL-6216

BAEL-6216 Use Mapper in Another Mapper with Mapstruct and Java

---

pom.xml

Reverts eugenp/tutorials#13823

Revert "JAVA-19475: Changes made for uncommenting feign module in the root po…"

---

spring-boot-modules/spring-boot-data-3/pom.xml
spring-boot-modules/spring-boot-data-3/src/main/java/com/baeldung/nopropertyfound/NoPropertyFoundApplication.java
spring-boot-modules/spring-boot-data-3/src/main/java/com/baeldung/nopropertyfound/config/DbConfig.java
spring-boot-modules/spring-boot-data-3/src/main/java/com/baeldung/nopropertyfound/model/Person.java
spring-boot-modules/spring-boot-data-3/src/main/java/com/baeldung/nopropertyfound/repository/PersonRepository.java
spring-boot-modules/spring-boot-data-3/src/main/resources/application.properties
spring-boot-modules/spring-boot-data-3/src/main/resources/data.sql
spring-boot-modules/spring-boot-data-3/src/main/resources/schema.sql
spring-boot-modules/spring-boot-data-3/src/test/java/com/baeldung/nopropertyfound/PersonRepositoryIntegrationTest.java

BAEL-6110: Fix Spring Data JPA Exception: No Property Found for Type

---

jackson-modules/jackson-exceptions/src/main/java/com/baeldung/mappingexception/Country.java
jackson-modules/jackson-exceptions/src/test/java/com/baeldung/mappingexception/JacksonMappingExceptionUnitTest.java

+ Add a new class: Country
+ Add two tests: givenJsonWithInvalidList_whenDeserializing_thenThrowException and givenJsonWithvalidList_whenDeserializing_thenCorrect
+ Remove _final_ from test methods

BAEL-5737: Fix the JsonMappingException: Can not deserialize instance of java.util.ArrayList

---

core-java-modules/core-java-string-algorithms/src/main/java/com/baeldung/reverse/ReverseStringExamples.java
core-java-modules/core-java-string-algorithms/src/test/java/com/baeldung/reverse/ReverseStringExamplesUnitTest.java

+ Add methods to inverse a given string using Stream API
+ Add test cases

BAEL-6435: Reverse a String in Java 8 using Lambda and Streams

---

persistence-modules/spring-boot-persistence-h2/src/main/java/com/baeldung/h2/exceptions/SpringBootH2Exceptions.java
persistence-modules/spring-boot-persistence-h2/src/main/java/com/baeldung/h2/exceptions/models/User.java
persistence-modules/spring-boot-persistence-h2/src/main/java/com/baeldung/h2/exceptions/repos/UserRepository.java
persistence-modules/spring-boot-persistence-h2/src/main/resources/app-h2.properties
persistence-modules/spring-boot-persistence-h2/src/main/resources/user-data.sql
persistence-modules/spring-boot-persistence-h2/src/test/java/com/baeldung/h2/exceptions/SpringBootH2ExceptionsIntegrationTest.java

+ Create new main app class
+ Add basic SQL script to seed H2 database with data
+ Add an entiy class named _User_
+ Add an IT

BAEL-6326: Spring Boot H2 JdbcSQLSyntaxErrorException

---

core-java-modules/core-java-records/pom.xml
core-java-modules/core-java-records/src/main/java/com/baeldung/equalshashcoderecords/Movie.java
core-java-modules/core-java-records/src/main/java/com/baeldung/equalshashcoderecords/Person.java
core-java-modules/core-java-records/src/test/java/com/baeldung/equalshashcoderecords/CustomRecordEqualsHashCode.java
core-java-modules/pom.xml

[BAEL-6253] record equals hashcode

---

core-java-modules/core-java-concurrency-basic-3/src/test/java/com/baeldung/concurrent/RequestProcessorUnitTest.java

in module: core-java-concurrency-basics-3

JAVA-19152: fix intermittently failing RequestProcessorUnitTest

---

core-java-modules/core-java-concurrency-advanced-4/src/main/java/com/baeldung/producerconsumer/Consumer.java
core-java-modules/core-java-concurrency-advanced-4/src/main/java/com/baeldung/producerconsumer/Producer.java
core-java-modules/core-java-concurrency-advanced-4/src/main/java/com/baeldung/producerconsumer/SimpleProducerConsumerDemonstrator.java

Minimal improvements to the code

BAEL-6501 Update article "The producer-consumer problem example in Java"

---

persistence-modules/pom.xml
persistence-modules/spring-boot-persistence-2/pom.xml
persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/boot/jdbi/JdbiConfiguration.java
persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/boot/jdbi/domain/CarModel.java
persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/boot/jdbi/mapper/CarModelMapper.java
persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/db/indexing/Image.java
persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/spring/oracle/pooling/entity/Book.java
persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/springboothsqldb/application/entities/Customer.java
persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/states/UserEntity.java
persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/states/UserEntityWithCascade.java
persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/tomcatconnectionpool/application/entities/Customer.java
persistence-modules/spring-boot-persistence-2/src/main/resources/com/baeldung/boot/jdbi/dao/CarMakerDao/insert.sql
persistence-modules/spring-boot-persistence-2/src/main/resources/com/baeldung/boot/jdbi/dao/CarModelDao/insert.sql
persistence-modules/spring-boot-persistence-2/src/test/java/com/baeldung/boot/jdbi/SpringBootJdbiApplicationIntegrationTest.java
persistence-modules/spring-boot-persistence-2/src/test/java/com/baeldung/db/indexing/FileSystemImageIntegrationTest.java
persistence-modules/spring-boot-persistence-2/src/test/java/com/baeldung/db/indexing/ImageIntegrationTest.java
persistence-modules/spring-boot-persistence-2/src/test/java/com/baeldung/springboothsqldb/application/tests/CustomerControllerIntegrationTest.java
persistence-modules/spring-boot-persistence-2/src/test/java/com/baeldung/states/UserEntityIntegrationTest.java
persistence-modules/spring-boot-persistence-2/src/test/resources/data.sql
persistence-modules/spring-boot-persistence-2/src/test/resources/schema.sql
persistence-modules/spring-boot-persistence-mongodb-2/pom.xml
persistence-modules/spring-boot-persistence-mongodb-3/pom.xml
persistence-modules/spring-boot-persistence-mongodb/pom.xml

Migrating spring boot modules with hibernate to jdk11

JAVA-20165 Upgrade spring-boot hibernate specific modules to JDK 11

---

aws-modules/aws-s3/src/main/java/com/baeldung/s3/AWSS3ObjectUtils.java
aws-modules/aws-s3/src/test/java/com/baeldung/s3/AWSS3ObjectIntegrationTest.java

[Check If a Specified Key Exists in a Given S3 Bucket using Java] added code examples

---

core-java-modules/core-java-collections-list-5/pom.xml
core-java-modules/core-java-collections-list-5/src/main/java/com/baeldung/arrayandlistperformance/ArrayAndArrayListPerformance.java

This commit is related to the article entitled "Array vs List Performance in Java"

Article: Array vs List Performance in Java

---

core-java-modules/core-java-io-conversions-2/src/main/java/com/baeldung/printstreamtostring/PrintStreamToStringUtil.java
core-java-modules/core-java-io-conversions-2/src/test/java/com/baeldung/printstreamtostring/PrintStreamToStringUtilUnitTest.java

+ Add methods to convert PrintStream to string
+ Add test cases

BAEL-6398: Java PrintStream to String

---

spring-reactive-modules/spring-reactive-exceptions/src/main/resources/application.yaml

This reverts commit 58d9bcb3b4cd8d79c8521945368722caef3bfc53.

Revert "JAVA-20280: remove wrong property (#13874)"

---

core-java-modules/core-java-collections-5/pom.xml
core-java-modules/core-java-collections-5/src/main/java/com/baeldung/customiterators/CustomMovieIterator.java
core-java-modules/core-java-collections-5/src/main/java/com/baeldung/customiterators/Movie.java
core-java-modules/core-java-collections-5/src/main/java/com/baeldung/customiterators/MyList.java
core-java-modules/core-java-collections-5/src/main/java/com/baeldung/customiterators/PalindromIterator.java
core-java-modules/core-java-collections-5/src/test/java/com/baeldung/customiterators/IteratorsUnitTest.java

[BAEL-6339] custom iterator with testcases

---

spring-web-modules/spring-resttemplate-3/src/test/java/com/baeldung/encoding/service/HttpBinServiceLiveTest.java

- Since it is making actual live request to httpbin.org

JAVA-20946 Renamed HttpBinServiceUnitTest to LiveTest

---

spring-reactive-modules/spring-reactive-exceptions/pom.xml
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/CustomExceptionApplication.java
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/config/ErrorDetailsSerializer.java
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/config/ProblemDetailsSerializer.java
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/controller/UserController.java
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/exception/CustomErrorException.java
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/exception/GlobalExceptionHandler.java
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/exception/UserNotFoundException.java
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/model/CustomErrorResponse.java
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/model/Error.java
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/model/ErrorDetails.java
spring-reactive-modules/spring-reactive-exceptions/src/main/java/com/baeldung/spring/reactive/customexception/model/User.java
spring-reactive-modules/spring-reactive-exceptions/src/test/java/com/baeldung/spring/reactive/customexception/controller/UserControllerUnitTest.java

This PR contains changes for the article BAEL-6086: Customize WebFlux Exceptions in Spring Boot 3

BAEL-6086: Customize WebFlux Exceptions in Spring Boot 3

---

persistence-modules/hibernate-annotations/src/test/java/com/baeldung/hibernate/creationupdatetimestamp/HibernateCreationUpdateTimestampIntegrationTest.java
persistence-modules/pom.xml
pom.xml

Fix failed Integration test and some adjustments in the pom.xml

JAVA-20163 Fix failed integration test with date creation comparison

---

core-java-modules/core-java-io-apis/src/main/java/com/baeldung/scanner/NextLineAfterNextMethods.java

BAEL-6460: Why is Scanner skipping nextLine() after using other next functions?

---

core-java-modules/core-java-collections-list-5/src/main/java/com/baeldung/list/Country.java
core-java-modules/core-java-collections-list-5/src/test/java/com/baeldung/java/list/ListContainsElementFromOtherListTest.java

Update to existing test case to improve the clarity of the example in the article.

BAEL-6334 Make object properties example clearer

---

core-java-modules/core-java-collections-maps-6/src/test/java/com/baeldung/maptojson/MapToJsonUnitTest.java

This PR is for Convert Hashmap to JSON object in Java

Convert Hashmap to JSON object in Java

---

pom.xml

Reverts eugenp/tutorials#14105

Revert "JAVA-19670: changes made for upgrading jenkins module to jdk-9 above"

---

jackson-simple/src/main/java/com/baeldung/jackson/objectmapper/ObjectMapperBuilder.java
jackson-simple/src/test/java/com/baeldung/jackson/objectmapper/ObjectMapperBuilderUnitTest.java

Add builder pattern for ObjectMapper creation
[BAEL-6293](https://jira.baeldung.com/browse/BAEL-6293)

BAEL-6293: Add builder pattern for ObjectMapper creation

---

core-java-modules/core-java-io-apis-2/src/main/java/com/baeldung/scanner/ScannerNoSuchElementException.java
core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/scanner/ScannerNoSuchElementExceptionUnitTest.java

BAEL-6465: How to handle NoSuchElementException when reading a file through a Scanner ?

---

core-java-modules/core-java-collections-maps-6/src/test/com/baeldung/objecttomap/ObjectToMapUnitTest.java

This PR is related to the article entitled "Converting Object To Map in Java"

Article: Converting Object To Map in Java

---

persistence-modules/querydsl/src/test/java/com/baeldung/dao/PersonDaoIntegrationTest.java

Updating the name of test methods

JAVA-20164 Renaming test methods

---

core-java-modules/core-java-io-2/src/test/java/com/baeldung/readlargefile/ReadLargeFileUnitTest.java

Add more methods to read large files

BAEL-6545: Update article https://www.baeldung.com/java-read-lines-large-file

---

core-java-modules/core-java-collections-list-5/src/test/java/com/baeldung/listtojson/ListToJsonArrayUnitTest.java

Hello there, 
The code provides a test class for a Java list to JSON conversion. Regards,
Mohamed.

Convert List to JSON

---

core-java-modules/core-java-booleans/src/test/java/com/baeldung/booleans/BooleanTrueVsTrueUnitTest.java

This PR is related to the article "Difference Between Boolean.TRUE and true in Java"

Difference Between Boolean.TRUE and true in Java

---

persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/listrepositories/entity/Person.java
persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/listrepositories/repository/PersonRepository.java
persistence-modules/spring-data-jpa-repo-3/src/main/resources/application.properties
persistence-modules/spring-data-jpa-repo-3/src/main/resources/data.sql
persistence-modules/spring-data-jpa-repo-3/src/main/resources/schema.sql
persistence-modules/spring-data-jpa-repo-3/src/test/java/com/baeldung/spring/data/jpa/listrepositories/repository/PersonRepositoryIntegrationTest.java

BAEL-6523: Difference Between findBy and findOneBy in Spring Data JPA

---

core-java-modules/core-java-19/pom.xml
core-java-modules/core-java-19/src/main/java/com/baeldung/vectors/VectorAPIExamples.java
core-java-modules/core-java-19/src/test/java/com/baeldung/vectors/VectorAPIUnitTest.java

[BAEL-6090] vector api examples

---

core-java-modules/core-java-streams-collect/pom.xml
maven-modules/dependency-exclusion/dummy-surefire-junit47/pom.xml
spring-boot-modules/spring-boot-3-url-matching/pom.xml
spring-boot-modules/spring-boot-aws/pom.xml

Java 20405 Align module names, folder names and artifact id - Week 18 - 2023 (moved-7)

---

spring-boot-modules/spring-boot-basic-customization/pom.xml
spring-boot-modules/spring-boot-basic-customization/src/main/java/com/baeldung/bootcustomfilters/SpringBootFiltersApplication.java
spring-boot-modules/spring-boot-basic-customization/src/main/java/com/baeldung/changeport/CustomApplication.java
spring-boot-modules/spring-boot-basic-customization/src/main/java/com/baeldung/errorhandling/ErrorHandlingApplication.java
spring-boot-modules/spring-boot-basic-customization/src/main/java/com/baeldung/failureanalyzer/FailureAnalyzerApplication.java
spring-boot-modules/spring-boot-basic-customization/src/main/java/com/baeldung/favicon/FaviconApplication.java
spring-boot-modules/spring-boot-basic-customization/src/test/java/com/baeldung/failureanalyzer/FailureAnalyzerAppIntegrationTest.java

Define main class when using multiple profiles in a Spring Boot project
[BAEL-6532](https://jira.baeldung.com/browse/BAEL-6532)

BAEL-6532: Define main class when using multiple profiles in a Spring Boot project

---

core-java-modules/core-java-date-operations-3/pom.xml
core-java-modules/core-java-date-operations-3/src/test/java/com/baeldung/date/AddOneMonthToCurrentDateUnitTest.java

+ Add tests for adding one month to the current date

BAEL-6397: Adding One Month to Current Date in Java

---

core-java-modules/core-java-date-operations-3/src/main/java/com/baeldung/lastdaymonth/LastDayOfMonth.java
core-java-modules/core-java-date-operations-3/src/test/java/com/baeldung/lastdaymonth/LastDayOfMonthUnitTest.java

BAEL-6597: How to get the last Day of the Month in Java

---

jackson-modules/jackson-core/src/test/java/com/baeldung/jackson/jsonnode/RemoveJsonElementsUnitTest.java

This PR adds a test class for removing JSON elements using the Jackson library.

Removing JSON elements with Jackson [BAEL-6511]

---

jackson-jr/src/main/java/com/baeldung/jacksonjr/MyHandlerProvider.java

Tudor jacksonjr2

---

core-java-modules/core-java-concurrency-simple/src/test/java/com/baeldung/concurrent/anonymousthread/AnonymousThreadUnitTest.java

Demonstrate how to start a thread using an Anonymous Class
[BAEL-6627](https://jira.baeldung.com/browse/BAEL-6627)

BAEL-6627: How to start a thread using an anonymous alass

---

spring-web-modules/spring-resttemplate-2/src/main/java/com/baeldung/resttemplate/RestTemplateApplication.java
spring-web-modules/spring-resttemplate-2/src/test/java/com/baeldung/resttemplate/postjson/RestTemplatePostRequestEncodingLiveTest.java

How to handle character encoding in JSON POST Request
[BAEL-6647](https://jira.baeldung.com/browse/BAEL-6647)

BAEL-6647: How to handle character encoding in JSON POST Request

---

json-modules/gson-2/src/main/java/com/baeldung/gson/entities/BankAccount.java
json-modules/gson-2/src/main/java/com/baeldung/gson/entities/Country.java
json-modules/gson-2/src/main/java/com/baeldung/gson/entities/Person.java
json-modules/gson-2/src/main/java/com/baeldung/gson/exposevsserializedname/PersonSerializer.java
json-modules/gson-2/src/test/java/com/baeldung/gson/exposevsserializedname/PersonSerializerUnitTest.java

JIRA BAEL-6693, difference between Gson @Expose and @SerializedName

---

core-java-modules/core-java-date-operations-3/src/test/java/com/baeldung/date/GetYesterdayDateUnitTest.java

BAEL-6399: Getting Yesterday's Date in Java

---

messaging-modules/spring-apache-camel/README.md
messaging-modules/spring-apache-camel/pom.xml
messaging-modules/spring-apache-camel/src/main/java/com/baeldung/camel/apache/file/cfg/ContentBasedFileRouterConfig.java

Upgrade to the latest camel version

JAVA-22210 Upgrade dependencies versions for spring-apache-camel module

---

core-java-modules/core-java-numbers-6/src/test/java/com/baeldung/integerclassintegertypeintclass/IntegerClassIntegerTYPEIntClassUnitTest.java

This PR aims to add a test class for the article BAEL-6418

 BAEL-6418

---

json-modules/json-2/src/main/java/com/baeldung/jsonprettyprinter/JsonPrettyPrinter.java
json-modules/json-2/src/test/java/com/baeldung/jsonprettyprinter/JsonPrettyPrinterUnitTest.java

Remove the wrong package statement.
Add System.out.println in tests for easier understanding.

[BAEL-6506] Address review comments

---

core-java-modules/core-java-lang-6/README.md
core-java-modules/core-java-lang-6/pom.xml
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/enums/mapping/EnumMapper.java
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/enums/mapping/order/CmsOrderStatus.java
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/enums/mapping/order/OrderStatus.java
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/enums/mapping/user/ExternalUserStatus.java
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/enums/mapping/user/UserStatus.java
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/enums/mapping/user/UserStatusMapper.java
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/enums/mapping/user/UserStatusWithFieldVariable.java
core-java-modules/core-java-lang-6/src/test/java/com/baeldung/enums/mapping/EnumConversionUnitTest.java
core-java-modules/pom.xml

- added new module core-java-lang-6
- added data model and test for enums

BAEL-6717 Convert One Enum to Another Enum in Java

---

microservices-modules/helidon/helidon-se/pom.xml
microservices-modules/helidon/helidon-se/src/main/java/com/baeldung/helidon/se/config/ConfigApplication.java
microservices-modules/helidon/helidon-se/src/main/java/com/baeldung/helidon/se/routing/BookResource.java
microservices-modules/helidon/helidon-se/src/main/java/com/baeldung/helidon/se/routing/WebApplicationRouting.java
microservices-modules/helidon/helidon-se/src/main/java/com/baeldung/helidon/se/security/MyUser.java
microservices-modules/helidon/helidon-se/src/main/java/com/baeldung/helidon/se/security/WebApplicationSecurity.java
microservices-modules/helidon/helidon-se/src/main/java/com/baeldung/helidon/se/webserver/SimpleWebApplication.java

Migration helidon-se dependencies to the latest version

JAVA-22211 Upgrade dependencies versions for helidon-se module

---

security-modules/java-ee-8-security-api/app-auth-basic-store-db/src/main/java/com/baeldung/javaee/security/AdminServlet.java
security-modules/java-ee-8-security-api/app-auth-basic-store-db/src/main/java/com/baeldung/javaee/security/AppConfig.java
security-modules/java-ee-8-security-api/app-auth-basic-store-db/src/main/java/com/baeldung/javaee/security/UserServlet.java
security-modules/java-ee-8-security-api/app-auth-basic-store-db/src/main/liberty/config/server.xml
security-modules/java-ee-8-security-api/pom.xml
security-modules/pom.xml

Move the the latest version of openLiberty library.

JAVA-23118 Fix java-ee-8-security-api module

---

core-java-modules/core-java-string-operations-6/src/main/java/com/baeldung/performance/BatchConcatBenchmark.java
core-java-modules/core-java-string-operations-6/src/main/java/com/baeldung/performance/LoopConcatBenchmark.java

BAEL-6725 - Performance Comparison Between Different Java String Concatenation Methods

BAEL-6725 - Performance Comparison Between Different Java String Concatenation Methods

---

json-modules/json-2/src/main/java/com/baeldung/jsonminifier/JsonMinifier.java
json-modules/json-2/src/test/java/com/baeldung/jsonminifier/JsonMinifierUnitTest.java

Add functionality to minify a JSON string

[BAEL-6494] Add functionality to minify a JSON string

---

logging-modules/logback/README.md
logging-modules/logback/pom.xml
logging-modules/logback/src/main/java/com/baeldung/parameterized/logging/FluentLoggingPlayground.java
logging-modules/logback/src/main/java/com/baeldung/parameterized/logging/LoggingPlayground.java
logging-modules/logback/src/main/resources/logback.xml

- updated logback-classic version
- updated logback.xml to have only one appender for new classes
- added sample parameterized logging and fluent logging

BAEL-6754 Parameterized Logging with Slf4j

---

microservices-modules/helidon/helidon-mp/pom.xml
microservices-modules/helidon/helidon-mp/src/main/java/com/baeldung/microprofile/LibraryApplication.java
microservices-modules/helidon/helidon-mp/src/main/java/com/baeldung/microprofile/providers/BookListMessageBodyWriter.java
microservices-modules/helidon/helidon-mp/src/main/java/com/baeldung/microprofile/providers/BookMessageBodyReader.java
microservices-modules/helidon/helidon-mp/src/main/java/com/baeldung/microprofile/providers/BookMessageBodyWriter.java
microservices-modules/helidon/helidon-mp/src/main/java/com/baeldung/microprofile/repo/BookManager.java
microservices-modules/helidon/helidon-mp/src/main/java/com/baeldung/microprofile/util/BookMapper.java
microservices-modules/helidon/helidon-mp/src/main/java/com/baeldung/microprofile/web/BookEndpoint.java

Upgrade dependencies of helidon-mp module

JAVA-23211 Upgrade dependencies versions for helidon-mp module

---

persistence-modules/spring-boot-persistence-4/pom.xml
persistence-modules/spring-boot-persistence-4/src/main/java/com/baeldung/scrollapi/ScrollAPIApplication.java
persistence-modules/spring-boot-persistence-4/src/main/java/com/baeldung/scrollapi/entity/BookReview.java
persistence-modules/spring-boot-persistence-4/src/main/java/com/baeldung/scrollapi/repository/BookRepository.java
persistence-modules/spring-boot-persistence-4/src/main/java/com/baeldung/scrollapi/service/BookLogic.java
persistence-modules/spring-boot-persistence-4/src/main/resources/application.yml
persistence-modules/spring-boot-persistence-4/src/test/java/com/baeldung/boot/scrollapi/service/BookLogicUnitTest.java
persistence-modules/spring-boot-persistence-4/src/test/resources/application.properties

JIRA : https://jira.baeldung.com/browse/BAEL-6512

Scroll API Implementation

---

persistence-modules/hibernate-annotations/pom.xml
persistence-modules/hibernate-annotations/src/main/java/com/baeldung/hibernate/primarykeyjoincolumn/Department.java
persistence-modules/hibernate-annotations/src/main/resources/META-INF/persistence.xml
persistence-modules/hibernate-annotations/src/test/java/com/baeldung/hibernate/primarykeyjoincolumn/PrimaryKeyJoinColumnIntegrationTest.java

Fix errors for PrimaryKeyJoinColumnIntegrationTest

JAVA-23344 Fix failing tests in hibernate-annotations

---

core-java-modules/core-java-networking-4/src/main/java/com/baeldung/socketexception/brokenpipe/Client.java
core-java-modules/core-java-networking-4/src/main/java/com/baeldung/socketexception/brokenpipe/Server.java

https://drafts.baeldung.com/wp-admin/post.php?post=168213&action=edit
jira: https://jira.baeldung.com/browse/BAEL-4895

BAEL-4895 brokenpipe error

---

core-java-modules/core-java-collections-maps-6/src/test/java/com/baeldung/strringtomap/StringToMapUnitTest.java

This PR aims to add a test class namely (StringToMapUnitTest) that tests the conversion of string and string array into map.

This PR is for the article BAEL-6792

---

core-java-modules/core-java-string-conversions-3/src/java.com.baeldung.multivluehashmap/MultiValueHashMapTest.java

This PR aims to add a test class (MultiValueHashMapTest) to test the HashMap that allows multiple values to be associated with the same key

This PR is for the article BAEL-6788

---

apache-poi-2/src/main/java/com/baeldung/poi/excel/locksheet/LockSheet.java
apache-poi-2/src/test/java/com/baeldung/poi/excel/locksheet/LockSheetUnitTest.java

https://jira.baeldung.com/browse/BAEL-6521

BAEL-6521 - Lock Header Rows with Apache POI

---

core-java-modules/core-java-string-conversions-3/src/main/java/com/baeldung/hashmapmultivalues/MultiValueHashMap.java
core-java-modules/core-java-string-conversions-3/src/test/java/com/baeldung/hashmapmultivalues/MultiValueHashMapUnitTest.java

This PR aims to add java classes for the HashMap multi values operations with same key

This PR is for BAEL-6788

---

core-java-modules/core-java-lang-oop-types/pom.xml
pom.xml

JAVA-24054 Upgrade java-enum-values article

---

core-java-modules/core-java-lang-oop-inheritance/src/main/java/com/baeldung/subclassinnerclass/EmailNotifier.java
core-java-modules/core-java-lang-oop-inheritance/src/main/java/com/baeldung/subclassinnerclass/Message.java
core-java-modules/core-java-lang-oop-inheritance/src/main/java/com/baeldung/subclassinnerclass/NotificationService.java
core-java-modules/core-java-lang-oop-inheritance/src/main/java/com/baeldung/subclassinnerclass/Notifier.java
core-java-modules/core-java-lang-oop-inheritance/src/main/java/com/baeldung/subclassinnerclass/TextMessageNotifier.java
core-java-modules/core-java-lang-oop-inheritance/src/test/java/com/baeldung/subclassinnerclass/InnerClassUnitTest.java
core-java-modules/core-java-lang-oop-inheritance/src/test/java/com/baeldung/subclassinnerclass/SubClassUnitTest.java

[BAEL-6859] Inner Classes vs. Subclasses in Java

---

core-java-modules/core-java-lang-oop-patterns/src/main/java/com/baeldung/deepcopyarraylist/Course.java
core-java-modules/core-java-lang-oop-patterns/src/main/java/com/baeldung/deepcopyarraylist/Student.java
core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/deepcopyarraylist/DeepCopyArrayListUnitTest.java

Override Equals method so that we can verify that the objects are equal but not same.

BAEL-6771 Improvement

---

json-modules/json-2/pom.xml
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/configuration/AdvancedArticle.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/configuration/AdvancedConfigurationSchemaGenerator.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/configuration/AllowedTypes.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/configuration/IndividualConfigurationSchemaGenerator.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/modules/JacksonModuleSchemaGenerator.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/modules/JakartaValidationModuleSchemaGenerator.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/plugin/Person.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/recursive/Author.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/recursive/AuthoredArticle.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/recursive/RecursiveSchemaGenerator.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/simple/Article.java
json-modules/json-2/src/main/java/com/baeldung/jsonschemageneration/simple/SimpleSchemaGenerator.java
json-modules/json-2/src/main/resources/schemas/com/baeldung/jsonschemageneration/plugin/Person.json

See https://jira.baeldung.com/browse/BAEL-3325

BAEL-3325: Programmatic generation of JSON Schemas in Java 

---

core-java-modules/core-java-io/pom.xml
core-java-modules/core-java-io/src/test/java/com/baeldung/mimetype/MimeTypeUnitTest.java

JAVA-24055 Upgrade reading-file-in-java article

---

core-java-modules/core-java-collections-set-2/pom.xml
core-java-modules/core-java-collections-set-2/src/main/java/com/baeldung/cartesianproduct/CartesianProduct.java
core-java-modules/core-java-collections-set-2/src/test/java/com/baeldung/cartesianproduct/CartesianProductUnitTest.java

Calculate Cartesian Product using various approaches

[BAEL-6708] Add Cartesian Product

---

core-java-modules/core-java-17/src/test/java/com/baeldung/multipleorwithif/MultipleOrWithIfUnitTest.java

How to format multiple or condition with an if statement unit tests

BAEL-6774: format multiple or in an if

---

core-java-modules/core-java-string-operations/pom.xml
core-java-modules/core-java-string-operations/src/test/java/com/baeldung/base64encodinganddecoding/StringToByteArrayUnitTest.java

JAVA-24051 Upgrade java-base64-encode-and-decode

---

core-java-modules/core-java-arrays-operations-advanced/src/main/java/com/baeldung/arraymiddle/MiddleOfArray.java
core-java-modules/core-java-arrays-operations-advanced/src/test/java/com/baeldung/arraymiddle/MiddleOfArrayUnitTest.java

[BAEL-6823] middle of array

---

pom.xml

This reverts commit 66bee175a72090c564374d7bf1911d51e2548698.

Revert "JAVA-24559 moved bookstore-monolith to heavy profile"

---

core-java-modules/core-java-collections-maps/src/test/java/com/baeldung/map/UsingtoStringUnitTest.java

This PR aims to add a new test class to convert a HashMap string into a HashMap object using toString().

This PR related to the article BAEL-6877

---

core-java-modules/core-java-collections-maps/src/main/java/com/baeldung/map/MapClear.java
core-java-modules/core-java-collections-maps/src/test/java/com/baeldung/map/MapClearUnitTest.java

Creating pull request for showing map clear() vs making new Map difference in Java

BAEL-6142 Map clear methods in Java

---

core-java-modules/core-java-collections-set-2/pom.xml
core-java-modules/core-java-collections-set-2/src/main/java/com/baeldung/indexawareset/IndexOfElementsInSet.java
core-java-modules/core-java-collections-set-2/src/main/java/com/baeldung/indexawareset/InsertionIndexAwareSet.java
core-java-modules/core-java-collections-set-2/src/test/java/com/baeldung/indexawareset/IndexOfSetElementsUsingListUnitTest.java

BAEL-6838-index-of-set-element

---

core-java-modules/core-java-io/src/test/java/com/baeldung/extension/ExtensionFromMimeTypeUnitTest.java

Fix implementation by using ContentType enum.

[BAEL-6730] Use ContentType to fetch the extensions

---

apache-poi-3/pom.xml
apache-poi-3/src/test/java/com/baeldung/poi/excel/expandcolumn/ExpandColumnUnitTest.java
pom.xml

BAEL-6522: Expand Columns with Apache POI

BAEL-6522: Expand Columns with Apache POI

---

core-java-modules/core-java-collections-conversions-3/README.md
core-java-modules/core-java-collections-conversions-3/pom.xml
core-java-modules/core-java-collections-conversions-3/src/main/java/com/baeldung/hashmaptoarraylist/HashMapToArrayListConverterUtils.java
core-java-modules/core-java-collections-conversions-3/src/test/java/com/baeldung/hashmaptoarraylist/HashMapToArrayListConverterUtilsUnitTest.java

+ Create a new module
+ Add methods to convert HashMap to ArrayList
+ Add unit tests

BAEL-6783: Converting HashMap to an ArrayList in Java

---

core-java-modules/core-java-21/pom.xml
core-java-modules/core-java-21/src/main/java/com/baeldung/stringtemplates/StringCompositionTechniques.java
core-java-modules/core-java-21/src/main/java/com/baeldung/stringtemplates/StringTemplateExamples.java
core-java-modules/core-java-21/src/test/java/com.baeldung.stringtemplates/StringTemplatesUnitTest.java

[BAEL-6956] string templates

---

core-java-modules/core-java-lang-6/pom.xml
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/compareobjects/Address.java
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/compareobjects/Person.java
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/compareobjects/PersonDiffBuilder.java
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/compareobjects/PersonReflectionDiffBuilder.java
core-java-modules/core-java-lang-6/src/main/java/com/baeldung/compareobjects/PhoneNumber.java
core-java-modules/core-java-lang-6/src/test/java/com/baeldung/compareobjects/PersonDiffBuilderUnitTest.java
core-java-modules/core-java-lang-6/src/test/java/com/baeldung/compareobjects/PersonReflectionDiffBuilderUnitTest.java

https://jira.baeldung.com/browse/BAEL-6871

BAEL-6871: Using the Apache Commons Lang 3 for Comparing Objects in Java

---

spring-boot-modules/spring-boot-3/pom.xml
spring-boot-modules/spring-boot-3/src/main/java/com/baeldung/restclient/Article.java
spring-boot-modules/spring-boot-3/src/main/java/com/baeldung/restclient/ArticleController.java
spring-boot-modules/spring-boot-3/src/main/java/com/baeldung/restclient/RestClientApplication.java
spring-boot-modules/spring-boot-3/src/test/java/com/baeldung/restclient/RestClientIntegrationTest.java

https://drafts.baeldung.com/wp-admin/post.php?post=176239&action=edit

BAEL-6911 A Guide to RestClient in Spring Boot

---

spring-reactive-modules/spring-5-reactive/src/main/java/com/baeldung/reactive/controller/PathPatternController.java
spring-reactive-modules/spring-5-reactive/src/main/java/com/baeldung/reactive/urlmatch/ExploreSpring5URLPatternUsingRouterFunctions.java
spring-reactive-modules/spring-5-reactive/src/test/java/com/baeldung/reactive/urlmatch/ExploreSpring5URLPatternUsingRouterFunctionsIntegrationTest.java
spring-reactive-modules/spring-5-reactive/src/test/java/com/baeldung/reactive/urlmatch/PathPatternsUsingHandlerMethodIntegrationTest.java

JAVA-24463 Fixing Failed tests from spring-5-reactive

---

microservices-modules/micronaut/pom.xml
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/apiversioning/custom/client/BirdCountClient.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/apiversioning/custom/server/BirdCountController.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/apiversioning/custom/server/CustomVersionResolver.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/apiversioning/header/client/DogCountClient.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/apiversioning/header/server/DogCountController.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/apiversioning/param/client/CatCountClient.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/apiversioning/param/server/CatCountController.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/apiversioning/url/client/SheepCountClient.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/apiversioning/url/server/SheepCountControllerV1.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/apiversioning/url/server/SheepCountControllerV2.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/helloworld/client/ConcreteGreetingClient.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/helloworld/server/controller/AsyncGreetController.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/helloworld/server/controller/GreetController.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/helloworld/server/service/EnglishGreetingService.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/helloworld/server/service/SpanishGreetingService.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/vs/springboot/CompareApplication.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/vs/springboot/client/ArithmeticClientImpl.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/vs/springboot/controller/ArithmeticController.java
microservices-modules/micronaut/src/main/java/com/baeldung/micronaut/vs/springboot/service/ArithmeticService.java
microservices-modules/micronaut/src/main/resources/application.yml
microservices-modules/micronaut/src/main/resources/logback.xml
microservices-modules/micronaut/src/test/java/com/baeldung/micronaut/apiversioning/custom/client/BirdCountClientUnitTest.java
microservices-modules/micronaut/src/test/java/com/baeldung/micronaut/apiversioning/header/client/DogCountClientUnitTest.java
microservices-modules/micronaut/src/test/java/com/baeldung/micronaut/apiversioning/param/client/CatCountClientUnitTest.java
microservices-modules/micronaut/src/test/java/com/baeldung/micronaut/apiversioning/url/client/SheepCountClientUnitTest.java
microservices-modules/micronaut/src/test/java/com/baeldung/micronaut/helloworld/client/ConcreteGreetingClientUnitTest.java
microservices-modules/micronaut/src/test/java/com/baeldung/micronaut/helloworld/client/GreetingClientUnitTest.java
microservices-modules/micronaut/src/test/java/com/baeldung/micronaut/vs/springboot/ArithmeticClientUnitTest.java

https://jira.baeldung.com/browse/BAEL-6917

Bael 6917/api versioning micronaut

---

core-java-modules/core-java-string-apis/src/test/java/com/baeldung/charsequence/CharSequenceVsStringUnitTest.java

+ Add a section to talk about how to convert CharSequence to String

BAEL-7057: How to convert CharSequence to String?

---

core-java-modules/core-java-arrays-convert/src/main/java/com/baeldung/array/conversions/CharArrayToIntArrayUtils.java
core-java-modules/core-java-arrays-convert/src/test/java/com/baeldung/array/conversions/CharArrayToIntArrayUtilsUnitTest.java

BAEL-6714: Convert Char Array to Int Array in Java

---

mapstruct/src/main/java/com/baeldung/expression/dto/LicenseDto.java
mapstruct/src/main/java/com/baeldung/expression/mapper/LicenseMapper.java
mapstruct/src/main/java/com/baeldung/expression/model/License.java
mapstruct/src/test/java/com/baeldung/expression/mapper/LicenseMapperUnitTest.java

BAEL-7032: Improvement to conditional mapping by using @Condition

---

core-java-modules/core-java-18/pom.xml
core-java-modules/core-java-18/src/main/java/com/baeldung/finalization_closeable_cleaner/FinalizationExamples.java
core-java-modules/core-java-18/src/main/java/com/baeldung/finalization_closeable_cleaner/MyCleanerResourceClass.java
core-java-modules/core-java-18/src/main/java/com/baeldung/finalization_closeable_cleaner/MyCloseableResourceClass.java
core-java-modules/core-java-18/src/main/java/com/baeldung/finalization_closeable_cleaner/MyFinalizableResourceClass.java
core-java-modules/core-java-18/src/main/resources/file.txt
core-java-modules/core-java-18/src/test/java/com/baeldung/finalization_closeable_cleaner/FinalizationCloseableCleanerUnitTest.java

[BAEL-6955] finalization deprcation

---

core-java-modules/core-java-16/src/main/java/com/baeldung/value_based_class/Point.java
core-java-modules/core-java-16/src/test/java/com/baeldung/value_based_class/ValueBasedClassUnitTest.java

[BAEL-7035] improvement to value based class

---

algorithms-modules/algorithms-miscellaneous-7/src/main/java/com/baeldung/algorithms/rotatearray/RotateArray.java
algorithms-modules/algorithms-miscellaneous-7/src/test/java/com/baeldung/algorithms/rotatearray/RotateArrayUnitTest.java

Algorithms for array rotation in Java. Unit testing added

BAEL-6913 - Rotate array in java

---

core-java-modules/core-java-string-conversions-3/src/test/java/com/baeldung/stringsplitkeyvalue/StringSplitKeyValueUnitTest.java

This PR aims to add a new test class to split Java String into Key-Value pairs

This PR related to the article BAEL-6784

---

core-java-modules/core-java-collections-maps-7/src/test/java/com/baeldung/map/writehashmaptocsvfile/WriteHashmaptoCVSFileUnitTest.java

This PR aims to add a new test class named "WriteHashmaptoCVSFileUnitTest.java" that explains how to write HashMap to a CSV file.

This PR is related to the article BAEL-7017

---

core-java-modules/core-java-string-operations-7/README.md
core-java-modules/core-java-string-operations-7/pom.xml
core-java-modules/core-java-string-operations-7/src/test/java/com/baeldung/centertext/CenteringTextUnitTest.java
core-java-modules/pom.xml

This PR aims to add a test class 'CenteringTextUnitTest.java' proposing several ways to center text in Java. Moreover, this PR updates the pom file with necessary dependencies.

 This PR related to the article BAEL-7023

---

core-java-modules/core-java-networking/src/test/java/com/baeldung/networking/url/UrlUnitTest.java

JAVA-20429 : Used URI constructions instead of the deprecated URL constructors.

JAVA-20429 : Used URI() instead of the deprecated URL()

---

core-java-modules/core-java-collections-maps-7/pom.xml
core-java-modules/core-java-collections-maps-7/src/test/java/com/baeldung/map/writehashmaptocsvfile/WriteHashmaptoCVSFileUnitTest.java

This PR aims to add a new test method to solve the problem using Apache Commons CSV.

Updating code related to the article BAEL-7017

---

core-java-modules/core-java-collections-5/src/test/java/com/baeldung/removequeueelements/RemoveQueueElementsUnitTest.java

This PR aims to add a test class named "RemoveQueueElementsUnitTest" that provides code snippets for removing elements from a queue.

This PR is related to the article BAEL-7089

---

xml-2/pom.xml
xml-2/src/main/resources/log4j2.xml
xml-2/src/test/java/com/baeldung/xml/xml2string/XMLObjectToStringUnitTest.java

This PR suggests several approaches to convert XML objects to a Java string.

 This PR is related to the article BAEL-6878 

---

core-java-modules/core-java-string-operations-7/src/main/java/com/baeldung/capitalizefirstcharactereachword/CapitalizeFirstCharacterEachWordUtils.java
core-java-modules/core-java-string-operations-7/src/test/java/com/baeldung/capitalizefirstcharactereachword/CapitalizeFirstCharacterEachWordUtilsUnitTest.java

+ Create a new module for string operations: core-java-string-operations-7
+ Create methods to capitalize the first letter of each word in a given string
+ Create test case for each method

BAEL-7055: How can I capitalize the first letter of each word in a string

---

core-java-modules/core-java-strings/src/test/java/com/baeldung/passstringbyreference/Dummy.java
core-java-modules/core-java-strings/src/test/java/com/baeldung/passstringbyreference/PassStringUnitTest.java

test cases for passing a string to a method and modify it

[BAEL-7048] - Passing Strings By Reference in Java

---

core-java-modules/core-java-concurrency-basic-3/src/main/java/com/baeldung/concurrent/completablefuturelist/Application.java

JIRA Link: BAEL-6814 Convert List<CompletableFuture> to CompletableFuture<List>

BAEL-6814 Convert List<CompletableFuture> to CompletableFuture<List>

---

core-java-modules/core-java-io-5/pom.xml
core-java-modules/core-java-io-5/src/main/java/com/baeldung/zip/ZipBenchmark.java
core-java-modules/core-java-io-5/src/main/java/com/baeldung/zip/ZipSampleFileStore.java
core-java-modules/core-java-io-5/src/test/java/com/baeldung/zip/ZipUnitTest.java

https://jira.baeldung.com/browse/BAEL-6804

BAEL-6804: Difference Between ZipFile and ZipInputStream in Java

---

core-java-modules/core-java-date-operations-3/src/test/java/com/baeldung/firstdaymonth/FirstDayOfMonthUnitTest.java

BAEL-7111: Get First Date of Current Month in Java

---

spring-boot-modules/spring-boot-mvc/pom.xml
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/RestValidationApplication.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/config/MessageConfig.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/config/RecursiveLocaleContextMessageInterpolator.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/response/InputFieldError.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/response/UpdateUserResponse.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/service1/User.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/service1/UserService1.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/service2/User.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/service2/UserService2.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/service3/FieldNotEmpty.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/service3/FieldNotEmptyValidator.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/service3/User.java
spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/restvalidation/service3/UserService3.java
spring-boot-modules/spring-boot-mvc/src/main/resources/CustomValidationMessages.properties
spring-boot-modules/spring-boot-mvc/src/main/resources/CustomValidationMessages_zh.properties
spring-boot-modules/spring-boot-mvc/src/main/resources/ValidationMessages.properties
spring-boot-modules/spring-boot-mvc/src/main/resources/ValidationMessages_zh.properties
spring-boot-modules/spring-boot-mvc/src/test/java/com/baeldung/restvalidation/service1/UserService1IntegrationTest.java
spring-boot-modules/spring-boot-mvc/src/test/java/com/baeldung/restvalidation/service2/UserService2IntegrationTest.java
spring-boot-modules/spring-boot-mvc/src/test/java/com/baeldung/restvalidation/service3/UserService3IntegrationTest.java

https://jira.baeldung.com/browse/BAEL-7119

BAEL-7119: Localized Validation Messages in REST

---

core-java-modules/core-java-8-datetime-2/src/main/java/com/baeldung/rounddate/RoundDate.java
core-java-modules/core-java-8-datetime-2/src/test/java/com/baeldung/rounddate/DateRoundingUnitTest.java

This PR aims to add two classes:
- RoundDate
- DateRoundingUnitTest
-

This PR is related to the article BAEL-7130

---

core-java-modules/core-java-jndi/src/test/java/com/baeldung/jndi/JndiNamingUnitTest.java

Hello Saajan,
Hope you are doing well!
I have completed the draft and created a PR:
Draft Link: https://drafts.baeldung.com/wp-admin/post.php?post=179928&action=edit 
Palani

BAEL-4200: JNDI - What Is java:comp/env?

---

core-java-modules/core-java-streams-5/src/test/java/com/baeldung/streamtomapandmultimap/StreamToMapAndMultiMapUnitTest.java

This PR aims to add a test class "StreamToMapAndMultiMapUnitTest" that provides several approaches to convert Java stream to Map or MultiMap.

This PR is related to BAEL-7161

---

core-java-modules/core-java-hex/test/java/com/baeldung/hextoint/HexToIntConversionUnitTest.java

This PR aims to add a test class "HexToIntConversionUnitTest.java" that provides several ways to convert Hex string into int.

This PR is related to the article BAEL-6988

---

core-java-modules/core-java-io-conversions-2/src/test/java/com/baeldung/filetofrombytearray/FileToByteArrayUnitTest.java

BAEL-6776: Convert File to Byte Array in Java

---

libraries-5/pom.xml
spring-5-webflux-2/pom.xml
spring-boot-modules/spring-boot-libraries/pom.xml
spring-boot-modules/spring-caching-2/pom.xml
spring-boot-modules/spring-caching/pom.xml

Upgrade caffeine version to the latest 3.x

java-26718: upgrade caffeine version to 3.x

---

core-java-modules/core-java-collections-5/toarraymethod/ConvertingHashSetToArrayUnitTest.java

This PR aims to add a test class named "ConvertingHashSetToArrayUnitTest" that provides test methods to convert HashSet to an array.

This PR related to BAEL-7103

---

core-java-modules/core-java-datetime-conversion/src/main/java/com/baeldung/timestamptolong/TimestampToLong.java
core-java-modules/core-java-datetime-conversion/src/test/java/com/baeldung/timestamptolong/TimestampToLongUnitTest.java

This PR aims to add:
1. A class "TimestampToLong.java"
2. A test class "TimestampToLongUnitTest.java"

This PR is related to BAEL-7181

---

core-java-modules/core-java-streams-5/src/test/java/com/baeldung/nosuchelementexception/NoSuchElementExceptionStreamUnitTest.java

+ Add unit test to showcase how to avoid NoSuchElementException when working with the stream API

BAEL-7176: How to avoid NoSuchElementException with Stream

---

core-java-modules/core-java-collections-5/src/main/java/com/baeldung/collectionssortcomplexity/CollectionsSortTimeComplexityJMH.java
core-java-modules/core-java-collections-5/src/main/java/com/baeldung/collectionssortcomplexity/CollectionsSortTimeComplexityMain.java

This PR aims to add two classes that provide insights about the time complexity of Collections.sort().

This PR is related to the article BAEL-7172

---

core-java-modules/core-java-collections-maps-7/pom.xml
core-java-modules/core-java-collections-maps-7/src/main/java/com/baeldung/map/BenchmarkMapMethods.java
core-java-modules/core-java-collections-maps-7/src/main/java/com/baeldung/map/IncrementMapValueWays.java
core-java-modules/core-java-collections-maps-7/src/test/java/com/baeldung/map/IncrementMapValueUnitTest.java

[BAEL-6787] increment value of a map

---

core-java-modules/core-java-io-conversions-2/src/main/java/com/baeldung/csv/WriteCsvFileExample.java

Closes #15250
Adding a null check.

BAEL-2499 - Write to CSV in Java

---

core-java-modules/core-java-arrays-convert/src/test/java/com/baeldung/array/conversions/ByteToCharArrayUnitTest.java

This PR aims to add a new test class "ByteToCharArrayUnitTest" that validates the conversion process of a Byte array into a Char array.

This PR is related to BAEL-7254

---

core-java-modules/core-java-strings/src/main/java/com/baeldung/stringbuffer/ComparePerformance.java
core-java-modules/core-java-strings/src/main/java/com/baeldung/stringbuffer/HashCode.java
core-java-modules/core-java-strings/src/test/java/com/baeldung/stringIterator/StringIteratorTest.java
core-java-modules/core-java-strings/src/test/java/com/baeldung/stringbuffer/ComparePerformanceTest.java
core-java-modules/core-java-strings/src/test/java/com/baeldung/stringbuffer/HashCodeTest.java

BAEL-7138 : Difference between String and StringBuffer in Java

string vs stringBuffer comparison

---

apache-httpclient4/src/main/java/com/baeldung/filter/CustomWebSecurityConfigurerAdapter.java
jmeter/src/main/java/com/baeldung/configuration/WebSecurityConfiguration.java
security-modules/jjwt/src/main/java/io/jsonwebtoken/jjwtfun/config/WebSecurityConfig.java

From the following modules: 
- apache-httpclient4
- jmeter
- security-modules
Following the instructions provided by spring:
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter

Java-27655 | Removing deprecated WebSecurityConfigurerAdapter

---

core-java-modules/core-java-numbers-conversions/src/test/java/com/baeldung/roundnumbertonearestmultiple/RoundNumberToNearestMultipleUnitTest.java

This PR adds a new test class "RoundNumberToNearestMultipleUnitTest" that suggests multiplе mеthods for rounding up a numbеr to thе nеarеst multiplе of 5 in Java.

This PR is related to BAEL-7113

---

core-java-modules/core-java-20/src/main/java/com/baeldung/deserialization/Contact.java
core-java-modules/core-java-20/src/main/java/com/baeldung/deserialization/Person.java
core-java-modules/core-java-20/src/test/java/com/baeldung/deserialization/DeserializationUnitTest.java

This PR aims to add classes for the serialization of JSON.

This PR is related to BAEL-6315

---

json-modules/json-conversion/src/test/java/com/baeldung/jsonnodetojsonobject/JsonNodeToJsonObjectUnitTest.java

Pull request to a new article (How to convert JsonNode to ObjectNode). Adding a test class (JsonNodeToJsonObjectUnitTest).

baeldung-articles: baeldung-articlesBAEL-7234

---

xml/src/main/java/com/baeldung/xml/DefaultParser.java

Based on email feedback.
* Changing `childs` to `childNodes`

BAEL ???? - Intro to XPath with Java - quick fix

---

core-java-modules/core-java-concurrency-2/src/test/java/com/baeldung/concurrent/completablefuture/CompletableFutureTest.java
core-java-modules/core-java-concurrency-2/src/test/java/com/baeldung/concurrent/completablefuture/CompletableFutureUnitTest.java

First version of Unit Testing for CompletableFuture class

Unit Testing for CompletableFuture class

---

core-java-modules/core-java-streams/src/test/java/com/baeldung/skipinputstream/SkipInputStreamUnitTest.java

This PR aims to add a test class "SkipInputStreamUnitTest" that provide a test method that utilizes the skip() method.

This PR is related to BAEL-7104

---

core-java-modules/core-java-string-operations-7/src/main/java/com/baeldung/stringmaxlength/StringMaxLengthMain.java

This PR aims to add a class "StringMaxLengthMain" showing the string max length.

This PR is related to BAEL-6920

---

core-java-modules/core-java-string-conversions-3/src/test/java/com/baeldung/stringtocharlist/StringToCharListUnitTest.java

This PR aims to add a test class "StringToCharListUnitTest" that suggests several ways to convert a string into a list of charachters.

This PR is related to BAEL-7341

---

core-java-modules/core-java-concurrency-advanced-5/src/main/java/com/baeldung/callback/completablefuture/CompletableFutureCallbackExample.java
core-java-modules/core-java-concurrency-advanced-5/src/main/java/com/baeldung/callback/listenablefuture/ListenableFutureCallbackExample.java

Added code for callbacks in ListenableFuture and CompletableFuture.

BAEL-7011 Callbacks in ListenableFuture and CompletableFuture

---

core-java-modules/core-java-8-datetime-2/src/main/java/com/baeldung/localdatetoiso/LocalDateToISO.java
core-java-modules/core-java-8-datetime-2/src/test/java/com/baeldung/localdatetoiso/LocalDateToISOUnitTest.java

LocalDate to ISO 8601 conversion

LocalDate to ISO 8601 conversion

---

libraries-data/pom.xml
libraries-data/src/main/java/com/baeldung/objecthydration/User.java
libraries-data/src/main/java/com/baeldung/objecthydration/UserSerialisationDeserialisation.java
libraries-data/src/main/java/com/baeldung/objecthydration/entity/Book.java
libraries-data/src/main/java/com/baeldung/objecthydration/repository/BookRepository.java
libraries-data/src/test/java/com/baeldung/objecthydration/HydrationUnitTest.java

[BAEL-6535] hydration of object examples

---

persistence-modules/spring-data-jpa-query-3/src/main/java/com/baeldung/spring/data/jpa/paging/CustomerService.java
persistence-modules/spring-data-jpa-query-3/src/test/java/com/baeldung/spring/data/jpa/paging/CustomerServiceUnitTest.java

Add a method/test case to demonstrate how to convert a page to a list in Spring Data

BAEL-7283: Convert a page of objects to list in Spring Data

---

persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/listrepositories/lastrecord/Post.java
persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/listrepositories/lastrecord/PostRepository.java
persistence-modules/spring-data-jpa-repo-3/src/main/resources/data.sql
persistence-modules/spring-data-jpa-repo-3/src/main/resources/schema.sql
persistence-modules/spring-data-jpa-repo-3/src/test/java/com/baeldung/spring/data/jpa/listrepositories/lastrecord/PostRepositoryIntegrationTest.java

+ Create Post entity class
+ Create Post JPA repository
+ Create test class

BAEL-7280: How to get last record ordered by date in Spring Data

---

persistence-modules/spring-boot-mysql/pom.xml
persistence-modules/spring-boot-mysql/src/main/java/com/baeldung/boot/Application.java
persistence-modules/spring-boot-mysql/src/main/java/com/baeldung/boot/User.java
persistence-modules/spring-boot-mysql/src/main/java/com/baeldung/boot/jpa/Employee.java
persistence-modules/spring-boot-mysql/src/main/resources/application.yml

Made changes in POM and also some changes as per the new profile settings required for boot3.

 29203:- Upgrade to Spring Boot 3 for Mysql

---

core-java-modules/core-java-string-operations-7/src/test/java/com/baeldung/stringbuilderhaschar/CheckIfStringBuilderContainsCharUnitTest.java

This PR aims to add a test class "CheckIfStringBuilderContainsCharUnitTest" that suggests several ways to check if a StringBuilder has a char or not.

This PR is related to BAEL-7342

---

spring-web-modules/spring-resttemplate-3/pom.xml
spring-web-modules/spring-resttemplate-3/src/main/java/com/baeldung/resttemplate/custom/CustomRestTemplateConfiguration.java

Changes in pom and slight change in config for SSL RestTemplate.

Made changes to upgrade the module spring-resttemplate-3 to Spring Boot 3

---

persistence-modules/spring-mybatis/pom.xml
persistence-modules/spring-mybatis/src/test/java/com/baeldung/mybatis/spring/ArticleMapperCommonUnitTest.java

Made changes to upgrade to Spring Boot 3 for Mybatis. Mostly version conflicts fixed in maven.

Made changes to upgrade to Spring Boot 3 for Mybatis

---

spring-web-modules/spring-mvc-basics-4/pom.xml
spring-web-modules/spring-mvc-basics-4/src/main/java/com/baeldung/config/WebConfig.java
spring-web-modules/spring-mvc-basics-4/src/main/java/com/baeldung/contexts/services/GreeterService.java
spring-web-modules/spring-mvc-basics-4/src/main/java/com/baeldung/validation/listvalidation/constraint/MaxSizeConstraint.java
spring-web-modules/spring-mvc-basics-4/src/main/java/com/baeldung/validation/listvalidation/constraint/MaxSizeConstraintValidator.java
spring-web-modules/spring-mvc-basics-4/src/main/java/com/baeldung/validation/listvalidation/controller/MovieController.java
spring-web-modules/spring-mvc-basics-4/src/main/java/com/baeldung/validation/listvalidation/exception/ConstraintViolationExceptionHandler.java
spring-web-modules/spring-mvc-basics-4/src/main/java/com/baeldung/validation/listvalidation/model/Movie.java
spring-web-modules/spring-mvc-basics-4/src/test/java/com/baeldung/controller/ControllerAnnotationIntegrationTest.java
spring-web-modules/spring-mvc-basics-4/src/test/java/com/baeldung/controller/ControllerIntegrationTest.java

Also removed unwanted imports in some classes

Updated Spring-mvc-basics-4 to boot 3 for and added correct imports for Jakarta

---

persistence-modules/spring-data-yugabytedb/pom.xml
persistence-modules/spring-data-yugabytedb/src/main/java/com/baeldung/User.java
persistence-modules/spring-data-yugabytedb/src/main/resources/application.properties

Made changes to upgrade Spring-Data-YugabyteDB from Boot 2 to Boot 3.

Upgrade Spring-Data-YugabyteDB to boot 3

---

persistence-modules/spring-jdbc/pom.xml
persistence-modules/spring-jdbc/src/main/java/com/baeldung/spring/jdbc/autogenkey/repository/MessageRepositoryJDBCTemplate.java
persistence-modules/spring-jdbc/src/main/java/com/baeldung/spring/jdbc/autogenkey/repository/MessageRepositorySimpleJDBCInsert.java
persistence-modules/spring-jdbc/src/main/java/com/baeldung/spring/jdbc/replacedeprecated/StudentDaoWithDeprecatedJdbcTemplateMethods.java
persistence-modules/spring-jdbc/src/main/java/com/baeldung/spring/jdbc/replacedeprecated/model/StudentResultExtractor.java
persistence-modules/spring-jdbc/src/main/java/com/baeldung/spring/jdbc/template/guide/EmployeeDAO.java
persistence-modules/spring-jdbc/src/main/java/com/baeldung/spring/jdbc/template/inclause/EmployeeDAO.java
persistence-modules/spring-jdbc/src/main/resources/com/baeldung/spring/jdbc/autogenkey/autogenkey-schema.sql
persistence-modules/spring-jdbc/src/test/java/com/baeldung/spring/jdbc/autogenkey/GetAutoGenKeyByJDBC.java
persistence-modules/spring-jdbc/src/test/java/com/baeldung/spring/jdbc/template/guide/EmployeeDAOIntegrationTest.java

The changes are :- 
1. Made Spring Boot 3 the parent for the Spring JDBC project.
2. Removed the deprecated methods in Spring JDBC.
3. Made change in the POM to avoid repackaging , Boot-2 parent POM didn't have repackaging enabled, 3 has.
4. Made some minor change to adhere to the post JDK 7 generics (using <> for initialization of objects) and removed an unused imports.

Java 29169 :- Upgrade spring-jdbc to Spring Boot 3

---

persistence-modules/hibernate-exceptions/src/main/java/com/baeldung/hibernate/exception/persistentobject/HibernateUtil.java
persistence-modules/hibernate-exceptions/src/main/java/com/baeldung/hibernate/namedparameternotbound/Person.java
persistence-modules/hibernate-exceptions/src/test/java/com/baeldung/hibernate/namedparameternotbound/NamedParameterNotBoundExceptionUnitTest.java

+ Create an entity class Person
+ Create a unit test to test the exception

BAEL-6979: How to fix Hibernate QueryException: Named parameter not bound

---

mustache/pom.xml
mustache/src/main/java/com/baeldung/springmustache/controller/ArticleController.java
mustache/src/test/java/com/baeldung/mustache/TodoMustacheServiceUnitTest.java
mustache/src/test/java/com/baeldung/springmustache/SpringMustacheApplicationIntegrationTest.java

No major changes some minor typo fixes.

 JAVA-28929 :- Upgraded to mustache  to Spring boot 3

---

docker-modules/jib/pom.xml

Also upgraded the JIB version to the latest as the old one had security vulnerbailities.
Tested by uploading to my personal docker hub registry that upload works.

Java 28923 :- Upgrade JIB module to use Boot 3

---

core-java-modules/core-java-loops/README.md
core-java-modules/core-java-string-algorithms-4/README.md

Added link to the relevant article section.

Update README.md 

---

core-java-modules/core-java-string-operations-7/src/test/java/com/baeldung/replacenonprintablecharacters/ReplaceNonPrintableCharsUnitTest.java

This PR aims to add a new test class "ReplaceNonPrintableCharsUnitTest".

This PR is related to BAEL-7024

---

core-java-modules/core-java-datetime-conversion/src/test/java/com/baeldung/jodadatetimetostandarddate/JodaDateTimeToDateAndViceVersaUnitTest.java

Convert Joda-Time DateTime to Date and Vice Versa

baeldung-articles : BAEL-7403

---

parent-spring-6/pom.xml
pom.xml
spring-6/api-gateway/pom.xml
spring-6/api-gateway/src/main/java/com/baeldung/errorhandling/CustomGlobalExceptionHandler.java
spring-6/api-gateway/src/main/java/com/baeldung/errorhandling/CustomRequestAuthException.java
spring-6/api-gateway/src/main/java/com/baeldung/errorhandling/ErrorWebExceptionHandler.java
spring-6/api-gateway/src/main/java/com/baeldung/errorhandling/Main.java
spring-6/api-gateway/src/main/java/com/baeldung/errorhandling/MyCustomFilter.java
spring-6/api-gateway/src/main/java/com/baeldung/errorhandling/MyGlobalFilter.java
spring-6/api-gateway/src/main/java/com/baeldung/errorhandling/RateLimitRequestException.java
spring-6/api-gateway/src/main/resources/application.properties
spring-6/api-gateway/src/main/resources/logback.xml
spring-6/api-gateway/src/test/java/com/baeldung/errorhandling/RouteUnitTest.java
spring-6/pom.xml

https://jira.baeldung.com/browse/BAEL-7125

BAEL-7125: Global Exception Handling with Spring Cloud Gateway

---

core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/readinputcharbychar/ReadInputCharByCharUnitTest.java

This PR aims to add a class "ReadInputCharByChar" that provides several approaches to read input char by char.

This PR is related to BAEL-6873

---

kubernetes-modules/k8s-operator/.gitignore
kubernetes-modules/k8s-operator/README.md
kubernetes-modules/k8s-operator/k8s/deptrack-controller.yaml
kubernetes-modules/k8s-operator/k8s/test-resource.yaml
kubernetes-modules/k8s-operator/pom.xml
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/Application.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/config/OperatorConfiguration.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/controller/deptrack/DeptrackOperatorReconciler.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/resources/Constants.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/resources/deptrack/BuilderHelper.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/resources/deptrack/DeptrackApiServerDeploymentResource.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/resources/deptrack/DeptrackApiServerServiceResource.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/resources/deptrack/DeptrackFrontendDeploymentResource.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/resources/deptrack/DeptrackFrontendServiceResource.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/resources/deptrack/DeptrackIngressResource.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/resources/deptrack/DeptrackResource.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/resources/deptrack/DeptrackSpec.java
kubernetes-modules/k8s-operator/src/main/java/com/baeldung/operators/deptrack/resources/deptrack/DeptrackStatus.java
kubernetes-modules/k8s-operator/src/main/logback.xml
kubernetes-modules/k8s-operator/src/main/resources/application.properties
kubernetes-modules/k8s-operator/src/main/resources/templates/api-server-deployment.yaml
kubernetes-modules/k8s-operator/src/main/resources/templates/api-server-pvc.yaml
kubernetes-modules/k8s-operator/src/main/resources/templates/api-server-service.yaml
kubernetes-modules/k8s-operator/src/main/resources/templates/frontend-deployment.yaml
kubernetes-modules/k8s-operator/src/main/resources/templates/frontend-service.yaml
kubernetes-modules/k8s-operator/src/main/resources/templates/ingress.yaml
kubernetes-modules/k8s-operator/src/test/java/com/baeldung/operators/deptrack/ApplicationUnitTest.java
kubernetes-modules/pom.xml

WP: https://drafts.baeldung.com/wp-admin/post.php?post=185608
JIRA: https://jira.baeldung.com/browse/BAEL-7049

[BAEL-7049] Kubernetes Operator

---

core-java-modules/core-java-numbers-7/src/test/java/com/baeldung/checkiffloatequivalenttointeger/CheckIfFloatEquivalentToIntegerUnitTest.java

Check if a float value is equivalent to an integer value in Java.

baeldung-articles : BAEL-7180

---

json-modules/gson-2/src/test/java/com/baeldung/gson/deprecatedjsonparser/DeprecatedJsonParserUnitTest.java

This PR aims to add a new test class "DeprecatedJsonParserUnitTest".

This PR is related to BAEL-7331

---

core-java-modules/core-java-console/src/main/java/com/baeldung/printmessagewithoutmain/PrintMessageWithoutMainMethod.java
core-java-modules/core-java-console/src/test/java/com/baeldung/printmessagewithoutmain/PrintMessageWithoutMainUnitTest.java

This PR aims to add two classes:
-  PrintMessageWithoutMainMethod
- PrintMessageWithoutMainUnitTest

This PR is related to BAEL-7028

---

spring-cloud-modules/pom.xml
spring-cloud-modules/spring-cloud-aws-v3/README.md
spring-cloud-modules/spring-cloud-aws-v3/pom.xml
spring-cloud-modules/spring-cloud-aws-v3/src/main/java/com/baeldung/spring/cloud/aws/SpringCloudAwsApplication.java
spring-cloud-modules/spring-cloud-aws-v3/src/main/java/com/baeldung/spring/cloud/aws/sqs/EventQueuesProperties.java
spring-cloud-modules/spring-cloud-aws-v3/src/main/java/com/baeldung/spring/cloud/aws/sqs/User.java
spring-cloud-modules/spring-cloud-aws-v3/src/main/java/com/baeldung/spring/cloud/aws/sqs/UserCreatedEvent.java
spring-cloud-modules/spring-cloud-aws-v3/src/main/java/com/baeldung/spring/cloud/aws/sqs/UserEventListeners.java
spring-cloud-modules/spring-cloud-aws-v3/src/main/java/com/baeldung/spring/cloud/aws/sqs/UserRepository.java
spring-cloud-modules/spring-cloud-aws-v3/src/main/resources/application.yaml
spring-cloud-modules/spring-cloud-aws-v3/src/test/java/com/baeldung/spring/cloud/aws/sqs/BaseSqsIntegrationTest.java
spring-cloud-modules/spring-cloud-aws-v3/src/test/java/com/baeldung/spring/cloud/aws/sqs/SpringCloudAwsSQSLiveTest.java

Opening a new PR with the new fork / history.

BAEL-7349 - Spring Cloud AWS 3.0 SQS - Introduction

---

core-java-modules/core-java-string-operations-7/src/test/java/com/baeldung/checkifstringcontainsinvalidcharacters/CheckIfStringContainsInvalidEncodedCharactersUnitTest.java

This PR aims to add a new test class "CheckIfStringContainsInvalidEncodedCharactersUnitTest".

This PR is related to BAEL-7174

---

core-java-modules/core-java-datetime-string-2/pom.xml
core-java-modules/core-java-datetime-string-2/src/test/java/com/baeldung/timestamp/CurrentTimeAsFileNameUnitTest.java

Using Current Time as Filename in Java

BAEL-7270 - Current Time as Filename

---

core-java-modules/core-java-lang-math-3/src/test/java/com/baeldung/com.baeldung.powerinsteadofmathpow/FindPowerInsteadOfUsingMathPowUnitTest.java

Calculating the Power of a Number in Java Without Using Math pow() Method (request to pull)

baeldung-articles : BAEL - 6856

---

apache-poi-3/pom.xml
apache-poi-3/src/main/java/com/baeldung/poi/rowstyle/PoiUtils.java
apache-poi-3/src/test/java/com/baeldung/poi/rowstyle/PoiBoldStyleIntegrationTest.java

PR was recreated due to repository truncation.
Draft: https://drafts.baeldung.com/wp-admin/post.php?post=185237&action=edit

BAEL-7129 Apply Bold Text Style for an Entire Row Using Apache POI

---

spring-web-modules/spring-mvc-java-2/pom.xml
spring-web-modules/spring-mvc-java-2/src/main/java/com/baeldung/cache/CacheControlController.java
spring-web-modules/spring-mvc-java-2/src/main/java/com/baeldung/excel/ExcelController.java
spring-web-modules/spring-mvc-java-2/src/main/java/com/baeldung/matrix/controller/CompanyController.java
spring-web-modules/spring-mvc-java-2/src/main/java/com/baeldung/matrix/controller/EmployeeController.java
spring-web-modules/spring-mvc-java-2/src/main/java/com/baeldung/matrix/model/Employee.java
spring-web-modules/spring-mvc-java-2/src/main/java/com/baeldung/multiparttesting/MultipartPostRequestController.java
spring-web-modules/spring-mvc-java-2/src/main/java/com/baeldung/pathvariable.dottruncated/CustomWebMvcConfigurationSupport.java
spring-web-modules/spring-mvc-java-2/src/main/java/com/baeldung/pathvariable.dottruncated/SiteController.java
spring-web-modules/spring-mvc-java-2/src/test/java/com/baeldung/htmlunit/TestConfig.java
spring-web-modules/spring-mvc-java-2/src/test/java/com/baeldung/matrix/EmployeeMvcIntegrationTest.java
spring-web-modules/spring-mvc-java-2/src/test/java/com/baeldung/multipart/file/ConvertFileToMultipartFileUnitTest.java

Upgrade spring-mvc-java-2 to Spring Boot 3

JAVA-30357 :- Upgrade spring-mvc-java-2 to Spring Boot 3

---

spring-boot-rest/pom.xml
spring-boot-rest/src/main/java/com/baeldung/persistence/model/Foo.java
spring-boot-rest/src/main/java/com/baeldung/persistence/service/common/AbstractService.java
spring-boot-rest/src/main/java/com/baeldung/persistence/service/impl/FooService.java
spring-boot-rest/src/main/java/com/baeldung/springpagination/model/Post.java
spring-boot-rest/src/main/java/com/baeldung/springpagination/model/Preference.java
spring-boot-rest/src/main/java/com/baeldung/springpagination/model/Subject.java
spring-boot-rest/src/main/java/com/baeldung/springpagination/model/User.java
spring-boot-rest/src/main/java/com/baeldung/springpagination/repository/PostRepository.java
spring-boot-rest/src/main/java/com/baeldung/springpagination/service/PostService.java
spring-boot-rest/src/main/java/com/baeldung/web/config/MyErrorController.java
spring-boot-rest/src/main/java/com/baeldung/web/controller/FooController.java
spring-boot-rest/src/main/java/com/baeldung/web/controller/RootController.java
spring-boot-rest/src/main/java/com/baeldung/web/controller/students/StudentService.java
spring-boot-rest/src/main/java/com/baeldung/web/error/RestResponseEntityExceptionHandler.java
spring-boot-rest/src/main/java/com/baeldung/web/error/RestResponseStatusExceptionResolver.java
spring-boot-rest/src/main/java/com/baeldung/web/hateoas/event/PaginatedResultsRetrievedEvent.java
spring-boot-rest/src/main/java/com/baeldung/web/hateoas/event/ResourceCreatedEvent.java
spring-boot-rest/src/main/java/com/baeldung/web/hateoas/event/SingleResourceRetrievedEvent.java
spring-boot-rest/src/main/java/com/baeldung/web/hateoas/listener/PaginatedResultsRetrievedDiscoverabilityListener.java
spring-boot-rest/src/main/java/com/baeldung/web/hateoas/listener/ResourceCreatedDiscoverabilityListener.java
spring-boot-rest/src/main/java/com/baeldung/web/hateoas/listener/SingleResourceRetrievedDiscoverabilityListener.java
spring-boot-rest/src/main/java/com/baeldung/web/util/LinkUtil.java
spring-boot-rest/src/test/java/com/baeldung/common/web/AbstractBasicLiveTest.java
spring-boot-rest/src/test/java/com/baeldung/common/web/AbstractDiscoverabilityLiveTest.java
spring-boot-rest/src/test/java/com/baeldung/rest/GithubBasicLiveTest.java
spring-boot-rest/src/test/java/com/baeldung/springhateoas/CustomerControllerIntegrationTest.java
spring-boot-rest/src/test/java/com/baeldung/web/FooControllerCustomEtagIntegrationTest.java
spring-boot-rest/src/test/java/com/baeldung/web/FooMessageConvertersLiveTest.java
spring-boot-rest/src/test/java/com/baeldung/web/FooPageableLiveTest.java

Upgrade spring-boot-rest to Spring Boot 3

Java 28951 :- Upgrade spring-boot-rest to Spring Boot 3

---

spring-boot-modules/spring-boot-validation/pom.xml
spring-boot-modules/spring-boot-validation/src/main/java/com/baeldung/beanvalidation/application/Application.java
spring-boot-modules/spring-boot-validation/src/main/java/com/baeldung/beanvalidation/application/controllers/UserController.java
spring-boot-modules/spring-boot-validation/src/main/java/com/baeldung/beanvalidation/application/entities/User.java
spring-boot-modules/spring-boot-validation/src/main/java/com/baeldung/spring/servicevalidation/dao/UserAccountDao.java
spring-boot-modules/spring-boot-validation/src/main/java/com/baeldung/spring/servicevalidation/domain/UserAccount.java
spring-boot-modules/spring-boot-validation/src/main/java/com/baeldung/spring/servicevalidation/domain/UserAddress.java
spring-boot-modules/spring-boot-validation/src/main/java/com/baeldung/spring/servicevalidation/service/UserAccountService.java
spring-boot-modules/spring-boot-validation/src/main/resources/application.properties
spring-boot-modules/spring-boot-validation/src/test/java/com/baeldung/beanvalidation/application/UserControllerIntegrationTest.java

Also added a application.properties as without the application was not starting due to the table name user being a reserved keyword.

JAVA-27509 :- Update Spring Boot validation to Spring Boot 3. 

---

core-java-modules/core-java-networking-4/urlnormalization/URLNormalizationUnitTest.java

Normalize a URL in Java (request to pull)

baeldung-articles : BAEL-6777

---

apache-poi-3/README.md
core-java-modules/core-java-21/README.md
core-java-modules/core-java-8-datetime-2/README.md
core-java-modules/core-java-arrays-convert/README.md
core-java-modules/core-java-collections-5/README.md
core-java-modules/core-java-collections-list-6/README.md
core-java-modules/core-java-console/README.md
core-java-modules/core-java-date-operations-4/README.md
core-java-modules/core-java-datetime-string-2/README.md
core-java-modules/core-java-lang-math-3/README.md
core-java-modules/core-java-numbers-7/README.md
core-java-modules/core-java-security-4/README.md
core-java-modules/core-java-string-operations-7/README.md
json-modules/gson-2/README.md
maven-modules/maven-build-lifecycle/README.md
patterns-modules/design-patterns-creational-2/README.md
persistence-modules/java-calcite/README.md
persistence-modules/spring-boot-persistence-4/README.md
spring-6/api-gateway/README.md
spring-boot-modules/spring-boot-3-grpc/README.md
spring-boot-modules/spring-boot-libraries-3/README.md
spring-boot-modules/spring-boot-testing-spock/README.md
spring-cloud-modules/spring-cloud-aws-v3/README.md
spring-kafka-3/README.md
spring-web-modules/spring-mvc-basics-5/README.md
testing-modules/groovy-spock/README.md

Updated the relevant articles on README.md for UX-11299

Update on README.md

---

spring-web-modules/spring-rest-query-language/pom.xml
spring-web-modules/spring-rest-query-language/src/main/java/com/baeldung/persistence/dao/UserDAO.java
spring-web-modules/spring-rest-query-language/src/main/java/com/baeldung/persistence/dao/UserSearchQueryCriteriaConsumer.java
spring-web-modules/spring-rest-query-language/src/main/java/com/baeldung/persistence/dao/UserSpecification.java
spring-web-modules/spring-rest-query-language/src/main/java/com/baeldung/persistence/dao/rsql/GenericRsqlSpecification.java
spring-web-modules/spring-rest-query-language/src/main/java/com/baeldung/persistence/model/MyUser.java
spring-web-modules/spring-rest-query-language/src/main/java/com/baeldung/persistence/model/User.java
spring-web-modules/spring-rest-query-language/src/main/java/com/baeldung/persistence/model/User_.java
spring-web-modules/spring-rest-query-language/src/main/java/com/baeldung/spring/Application.java
spring-web-modules/spring-rest-query-language/src/main/java/com/baeldung/web/error/RestResponseEntityExceptionHandler.java

JAVA-30682 :- Upgrade to Spring Boot 3 and latest hibernate-core. Also upgrade to relevant query-dsl versions

JAVA-30682 :- Upgrade to Spring Boot 3 and latest hibernate-core. Also upgrade to relevant query-dsl versions

---

spring-jinq/pom.xml

JAVA-30683 :- Upgrade Spring-Jinq module to use latest hibernate-core version

JAVA-30683 :- Upgrade Spring-Jinq module to use latest hibernate-core version

---

spring-batch-2/pom.xml
spring-batch-2/src/main/java/com/baeldung/batchreaderproperties/BatchConfiguration.java
spring-batch-2/src/main/java/com/baeldung/batchreaderproperties/BatchConstants.java
spring-batch-2/src/main/java/com/baeldung/batchreaderproperties/ContainsJobParameters.java
spring-batch-2/src/main/java/com/baeldung/batchreaderproperties/MedExpirationBatchRunner.java
spring-batch-2/src/main/java/com/baeldung/batchreaderproperties/SpringBatchExpireMedicationApplication.java
spring-batch-2/src/main/java/com/baeldung/batchreaderproperties/job/ExpiresSoonMedicineReader.java
spring-batch-2/src/main/java/com/baeldung/batchreaderproperties/job/MedicineProcessor.java
spring-batch-2/src/main/java/com/baeldung/batchreaderproperties/job/MedicineWriter.java
spring-batch-2/src/main/java/com/baeldung/batchreaderproperties/model/Medicine.java
spring-batch-2/src/main/java/com/baeldung/batchreaderproperties/model/MedicineCategory.java
spring-batch-2/src/main/resources/application.properties
spring-batch-2/src/main/resources/data.sql
spring-batch-2/src/main/resources/disable-job-autorun.properties
spring-batch-2/src/main/resources/schema-all.sql

- added implementation for batch that track expiring medicine to demonstrate JobParameters usage

BAEL-7185 Access Job Parameters from ItemReader in Spring Batch

---

core-java-modules/core-java-lang-operators-2/src/main/java/com/baeldung/infixpostfix/InfixToPostFixExpressionConversion.java
core-java-modules/core-java-lang-operators-2/src/test/java/com/baeldung/infixpostfix/InfixToPostfixExpressionUnitTest.java

[BAEL-7501] Infix to Postfix

---

spring-security-modules/spring-security-web-sockets/pom.xml

Upgrade Hibernate-core to the latest version for Spring Security web sockets module.

JAVA-30681 :- Upgrade Hibernate-core to the latest version for Spring Security web sockets module.

---

pom.xml

Reverts eugenp/tutorials#15789

Revert "JAVA-27339: Changes made for adding java-panama module back"

---

core-java-modules/core-java-date-operations-4/src/test/java/com/baeldung/datetounixtimestamp/DateToUnixTimeStampUnitTest.java

+ Create test cases to test how to convert Date to Unix Timestamp

BAEL-7269: How to Convert Date to unix Timestamp in Java?

---

persistence-modules/hibernate-mapping-2/pom.xml
persistence-modules/hibernate-mapping/pom.xml
persistence-modules/hibernate-queries/pom.xml

JAVA-31113:- Upgrade projects to latest hibernate version

JAVA-31113:- Upgrade projects to latest hibernate version

---

core-java-modules/core-java-string-operations-8/README.md
core-java-modules/core-java-string-operations-8/pom.xml
core-java-modules/core-java-string-operations-8/src/test/java/com/baeldung/emailandphonemasking/EmailAndPhoneMaskingUnitTest.java
core-java-modules/pom.xml

This PR aims to add a new module "core-java-string-operations-8" and a test class "EmailAndPhoneMaskingUnitTest"

This PR is related to BAEL-7528

---

metrics/pom.xml
metrics/src/test/java/com/baeldung/metrics/micrometer/MicrometerAtlasManualTest.java
metrics/src/test/java/com/baeldung/metrics/servo/MetricAnnotationManualTest.java
metrics/src/test/java/com/baeldung/metrics/servo/MetricObserverManualTest.java

JAVA-22846 :- Fix MicrometerAtlasManualTest , update dependencies and also fix other needed tests.

---

core-java-modules/core-java-string-operations-8/src/test/java/com/baeldung/findlargestnuminstring/FindLargestNumInStringUnitTest.java

This PR aims to add a test class "FindLargestNumInStringUnitTest.java".

This PR is related to BAEL-7554

---

core-java-modules/core-java-string-operations-8/src/test/java/com/baeldung/checkifstringisbased64/CheckIfStringIsBased64UnitTest.java

Check if String is Base64 Encoded (request to pull)

baeldung-articles : BAEL-7442

---

spring-ejb-modules/spring-ejb-client/pom.xml
spring-ejb-modules/spring-ejb-client/src/main/java/com/baeldung/springejbclient/SpringEjbClientApplication.java

JAVA-24962 - Modifications to make client work with EJB deployed in external Wildfly

---

jackson-modules/jackson-custom-conversions/javatypefromclassinjava/JavaTypeFromClassUnitTest.java

Create JavaType From Class with Jackson (request to pull).

baeldung-articles : BAEL-5937

---

algorithms-modules/algorithms-miscellaneous-7/src/main/java/com/baeldung/algorithms/stringrotation/StringRotation.java
algorithms-modules/algorithms-miscellaneous-7/src/test/java/com/baeldung/algorithms/stringrotation/StringRotationUnitTest.java

Check if two strings are rotations of each other [BAEL-7493]

---

core-java-modules/core-java-string-operations-8/src/test/java/com/baeldung/finduniqueemails/FindUniqueEmailsUnitTest.java

This PR aims to add a test class "FindUniqueEmailsUnitTest.java".

This PR is related to BAEL-7556

---

testing-modules/spring-testing/pom.xml
testing-modules/spring-testing/src/main/java/com/baeldung/config/WebConfig.java
testing-modules/spring-testing/src/test/resources/logback-spring.xml

Fix integration tests in spring-testing module

Bael 7136 improvement

---

spring-security-modules/spring-security-ldap/pom.xml
spring-security-modules/spring-security-ldap/src/main/java/com/baeldung/SampleLDAPApplication.java
spring-security-modules/spring-security-ldap/src/main/java/com/baeldung/config/SecurityConfig.java
spring-security-modules/spring-security-ldap/src/main/java/org/apache/directory/server/core/avltree/ArrayMarshaller.java

Upgrade Spring Security LDAP to Spring Boot 3

Java 29291 :- Upgrade Spring Security LDAP to Spring Boot 3

---

core-java-modules/core-java-string-operations-8/pom.xml
core-java-modules/core-java-string-operations-8/src/test/java/com/baeldung/firstnchars/FirstNCharactersUnitTest.java

+ Add new module
+ Add test cases to test how to get the first n chars

BAEL-7514: Get first n characters in a String in Java

---

libraries-4/pom.xml
libraries-4/src/main/java/com/baeldung/jfreechart/BarChartExample.java
libraries-4/src/main/java/com/baeldung/jfreechart/CombinationChartExample.java
libraries-4/src/main/java/com/baeldung/jfreechart/LineChartExample.java
libraries-4/src/main/java/com/baeldung/jfreechart/PieChartExample.java
libraries-4/src/main/java/com/baeldung/jfreechart/TimeSeriesChartExample.java
libraries-4/src/main/java/com/baeldung/jfreechart/ignore-this-file

https://jira.baeldung.com/browse/BAEL-7575

https://jira.baeldung.com/browse/BAEL-7575

---

spring-web-modules/spring-mvc-basics/pom.xml

tested by upgrading parent-boot3 to 3.2.2 locally.

JAVA-31813 :- Upgrade parent-boot-3.2.2 , fix spring-mvc-basics tests.

---

spring-security-modules/spring-security-web-sockets/pom.xml

In this PR we are only upgrading :- spring-security-modules/spring-security-web-sockets

JAVA-30233 :- Upgrade Hibernate-core to the latest version

---

core-java-modules/core-java-security-algorithms/src/test/java/com/baeldung/blowfish/BlowFishUnitTest.java

Hello David Martinez,
Hope you are doing well!
I have completed the draft and created this PR:
Draft Link: https://drafts.baeldung.com/wp-admin/post.php?post=191149&action=edit
Palani

BAEL-7495: Blowfish Encryption Algorithm

---

spring-web-modules/spring-thymeleaf-2/pom.xml
spring-web-modules/spring-thymeleaf-2/src/main/java/com/baeldung/thymeleaf/enums/WidgetController.java
spring-web-modules/spring-thymeleaf-3/pom.xml
spring-web-modules/spring-thymeleaf-3/src/main/java/com/baeldung/thymeleaf/errors/User.java
spring-web-modules/spring-thymeleaf-3/src/main/java/com/baeldung/thymeleaf/errors/UserController.java
spring-web-modules/spring-thymeleaf-3/src/main/java/com/baeldung/thymeleaf/option/Student.java

Clubbed the two project updates as they are pretty similar.

JAVA-29175 :- Upgrade Spring-Thymeleaf2 and Spring-Thymeleaf-3 to boot 3.

---

core-java-modules/core-java-networking-4/src/test/java/com/baeldung/obtainlastsegmentofurl/ObtainLastSegmentOfURLUnitTest.java

Obtaining the Last Path Segment of a URI in Java.

baeldung-articles : BAEL-6349

---

testing-modules/groovy-spock/src/main/java/com/baeldung/spock/capture/ArgumentCaptureDependency.java
testing-modules/groovy-spock/src/main/java/com/baeldung/spock/capture/ArgumentCaptureSubject.java
testing-modules/groovy-spock/src/test/groovy/com/baeldung/spock/capture/ArgumentCaptureUnitTest.groovy

@maibin Please review for the BAEL-7315 article.

BAEL-7315 Add source code for Spock Argument Capture tutorial

---

jsoup/src/main/java/com/baeldung/jsoup/JsoupTableParser.java
jsoup/src/main/resources/Students.html
jsoup/src/test/java/com/baeldung/jsoup/JsoupTableParserUnitTest.java

Added code for parsing html table using jsoup library.
Added dependency in pom.xml
Added html file in resources folder to test html parsing

Parsing HTML Table in Java With Jsoup

---

core-java-modules/core-java-collections/src/test/java/com/baeldung/listiteration/ListIterationUnitTest.java

Adding elements to a collection during iteration.

baeldung-articles : BAEL-7500

---

persistence-modules/hibernate-enterprise/src/test/java/com/baeldung/persistence/save/SaveMethodsIntegrationTest.java
persistence-modules/hibernate-enterprise/src/test/resources/h2-trigger.sql

Created test cases for refresh() and replicate() Hibernate methods & Fixed indentation

BAEL-7460: Hibernate: Refresh, Evict, Replicate and Flush

---

spring-boot-modules/spring-boot-3-2/src/test/java/com/baeldung/restclient/RestClientLiveTest.java

Test requires Docker so renamed to Live

JAVA-28828 Rename RestClientIntegrationTest to RestClientLiveTest

---

core-java-modules/core-java-lang-operators-2/src/test/java/com/baeldung/integersatbitlevel/IntegersBitLevelUnitTest.java

This commit aims to add a test class "IntegersBitLevelUnitTest.java".

This commit is related to BAEL-6825

---

core-java-modules/core-java-collections-array-list-2/src/main/java/com/baeldung/peakelements/MultiplePeakFinder.java
core-java-modules/core-java-collections-array-list-2/src/main/java/com/baeldung/peakelements/PeakElementFinder.java
core-java-modules/core-java-collections-array-list-2/src/main/java/com/baeldung/peakelements/SinglePeakFinder.java
core-java-modules/core-java-collections-array-list-2/src/test/java/com/baeldung/peakelements/MultiplePeakFinderUnitTest.java
core-java-modules/core-java-collections-array-list-2/src/test/java/com/baeldung/peakelements/PeakElementFinderUnitTest.java
core-java-modules/core-java-collections-array-list-2/src/test/java/com/baeldung/peakelements/SinglePeakFinderUnitTest.java

Added 6 files in the core-java-collections-array-list-2 module

[BAEL-7527] Find Peak Elements of a List 

---

core-java-modules/core-java-lang-oop-constructors-2/src/main/java/com/baeldung/objectcreation/constructorversussettermethod/Product.java
core-java-modules/core-java-lang-oop-constructors-2/src/main/java/com/baeldung/objectcreation/constructorversussettermethod/User.java
core-java-modules/core-java-lang-oop-constructors-2/src/test/java/com/baeldung/objectcreation/constructorversussettermethod/ConstructorsVersusSetterMethodsUnitTest.java

When to Use Setter Methods or Constructors for Setting a Variable's Value in Java.

baeldung-articles : BAEL-6752

---

spring-boot-modules/pom.xml
spring-boot-modules/spring-boot-mvc-2/pom.xml
spring-boot-modules/spring-boot-mvc-2/src/main/java/com/baeldung/mime/FooController.java
spring-boot-modules/spring-boot-mvc-2/src/main/java/com/baeldung/springbootmvc/ctrl/ProductController.java
spring-boot-modules/spring-boot-mvc-2/src/main/java/com/baeldung/springbootmvc/svc/ProductService.java
spring-boot-modules/spring-boot-mvc-2/src/main/java/com/baeldung/students/StudentService.java
spring-boot-modules/spring-boot-mvc-5/pom.xml
spring-boot-modules/spring-boot-mvc-5/src/main/java/com/baeldung/modifyrequest/requestwrapper/EscapeHtmlRequestWrapper.java
spring-boot-modules/spring-boot-mvc-5/src/test/java/com/baeldung/modifyrequest/EscapeHtmlAspectIntegrationTest.java
spring-boot-modules/spring-boot-mvc-5/src/test/java/com/baeldung/modifyrequest/EscapeHtmlFilterIntegrationTest.java

Code was failing after upgrade to 3.2.2

JAVA-31602 :- Upgrade spring-boot-mvc-2, spring-boot-mvc-5 to boot 3.2.2

---

spring-di-4/src/main/java/com/baeldung/prototypebean/dynamicarguments/Employee.java
spring-di-4/src/main/java/com/baeldung/prototypebean/dynamicarguments/EmployeeBeanUsingFunction.java
spring-di-4/src/main/java/com/baeldung/prototypebean/dynamicarguments/EmployeeBeanUsingLookUp.java
spring-di-4/src/main/java/com/baeldung/prototypebean/dynamicarguments/EmployeeBeanUsingObjectFactory.java
spring-di-4/src/main/java/com/baeldung/prototypebean/dynamicarguments/EmployeeBeanUsingObjectProvider.java
spring-di-4/src/main/java/com/baeldung/prototypebean/dynamicarguments/EmployeeConfig.java
spring-di-4/src/test/java/com/baeldung/prototypebean/dynamicarguments/DynamicBeanUnitTest.java

https://drafts.baeldung.com/wp-admin/post.php?post=189380&action=edit

Prototype Scoped Bean With Runtime Arguments

---

json-modules/json-conversion/src/main/java/com/baeldung/includenullinjson/Customer.java
json-modules/json-conversion/src/test/java/com/baeldung/includenullinjson/IncludeNullValuesInJsonUnitTest.java

Include null value in JSON serialization.

baeldung-articles : BAEL-7644

---

core-java-modules/core-java-lang-oop-others/src/main/java/com/baeldung/statementsbeforesuper/Child.java
core-java-modules/core-java-lang-oop-others/src/main/java/com/baeldung/statementsbeforesuper/Parent.java

This PR aims to add two classes Child and Parent.

This PR is related to BAEL-6972

---

image-processing/src/main/java/com/baeldung/imageprocessing/bufferedimageresize/Application.java

Ticket: https://jira.baeldung.com/browse/BAEL-6840
Draft: https://drafts.baeldung.com/wp-admin/post.php?post=192733&action=edit

Example code for BAEL-6840: How to scale a BufferedImage in Java?

---

core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/getpathtoresource/GetPathToResourceUnitTest.java

Get a Path to a Resource in a Java JAR File.

baeldung-articles : BAEL-6607

---

core-java-modules/core-java-io-5/src/test/java/com/baeldung/com.baeldung.openhtmlfiles/OpenHtmlFilesUnitTest.java
core-java-modules/core-java-io-5/src/test/resources/test.html

This PR aims to add ways to open HTML File using Java.

This PR is related to BAEL-6429

---

core-java-modules/core-java-datetime-conversion-2/src/test/java/com/baeldung/TemporalAccessorToLocalDate/TemporalAccessorToLocalDateUnitTest.java

Convert TemporalAccessor to LocalDate.

baeldung-articles BAEL-7642

---

spring-5-webflux-2/pom.xml
spring-5-webflux-2/src/main/resources/logback.xml
spring-5-webflux-2/src/test/resources/logback-test.xml
spring-5-webflux/pom.xml
spring-5-webflux/src/main/java/com/baeldung/spring/responsestatus/ResponseStatusController.java
spring-5-webflux/src/main/java/com/baeldung/spring/retry/ExternalConnector.java
spring-5-webflux/src/main/java/com/baeldung/spring/serverconfig/NettyWebServerFactorySslCustomizer.java
spring-5-webflux/src/main/java/com/baeldung/spring/serverconfig/TimeoutController.java
spring-5-webflux/src/main/resources/logback.xml
spring-5-webflux/src/test/resources/logback-test.xml

JAVA-29183 :- Upgrade spring-5-webflux & spring-5-webflux-2 to Spring Boot 3.

---

core-java-modules/core-java-collections-set-2/src/test/java/com/baeldung/checkifpresentinset/CheckIfPresentInSetUnitTest.java

+ Create test cases to check if an element is present in a Set

BAEL-7499: Check if an element is present in a Set in Java

---

testing-modules/mockito-2/pom.xml
testing-modules/mockito-2/src/main/java/com/baeldung/injectmockintospy/Book.java
testing-modules/mockito-2/src/main/java/com/baeldung/injectmockintospy/BookControlService.java
testing-modules/mockito-2/src/main/java/com/baeldung/injectmockintospy/BookStorageService.java
testing-modules/mockito-2/src/main/java/com/baeldung/injectmockintospy/RepairService.java
testing-modules/mockito-2/src/main/java/com/baeldung/injectmockintospy/StatisticService.java
testing-modules/mockito-2/src/test/java/com/baeldung/injectmockintospy/MultipleInjectMockAndManualSpyWithExtensionUnitTest.java
testing-modules/mockito-2/src/test/java/com/baeldung/injectmockintospy/MultipleInjectMockAndManualSpyWithOpenMocksUnitTest.java
testing-modules/mockito-2/src/test/java/com/baeldung/injectmockintospy/MultipleInjectMockAndMockitoSpyDoesnotWorkUnitTest.java
testing-modules/mockito-2/src/test/java/com/baeldung/injectmockintospy/SingleInjectMockAndAnnotatedSpyUnitTest.java
testing-modules/mockito-2/src/test/java/com/baeldung/injectmockintospy/SingleInjectMockAndManualSpyWithReflectionUnitTest.java

- added "library" service to demonstrate mockito injection features
- updated mockito version to 5.10

BAEL-7238 Inject mock into Spy object in Mockito

---

algorithms-modules/algorithms-miscellaneous-8/README.md
core-java-modules/core-java-collections-maps-8/README.md
core-java-modules/core-java-collections-set-2/README.md
core-java-modules/core-java-datetime-conversion-2/README.md
core-java-modules/core-java-io-apis-2/README.md
core-java-modules/core-java-io-apis/README.md
core-java-modules/core-java-string-operations-8/README.md
json-modules/json-conversion/README.md
microservices-modules/saga-pattern/README.md
persistence-modules/hibernate-annotations/README.md
persistence-modules/hibernate-jpa/README.md
persistence-modules/hibernate-queries/README.md
spring-boot-modules/spring-boot-logging-loki/README.md
spring-di-4/README.md
testing-modules/mockito-2/README.md
testing-modules/selenium-2/README.md

Updated the relevant articles on README.md for UX-12963

Update on README.md 

---

persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/joinquery/AppConfig.java
persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/joinquery/DTO/ResultDTO.java
persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/joinquery/DTO/ResultDTO_wo_Ids.java
persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/joinquery/entities/Customer.java
persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/joinquery/entities/CustomerOrder.java
persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/joinquery/entities/Product.java
persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/joinquery/repositories/CustomerRepository.java
persistence-modules/spring-data-jpa-repo-3/src/main/java/com/baeldung/spring/data/jpa/joinquery/repositories/JoinRepository.java
persistence-modules/spring-data-jpa-repo-3/src/test/java/com/baeldung/spring/data/jpa/joinquery/JoinRepositoryTest.java
persistence-modules/spring-data-jpa-repo-3/src/test/java/com/baeldung/spring/data/jpa/joinquery/JoinRepositoryUnitTest.java

code corresponding to ticket BAEL-7692, dealing with join clauses in @Query annotations for both JPQL and native queries, and how to select specific columns from the query using DTOs and/or nativeQuery approach.

Bael 7692 join queries

---

xml-2/src/test/java/com/baeldung/xml/invalidcharacters/InvalidCharactersUnitTest.java

BAEL-6534 Add InvalidCharactersUnitTest.java

---

core-java-modules/core-java-string-operations-8/src/test/java/com/baeldung/symmetricsubstringlength/SymmetricSubstringMaxLengthUnitTest.java

This PR aims to update SymmetricSubstringMaxLengthUnitTest.java.

This PR is related to BAEL-7722

---

persistence-modules/duckdb/pom.xml
persistence-modules/duckdb/src/test/java/com/baeldung/DuckDbAccess.java
persistence-modules/duckdb/src/test/resources/customer.csv
persistence-modules/duckdb/src/test/resources/product.json
persistence-modules/pom.xml

JIRA: https://jira.baeldung.com/browse/BAEL-7670

BAEL-7670: Introduction to DuckDB

---

core-java-modules/core-java-lang-oop-others/src/main/java/com/baeldung/printnullvalues/Employee.java
core-java-modules/core-java-lang-oop-others/src/test/java/com/baeldung/printnullvalues/PrintingNullValuesUnitTest.java

This PR aims to add two classes: (Employee, and PrintingNullValuesUnitTest).

This PR is related to BAEL-5998

---

core-java-modules/core-java-networking-5/README.md
core-java-modules/core-java-networking-5/pom.xml
core-java-modules/core-java-networking-5/src/test/java/com/baeldung/redirectedurl/RedirectedUrlUnitTest.java
core-java-modules/pom.xml

Finding the Redirected URL of a URL in Java.

baeldung-articles : BAEL-6484

---

core-java-modules/core-java-8-datetime-3/src/test/java/com/baeldung/stringtooffsetdatetime/StringToOffsetDateTimeUnitTest.java

This PR aims to add a test class "StringToOffsetDateTimeUnitTest".

This PR  is related to 6437

---

core-java-modules/core-java-string-operations-9/src/test/java/com/baeldung/LastOccurrenceFinder/LastOccurrenceFinderUnitTest.java

This PR aims to add a test class named "LastOccurrenceFinderUnitTest".

This PR is related to BAEL-7856

---

core-java-modules/core-java-lang-oop-methods/src/test/java/com/baeldung/testhashcode/HahCodeUnitTest.java
core-java-modules/core-java-lang-oop-methods/src/test/java/com/baeldung/testhashcode/MyClass.java

Unit Test for hashCode() in Java.

baeldung-articles : BAEL-7649

---

core-java-modules/core-java-exceptions-4/README.md
core-java-modules/core-java-exceptions-4/src/main/java/com/baeldung/exception/eof/EOFExceptionDemo.java
core-java-modules/core-java-exceptions-4/src/main/java/com/baeldung/exception/eof/EOFExceptionDemo2.java
core-java-modules/core-java-exceptions-4/src/main/java/com/baeldung/exception/eof/EOFExceptionDemo3.java
core-java-modules/core-java-exceptions-4/src/test/java/com/baeldung/exception/eof/EOFExceptionDemo2UnitTest.java
core-java-modules/core-java-exceptions-4/src/test/java/com/baeldung/exception/eof/EOFExceptionDemo3UnitTest.java
core-java-modules/core-java-exceptions-4/src/test/java/com/baeldung/exception/eof/EOFExceptionDemoUnitTest.java

Code for the article https://drafts.baeldung.com/java-fix-eofexception/?preview=true

[BAEL-7441] Fixing EOFException in Java

---

core-java-modules/core-java-string-operations-9/src/test/java/com/baeldung/hashmapcharactercount/HashMapCharacterCountUnitTest.java

This PR aims to add a test class named "HashMapCharacterCountUnitTest".

This PR is related to BAEL-7854

---

testing-modules/assertion-libraries/src/main/java/com/baeldung/assertj/exceptions/CityNotFoundException.java
testing-modules/assertion-libraries/src/main/java/com/baeldung/assertj/exceptions/CityUtils.java
testing-modules/assertion-libraries/src/test/java/com/baeldung/assertj/exceptions/Java8StyleAssertions.java

Explain how to assert properties of custom exceptions

BAEL-7783: Assert properties of custom exceptions with catchThrowableOfType in AssertJ

---

core-java-modules/core-java-string-operations-9/src/test/java/com/baeldung/removeallcharsbeforechar/RemoveAllCharsBeforeSpecificOneUnitTest.java

This PR aims to add a test class "RemoveAllCharsBeforeSpecificOneUnitTest".

This PR is related to BAEL-7858

---

core-java-modules/core-java-collections-maps-8/src/test/java/com/baeldung/map/valuetokeyset/PositionKeyValueInLinkedHashMapUsingItsKeyUnitTest.java

This PR aims to add a test class "PositionKeyValueInLinkedHashMapUsingItsKeyUnitTest".

This PR is related to BAEL-6682

---

core-java-modules/core-java-collections-maps-8/shorttobytearray/ShortToByteArrayUnitTest.java

This PR aims to add a test class "ShortToByteArrayUnitTest".

This PR is related to BAEL-6872

---

core-groovy-modules/core-groovy-collections/pom.xml

JAVA-28833 :- Fix core-groovy-collections module by Upgrading dependency for JDK 21

---

core-groovy-modules/core-groovy/pom.xml
core-groovy-modules/core-groovy/src/test/groovy/com/baeldung/closures/ClosuresUnitTest.groovy
core-groovy-modules/core-groovy/src/test/groovy/com/baeldung/file/ReadFileUnitTest.groovy
core-groovy-modules/core-groovy/src/test/groovy/com/baeldung/json/JsonParserTest.groovy

Fix core-groovy-modules/core-groovy in the context of migration to JDK 21

JAVA-28832 :- Fix core groovy module major minor error.

---

spring-boot-modules/spring-boot-groovy/pom.xml

JAVA-28826 :- Fix spring-boot-modules/spring-boot-groovy in the context of migration to JDK 21.

---

persistence-modules/spring-boot-persistence-h2/src/main/java/com/baeldung/h2/tablenotfound/TableNotFoundExceptionApplication.java
persistence-modules/spring-boot-persistence-h2/src/main/java/com/baeldung/h2/tablenotfound/entity/Person.java
persistence-modules/spring-boot-persistence-h2/src/main/java/com/baeldung/h2/tablenotfound/repository/PersonRepository.java
persistence-modules/spring-boot-persistence-h2/src/main/resources/data.sql
persistence-modules/spring-boot-persistence-h2/src/test/java/com/baeldung/h2/tablenotfound/TableNotFoundExceptionIntegrationTest.java

BAEL-7759: How to fix Spring Boot H2 JdbcSQLSyntaxErrorException "Table not found"

---

core-java-modules/core-java-io-conversions-2/src/test/java/com/baeldung/csv/ReadCSVInArrayUnitTest.java

Add new methods to read CSV files (I tried to keep the same structure as the existing examples: Junit 4, same assertion logic ...)

BAEL-7887: Reading CSV file using Java 8 Stream API

---

testing-modules/junit-5-advanced/src/test/java/com/baeldung/displayname/ParameterizedTestNameGeneratorUnitTest.java

BAEL-7866: Generating display names for @ParameterizedTest in JUnit 5

---

core-java-modules/core-java-streams-6/src/test/java/com/baeldung/streams/inputstreamintostringstream/InputStreamToStringStreamUnitTest.java

Convert InputStream into Stream<String> in Java.

baeldung-articles : BAEL-7658

---

core-java-modules/core-java-arrays-sorting/src/test/java/com/baeldung/getindicesaftersorting/GetIndicesAfterSortingUnitTest.java

Get the Indices of an Array After Sorting in Java

baeldung-articles : BAEL-6341

---

core-java-modules/core-java-regex-3/extracthtmltag/GetTextFromHtmlTagUnitTest.java
core-java-modules/core-java-regex-3/pom.xml

This PR aims to add a test class and a dependency to the module.

This PR is related to BAEL-7443

---

algorithms-modules/algorithms-miscellaneous-9/README.md
algorithms-modules/algorithms-miscellaneous-9/pom.xml
algorithms-modules/algorithms-miscellaneous-9/src/main/java/com/baeldung/algorithms/permutation/StringPermutation.java
algorithms-modules/algorithms-miscellaneous-9/src/test/java/com/baeldung/algorithms/permutation/StringPermutationTest.java
algorithms-modules/algorithms-miscellaneous-9/src/test/java/com/baeldung/algorithms/permutation/StringPermutationUnitTest.java
algorithms-modules/pom.xml

https://jira.baeldung.com/browse/BAEL-7879
string permutation and tests

BAEL-7879 - Check if two strings are permutations of each other in Java

---

core-java-modules/core-java-collections-6/src/test/java/com/baeldung/IteratorversusIterable/IteratorVersusIterableUnitTest.java

This PR aims to add a test class "IteratorVersusIterableUnitTest".

This PR is related to BAEL-7660

---

core-java-modules/core-java-string-conversions-3/src/test/java/com/baeldung/colbtostringandviceversa/ClobToStringAndViceVersaUnitTest.java

This PR aims to add a test class "ClobToStringAndViceVersaUnitTest".

This PR is related to BAEL-6832

---

core-java-modules/core-java-optional/src/test/java/com/baeldung/ofvsofnullable/OptionalOfVsOfNullableUnitTest.java

Optional.of and Optional.ofNullable unit tests

BAEL-7928: Difference between Optional.of and Optional.ofNullable 

---

core-java-modules/core-java-lang-oop-types-2/src/main/java/com/baeldung/staticenum/Outer.java

This PR aims to add the class "Outer".

This PR is related to BAEL-6826

---

persistence-modules/spring-data-jpa-repo-4/src/main/java/com/baeldung/spring/data/noconverterfound/NoConverterFoundApplication.java
persistence-modules/spring-data-jpa-repo-4/src/main/java/com/baeldung/spring/data/noconverterfound/models/Employee.java
persistence-modules/spring-data-jpa-repo-4/src/main/java/com/baeldung/spring/data/noconverterfound/models/EmployeeFullName.java
persistence-modules/spring-data-jpa-repo-4/src/main/java/com/baeldung/spring/data/noconverterfound/models/IEmployeeFullName.java
persistence-modules/spring-data-jpa-repo-4/src/main/java/com/baeldung/spring/data/noconverterfound/repositories/EmployeeRepository.java
persistence-modules/spring-data-jpa-repo-4/src/test/java/com/baeldung/spring/data/noconverterfound/NoConverterFoundApplicationIntegrationTest.java

+ Create a JPA entity and Spring Data repository
+ Add a test case to test how to reproduce the exception
+ Add another test to test the first solution: class-based projection
+ Add another test to test the second solution: interface-based projection

BAEL-7236: How to solve the exception: No converter found capable of converting from type in Spring Data JPA

---

core-java-modules/core-java-concurrency-advanced-5/src/main/java/com/baeldung/executorservicetest/MyThreadPoolExecutor.java
core-java-modules/core-java-concurrency-advanced-5/src/test/java/com/baeldung/executorservicetest/ExecutorServiceUnitTest.java

[BAEL-7981] How to Unit test an ExecutorService without using Thread.sleep

---

core-java-modules/core-java-io-conversions-3/README.md
core-java-modules/core-java-io-conversions-3/pom.xml
core-java-modules/core-java-io-conversions-3/src/test/java/com/baeldung/csvheadersaslist/CsvHeadersAsListUnitTest.java
core-java-modules/core-java-io-conversions-3/src/test/resources/employees.csv
core-java-modules/pom.xml

+ Create new module
+ Add test cases to test how to read CSV headers into a list

BAEL-7956: Reading CSV headers into a list

---

core-java-modules/core-java-io-6/src/test/java/com/baeldung/removebomfromfile/RemoveBOMUnitTest.java
core-java-modules/core-java-io-6/src/test/resources/file.txt

This PR aims to add a test class "RemoveBOMUnitTest" and a "file.txt".

This PR is related to the article BAEL-6944

---

core-java-modules/core-java-streams-3/src/test/java/com/baeldung/streams/conditional/StreamForEachIfElseUnitTest.java

+ Add test cases to highlight how to use **_Collectors.partitioningBy_**, _**Collectors.groupingBy**_, and **custom consumer** to implement if/else Logic in Java 8 Streams
+ Keep the same existing assertion structure/logic (Junit 4)

BAEL-8000: Conditional processing using the Stream API

---

core-java-modules/core-java-arrays-operations-advanced-2/src/main/java/com/baeldung/closesttozero/BruteForce.java
core-java-modules/core-java-arrays-operations-advanced-2/src/main/java/com/baeldung/closesttozero/PriorityQueueToZero.java
core-java-modules/core-java-arrays-operations-advanced-2/src/main/java/com/baeldung/closesttozero/SortingAndBinarySearch.java
core-java-modules/core-java-arrays-operations-advanced-2/src/test/java/com/baeldung/closesttozero/BruteForceUnitTest.java
core-java-modules/core-java-arrays-operations-advanced-2/src/test/java/com/baeldung/closesttozero/PriorityQueueTOZeroUnitTest.java
core-java-modules/core-java-arrays-operations-advanced-2/src/test/java/com/baeldung/closesttozero/SortingAndBinarySearchUnitTest.java

Closest number to zero

---

core-java-modules/core-java-io-6/src/test/java/com/baeldung/removebomfromfile/RemoveBOMUnitTest.java
core-java-modules/core-java-io-6/src/test/resources/file.txt

This PR aims to update code related to BAEL-6944

This PR is related to BAEL-6944

---

core-java-modules/core-java-io-6/src/test/java/com/baeldung/clearscannerbuffer/ClearScannerBufferUnitTest.java

This PR  aims to add a test class ClearScannerBufferUnitTest.

This PR is related to BAEL-6463

---

json-modules/json/pom.xml
json-modules/json/src/test/java/com/baeldung/json/schema/JSONSchemaUnitTest.java
json-modules/json/src/test/resources/schema.json

- Update dependency to the latest version
- Update JSON Schema version in tests

GST-14 - Update json schema library and version

---

core-java-modules/core-java-date-operations-3/src/test/java/com/baeldung/lastdaymonth/LastDayOfMonthUnitTest.java
pom.xml

Merge branch JAVA-30187 to master.

[JAVA-30187] Upgrade-junit-platform-library-in-the-main-pom (#16585)

---

persistence-modules/spring-boot-persistence-4/pom.xml
persistence-modules/spring-boot-persistence-4/src/main/java/com/baeldung/enumquery/Application.java
persistence-modules/spring-boot-persistence-4/src/main/java/com/baeldung/enumquery/entity/Article.java
persistence-modules/spring-boot-persistence-4/src/main/java/com/baeldung/enumquery/entity/ArticleStage.java
persistence-modules/spring-boot-persistence-4/src/main/java/com/baeldung/enumquery/repository/ArticleRepository.java
persistence-modules/spring-boot-persistence-4/src/test/java/com/baeldung/enumquery/EnumJpaQueryIntegrationTest.java
persistence-modules/spring-boot-persistence-4/src/test/java/com/baeldung/enumquery/EnumNativeQueryIntegrationTest.java

Codebase for the article: **Using Enum in Spring Data JPA queries**

codebase/using-enum-in-spring-data-jpa-queries [BAEL-8042]

---

jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/constructordetector/Address.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/constructordetector/Product.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/constructordetector/StringWrapper.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/constructordetector/User.java
jackson-modules/jackson-custom-conversions/src/test/java/com/baeldung/constructordetector/ConstructorDetectorUnitTest.java

This PR aims to add a main and test classes to the module.

This PR is related to BAEL-6306

---

javaxval-2/src/main/java/com/baeldung/javaxval/childvalidation/Project.java
javaxval-2/src/main/java/com/baeldung/javaxval/childvalidation/Task.java
javaxval-2/src/main/java/com/baeldung/javaxval/childvalidation/User.java
javaxval-2/src/test/java/com/baeldung/javaxval/childvalidation/ChildValidationUnitTest.java

Validate nested child objects using @Valid annotation

BAEL-6118 Child object validation

---

core-java-modules/core-java-numbers-conversions-2/exponentialtonumber/ExponentialToNumberUnitTest.java

Converting Exponential Value to a Number Format in Java.

baeldung-articles : BAEL-6632

---

core-java-modules/core-java-string-operations-9/src/test/java/com/baeldung/insertemojiinstring/InsertEmojiInStringUnitTest.java

This PR aims to add a test class InsertEmojiInStringUnitTest.

This PR is related to BAEL-7857

---

core-java-modules/core-java-lang-oop-inheritance/src/main/java/com/baeldung/upcastingvsdowncasting/Animal.java
core-java-modules/core-java-lang-oop-inheritance/src/main/java/com/baeldung/upcastingvsdowncasting/Dog.java
core-java-modules/core-java-lang-oop-inheritance/src/main/java/com/baeldung/upcastingvsdowncasting/Main.java

Upcasting Versus Downcasting in Java.

baeldung-articles : BAEL-7833

---

core-java-modules/core-java-numbers-conversions-2/inttounsignedbyte/IntToUnsignedByteUnitTest.java

This PR aims to add a test class IntToUnsignedByteUnitTest.

This PR is related to BAEL-7837

---

core-java-modules/core-java-collections-array-list-2/src/test/java/com/baeldung/avoidduplicatearraylist/AvoidDuplicateInArrayListUnitTest.java

+ Add tests to showcase how to avoid inserting duplicates in ArrayList

BAEL-7910: Avoid Inserting Duplicate in ArrayList in Java

---

jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/formatinstantobjectmapper/Event.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/formatinstantobjectmapper/History.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/formatinstantobjectmapper/Session.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/formatinstantobjectmapper/serializer/CustomInstantDeserializer.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/formatinstantobjectmapper/serializer/CustomInstantSerializer.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/formatinstantobjectmapper/serializer/GlobalInstantDeserializer.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/formatinstantobjectmapper/serializer/GlobalInstantSerializer.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/formatinstantobjectmapper/utils/Instants.java
jackson-modules/jackson-custom-conversions/src/main/java/com/baeldung/formatinstantobjectmapper/utils/TimeStampTracker.java
jackson-modules/jackson-custom-conversions/src/test/java/com/baeldung/formatinstantobjectmapper/InstantFormatUnitTest.java

Draft: https://drafts.baeldung.com/wp-admin/post.php?post=201560&action=edit

BAEL-7888 - Set Format for Instant Using ObjectMapper

---

core-java-modules/core-java-io-6/pom.xml
core-java-modules/core-java-io-6/src/test/java/com/baeldung/readlastlines/ReadLastLinesUnitTest.java
core-java-modules/core-java-io-6/src/test/resources/data.txt

BAEL-8072 read last n lines from file. Added common-io dependency in pom.xml.

BAEL-8072 read last n lines from file

---

persistence-modules/java-jpa/src/test/java/com/baeldung/jpa/convertdates/LocalDateTimeToSqlDateUnitTest.java

+ Add a class test to test how to perform LocalDateTime/java.sql.Date conversion

BAEL-7952: Convert LocalDateTime to java.sql.Date

---

libraries-data-db/pom.xml
libraries-data-db/src/main/java/com/baeldung/libraries/tigerbeetle/config/TigerBeetleConfig.java
libraries-data-db/src/main/java/com/baeldung/libraries/tigerbeetle/domain/Account.java
libraries-data-db/src/main/java/com/baeldung/libraries/tigerbeetle/domain/AccountException.java
libraries-data-db/src/main/java/com/baeldung/libraries/tigerbeetle/domain/Balance.java
libraries-data-db/src/main/java/com/baeldung/libraries/tigerbeetle/domain/Transfer.java
libraries-data-db/src/main/java/com/baeldung/libraries/tigerbeetle/domain/TransferException.java
libraries-data-db/src/main/java/com/baeldung/libraries/tigerbeetle/repository/AccountRepository.java
libraries-data-db/src/test/java/com/baeldung/libraries/tigerbeetle/TigerBeetleLiveTest.java

JIRA: https://jira.baeldung.com/browse/BAEL-7978
WP: https://drafts.baeldung.com/wp-admin/post.php?post=204176&action=edit

[BAEL-7978] WIP: Sanity check

---

testing-modules/cors/pom.xml
testing-modules/cors/src/main/java/com/example/cors/Application.java
testing-modules/cors/src/main/java/com/example/cors/configuration/SecurityConfiguration.java
testing-modules/cors/src/main/java/com/example/cors/controller/JokeController.java
testing-modules/cors/src/test/java/com/example/cors/CorsIntegrationTest.java
testing-modules/pom.xml

Codebase for the article: **Testing CORS in Spring Boot**

codebase/testing-cors-in-spring-boot [BAEL-7038]

---

persistence-modules/hibernate-exceptions/src/test/java/com/baeldung/hibernate/unknownentityexception/UnknownEntityExceptionUnitTest.java

+ Add a test class to showcase how to reproduce and fix _UnknownEntityException: Could not resolve root entity_

BAEL-7982: How to fix Hibernate UnknownEntityException: Could not resolve root entity

---

spring-core-4/src/main/java/com/baeldung/destroyprototypebean/PrototypeExample.java
spring-core-4/src/main/java/com/baeldung/destroyprototypebean/beanpostprocessor/CustomPostProcessor.java
spring-core-4/src/main/java/com/baeldung/destroyprototypebean/beanpostprocessor/PostProcessorBeanExample.java
spring-core-4/src/main/java/com/baeldung/destroyprototypebean/destorymethod/CustomMethodBeanExample.java
spring-core-4/src/main/java/com/baeldung/destroyprototypebean/disposablebean/DisposableBeanExample.java
spring-core-4/src/main/java/com/baeldung/destroyprototypebean/predestroy/PreDestroyBeanExample.java
spring-core-4/src/test/java/com/baeldung/destroyprototypebean/beanpostprocessor/BeanPostProcessorConfig.java
spring-core-4/src/test/java/com/baeldung/destroyprototypebean/beanpostprocessor/CustomPostProcessorUnitTest.java
spring-core-4/src/test/java/com/baeldung/destroyprototypebean/destroymethod/CustomMethodBeanExampleUnitTest.java
spring-core-4/src/test/java/com/baeldung/destroyprototypebean/destroymethod/DestroyMethodConfig.java
spring-core-4/src/test/java/com/baeldung/destroyprototypebean/disposablebean/DisposableBeanConfig.java
spring-core-4/src/test/java/com/baeldung/destroyprototypebean/disposablebean/DisposableBeanExampleUnitTest.java
spring-core-4/src/test/java/com/baeldung/destroyprototypebean/predestroy/PreDestroyBeanExampleUnitTest.java
spring-core-4/src/test/java/com/baeldung/destroyprototypebean/predestroy/PreDestroyConfig.java

Examples of how to manually destroy prototype beans

BAEL-7004 Manually destroy prototype beans

---

core-java-modules/core-java-concurrency-advanced-5/pom.xml
core-java-modules/core-java-concurrency-advanced-5/src/main/java/com/baeldung/executerservicecustomthreadname/CustomThreadFactory.java
core-java-modules/core-java-concurrency-advanced-5/src/main/java/com/baeldung/executerservicecustomthreadname/ExecuterServiceCustomThreadName.java
core-java-modules/core-java-concurrency-advanced-5/src/test/java/executerservicecustomthreadname/ExecuterServiceCustomThreadNameUnitTest.java

https://drafts.baeldung.com/wp-admin/post.php?post=201102&action=edit
https://jira.baeldung.com/browse/BAEL-7921

executerservice custom thread name

---

parent-boot-3/pom.xml
pom.xml
spring-security-modules/pom.xml
spring-security-modules/spring-security-authorization/pom.xml
spring-security-modules/spring-security-authorization/spring-security-annotation-template-parameter/pom.xml
spring-security-modules/spring-security-authorization/spring-security-annotation-template-parameter/src/main/java/com/baeldung/SpringSecurityAnnotationParameterApplication.java
spring-security-modules/spring-security-authorization/spring-security-annotation-template-parameter/src/main/java/com/baeldung/annotation/CustomHasAnyRole.java
spring-security-modules/spring-security-authorization/spring-security-annotation-template-parameter/src/main/java/com/baeldung/controller/MessageController.java
spring-security-modules/spring-security-authorization/spring-security-annotation-template-parameter/src/main/java/com/baeldung/model/Message.java
spring-security-modules/spring-security-authorization/spring-security-annotation-template-parameter/src/main/java/com/baeldung/security/SecurityConfiguration.java
spring-security-modules/spring-security-authorization/spring-security-annotation-template-parameter/src/main/java/com/baeldung/service/MessageService.java
spring-security-modules/spring-security-authorization/spring-security-annotation-template-parameter/src/test/java/com/baeldung/SpringSecurityAnnotationParameterApplicationTests.java
spring-security-modules/spring-security-authorization/spring-security-secure-domain-object/pom.xml
spring-security-modules/spring-security-authorization/spring-security-secure-domain-object/src/main/java/com/baeldung/SpringSecuritySeureReturnObject.java
spring-security-modules/spring-security-authorization/spring-security-secure-domain-object/src/main/java/com/baeldung/config/SecurityConfiguration.java
spring-security-modules/spring-security-authorization/spring-security-secure-domain-object/src/main/java/com/baeldung/error/handler/MaskMethodAuthorizationDeniedHandler.java
spring-security-modules/spring-security-authorization/spring-security-secure-domain-object/src/main/java/com/baeldung/model/Account.java
spring-security-modules/spring-security-authorization/spring-security-secure-domain-object/src/main/java/com/baeldung/repo/AccountService.java
spring-security-modules/spring-security-authorization/spring-security-secure-domain-object/src/test/java/com/baeldung/SpringSecuritySecureDomainObjectTest.java

Spring Security 6.3 New Changes

BAEL-8034: Spring Security 6.3 New Changes

---

testing-modules/cucumber/src/main/passinglistascucumberparameter/DataTableLoginSteps.java
testing-modules/cucumber/src/main/passinglistascucumberparameter/LocalDateTransformer.java
testing-modules/cucumber/src/main/passinglistascucumberparameter/LoginSteps.java
testing-modules/cucumber/src/main/passinglistascucumberparameter/RegexLoginSteps.java

- Added DataTableLoginSteps.java to handle login steps using DataTable for list parameters.
- Added LocalDateTransformer.java to transform date strings into LocalDate objects.
- Added LoginSteps.java for basic login step definitions.
- Added RegexLoginSteps.java to handle login steps using regular expressions.

Add Cucumber for passing list parameters

---

core-java-modules/core-java-date-operations-1/src/test/java/com/baeldung/datetime/TimeStampExtractYearMonthDayIntegerValuesUnitTest.java

BAEL-8120 improvement to add java.sql.Timestamp example to extract day , month and year

BAEL-8120 improvement add timestamp example

---

testing-modules/groovy-spock/src/main/java/com/baeldung/spock/helpermethods/Account.java
testing-modules/groovy-spock/src/main/java/com/baeldung/spock/helpermethods/Address.java
testing-modules/groovy-spock/src/test/groovy/com/baeldung/spock/helpermethods/AccountUnitTest.groovy

BAEL-7313 Spock Helper methods - with and verifyAll

---

core-java-modules/core-java-collections-maps-8/src/literalsyntaxforbytearraysusinghexnotation/LiteralSyntaxForByteArraysUsingHexNotation.java

This PR aims to add a Java class to the module.

This PR is related to BAEL-8145

---

core-java-modules/core-java-date-operations-4/src/test/java/com/baeldung/monthnamestonumbers/MonthNamesToNumbersUnitTest.java

+ Add tests to showcase how to get a month number from its name

BAEL-8121: Getting month number from its name in Java

---

apache-kafka/src/test/java/com/baeldung/flink/BackupCreatorUnitTest.java

tested all tests working. Changed to CopyOnWriteArrayList to avoid contention and make tests faster.

JAVA-37247:- Check inconsistent test apache-kafka/.../BackupCreatorUnitTest.java

---

reactor-core-2/src/test/java/com/baeldung/reactor/convertlistoflux/ListToFluxUnitTest.java

BAEL-7567 - How to convert List<T> to Flux<T> in Spring Reactor

---

persistence-modules/core-java-persistence-3/src/test/java/com/baeldung/eclipse/mysql/EclipseMySQLLiveTest.java

This is pertaining to Jira BAEL-8220

Setup MySQL DB in Eclipse

---

testing-modules/automated-testing/.gitignore
testing-modules/automated-testing/base/page-object-model-fixture.ts
testing-modules/automated-testing/package-lock.json
testing-modules/automated-testing/package.json
testing-modules/automated-testing/playwright.config.ts
testing-modules/automated-testing/readme.md
testing-modules/automated-testing/test-data/register-user-data.json
testing-modules/automated-testing/tests/pageobjects/home-page.ts
testing-modules/automated-testing/tests/pageobjects/my-account-page.ts
testing-modules/automated-testing/tests/pageobjects/registration-page.ts
testing-modules/automated-testing/tests/pageobjects/search-result-page.ts
testing-modules/automated-testing/tests/pageobjects/shopping-cart-page.ts
testing-modules/automated-testing/tests/specs/e-commerce.spec.ts

added playwright ts demo project in testing-modules/automated-testing folder

---

libraries-http-3/pom.xml
libraries-http-3/src/main/java/com/baeldung/enumwithallhttpstatuscodes/HttpStatus.java
libraries-http-3/src/test/java/com/baeldung/enumwithallhttpstatuscodes/EnumWithHttpStatusCodesLiveTest.java
libraries-http-3/src/test/java/com/baeldung/enumwithallhttpstatuscodes/EnumWithHttpStatusCodesUnitTest.java
pom.xml

PR to the article named Java Enums with all HTTP status codes [BAEL-6037].

PR:BAEL-6037

---

core-java-modules/core-java-io-6/src/main/java/com/baeldung/filelisting/FileListing.java
core-java-modules/core-java-io-6/src/test/java/com/baeldung/filelisting/FileListingUnitTest.java

Added code for BAEL-8076

---

security-modules/java-ee-8-security-api/app-auth-basic-store-db/pom.xml
security-modules/java-ee-8-security-api/app-auth-custom-form-store-custom/pom.xml
security-modules/java-ee-8-security-api/app-auth-custom-no-store/pom.xml
security-modules/java-ee-8-security-api/app-auth-form-store-ldap/pom.xml

added the version number in pom file.

Java-37858 fix missing plugin version

---

json-modules/json-arrays/updatingvaluesinjsonarray/UpdatingValuesUnitTest.java

This PR aims to add a Java class to the module.

This PR is related to BAEL-8299

---

spring-cloud-modules/pom.xml
spring-cloud-modules/spring-cloud-gateway-3/README.md
spring-cloud-modules/spring-cloud-gateway-3/pom.xml
spring-cloud-modules/spring-cloud-gateway-3/spring-backend-service/pom.xml
spring-cloud-modules/spring-cloud-gateway-3/spring-backend-service/src/main/java/com/baeldung/productservice/ProductApplication.java
spring-cloud-modules/spring-cloud-gateway-3/spring-backend-service/src/main/java/com/baeldung/productservice/config/OpenAPIConfig.java
spring-cloud-modules/spring-cloud-gateway-3/spring-backend-service/src/main/java/com/baeldung/productservice/controller/ProductController.java
spring-cloud-modules/spring-cloud-gateway-3/spring-backend-service/src/main/java/com/baeldung/productservice/model/Product.java
spring-cloud-modules/spring-cloud-gateway-3/spring-backend-service/src/main/resources/application.yml
spring-cloud-modules/spring-cloud-gateway-3/spring-backend-service/src/test/java/com/baeldung/productservice/SpringContextTest.java
spring-cloud-modules/spring-cloud-gateway-3/spring-backend-service/src/test/java/com/baeldung/productservice/controller/ProductControllerUnitTest.java
spring-cloud-modules/spring-cloud-gateway-3/spring-cloud-gateway-service/pom.xml
spring-cloud-modules/spring-cloud-gateway-3/spring-cloud-gateway-service/src/main/java/com/baeldung/apigateway/ApiGatewayApplication.java
spring-cloud-modules/spring-cloud-gateway-3/spring-cloud-gateway-service/src/main/java/com/baeldung/apigateway/config/OpenAPIConfig.java
spring-cloud-modules/spring-cloud-gateway-3/spring-cloud-gateway-service/src/main/resources/application.yml
spring-cloud-modules/spring-cloud-gateway-3/spring-cloud-gateway-service/src/test/java/com/baeldung/apigayewayapp/SpringContextTest.java

Integrated OpenAPI specification for a backend service in the API Gateway service.
A seperate repo with two projects was needed as the OpenAPI dependency between spring cloud gateway webflux-ui and spring boot web's open-webmvc conflicts and does not work properly.

Bael 6599: OpenAPI documentation integrated in API Gateway Service

---

spring-boot-modules/spring-boot-mvc-jersey/spring-boot-jersey/src/main/java/com/baeldung/boot/jersey/JerseyResourceConfig.java

Expose REST resource via config

---

core-java-modules/pom.xml
json-modules/pom.xml
pom.xml
quarkus-modules/pom.xml
spring-security-modules/pom.xml
testing-modules/pom.xml

[JAVA-37091]

---

spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/SynchronousRequestsApp.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/gateway/ApiGatewayController.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/gateway/ApiGatewayException.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/gateway/CustomerInfo.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/gateway/CustomerInfoService.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/system/billing/Billing.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/system/billing/BillingController.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/system/billing/BillingService.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/system/billing/BillingServiceFake.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/system/customer/Customer.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/system/customer/CustomerController.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/system/customer/CustomerService.java
spring-reactive-modules/spring-reactive-client-2/src/main/java/com/baeldung/synchronous/system/customer/CustomerServiceFake.java
spring-reactive-modules/spring-reactive-client-2/src/test/java/com/baeldung/synchronous/gateway/ApiGatewayControllerIntegrationTest.java

- add synchronous request app
- add CustomerInfoService that invokes BillingController and CustomerController in a blocking manner and returns a response synchronously
- add junit test with timeout condition

[BAEL-7389] Execute Synchronous Request With Webclient

---

core-java-modules/core-java-io/src/main/java/com/baeldung/fileparser/CommonsFileUtilsExample.java
core-java-modules/core-java-io/src/main/java/com/baeldung/fileparser/FilesLinesExample.java
core-java-modules/core-java-io/src/main/java/com/baeldung/fileparser/GuavaFilesExample.java
core-java-modules/core-java-io/src/test/java/com/baeldung/fileparser/CommonsFileUtilsExampleUnitTest.java
core-java-modules/core-java-io/src/test/java/com/baeldung/fileparser/FilesLinesExampleUnitTest.java
core-java-modules/core-java-io/src/test/java/com/baeldung/fileparser/GuavaFilesExampleUnitTest.java

+ Add test cases to test how to read a file into an ArrayList using new methods and classes: Java 8 _**Files**_ class, **_FileUtils_** from Apache Commons, and **_Files_** class from Guava.
+ I kept the same logic and structure in both the PR and article (Maybe re-organize the code in another improvement ... I think we don't need to create a class/test for each solution).

BAEL-8509: Improve article low in traffic: Read a File into an ArrayList

---

quarkus-modules/pom.xml
quarkus-modules/quarkus-clientbasicauth/README.md
quarkus-modules/quarkus-clientbasicauth/pom.xml
quarkus-modules/quarkus-clientbasicauth/src/main/java/com/baeldung/quarkus/MyService.java
quarkus-modules/quarkus-clientbasicauth/src/main/java/com/baeldung/quarkus/MyServiceImpl.java
quarkus-modules/quarkus-clientbasicauth/src/main/resources/application.properties
quarkus-modules/quarkus-clientbasicauth/src/test/java/com/baeldung/quarkus/ClientBasicAuthUnitTest.java
quarkus-modules/quarkus-clientbasicauth/src/test/java/com/baeldung/quarkus/GreetingResourceTest.java
quarkus-modules/quarkus-clientbasicauth/src/test/java/com/baeldung/quarkus/MyServiceJohnRightCredentials.java
quarkus-modules/quarkus-clientbasicauth/src/test/java/com/baeldung/quarkus/MyServiceJohnWrongCredentials.java

BAEL-7781 - @ClientBasicAuth in Quarkus REST Client

BAEL-7781 - @ClientBasicAuth in Quarkus REST Client

---

json-modules/json-operations/src/test/jacksonfindvalue/JacksonFindValueUnitTest.java

PR to the article named Using findValue to get the value for a nested key in Jackson [BAEL-7820].

PR: BAEL-7820

---

testing-modules/selenium-2/src/test/java/com/baeldung/selenium/find/CheckIfElementPresentManualTest.java

Add code examples for article "Checking if an element exists with Selenium WebDriver"

---

core-java-modules/core-java-23/README.md
core-java-modules/core-java-23/pom.xml
core-java-modules/core-java-23/src/main/java/com/baeldung/javafeatures/ImplicitClass.java
core-java-modules/pom.xml

https://jira.baeldung.com/browse/BAEL-8366

Implicit classes and instance main methods in jdk23

---

spring-web-modules/spring-mvc-test/build.gradle
spring-web-modules/spring-mvc-test/settings.gradle
spring-web-modules/spring-mvc-test/src/main/java/com/testing/mvc/MvcApplication.java
spring-web-modules/spring-mvc-test/src/main/java/com/testing/mvc/SortingController.java
spring-web-modules/spring-mvc-test/src/main/java/com/testing/mvc/SortingService.java
spring-web-modules/spring-mvc-test/src/main/resources/application.properties
spring-web-modules/spring-mvc-test/src/test/java/com/testing/mvc/springboottest/SortingControllerIntegrationTest.java
spring-web-modules/spring-mvc-test/src/test/java/com/testing/mvc/springboottest/SortingControllerWithWebEnvironmentIntegrationTest.java
spring-web-modules/spring-mvc-test/src/test/java/com/testing/mvc/webmvctest/SortingControllerUnitTest.java

Hi software.michael@gmx.de ,
Could you please review the following PR related to [BAEL-8418](https://jira.baeldung.com/browse/BAEL-8418) .
Article Draft link: https://drafts.baeldung.com/?p=211936&preview=true

adding "Difference Between Using MockMvc with SpringBootTest and Using WebMvcTest" | BAEL-8418

---

core-java-modules/core-java-interface/README.md
core-java-modules/core-java-interface/pom.xml
core-java-modules/core-java-interface/src/main/java/org/annotations/Review.java
core-java-modules/core-java-interface/src/main/java/org/annotations/ReviewUsage.java
core-java-modules/core-java-interface/src/main/java/org/interfaces/Animal.java
core-java-modules/core-java-interface/src/main/java/org/interfaces/Dog.java
core-java-modules/core-java-interface/src/test/java/org/annotations/ReviewUsageTest.java
core-java-modules/core-java-interface/src/test/java/org/interfaces/DogTest.java

Article link: https://drafts.baeldung.com/interface-vs-interface/

BAEL-8458: What's the difference between interface and @interface in Java

---

core-java-modules/core-java-8-datetime-3/src/test/java/com/baeldung/datetimecombination/DateTimeCombinationUnitTest.java

This PR aims to add a Java class to the module.

This PR is related to BAEL-8116

---

microservices-modules/micronaut-configuration/src/main/java/com/baeldung/micronaut/globalexceptionhandler/ServerApplication.java
microservices-modules/micronaut-configuration/src/main/java/com/baeldung/micronaut/globalexceptionhandler/controller/ErroneousController.java
microservices-modules/micronaut-configuration/src/main/java/com/baeldung/micronaut/globalexceptionhandler/controller/ProbesController.java
microservices-modules/micronaut-configuration/src/main/java/com/baeldung/micronaut/globalexceptionhandler/error/CustomChildException.java
microservices-modules/micronaut-configuration/src/main/java/com/baeldung/micronaut/globalexceptionhandler/error/CustomException.java
microservices-modules/micronaut-configuration/src/main/java/com/baeldung/micronaut/globalexceptionhandler/error/handlers/CustomExceptionHandler.java
microservices-modules/micronaut-configuration/src/main/java/com/baeldung/micronaut/globalexceptionhandler/error/handlers/NotFoundController.java
microservices-modules/micronaut-configuration/src/test/java/com/baeldung/micronaut/globalexceptionhandler/ServerApplicationUnitTest.java

* Examples for error annotation, both for exceptions and status codes
* Examples for ExceptionHandler implementation for specific exceptions

[BAEL-6574] Introduced code examples for error handling in micronaut

---

libraries-bytecode/pom.xml
libraries-bytecode/src/main/java/com/baeldung/teavm/Calculator.java
libraries-bytecode/src/main/java/com/baeldung/teavm/TeaVMRunner.java
libraries-bytecode/src/test/java/com/baeldung/teavm/CalculatorUnitTest.java

https://jira.baeldung.com/browse/BAEL-7666

https://jira.baeldung.com/browse/BAEL-7666

---

algorithms-modules/algorithms-sorting/README.md

Updated README.md and fixed typo in reference to algorithms-sorting-2 article

fixed typo in reference to algorithms-sorting-2 article

---

spring-boot-modules/spring-boot-documentation/pom.xml
spring-boot-modules/spring-boot-documentation/src/main/java/com/baeldung/boot/documentation/springwolf/adapter/incoming/IncomingConsumer.java
spring-boot-modules/spring-boot-documentation/src/main/java/com/baeldung/boot/documentation/springwolf/adapter/outgoing/OutgoingProducer.java
spring-boot-modules/spring-boot-documentation/src/main/resources/application.properties
spring-boot-modules/spring-boot-documentation/src/test/java/com/baeldung/boot/documentation/springwolf/ApiIntegrationTest.java
spring-boot-modules/spring-boot-documentation/src/test/resources/asyncapi.json

Module: spring-boot-modules/spring-boot-documentation

Update to springwolf to 1.5.0

---

core-java-modules/core-java-lang-math-4/src/test/java/com/baeldung/math/percentdiffbetweentwonumberstest/PercentDiffBetweenTwoNumbersUnitTest.java

fix: fixed inconsitent namings

---

guava-modules/guava-collections-map/src/main/java/com/baeldung/guava/multimap/MultimapIteration.java

+ Add methods to demonstrate how to iterate over a Multimap
+ We're implementing iteration logic, so no test cases added (inspired from https://github.com/eugenp/tutorials/tree/master/core-java-modules/core-java-collections-maps-2/src/main/java/com/baeldung/map/iteration)

BAEL-8488: Iterating Through Guava Multimap

---

persistence-modules/hibernate-annotations-2/pom.xml
persistence-modules/hibernate-annotations-2/src/main/java/com/baeldung/hibernate/timezonestorage/Application.java
persistence-modules/hibernate-annotations-2/src/main/java/com/baeldung/hibernate/timezonestorage/AstronomicalObservation.java
persistence-modules/hibernate-annotations-2/src/main/java/com/baeldung/hibernate/timezonestorage/AstronomicalObservationRepository.java
persistence-modules/hibernate-annotations-2/src/main/resources/application.yml
persistence-modules/hibernate-annotations-2/src/test/java/com/baeldung/hibernate/timezonestorage/TimeZoneStorageIntegrationTest.java

Codebase for the article: **Guide to Hibernate’s @TimeZoneStorage Annotation**

codebase/guide-to-hibernate-timezonestorage-annotation [BAEL-8320]

---

persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/jsontypeexception/Student.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/Book.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/BookDto.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/OptionalFieldsApplication.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/dto/BookDtoRepository.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/objects/BookObjectsRepository.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/objects/BookTupleRepository.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/projection/BookProjection.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/projection/BookProjectionRepository.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/sqlmapping/BookCustomRepository.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/sqlmapping/BookSqlMappingRepository.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/optionalfields/sqlmapping/BookSqlMappingRepositoryImpl.java
persistence-modules/spring-data-jpa-query-5/src/main/resources/application-h2.properties
persistence-modules/spring-data-jpa-query-5/src/test/java/com/baeldung/spring/data/jpa/optionalfields/OptionalFieldsUnitTest.java

multiple solutions for making fields optional with spring data with tests

BAEL-8562 - How to make a field as optional in JPA Entity?

---

apache-poi-3/pom.xml
apache-poi-3/src/test/java/com/baeldung/resultset/DataPreparer.java
apache-poi-3/src/test/java/com/baeldung/resultset/ResultSet2Workbook.java
apache-poi-3/src/test/java/com/baeldung/resultset/ResultSetExcelUnitTest.java

BAEL-8564: Writing JDBC ResultSet to an Excel file using Apache POI

BAEL-8564: Writing JDBC ResultSet to an Excel file using Apache POI

---

json-modules/json-operations/src/test/jsoncollectioncomparison/JsonCollectionComparisonUnitTest.java

This PR aims to add a Java class to the module.

This PR is related to BAEL-7090

---

persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/filtering/FilteringApplication.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/filtering/WearableBrokenRepository.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/filtering/WearableInvalidEntity.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/filtering/WearableRepository.java
persistence-modules/spring-data-jpa-query-5/src/main/java/com/baeldung/spring/data/jpa/filtering/WearableValidEntity.java
persistence-modules/spring-data-jpa-query-5/src/test/java/com/baeldung/spring/data/jpa/filtering/WearableRepositoryInvalidEntityIntegrationTest.java
persistence-modules/spring-data-jpa-query-5/src/test/java/com/baeldung/spring/data/jpa/filtering/WearableRepositoryValidEntityIntegrationTest.java
persistence-modules/spring-data-jpa-query-5/src/test/resources/application-h2.properties
persistence-modules/spring-data-jpa-query-5/src/test/resources/testdata.sql

Adds the code implementation for the article
Spring data JPA - Unable to find local attribute with a given name

Bael-8362 BAEL-8362: Add Spring data jpa unable to find local attribute with a given name example in spring-data-jpa-query-5 module

---

spring-scheduling-2/src/main/java/com/baeldung/scheduleonlyonce/ScheduleOnylOnceApplication.java
spring-scheduling-2/src/main/java/com/baeldung/scheduleonlyonce/service/ScheduleOnceService.java
spring-scheduling-2/src/main/java/com/baeldung/scheduleonlyonce/trigger/OneOffTrigger.java
spring-scheduling-2/src/test/java/com/baeldung/scheduleonlyonce/ScheduleOnceServiceIntegrationTest.java

Draft: https://drafts.baeldung.com/wp-admin/post.php?post=214181&action=edit

BAEL 6990 - How to Execute a Scheduled Task Only Once for a Spring Boot Application

---

apache-libraries-2/src/main/java/com/baeldung/apache/avrotojson/AvroFileToJsonFile.java
apache-libraries-2/src/main/java/com/baeldung/apache/avrotojson/Point.java
apache-libraries-2/src/test/java/com/baeldung/apache/avrotojson/AvroFileToJsonFileTests.java

Added implementation of Avro file to JSON file conversion

Added implementation of Avro file to JSON file conversion - BAEL-8667

---

core-java-modules/core-java-date-operations-4/src/main/java/com/baeldung/sundaystartyears/FindSundayStartYearsLegacy.java
core-java-modules/core-java-date-operations-4/src/main/java/com/baeldung/sundaystartyears/FindSundayStartYearsSpliterator.java
core-java-modules/core-java-date-operations-4/src/main/java/com/baeldung/sundaystartyears/FindSundayStartYearsTimeApi.java
core-java-modules/core-java-date-operations-4/src/test/java/com/baeldung/sundaystartyears/FindSundayStartYearsLegacyUnitTest.java
core-java-modules/core-java-date-operations-4/src/test/java/com/baeldung/sundaystartyears/FindSundayStartYearsSpliteratorUnitTest.java
core-java-modules/core-java-date-operations-4/src/test/java/com/baeldung/sundaystartyears/FindSundayStartYearsTimeApiUnitTest.java

- Implements the solution using Date and Calendar, and the new approach using java.time API.
- Implements an optimized example using Spliterator<LocalDate>.
- Provides unit tests for each of the added classes.

BAEL-8318 Code and Unit Tests for Years Start on Sunday

---

libraries-5/pom.xml
libraries-5/src/main/java/com/baeldung/yauaa/Application.java
libraries-5/src/main/java/com/baeldung/yauaa/HomePageController.java
libraries-5/src/main/java/com/baeldung/yauaa/UserAgentAnalyzerConfiguration.java
libraries-5/src/main/java/com/baeldung/yauaa/UserAgentAttributeLoggingFilter.java
libraries-5/src/main/resources/templates/error/open-in-mobile.html
libraries-5/src/main/resources/templates/mobile-home.html
libraries-5/src/test/java/com/baeldung/yauaa/HomePageControllerIntegrationTest.java

Codebase for the article: **User Agent Parsing Using Yauaa**

codebase/user-agent-parsing-using-yauaa [BAEL-8700]

---

core-java-modules/core-java-io-7/README.md
core-java-modules/core-java-io-7/pom.xml
core-java-modules/core-java-io-7/src/test/java/com/baeldung/fileto2darray/FileTo2DArrayUnitTest.java
core-java-modules/core-java-io-7/src/test/resources/test_file.csv
core-java-modules/core-java-io-7/src/test/resources/test_file.txt
core-java-modules/pom.xml

This PR aims to add files and test class regarding BAEL-8254

PR: BAEL-8254

---

gcp-firebase/pom.xml
gcp-firebase/src/main/java/com/baeldung/gcp/firebase/firestore/FirestoreConfiguration.java
gcp-firebase/src/test/java/com/baeldung/gcp/firebase/firestore/TaskCrudLiveTest.java

PR converts an IntegrationTest to a LiveTest due to Docker dependency.

fix/renaming-test-class [BAEL-8475]

---

persistence-modules/hibernate-annotations-2/src/main/java/com/baeldung/hibernate/timezonestorage/AstronomicalObservation.java
persistence-modules/hibernate-annotations-2/src/test/java/com/baeldung/hibernate/timezonestorage/TimeZoneStorageIntegrationTest.java

PR fixes intermittent integration test failure in class `TimeZoneStorageIntegrationTest`.

fix/integration-test [BAEL-8320]

---

persistence-modules/hibernate6/src/main/java/com/baeldung/arrayscollections/Application.java
persistence-modules/hibernate6/src/main/java/com/baeldung/arrayscollections/dialects/CustomDialect.java
persistence-modules/hibernate6/src/main/java/com/baeldung/arrayscollections/entity/MigratingUser.java
persistence-modules/hibernate6/src/main/java/com/baeldung/arrayscollections/entity/User.java
persistence-modules/hibernate6/src/main/java/com/baeldung/arrayscollections/repository/MigratingUserRepository.java
persistence-modules/hibernate6/src/main/resources/application-customdialect.yaml
persistence-modules/hibernate6/src/main/resources/application-oracle.yaml
persistence-modules/hibernate6/src/main/resources/application-postgres.yaml
persistence-modules/hibernate6/src/test/java/com/baeldung/arrayscollections/HibernateCollectionsCustomDialectUnitTest.java
persistence-modules/hibernate6/src/test/java/com/baeldung/arrayscollections/HibernateCollectionsOracleUnitTest.java
persistence-modules/hibernate6/src/test/java/com/baeldung/arrayscollections/HibernateCollectionsPostgresUnitTest.java

BAEL-6280 - Storing Basic Arrays and Collections using ARRAY/JSON/XML Types in HibernateMaster2

---

spring-web-modules/spring-mvc-basics-5/pom.xml
spring-web-modules/spring-mvc-basics-5/src/main/java/com/baeldung/deletewrequestbody/DeleteController.java
spring-web-modules/spring-mvc-basics-5/src/main/java/com/baeldung/deletewrequestbody/client/Apache5DeleteClient.java
spring-web-modules/spring-mvc-basics-5/src/main/java/com/baeldung/deletewrequestbody/client/ApacheDeleteClient.java
spring-web-modules/spring-mvc-basics-5/src/main/java/com/baeldung/deletewrequestbody/client/PlainDeleteClient.java
spring-web-modules/spring-mvc-basics-5/src/main/java/com/baeldung/deletewrequestbody/client/SpringTemplateDeleteClient.java
spring-web-modules/spring-mvc-basics-5/src/main/java/com/baeldung/deletewrequestbody/client/helper/HttpDeleteBody.java
spring-web-modules/spring-mvc-basics-5/src/main/java/com/baeldung/deletewrequestbody/model/Body.java
spring-web-modules/spring-mvc-basics-5/src/test/java/com/baeldung/deletewrequestbody/DeleteWithRequestBodyLiveTest.java

Draft: https://drafts.baeldung.com/wp-admin/post.php?post=216383&action=edit

BAEL-7003 - HTTP DELETE With Request Body

---

core-java-modules/core-java-networking-5/pom.xml
core-java-modules/core-java-networking-5/src/test/java/com/baeldung/ipaddresses/SubnetScannerUnitTest.java

This PR aims to add a test class SubnetScannerUnitTest to this module.

PR: BAEL-6608

---

persistence-modules/hibernate-jpa-2/src/main/java/com/baeldung/sfvsemf/SfVsEmfApplication.java
persistence-modules/hibernate-jpa-2/src/main/java/com/baeldung/sfvsemf/entity/Person.java
persistence-modules/hibernate-jpa-2/src/main/resources/META-INF/persistence.xml
persistence-modules/hibernate-jpa-2/src/main/resources/hibernate.cfg.xml
persistence-modules/hibernate-jpa-2/src/test/java/com/baeldung/sfvsemf/entitymanagerfactory/EntityManagerFactoryTest.java
persistence-modules/hibernate-jpa-2/src/test/java/com/baeldung/sfvsemf/sessionfactory/SessionFactoryTest.java

Add EntityManagerFactory and SessionFactory usage examples

BAEL-5984 Add EntityManagerFactory and SessionFactory usage examples

---

apache-poi-3/pom.xml
apache-poi-3/src/main/java/com/baeldung/poi/benchmark/WorkbookBenchmark.java
apache-poi-3/src/test/java/com/baeldung/poi/benchmark/SXSSFWorkbookFunctionTest.java

BAEL-8684: Comparison with HSSFWorkbook, XSSFWorkbook, and SXSSFWorkbook in Apache POI

BAEL-8684: Comparison with HSSFWorkbook, XSSFWorkbook, and SXSSFWorkbook in Apache POI

---

core-java-modules/core-java-networking-5/src/main/java/com/baeldung/urlipaddress/URLIPAddress.java

Update URLIPAddress.java - transfering validate ip address method to `urlipAddress` class

Finding IP Address of a URL in Java (biivincent4@gmail.com)

---

aws-modules/aws-s3/README.md
aws-modules/aws-s3/pom.xml
aws-modules/aws-s3/src/main/java/com/baeldung/s3/BucketNotEmptyException.java
aws-modules/aws-s3/src/main/java/com/baeldung/s3/S3BucketOperationService.java
aws-modules/aws-s3/src/main/java/com/baeldung/s3/S3ObjectOperationService.java
aws-modules/aws-s3/src/test/java/com/baeldung/s3/FileGeneratorUtil.java
aws-modules/aws-s3/src/test/java/com/baeldung/s3/S3BucketOperationServiceLiveTest.java
aws-modules/aws-s3/src/test/java/com/baeldung/s3/S3ObjectOperationServiceLiveTest.java
aws-modules/aws-s3/src/test/resources/init-s3-bucket.sh

[Improvement] Codebase for the article: **AWS S3 With Java**

codebase/aws-s3-with-java [BAEL-8724] [Improvement]

---

core-java-modules/core-java-collections-list-2/src/test/java/com/baeldung/linkedlist/LinkedListJUnitTest.java

Added a JUnit 5 test to _LinkedListJUnitTest.java_

Update LinkedListJUnitTest.java For "Insert an Element at a Specific Position in a Linked List"

---

spring-ai/src/main/java/com/baeldung/imagegen/Application.java
spring-ai/src/main/java/com/baeldung/imagegen/ImageGenerationRequest.java
spring-ai/src/main/java/com/baeldung/imagegen/ImageGenerator.java
spring-ai/src/main/resources/application-imagegen.properties
spring-ai/src/test/java/com/baeldung/imagegen/ImageGeneratorLiveTest.java

Codebase for the article: **AI Image Generation With OpenAI DALL·E 3 in Java**

codebase/ai-image-generation-with-openai-dall-e-3-in-java [BAEL-8850]

---

core-java-modules/core-java-arrays-operations-advanced-2/src/main/java/com/baeldung/maxdifference/MaxDifferenceBruteForce.java
core-java-modules/core-java-arrays-operations-advanced-2/src/main/java/com/baeldung/maxdifference/MaxDifferenceOptimized.java
core-java-modules/core-java-arrays-operations-advanced-2/src/main/java/com/baeldung/maxdifference/MaxDifferenceTreeSet.java
core-java-modules/core-java-arrays-operations-advanced-2/src/test/java/com/baeldung/maxdifference/MaxDifferenceBruteForceUnitTest.java
core-java-modules/core-java-arrays-operations-advanced-2/src/test/java/com/baeldung/maxdifference/MaxDifferenceOptimizedUnitTest.java
core-java-modules/core-java-arrays-operations-advanced-2/src/test/java/com/baeldung/maxdifference/MaxDifferenceTreeSetUnitTest.java

- Implements the solution using three approaches: brute force, optimized single-pass, and TreeSet.
- Provides unit tests for each of the added classes.

BAEL-8704 Code and Unit Tests for Max Difference in Array

---

core-java-modules/core-java-arrays-operations-advanced-2/src/main/java/com/baeldung/closesttozero/BruteForce.java
core-java-modules/core-java-arrays-operations-advanced-2/src/test/java/com/baeldung/closesttozero/BruteForceUnitTest.java

Modified 2 files:
- [BruteForce.java](https://github.com/Deepak-Vohra/tutorials/blob/master/core-java-modules/core-java-arrays-operations-advanced-2/src/main/java/com/baeldung/closesttozero/BruteForce.java)
- [BruteForceUnitTest](https://github.com/Deepak-Vohra/tutorials/blob/master/core-java-modules/core-java-arrays-operations-advanced-2/src/test/java/com/baeldung/closesttozero/BruteForceUnitTest.java)

PR For https://jira.baeldung.com/browse/BAEL-8331

---

spring-boot-modules/spring-boot-gradle/build.gradle

Update _//spring-boot-modules/spring-boot-gradle/build.gradle_ file.

PR For BAEL-8952 Update article "Spring Boot: Configuring a Main Class"

---

algorithms-modules/algorithms-miscellaneous-9/src/main/java/com/baeldung/algorithms/kthlargest/FindKthLargest.java
algorithms-modules/algorithms-miscellaneous-9/src/test/java/com/baeldung/algorithms/kthlargest/FindKthLargestUnitTest.java

Updated:
- [FindKthLargest](https://github.com/Deepak-Vohra/tutorials/blob/master/algorithms-modules/algorithms-miscellaneous-9/src/main/java/com/baeldung/algorithms/kthlargest/FindKthLargest.java)
- [FindKthLargestUnitTest](https://github.com/Deepak-Vohra/tutorials/blob/master/algorithms-modules/algorithms-miscellaneous-9/src/test/java/com/baeldung/algorithms/kthlargest/FindKthLargestUnitTest.java)

PR For BAEL-8808	Find the second largest element in an array without sorting

---

jackson-modules/jackson-exceptions/src/main/java/com/baeldung/mappingexception/Person.java
jackson-modules/jackson-exceptions/src/test/java/com/baeldung/mappingexception/JacksonMappingExceptionUnitTest.java

+ Create Person class
+ Create test cases to showcase how to reproduce and fix JsonMappingException

BAEL-8487: Fix the JsonMappingException: Can not deserialize instance of java.util.HashMap out of START_ARRAY token

---

spring-ai-2/src/main/java/com/baeldung/springai/chromadb/VectorStoreInitializer.java

PR fixes the poem line joining logic in `VectorStoreInitializer` class.

fix/poem-line-joining-logic [BAEL-8848]

---

pom.xml
spring-boot-rest-2/README.md
spring-boot-rest-2/pom.xml
spring-boot-rest-2/src/main/java/com/baeldung/SpringBootRestApplication.java
spring-boot-rest-2/src/main/java/com/baeldung/hateoasvsswagger/UserController.java
spring-boot-rest-2/src/main/java/com/baeldung/hateoasvsswagger/UserHateoasController.java
spring-boot-rest-2/src/main/java/com/baeldung/hateoasvsswagger/model/NewUser.java
spring-boot-rest-2/src/main/java/com/baeldung/hateoasvsswagger/model/User.java
spring-boot-rest-2/src/main/java/com/baeldung/hateoasvsswagger/repository/UserRepository.java
spring-boot-rest-2/src/test/java/com/baeldung/hateoasvsswagger/HateoasControllerIntegrationTest.java

difference between hateoas and swagger with tests

Difference between Swagger & HATEOAS

---

spring-batch/pom.xml
spring-batch/src/main/resources/spring.xml

Removed:
```
<jdbc:initialize-database data-source="dataSource">
<jdbc:script location="org/springframework/batch/core/schema-drop-h2.sql" />
<jdbc:script location="org/springframework/batch/core/schema-h2.sql" />
</jdbc:initialize-database>
```

Update spring.xml BAEL-8697 Auto create spring batch schema

---

core-java-modules/core-java-collections-set/pom.xml
core-java-modules/core-java-collections-set/src/test/java/com/baeldung/collection/Employee.java
core-java-modules/core-java-collections-set/src/test/java/com/baeldung/collection/WhenUsingHashSet.java

[BAEL-8986](https://jira.baeldung.com/browse/BAEL-8986)
A Guide to HashSet in Java

BAEL-8986 A Guide to HashSet in Java

---

spring-boot-modules/spring-boot-data-3/pom.xml
spring-boot-modules/spring-boot-data-3/src/main/java/com/baeldung/dynamicquery/DynamicQueryApplication.java
spring-boot-modules/spring-boot-data-3/src/main/java/com/baeldung/dynamicquery/model/School.java
spring-boot-modules/spring-boot-data-3/src/main/java/com/baeldung/dynamicquery/model/Student.java
spring-boot-modules/spring-boot-data-3/src/main/java/com/baeldung/dynamicquery/repository/SchoolRepository.java
spring-boot-modules/spring-boot-data-3/src/main/java/com/baeldung/dynamicquery/repository/StudentRepository.java
spring-boot-modules/spring-boot-data-3/src/main/java/com/baeldung/dynamicquery/spec/StudentSpecification.java
spring-boot-modules/spring-boot-data-3/src/main/resources/application-dynamicquery.properties
spring-boot-modules/spring-boot-data-3/src/test/java/com/baeldung/dynamicquery/DynamicQueryIntegrationTest.java

BAEL-8794: Dynamic Spring Data JPA Repository Query with Arbitrary AND Clauses

BAEL-8794: Dynamic Spring Data JPA Repository Query with Arbitrary AND Clauses

---

core-java-modules/core-java-collections-array-list/pom.xml
core-java-modules/core-java-collections-array-list/src/test/java/com/baeldung/collections/SequencedArrayListUnitTest.java

[BAEL-8985](https://jira.baeldung.com/browse/BAEL-8985)
Guide to the Java ArrayList

BAEL-8985 Guide to the Java ArrayList Create SequencedArrayListUnitTest.java

---

persistence-modules/liquibase/pom.xml
persistence-modules/liquibase/src/main/java/com/baeldung/liquibase/entity/Author.java
persistence-modules/liquibase/src/main/java/com/baeldung/liquibase/utility/LiquibaseDatatypes.java
persistence-modules/liquibase/src/main/resources/liquibase/changelog.xml

[BAEL-8226] changelog for liquibase

---

core-java-modules/core-java-date-operations-1/src/test/java/com/baeldung/date/DateDiffUnitTest.java
core-java-modules/core-java-date-operations-1/src/test/java/com/baeldung/jodatime/JodaTimeUnitTest.java

Hello.
I found a typo while looking through the document.
I think it should be "millis".
If I'm wrong, sorry.
And I fixed the spacing a little.

Typo correction

---

testing-modules/mocks-3/pom.xml
testing-modules/mocks-3/src/test/java/com/baeldung/mockjwt/jwtdecoder/junit/MockJwtDecoderJUnitTest.java
testing-modules/mocks-3/src/test/java/com/baeldung/mockjwt/jwtdecoder/junit/UserController.java

This pull request introduces a new tutorial on how to mock JWT (JSON Web Token) decoding in JUnit tests for Spring Security applications.

Fist commit: Mock JWT with JwtDecoder in JUnit Test

---

testing-modules/testing-assertions/pom.xml
testing-modules/testing-assertions/src/test/java/com/baeldung/junit/log/BusinessWorkerUnitTest.java

[Improvement] Codebase for the article: **Asserting Log Messages With JUnit**

codebase/asserting-log-messages-with-junit [BAEL-9045] [Improvement]

---

spring-boot-modules/spring-boot-gradle-2/README.md
spring-boot-modules/spring-boot-gradle/README.md

Moved article in readme only as per requirement.

JAVA-40689 Moved article in readme

---

core-java-modules/core-java-string-operations-12/src/test/java/com/baeldung/removeinsignificantzeros/RemoveInSignificantZeroTest.java

BAEL-8570 remove insignificant zeros from string represented by a number

BAEL-8570 remove insignificant zeros from string represented by a number

---

apache-kafka-3/src/test/java/com/baeldung/kafka/KafaProducerConsumerAckOpts.java
apache-kafka-3/src/test/java/com/baeldung/kafka/KafaProducerConsumerAckOptsLiveTest.java

Test cases for article : BAEL-7972 Kafka producer and consumer message acknowledgement options

BAEL-7972 Kafka producer and consumer message acknowledgement options

---

persistence-modules/spring-data-mongodb/pom.xml
persistence-modules/spring-data-mongodb/src/main/java/com/baeldung/Application.java
persistence-modules/spring-data-mongodb/src/main/java/com/baeldung/model/Author.java
persistence-modules/spring-data-mongodb/src/main/java/com/baeldung/repository/AuthorRepository.java
persistence-modules/spring-data-mongodb/src/test/java/com/baeldung/TestcontainersConfiguration.java
persistence-modules/spring-data-mongodb/src/test/java/com/baeldung/repository/AuthorCrudLiveTest.java

[Improvement] Codebase for the article: **Introduction to Spring Data MongoDB**

codebase/introduction-to-spring-data-mongodb [BAEL-8677] [Improvement]

---

core-java-modules/core-java-io-conversions/src/main/java/com/baeldung/csv/WriteCsvFileExample.java

bael-2499 - quick fix for github 18329

---

spring-ai-2/pom.xml
spring-ai-2/src/main/java/com/baeldung/springai/mcp/client/ChatbotConfiguration.java
spring-ai-2/src/main/java/com/baeldung/springai/mcp/client/ChatbotController.java
spring-ai-2/src/main/java/com/baeldung/springai/mcp/client/ChatbotService.java
spring-ai-2/src/main/java/com/baeldung/springai/mcp/client/ClientApplication.java
spring-ai-2/src/main/java/com/baeldung/springai/mcp/server/AuthorRepository.java
spring-ai-2/src/main/java/com/baeldung/springai/mcp/server/MCPServerConfiguration.java
spring-ai-2/src/main/java/com/baeldung/springai/mcp/server/ServerApplication.java
spring-ai-2/src/main/resources/application-mcp-client.properties
spring-ai-2/src/main/resources/application-mcp-server.properties
spring-ai-2/src/test/java/com/baeldung/springai/mcp/client/ChatbotServiceLiveTest.java

Codebase for the article: **Exploring Model Context Protocol (MCP) With Spring AI**

codebase/exploring-model-context-protocol-with-spring-ai [BAEL-9132]

---

persistence-modules/hibernate-jpa-3/pom.xml
persistence-modules/hibernate-jpa-3/src/main/java/com/baeldung/hibernate/dirtychecking/DirtyCheckingApplication.java
persistence-modules/hibernate-jpa-3/src/main/java/com/baeldung/hibernate/dirtychecking/entity/Product.java
persistence-modules/hibernate-jpa-3/src/main/java/com/baeldung/hibernate/dirtychecking/repository/ProductRepository.java
persistence-modules/hibernate-jpa-3/src/main/resources/application-dirtychecking.yml
persistence-modules/hibernate-jpa-3/src/test/java/com/baeldung/hibernate/dirtychecking/ProductRepositoryTest.java

Tests to showcase how dirty checking mechanism works

BAEL-8179 Dirty checking mechanism

---

spring-ai-2/src/main/java/com/baeldung/springai/deepseek/Application.java
spring-ai-2/src/main/java/com/baeldung/springai/deepseek/ChatRequest.java
spring-ai-2/src/main/java/com/baeldung/springai/deepseek/ChatResponse.java
spring-ai-2/src/main/java/com/baeldung/springai/deepseek/ChatbotConfiguration.java
spring-ai-2/src/main/java/com/baeldung/springai/deepseek/ChatbotController.java
spring-ai-2/src/main/java/com/baeldung/springai/deepseek/ChatbotService.java
spring-ai-2/src/main/java/com/baeldung/springai/deepseek/DeepSeekModelOutputConverter.java
spring-ai-2/src/main/java/com/baeldung/springai/deepseek/DeepSeekModelResponse.java
spring-ai-2/src/main/resources/application-deepseek.properties
spring-ai-2/src/test/java/com/baeldung/springai/deepseek/ChatbotServiceLiveTest.java
spring-ai-2/src/test/java/com/baeldung/springai/deepseek/DeepSeekModelOutputConverterUnitTest.java

Codebase for the article: **Building an AI Chatbot Using DeepSeek Models With Spring AI**

codebase/building-an-ai-chatbot-using-deepseek-models-with-spring-ai [BAEL-9195]

---

spring-ai-2/src/main/resources/application-mcp-client.properties

This PR updates the Claude model to the new 3.7 version.

update/spring-ai-2/mcp/claude-model [BAEL-9132]

---

spring-security-modules/pom.xml
spring-security-modules/spring-disable-security/README.md
spring-security-modules/spring-disable-security/pom.xml
spring-security-modules/spring-disable-security/spring-security-common-security-configuration/pom.xml
spring-security-modules/spring-disable-security/spring-security-common-security-configuration/src/main/java/com/baeldung/DisableSpringSecurityApplication.java
spring-security-modules/spring-disable-security/spring-security-common-security-configuration/src/main/java/com/baeldung/controller/MessageController.java
spring-security-modules/spring-disable-security/spring-security-common-security-configuration/src/main/java/com/baeldung/security/SecurityConfiguration.java
spring-security-modules/spring-disable-security/spring-security-common-security-configuration/src/test/java/com/baeldung/CommonSecurityConfigTest.java
spring-security-modules/spring-disable-security/spring-security-common-security-configuration/src/test/java/com/baeldung/DisableSpringSecurityApplicationTest.java
spring-security-modules/spring-disable-security/spring-security-noauth-config/pom.xml
spring-security-modules/spring-disable-security/spring-security-noauth-config/src/main/java/com/baeldung/DisableSpringSecurityWithConfig.java
spring-security-modules/spring-disable-security/spring-security-noauth-config/src/main/java/com/baeldung/controller/MessageController.java
spring-security-modules/spring-disable-security/spring-security-noauth-config/src/main/resources/application.properties
spring-security-modules/spring-disable-security/spring-security-noauth-config/src/test/java/com/baeldung/MessageControllerTest.java
spring-security-modules/spring-disable-security/spring-security-noauth-nodependencies/pom.xml
spring-security-modules/spring-disable-security/spring-security-noauth-nodependencies/src/main/java/com/baeldung/DisableSpringSecurityWithNoDependencies.java
spring-security-modules/spring-disable-security/spring-security-noauth-nodependencies/src/main/java/com/baeldung/controller/MessageController.java
spring-security-modules/spring-disable-security/spring-security-noauth-nodependencies/src/test/java/com/baeldung/DisableSpringSecurityWithNoDependenciesTest.java
spring-security-modules/spring-disable-security/spring-security-noauth-nodependencies/src/test/java/com/baeldung/MessageControllerTest.java
spring-security-modules/spring-disable-security/spring-security-noauth-profile/pom.xml
spring-security-modules/spring-disable-security/spring-security-noauth-profile/src/main/java/com/baeldung/SpringSecurityAnnotationParameterApplication.java
spring-security-modules/spring-disable-security/spring-security-noauth-profile/src/main/java/com/baeldung/controller/MessageController.java
spring-security-modules/spring-disable-security/spring-security-noauth-profile/src/main/java/com/baeldung/security/DevSecurityConfiguration.java
spring-security-modules/spring-disable-security/spring-security-noauth-profile/src/main/java/com/baeldung/security/SecurityConfiguration.java
spring-security-modules/spring-disable-security/spring-security-noauth-profile/src/test/java/com/baeldung/DevProfileSecurityConfigTest.java
spring-security-modules/spring-disable-security/spring-security-noauth-profile/src/test/java/com/baeldung/NonDevProfileSecurityConfigTest.java
spring-security-modules/spring-disable-security/spring-security-noauth-profile/src/test/java/com/baeldung/SpringSecurityAnnotationParameterApplicationTests.java

JIRA: https://jira.baeldung.com/browse/BAEL-9165

[BAEL-9165] by sgrverma23: Guide to disable Spring Security

---

spring-reactive-modules/spring-webflux/src/test/java/com/baeldung/spring/multipleheaders/MultipleHeadersTest.java
spring-reactive-modules/spring-webflux/src/test/java/com/baeldung/spring/multipleheaders/MultipleHeadersUnitTest.java

BAEL-7196 Multiple Headers on WebClient

---

mapstruct-2/src/main/java/com/baeldung/mapstruct/emptystringtonull/EmptyStringToNullCondition.java
mapstruct-2/src/main/java/com/baeldung/mapstruct/emptystringtonull/EmptyStringToNullConditionSourceProperty.java
mapstruct-2/src/main/java/com/baeldung/mapstruct/emptystringtonull/EmptyStringToNullExpression.java
mapstruct-2/src/main/java/com/baeldung/mapstruct/emptystringtonull/EmptyStringToNullGlobal.java
mapstruct-2/src/main/java/com/baeldung/mapstruct/emptystringtonull/Student.java
mapstruct-2/src/main/java/com/baeldung/mapstruct/emptystringtonull/Teacher.java
mapstruct-2/src/test/java/com/baeldung/mapstruct/emptystringtonull/MapEmptyStringToNullUnitTest.java

Adds code for the mapping empty string to null in mapstruct article.

BAEL-8307 Map empty string to null in MapStruct

---

core-java-modules/core-java-httpclient/src/test/java/com/baeldung/httpclient/HttpClientConnectionManagementUnitTest.java

Fix up package name in HttpClientConnectionManagementUnitTest

---

spring-boot-rest/src/main/java/com/baeldung/web/error/CustomExceptionObject.java
spring-boot-rest/src/main/java/com/baeldung/web/error/MyGlobalExceptionHandler.java
spring-boot-rest/src/main/java/com/baeldung/web/exception/CustomException5.java

- https://www.baeldung.com/exception-handling-for-rest-with-spring

BAEL-8372: Add missing code samples

---

logging-modules/logback/pom.xml
logging-modules/logback/src/test/java/com/baeldung/logback/ConditionalLoggingUnitTest.java
logging-modules/logback/src/test/resources/logback-conditional.xml

Hello Liam Williams,
Hope you are doing well!
I have completed the draft and created this PR:
Draft Link: https://drafts.baeldung.com/wp-admin/post.php?post=226703&action=edit 
Palani

BAEL-6478: Conditional Logging with Logback + tests

---

persistence-modules/hibernate-exceptions-2/src/main/java/com/baeldung/hibernate/columnduplicatedmapping/HibernateUtil.java
persistence-modules/hibernate-exceptions-2/src/main/java/com/baeldung/hibernate/columnduplicatedmapping/Person.java
persistence-modules/hibernate-exceptions-2/src/test/java/com/baeldung/hibernate/columnduplicatedmapping/ColumnDuplicatedMappingUnitTest.java

+ Create Person entity class
+ Create HibernateUtil class
+ Create test cases

BAEL-8213: Hibernate DuplicateMappingException: Column is Duplicated in Mapping For Entity

---

text-processing-libraries-modules/pdf/pom.xml
text-processing-libraries-modules/pdf/src/main/java/com/baeldung/pdf/PDFSampleMain.java

BAEL-9302 Set the Table Cell Width in PDF Using iText in Java

---

libraries-data/pom.xml
libraries-data/src/main/java/com/baeldung/guice/EmailNotifier.java
libraries-data/src/main/java/com/baeldung/guice/Logger.java
libraries-data/src/main/java/com/baeldung/guice/MyGuiceModule.java
libraries-data/src/main/java/com/baeldung/guice/Notifier.java
libraries-data/src/test/java/com/baeldung/guice/GuiceProviderTester.java

[BAEL-6028] Guice Provider class vs @Provides

---

json-modules/json/src/test/java/com/baeldung/jsonjava/JSONObjectIntegrationTest.java

…enCorrectValueReturned public

Update JSONObjectIntegrationTest.java to make givenJSON_whenParsed_th… method public

---

persistence-modules/hibernate-exceptions-2/src/main/java/com/baeldung/hibernate/annotationexception/HibernateUtil.java
persistence-modules/hibernate-exceptions-2/src/main/java/com/baeldung/hibernate/annotationexception/Student.java
persistence-modules/hibernate-exceptions-2/src/main/java/com/baeldung/hibernate/annotationexception/University.java
persistence-modules/hibernate-exceptions-2/src/test/java/com/baeldung/hibernate/annotationexception/ColumnNotAllowedOnManyToOneUnitTest.java

+ Create entity classes: Student and University
+ Create test cases to reproduce and fix the exception

BAEL-8210: Fixing Hibernate AnnotationException: Field is a @ManyToOne association and May Not Use @Column

---

json-modules/json-conversion/src/main/java/com/baeldung/jsonobjecttojsonarray/GsonConverter.java
json-modules/json-conversion/src/main/java/com/baeldung/jsonobjecttojsonarray/JacksonConverter.java
json-modules/json-conversion/src/main/java/com/baeldung/jsonobjecttojsonarray/OrgJsonConverter.java
json-modules/json-conversion/src/test/java/com/baeldung/jsonobjecttojsonarray/GsonConverterTest.java
json-modules/json-conversion/src/test/java/com/baeldung/jsonobjecttojsonarray/JacksonConverterTest.java
json-modules/json-conversion/src/test/java/com/baeldung/jsonobjecttojsonarray/OrgJsonConverterTest.java

[BAEL-9214](https://jira.baeldung.com/browse/BAEL-9214)

BAEL-9214: conversion from json object to json array by sgrverma23

---

libraries-7/pom.xml
libraries-7/src/main/java/com/baeldung/recordbuilderguide/Person.java
libraries-7/src/main/java/com/baeldung/recordbuilderguide/RecordBuilderDemo.java
libraries-7/src/test/java/com/baeldung/recordbuilderguide/RecordBuilderDemoUnitTest.java

- Adds a new package with use cases for RecordBuilder under libraries-7 module.
- Provides unit tests for each of the implemented use cases.

BAEL-9325 Implements Use Cases and Unit Tests for Guide to RecordBuilder

---

embabel-modules/embabel-quiz-generator/pom.xml
embabel-modules/embabel-quiz-generator/src/main/java/com/baeldung/quizzard/Application.java
embabel-modules/embabel-quiz-generator/src/main/java/com/baeldung/quizzard/Quiz.java
embabel-modules/embabel-quiz-generator/src/main/java/com/baeldung/quizzard/QuizGeneratorAgent.java
embabel-modules/embabel-quiz-generator/src/main/resources/application.properties
embabel-modules/embabel-quiz-generator/src/main/resources/application.yaml
embabel-modules/embabel-quiz-generator/src/main/resources/prompt-templates/quiz-generation.txt
embabel-modules/pom.xml
pom.xml

Codebase for the article: **Creating an AI Agent in Java Using Embabel Agent Framework**

codebase/introduction-to-embabel-agent-framework [BAEL-9346]

---

core-java-modules/core-java-concurrency-basic-4/src/test/java/com/baeldung/concurrent/busywaiting/BusyWaitingManualTest.java
core-java-modules/core-java-concurrency-basic-4/src/test/java/com/baeldung/concurrent/busywaiting/BusyWaitingUnitTest.java

BAEL-7699 Avoid busy-waiting examples

---

spring-boot-modules/spring-boot-mvc-5/src/main/java/com/baeldung/servletcontextlistener/CustomLifecycleLoggingListener.java
spring-boot-modules/spring-boot-mvc-5/src/main/java/com/baeldung/servletcontextlistener/CustomListenerConfiguration.java
spring-boot-modules/spring-boot-mvc-5/src/main/java/com/baeldung/servletcontextlistener/ServletContextListenerApplication.java

- implement two different ways of registering a custom ServletContextListener

[BAEL-9350] Register ServletContextListener in Spring Boot

---

core-java-modules/core-java-8-datetime-4/src/main/java/com/baeldung/instantandlong/InstantAndLong.java
core-java-modules/core-java-8-datetime-4/src/test/java/com/baeldung/instantandlong/InstantAndLongUnitTest.java

[BAEL-9349] Add main program and unit tests

Bael 9349 adding milliseconds to java date

---

persistence-modules/hibernate-exceptions-2/src/main/java/com/baeldung/hibernate/hibernateexception/Author.java
persistence-modules/hibernate-exceptions-2/src/main/java/com/baeldung/hibernate/hibernateexception/Book.java
persistence-modules/hibernate-exceptions-2/src/main/java/com/baeldung/hibernate/hibernateexception/HibernateUtil.java
persistence-modules/hibernate-exceptions-2/src/test/java/com/baeldung/hibernate/hibernateexception/HibernateExceptionUnitTest.java

+ Create Author and Book entities
+ Create test cases to reproduce and fix the exception

BAEL-5763: Fix the HibernateException: Illegal attempt to associate a collection with two open sessions

---

spring-boot-modules/flyway-multidb-springboot/src/main/resources/application.yml

This is the fix from the comment received on the published article. Here is the comment in [Jira](https://jira.baeldung.com/browse/BAEL-6525?focusedCommentId=369399&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-369399).

BAEL-6525: removing app.yml duplicate config

---

spring-ai-modules/pom.xml
spring-ai-modules/spring-ai-multiple-llms/pom.xml
spring-ai-modules/spring-ai-multiple-llms/src/main/java/com/baeldung/multillm/Application.java
spring-ai-modules/spring-ai-multiple-llms/src/main/java/com/baeldung/multillm/ChatbotConfiguration.java
spring-ai-modules/spring-ai-multiple-llms/src/main/java/com/baeldung/multillm/ChatbotController.java
spring-ai-modules/spring-ai-multiple-llms/src/main/java/com/baeldung/multillm/ChatbotService.java
spring-ai-modules/spring-ai-multiple-llms/src/main/resources/application.yaml
spring-ai-modules/spring-ai-multiple-llms/src/main/resources/logback.xml
spring-ai-modules/spring-ai-multiple-llms/src/test/java/com/baeldung/multillm/ChatbotServiceLiveTest.java

Codebase for the article: **Configuring Multiple LLMs in Spring AI**

codebase/configuring-multiple-llms-in-spring-ai [BAEL-9461]
