spring-rest/README.md, spring-rest/pom.xml, spring-rest/src/main/java/org/baeldung/web/controller/redirect/RedirectController.java, spring-rest/src/main/webapp/WEB-INF/api-servlet.xml, spring-rest/src/main/webapp/WEB-INF/spring-views.xml, spring-rest/src/main/webapp/WEB-INF/web.xml, spring-rest/src/test/java/org/baeldung/web/controller/redirect/RedirectControllerTest.java
=> A Guide To Spring Redirects

spring-data-mongodb/.classpath, spring-data-mongodb/.project, spring-data-mongodb/pom.xml, spring-data-mongodb/src/main/java/org/baeldung/config/MongoConfig.java, spring-data-mongodb/src/main/java/org/baeldung/model/User.java, spring-data-mongodb/src/main/java/org/baeldung/repository/UserRepository.java, spring-data-mongodb/src/main/webapp/WEB-INF/dispatcher-servlet.xml, spring-data-mongodb/src/main/webapp/WEB-INF/web.xml, spring-data-mongodb/src/test/java/org/baeldung/repository/UserRepositoryTest.java
=> Introduction to Spring Data Mongodb

core-java-8/src/main/java/com/demo/encoding/ApacheCommonsEncodeDecode.java, core-java-8/src/main/java/com/demo/encoding/Java8EncodeDecode.java
Hi Eugen,
Please review my code and let me know your comments.
Thanks.
Vrajesh
=> Java encode and decode test program

core-java-8/src/main/java/com/demo/encoding/Java8EncodeDecode.java
added method for basic encoding without padding
=> added method for basic encoding without padding

spring-security-rest-full/src/test/java/org/baeldung/Consts.java, spring-security-rest-full/src/test/java/org/baeldung/client/RestTemplateLiveTest.java, spring-security-rest-full/src/test/java/org/baeldung/common/web/AbstractLiveTest.java
- Introduce consistent test names
- Fix typo
=> [RestTemplate] Use constant for an application port value

spring-security-rest/pom.xml, spring-security-rest/src/main/java/org/baeldung/spring/SwaggerConfig.java, spring-security-rest/src/main/java/org/baeldung/spring/WebConfig.java
You should use folloving urls to see results:
JSON object: http://localhost:8082/api/v2/api-docs
UI: http://localhost:8082/api/swagger-ui.html
=> Fixed code for Setting Up Swagger 2 with a Spring REST API article

spring-thymeleaf/.classpath, spring-thymeleaf/.project, spring-thymeleaf/README.md, spring-thymeleaf/pom.xml, spring-thymeleaf/src/main/java/org/baeldung/thymeleaf/controller/HomeController.java, spring-thymeleaf/src/main/java/org/baeldung/thymeleaf/controller/StudentController.java, spring-thymeleaf/src/main/java/org/baeldung/thymeleaf/formatter/NameFormatter.java, spring-thymeleaf/src/main/java/org/baeldung/thymeleaf/model/Student.java, spring-thymeleaf/src/main/resources/logback.xml, spring-thymeleaf/src/main/resources/messages_en_US.properties, spring-thymeleaf/src/main/webapp/WEB-INF/appServlet/servlet-context.xml, spring-thymeleaf/src/main/webapp/WEB-INF/root-context.xml, spring-thymeleaf/src/main/webapp/WEB-INF/views/addStudent.html, spring-thymeleaf/src/main/webapp/WEB-INF/views/home.html, spring-thymeleaf/src/main/webapp/WEB-INF/views/listStudents.html, spring-thymeleaf/src/main/webapp/WEB-INF/web.xml
Initial version of spring-thymeleaf project for review
=> Initial version of spring-thymeleaf project for review

raml/introduction/0.8/api.raml, raml/introduction/0.8/error-example.json, raml/introduction/0.8/error.json, raml/introduction/0.8/foo-example.json, raml/introduction/0.8/foo.json, raml/introduction/0.8/foos-example.json, raml/introduction/0.8/foos.json, raml/introduction/1.0/api.raml, raml/introduction/1.0/examples/Error.json, raml/introduction/1.0/examples/Foo.json, raml/introduction/1.0/examples/Foos.json, raml/introduction/1.0/types/Error.raml, raml/introduction/1.0/types/Foo.raml, raml/resource-types-and-traits/api-before-resource-types-and-traits.raml, raml/resource-types-and-traits/api.raml, raml/resource-types-and-traits/examples/Bar.json, raml/resource-types-and-traits/examples/Bars.json, raml/resource-types-and-traits/examples/Error.json, raml/resource-types-and-traits/examples/Foo.json, raml/resource-types-and-traits/examples/Foos.json, raml/resource-types-and-traits/types/Bar.raml, raml/resource-types-and-traits/types/Error.raml, raml/resource-types-and-traits/types/Foo.raml
Hi Eugen, I have committed files for the first two RAML articles into the raml directory. Files for the first article are in the introduction folder, and for the second in the resource-types-and-traits folder.
-Kevin
=> Added RAML files for first two articles

mockito-mocks-spring-beans/.gitignore, mockito-mocks-spring-beans/pom.xml, mockito-mocks-spring-beans/src/main/java/org/baeldung/MocksApplication.java, mockito-mocks-spring-beans/src/main/java/org/baeldung/NameService.java, mockito-mocks-spring-beans/src/main/java/org/baeldung/UserService.java, mockito-mocks-spring-beans/src/test/java/org/baeldung/NameServiceTestConfiguration.java, mockito-mocks-spring-beans/src/test/java/org/baeldung/UserServiceTest.java
Added code for article on Injecting Mockito Mocks into Spring Beans
=> Initial commit, added code for article, "Injecting Mockito Mocks into Spring Beans"

mockito-mocks-spring-beans/pom.xml, mockito-mocks-spring-beans/src/main/java/com/baeldung/MocksApplication.java, mockito-mocks-spring-beans/src/main/java/com/baeldung/NameService.java, mockito-mocks-spring-beans/src/main/java/com/baeldung/UserService.java, mockito-mocks-spring-beans/src/test/java/com/baeldung/NameServiceTestConfiguration.java, mockito-mocks-spring-beans/src/test/java/com/baeldung/UserServiceTest.java
Clean up and make mock injection example clearer
=> Inject mocks cleanup

core-java-8/src/main/java/com/baeldung/doublecolumn/Computer.java, core-java-8/src/main/java/com/baeldung/doublecolumn/ComputerUtils.java, core-java-8/src/main/java/com/baeldung/doublecolumn/function/ComputerPredicate.java, core-java-8/src/main/java/com/baeldung/doublecolumn/function/TriFunction.java, core-java-8/src/test/java/com/baeldung/doublecolumn/TestComputerUtils.java
Examples of Method Reference and Constructor Reference.
=> Double column operator 

core-java-8/src/main/java/com/baeldung/doublecolon/Computer.java, core-java-8/src/main/java/com/baeldung/doublecolon/ComputerUtils.java, core-java-8/src/main/java/com/baeldung/doublecolon/MacbookPro.java, core-java-8/src/main/java/com/baeldung/doublecolon/function/ComputerPredicate.java, core-java-8/src/main/java/com/baeldung/doublecolon/function/TriFunction.java, core-java-8/src/test/java/com/baeldung/doublecolon/TestComputerUtils.java
Package renamed to doublecolon;
Some method reference examples added.
=> package renamed

querydsl/pom.xml, querydsl/src/main/java/org/baeldung/dao/PersonDao.java, querydsl/src/main/java/org/baeldung/dao/PersonDaoImpl.java, querydsl/src/main/java/org/baeldung/entity/Person.java, querydsl/src/main/resources/META-INF/persistence.xml, querydsl/src/main/resources/log4j.xml, querydsl/src/test/java/org/baeldung/dao/PersonDaoTest.java, querydsl/src/test/resources/db.properties, querydsl/src/test/resources/test-context.xml, querydsl/src/test/resources/test-db.xml
Project for article Intro to QueryDSL
=> Source code for Intro to QueryDSL article.

spring-mvc-java/pom.xml, spring-mvc-java/src/main/java/org/baeldung/model/Employee.java, spring-mvc-java/src/main/java/org/baeldung/spring/web/config/ContentManagementWebConfig.java, spring-mvc-java/src/main/java/org/baeldung/web/controller/EmployeeController.java, spring-mvc-java/src/main/webapp/WEB-INF/view/employeeHome.jsp, spring-mvc-java/src/main/webapp/WEB-INF/view/employeeView.jsp, spring-mvc-xml/pom.xml, spring-mvc-xml/src/main/java/com/baeldung/spring/controller/EmployeeController.java, spring-mvc-xml/src/main/java/com/baeldung/spring/form/Employee.java, spring-mvc-xml/src/main/resources/contentManagementWebMvcConfig.xml
Code files for two projects - spring-mvc-java and spring-mvc-xml
=> Content Negotiation Strategy

spring-mvc-java/src/main/java/org/baeldung/spring/web/config/ContentManagementWebConfig.java, spring-mvc-java/src/main/java/org/baeldung/web/controller/EmployeeController.java, spring-mvc-xml/src/main/java/com/baeldung/spring/controller/EmployeeController.java, spring-mvc-xml/src/main/resources/contentManagementWebMvcConfig.xml
=> Content Negotiation Strategy - Removed HTML media type.

jackson/pom.xml, jackson/src/test/java/com/baeldung/jackson/xml/TestXMLSerializeDeserialize.java, jackson/src/test/java/com/baeldung/xml/TestClass.java, jackson/src/test/resources/simple_bean.xml
#1.added simple_bean.xml to resources
#2.shifted xml package into jackson
#3.changed name of TestClass
#4.added maven dependency section to article
#5.corrected article formatting
=> New recommendations integrated

spring-autowire/pom.xml, spring-autowire/src/main/java/com/baeldung/autowire/sample/App.java, spring-autowire/src/main/java/com/baeldung/autowire/sample/AppConfig.java, spring-autowire/src/main/java/com/baeldung/autowire/sample/Bar.java, spring-autowire/src/main/java/com/baeldung/autowire/sample/BarFormatter.java, spring-autowire/src/main/java/com/baeldung/autowire/sample/Foo.java, spring-autowire/src/main/java/com/baeldung/autowire/sample/FooDAO.java, spring-autowire/src/main/java/com/baeldung/autowire/sample/FooFormatter.java, spring-autowire/src/main/java/com/baeldung/autowire/sample/FooService.java, spring-autowire/src/main/java/com/baeldung/autowire/sample/Formatter.java, spring-autowire/src/main/java/com/baeldung/autowire/sample/FormatterType.java, spring-autowire/src/test/java/com/baeldung/autowire/sample/FooServiceTest.java
Created basic maven java project showing spring autowiring concepts.
=> Guide to Spring @Autowired

core-java-8/src/main/java/com/baeldung/java_8_features/Address.java, core-java-8/src/main/java/com/baeldung/java_8_features/CustomException.java, core-java-8/src/main/java/com/baeldung/java_8_features/Detail.java, core-java-8/src/main/java/com/baeldung/java_8_features/OptionalAddress.java, core-java-8/src/main/java/com/baeldung/java_8_features/OptionalUser.java, core-java-8/src/main/java/com/baeldung/java_8_features/User.java, core-java-8/src/main/java/com/baeldung/java_8_features/Vehicle.java, core-java-8/src/main/java/com/baeldung/java_8_features/VehicleImpl.java, core-java-8/src/test/java/com/baeldung/java8/Java8Features.java
=> Code for the article "Java 8’s Features"

core-java-8/src/main/java/com/baeldung/enums/Pizza.java, core-java-8/src/main/java/com/baeldung/enums/PizzaDeliveryStrategy.java, core-java-8/src/main/java/com/baeldung/enums/PizzaDeliverySystemConfiguration.java, core-java-8/src/test/java/com/baeldung/enums/PizzaTest.java, core-java/pom.xml, core-java/src/main/java/com/baeldung/enums/Pizza.java, core-java/src/main/java/com/baeldung/enums/PizzaDeliveryStrategy.java, core-java/src/main/java/com/baeldung/enums/PizzaDeliverySystemConfiguration.java, core-java/src/test/java/org/baeldung/java/enums/PizzaTest.java
Enum example with java 7 and java 8- basics, EnumSet, EnumMap and Design Patterns
=> Core java enum examples

pom.xml, xml/pom.xml, xml/src/main/java/com/baeldung/xml/DefaultParser.java, xml/src/test/java/com/baeldung/xml/DefaultParserTest.java, xml/src/test/resources/example.xml, xml/src/test/resources/example_namespace.xml
New pull request for Introduction to XPath
=> Introduction to XPath

core-java-8/src/main/java/com/baeldung/streamApi/Product.java, core-java-8/src/test/java/com/baeldung/java8/Java8StreamApiTest.java
=> Code for the article "Java 8 Stream API Tutorial"

assertj-introduction/pom.xml, assertj-introduction/src/main/java/com/baeldung/assertj/domain/Dog.java, assertj-introduction/src/main/java/com/baeldung/assertj/domain/Person.java, assertj-introduction/src/test/java/com/baeldung/assertj/AssertJDemoTest.java, pom.xml
=> Assertj introduction

querydsl/pom.xml, querydsl/src/main/java/org/baeldung/dao/PersonDaoImpl.java, querydsl/src/main/java/org/baeldung/querydsl/intro/entities/BlogPost.java, querydsl/src/main/java/org/baeldung/querydsl/intro/entities/User.java, querydsl/src/main/resources/META-INF/persistence.xml, querydsl/src/main/resources/logback.xml, querydsl/src/test/java/org/baeldung/querydsl/intro/QueryDSLTest.java
Code samples for the article http://inprogress.baeldung.com/intro-to-querydsl/
I didn't put my code in the existing `querydsl` module, because that module uses Spring and a rather old and incompatible version of QueryDSL. My project `querydsl-intro` is much more simple, does not have a lot of dependencies and does not use Spring, so I put it into a separate module. But I can try to merge it with `querydsl`, if needed.
=> Added code samples for the article Intro to QueryDSL

assertj/src/test/java/com/baeldung/assertj/introduction/AssertJGuavaTest.java
=> Fix MMap examples

spring-rest/pom.xml
=> Changed Kryo version

pom.xml, redis/pom.xml, redis/src/test/java/com/baeldung/JedisTest.java
We have created this module to work with Redis Java libraries
Jedis tested so far
=> New redis module

pom.xml
Removed spring-4.3 leftover from the main pom.xml.
=> Removed spring-4.3 from the main module

spring-boot/pom.xml, spring-boot/src/main/java/org/baeldung/client/Details.java, spring-boot/src/main/java/org/baeldung/client/DetailsServiceClient.java, spring-boot/src/test/java/org/baeldung/SpringBootMailTest.java, spring-boot/src/test/java/org/baeldung/client/DetailsServiceClientTest.java, spring-boot/src/test/resources/application.properties
Added examples for the article about @RestClientTest.
Also changed the port in mail tests from 25 to 8025, as opening sockets on ports below 1024 on many systems requires admin privileges, which affects the build (the tests did not run on my machine without sudo).
=> Added examples for the @RestClientTest article, fixed mail port

spring-mvc-java/src/main/java/com/baeldung/circulardependency/CircularDependencyA, spring-mvc-java/src/main/java/com/baeldung/circulardependency/CircularDependencyB, spring-mvc-java/src/test/java/com/baeldung/circulardependency/CircularDependencyTest, spring-mvc-java/src/test/java/com/baeldung/circulardependency/TestConfig
Files for the article "Circular dependencies in Spring"
=> BAEL-83: Circular dependencies in Spring

spring-mvc-velocity/pom.xml, spring-mvc-velocity/src/main/java/com/baeldung/mvc/velocity/controller/MainController.java, spring-mvc-velocity/src/main/java/com/baeldung/mvc/velocity/domain/Tutorial.java, spring-mvc-velocity/src/main/java/com/baeldung/mvc/velocity/service/ITutorialsService.java, spring-mvc-velocity/src/main/java/com/baeldung/mvc/velocity/service/TutorialsService.java, spring-mvc-velocity/src/test/java/com/baeldung/mvc/velocity/test/DataContentControllerTest.java, spring-mvc-velocity/src/test/java/com/baeldung/mvc/velocity/test/NavigationControllerTest.java, spring-mvc-velocity/src/test/resources/mvc-servlet.xml
=> Test content

spring-security-rest-full/src/main/java/org/baeldung/spring/SecurityWithoutCsrfConfig.java, spring-security-rest-full/src/main/java/org/baeldung/spring/WebConfig.java, spring-security-rest-full/src/main/java/org/baeldung/web/controller/BankController.java, spring-security-rest-full/src/main/java/org/baeldung/web/controller/FooController.java, spring-security-rest-full/src/main/java/org/baeldung/web/controller/HomeController.java, spring-security-rest-full/src/main/java/org/baeldung/web/controller/RootController.java, spring-security-rest-full/src/main/java/org/baeldung/web/controller/UserController.java, spring-security-rest-full/src/test/java/org/baeldung/security/csrf/CsrfAbstractIntegrationTest.java, spring-security-rest-full/src/test/java/org/baeldung/security/csrf/CsrfDisabledIntegrationTest.java
PermitAll, hasRole, hasAnyRole etc.
I modified classes regards to Security
=> Expression-Based Access Control

spring-all/pom.xml, spring-all/src/main/java/org/baeldung/akka/AppConfiguration.java, spring-all/src/main/java/org/baeldung/akka/GreetingActor.java, spring-all/src/main/java/org/baeldung/akka/GreetingService.java, spring-all/src/main/java/org/baeldung/akka/SpringActorProducer.java, spring-all/src/main/java/org/baeldung/akka/SpringExtension.java, spring-all/src/test/java/org/baeldung/akka/SpringAkkaTest.java
Added source code for the article "An Intro to Spring with Akka" in the spring-all project.
Removed duplicate spring-orm dependency from the spring-all project.
=> Source code for the article "An Intro to Spring with Akka"

spring-mvc-java/src/main/java/com/baeldung/web/controller/CompanyController.java, spring-mvc-java/src/main/java/com/baeldung/web/controller/advice/JsonpControllerAdvice.java, spring-mvc-java/src/main/webapp/WEB-INF/company.html, spring-rest/src/main/java/org/baeldung/web/controller/CompanyController.java, spring-rest/src/main/java/org/baeldung/web/controller/advice/JsonpControllerAdvice.java, spring-rest/src/main/java/org/baeldung/web/dto/Company.java, spring-rest/src/main/webapp/WEB-INF/company.html
Article 'Spring JSONP with Jackson'
=> Spring JSONP with Jackson

spring-all/src/main/java/org/baeldung/controller/config/StudentControllerConfig.java, spring-all/src/main/java/org/baeldung/controller/config/WebConfig.java, spring-all/src/test/java/org/baeldung/controller/ControllerAnnotationTest.java
=> adding config files

spring-boot/pom.xml, spring-boot/src/main/java/org/baeldung/session/exception/Application.java, spring-boot/src/main/java/org/baeldung/session/exception/repository/FooRepository.java, spring-boot/src/main/java/org/baeldung/session/exception/repository/FooRepositoryImpl.java, spring-boot/src/test/java/org/baeldung/boot/ApplicationTests.java, spring-boot/src/test/java/org/baeldung/boot/repository/HibernateSessionTest.java, spring-boot/src/test/java/org/baeldung/boot/repository/NoHibernateSessionTest.java, spring-boot/src/test/resources/exception-hibernate.properties, spring-boot/src/test/resources/exception.properties
This is the source code for the article at <http://inprogress.baeldung.com/no-hibernate-session-bound-to-thread/>
=> Source code for 'No Hibernate Session bound to thread'

spring-cucumber/src/main/java/com/baeldung/SpringDemoApplication.java, spring-cucumber/src/test/java/com/baeldung/SpringIntegrationTest.java
Added the @Autowiring for RestTemplate.
=> Autowiring the RestTemplate

spring-cucumber/src/test/java/com/baeldung/SpringIntegrationTest.java
=> Removed unused coed

core-java-8/src/main/java/com/baeldung/threadpool/CountingTask.java, core-java-8/src/main/java/com/baeldung/threadpool/TreeNode.java, core-java-8/src/test/java/com/baeldung/threadpool/CoreThreadPoolTest.java
Examples for the article "Introduction to Thread Pool".
=> Core threadpool implementation examples

core-java-8/src/main/java/com/baeldung/threadpool/ExitingExecutorServiceExample.java, core-java-8/src/test/java/com/baeldung/threadpool/GuavaThreadPoolTest.java
Added Guava thread pool implementation examples for the article "Introduction to Thread Pool".
=> Added Guava thread pool examples

core-java-8/src/main/java/com/baeldung/threadpool/TreeNode.java
Fixed the TreeNode constructor according to the article review.
=> Optimized the TreeNode constructor

gson/src/main/java/org/baeldung/gson/entities/ActorGson.java, gson/src/main/java/org/baeldung/gson/entities/Movie.java, gson/src/main/java/org/baeldung/gson/entities/MovieWithNullValue.java, gson/src/main/java/org/baeldung/gson/serialization/ActorGsonDeserializer.java, gson/src/main/java/org/baeldung/gson/serialization/ActorGsonSerializer.java, gson/src/test/java/org/baeldung/gson/deserialization/GsonDeserializeTest.java, gson/src/test/java/org/baeldung/gson/serialization/GsonSerializeTest.java, jackson/src/main/java/org/baeldung/jackson/entities/ActorJackson.java, jackson/src/main/java/org/baeldung/jackson/entities/Movie.java, jackson/src/main/java/org/baeldung/jackson/entities/MovieWithNullValue.java, jackson/src/main/java/org/baeldung/jackson/serialization/ActorJacksonSerializer.java, jackson/src/test/java/org/baeldung/jackson/deserialization/JacksonDeserializeTest.java, jackson/src/test/java/org/baeldung/jackson/serialization/JacksonSerializeTest.java
Serialize/deserialize code and tests for jackson/gson
=> Added jackson/gson serialize/deserialize updates

core-java-8/src/test/java/com/baeldung/completablefuture/CompletableFutureTest.java
Test for the article "Guide to CompletableFuture"
=> Added test for the Guide to CompletableFuture

core-java-8/src/test/java/com/baeldung/completablefuture/CompletableFutureTest.java
Added an example with canceling the CompletableFuture.
=> Added cancellation example for CompletableFuture

spring-mvc-java/src/test/java/com/baeldung/web/controller/EmployeeTest.java
This is the example used for the article: "WebAppConfiguration in Spring Tests"
=> An example of a test using a WebAppConfiguration annotation

spring-mvc-java/src/test/java/com/baeldung/web/controller/EmployeeTest.java
An example of a test using a WebAppConfiguration annotation
=> Webapplicationcontext example

sockets/pom.xml, sockets/src/main/java/com/baeldung/socket/EchoClient.java, sockets/src/main/java/com/baeldung/socket/EchoMultiServer.java, sockets/src/main/java/com/baeldung/socket/EchoServer.java, sockets/src/main/java/com/baeldung/socket/GreetClient.java, sockets/src/main/java/com/baeldung/socket/GreetServer.java, sockets/src/test/java/com/baeldung/socket/EchoMultiTest.java, sockets/src/test/java/com/baeldung/socket/EchoTest.java, sockets/src/test/java/com/baeldung/socket/GreetServerTest.java
I have not added the module to parent pom because from my perspective, the tests cannot be run automatically as other projects. They need one to start atleast a server which is available in the project to be able to run the tests on them.
This is clearly explained in the article.
If there is a better way, let me know.
=> added project code for sockets

spring-mvc-java/src/test/java/com/baeldung/web/controller/EmployeeTestWithoutMockMvc.java
An example of a test that uses WebAppConfiguration without the need of a MockMvc object
=> Example of article "WebAppConfiguration in Spring Tests"

core-java-8/src/test/java/com/baeldung/functionalinterface/FunctionalInterfaceTest.java, core-java-8/src/test/java/com/baeldung/functionalinterface/ShortToByteFunction.java
Source code for the article "Guide to Java 8 Functional Interfaces".
=> Source code for the article Guide to Java 8 Functional Interfaces

eclipse/src/main/java/org/baeldung/equalshashcode/entities/ComplexClass.java, eclipse/src/main/java/org/baeldung/equalshashcode/entities/PrimitiveClass.java, eclipse/src/main/java/org/baeldung/equalshashcode/entities/Rectangle.java, eclipse/src/main/java/org/baeldung/equalshashcode/entities/Shape.java, eclipse/src/main/java/org/baeldung/equalshashcode/entities/Square.java, eclipse/src/test/java/org/baeldung/equalshashcode/entities/ComplexClassTest.java, eclipse/src/test/java/org/baeldung/equalshashcode/entities/PrimitiveClassTest.java, eclipse/src/test/java/org/baeldung/equalshashcode/entities/SquareClassTest.java
code/tests for equals()/hashcode() article
=> Added equals()/hashcode()

flyway-migration/.gitignore, flyway-migration/db/migration/V1_0__create_employee_schema.sql, flyway-migration/myFlywayConfig.properties, flyway-migration/pom.xml
This pull request contains sample maven project contains configurations required to manage database migration using Flyway.
Related Jira ID: BAEL-60
=> Database migration using flyway 

java-cassandra/pom.xml, java-cassandra/src/main/java/com/baeldung/cassandra/java/client/CassandraClient.java, java-cassandra/src/main/java/com/baeldung/cassandra/java/client/CassandraConnector.java, java-cassandra/src/main/java/com/baeldung/cassandra/java/client/domain/Book.java, java-cassandra/src/main/java/com/baeldung/cassandra/java/client/repository/BookRepository.java, java-cassandra/src/main/java/com/baeldung/cassandra/java/client/repository/KeyspaceRepository.java, java-cassandra/src/test/java/com/baeldung/cassandra/java/client/repository/BookRepositoryIntegrationTest.java, java-cassandra/src/test/java/com/baeldung/cassandra/java/client/repository/KeyspaceRepositoryIntegrationTest.java, pom.xml
Working example and test code for BAEL-54: A Guide to Cassandra with Java
=> java cassandra tutorial

spring-mvc-web-vs-initializer/.gitignore, spring-mvc-web-vs-initializer/pom.xml, spring-mvc-web-vs-initializer/src/main/java/org/baeldung/config/AppInitializer.java, spring-mvc-web-vs-initializer/src/main/java/org/baeldung/config/MvcConfig.java, spring-mvc-web-vs-initializer/src/main/java/org/baeldung/controller/java/JavaController.java, spring-mvc-web-vs-initializer/src/main/java/org/baeldung/controller/xml/XmlController.java, spring-mvc-web-vs-initializer/src/main/resources/mvc-configuration.xml, spring-mvc-web-vs-initializer/src/main/webapp/WEB-INF/view/from-java.jsp, spring-mvc-web-vs-initializer/src/main/webapp/WEB-INF/view/from-xml.jsp, spring-mvc-web-vs-initializer/src/main/webapp/WEB-INF/web.xml, spring-mvc-web-vs-initializer/src/test/java/org/baeldung/controller/JavaServletTest.java, spring-mvc-web-vs-initializer/src/test/java/org/baeldung/controller/XmlServletTest.java
I had to create a new project because spring-all already had a lot of configuration and avoiding conflicts was going to take too much time.
Besides the reader will have a cleaner and much simpler project to understand.
=> Created project "spring-mvc-web-vs-initializer" for the web.xml vs Initializer article.

spring-data-rest/pom.xml, spring-data-rest/src/main/java/com/baeldung/SpringDataRestApplication.java, spring-data-rest/src/main/java/com/baeldung/config/ValidatorEventRegister.java, spring-data-rest/src/main/java/com/baeldung/exception/handlers/RestResponseEntityExceptionHandler.java, spring-data-rest/src/main/java/com/baeldung/models/WebsiteUser.java, spring-data-rest/src/main/java/com/baeldung/repositories/UserRepository.java, spring-data-rest/src/main/java/com/baeldung/validators/WebsiteUserValidator.java, spring-data-rest/src/main/test/com/baeldung/validator/SpringDataRestValidatorTest.java
Added source code for Spring Data Rest Validators article
=> Spring Data Rest Validators introduction

flyway-migration/db/migration/V2_0__create_department_schema.sql, flyway-migration/pom.xml
Added a second migration to demonstrate database migration using Flyway.
Related Jira: BAEL-60
=> Add a second migration to demonstrate Flyway

selenium-junit-testng/pom.xml, selenium-junit-testng/src/main/java/com/baeldung/selenium/SeleniumExample.java, selenium-junit-testng/src/test/java/com/baeldung/selenium/junit/TestSeleniumWithJUnit.java, selenium-junit-testng/src/test/java/com/baeldung/selenium/testng/TestSeleniumWithTestNG.java, selenium-junit-testng/test/com/baeldun/selenium/testng/TestSeleniumWithTestNG.java, selenium-junit-testng/test/com/baeldung/selenium/junit/TestSeleniumWithJUnit.java
Pull request for BAEL 298 | Intro to Selenium with JUnit / TestNg
=> BAEL 298 | Intro to Selenium with JUnit / TestNg

pom.xml, spring-mvc-tiles/pom.xml, spring-mvc-tiles/src/main/java/com/baeldung/tiles/springmvc/ApplicationConfiguration.java, spring-mvc-tiles/src/main/java/com/baeldung/tiles/springmvc/ApplicationController.java, spring-mvc-tiles/src/main/java/com/baeldung/tiles/springmvc/ApplicationInitializer.java, spring-mvc-tiles/src/main/webapp/WEB-INF/views/pages/apachetiles.jsp, spring-mvc-tiles/src/main/webapp/WEB-INF/views/pages/home.jsp, spring-mvc-tiles/src/main/webapp/WEB-INF/views/pages/springmvc.jsp, spring-mvc-tiles/src/main/webapp/WEB-INF/views/tiles/layouts/defaultLayout.jsp, spring-mvc-tiles/src/main/webapp/WEB-INF/views/tiles/templates/defaultFooter.jsp, spring-mvc-tiles/src/main/webapp/WEB-INF/views/tiles/templates/defaultHeader.jsp, spring-mvc-tiles/src/main/webapp/WEB-INF/views/tiles/templates/defaultMenu.jsp, spring-mvc-tiles/src/main/webapp/WEB-INF/views/tiles/tiles.xml, spring-mvc-tiles/src/main/webapp/static/css/app.css
Hi Eugen,
Spring integration with Tiles code
Thank you,
Kiran.
=> Spring integration with Tiles

spring-jms/pom.xml, spring-jms/src/com/baeldung/spring/jms/Employee.java, spring-jms/src/com/baeldung/spring/jms/SampleJMSExample.java, spring-jms/src/com/baeldung/spring/jms/SampleJmsMessageSender.java, spring-jms/src/com/baeldung/spring/jms/SampleListener.java, spring-jms/src/com/baeldung/spring/jms/SampleMessageConverter.java, spring-jms/src/main/resources/applicationContext.xml
New Spring JMS library is getting added, hence new library. Please do add.
=> spring-jms

core-java/src/test/java/org/baeldung/java/sorting/Employee.java, core-java/src/test/java/org/baeldung/java/sorting/JavaSorting.java
new fork due to conflicts in PR-603.
=> Java sorting. Adding required files. This is commit for starting from

core-java-8/src/test/java/com/baeldung/util/CurrentDateTimeTest.java
=> Updating JUnits: Mocking current time using custom Clock

spring-jms/src/main/resources/EmbeddedActiveMQ.xml
Set the property useShutdownHook to false
=> Added useShutdownHook="false"

core-java-8/src/test/java/com/baeldung/file/FileOperationsTest.java
@slavisa-baeldung Please review and merge.
=> Added stream close snippet

pom.xml, spring-security-custom-voter/pom.xml, spring-security-custom-voter/src/main/java/org/baeldung/Application.java, spring-security-custom-voter/src/main/java/org/baeldung/security/MinuteBasedVoter.java, spring-security-custom-voter/src/main/java/org/baeldung/security/WebSecurityConfig.java, spring-security-custom-voter/src/main/java/org/baeldung/security/XmlSecurityConfig.java, spring-security-custom-voter/src/main/java/org/baeldung/web/MvcConfig.java, spring-security-custom-voter/src/main/resources/spring-security.xml, spring-security-custom-voter/src/main/resources/templates/private.html, spring-security-custom-voter/src/main/webapp/WEB-INF/web.xml, spring-security-custom-voter/src/test/java/org/baeldung/web/LiveTest.java
Vote method implementation changed.
=> [BAEL-123] Vote method

core-java/src/main/java/com/baeldung/hextToAscii/HexToAscii.java
=> Added HexToAscii example.

spring-cloud/pom.xml, spring-cloud/spring-cloud-ribbon-client/pom.xml, spring-cloud/spring-cloud-ribbon-client/src/main/java/com/baeldung/spring/cloud/ribbon/client/RibbonConfiguration.java, spring-cloud/spring-cloud-ribbon-client/src/main/java/com/baeldung/spring/cloud/ribbon/client/ServerLocationApp.java, spring-cloud/spring-cloud-ribbon-client/src/main/resources/application.yml, spring-cloud/spring-cloud-ribbon-client/src/test/java/com/baeldung/spring/cloud/ribbon/client/ServerLocationAppTests.java, spring-cloud/spring-cloud-ribbon-client/src/test/java/com/baeldung/spring/cloud/ribbon/client/TestConfig.java
Added new project module "spring-cloud-ribbon-client" under the spring-cloud project for the article reference number BAEL-396
=> Added new module "spring-cloud-ribbon-client"

spring-apache-camel/src/main/java/com/baeldung/camel/file/FileProcessor.java, spring-apache-camel/src/main/java/com/baeldung/camel/file/FileRouter.java, spring-apache-camel/src/main/resources/camel-context-test.xml, spring-apache-camel/src/main/resources/camel-context.xml, spring-apache-camel/src/test/java/org/apache/camel/file/processor/FileProcessorTest.java
- added new camel context for junit test
=> PR for Intro to Camel article

spring-apache-camel/pom.xml, spring-apache-camel/src/main/java/com/baeldung/camel/file/FileProcessor.java, spring-apache-camel/src/main/java/com/baeldung/camel/file/FileRouter.java, spring-apache-camel/src/main/resources/camel-context-test.xml, spring-apache-camel/src/main/resources/camel-context.xml, spring-apache-camel/src/test/java/org/apache/camel/file/processor/FileProcessorIntegrationTest.java, spring-apache-camel/src/test/java/org/apache/camel/file/processor/FileProcessorTest.java, spring-apache-camel/src/test/java/org/apache/camel/main/AppIntegrationTest.java
- jUnit version in pom.xml is updated
- test names are updated due to Baeldung name convenction
=> Intro to Apache Camel

spring-data-solr/pom.xml, spring-data-solr/src/main/java/com/baeldung/spring/data/solr/config/SolrConfig.java, spring-data-solr/src/main/java/com/baeldung/spring/data/solr/model/Product.java, spring-data-solr/src/main/java/com/baeldung/spring/data/solr/repository/ProductRepository.java, spring-data-solr/src/main/resources/solr-named-queries.properties, spring-data-solr/src/test/java/com/baeldung/spring/data/solr/repo/ProductRepositoryIntegrationTest.java
=> BAEL-346 - [PR -2]

core-java/src/test/java/org/baeldung/java/sorting/Employee.java, core-java/src/test/java/org/baeldung/java/sorting/JavaSorting.java
Changes as per latest conversation in http://jira.baeldung.com/browse/BAEL-32
=> Java Sorting BAEL-32

core-java/src/test/java/org/baeldung/java/collections/JoinSplitCollectionsUnitTest.java
No code changes just formatting
=> BAEL-7: Fix formatting

spring-session/pom.xml
Removing the dependency management module as it is not needed.
=> BAEL-89 Removing dependency management module.

spring-jpa/src/main/java/org/baeldung/config/PersistenceJPAConfigL2Cache.java, spring-jpa/src/main/resources/persistence-h2.properties, spring-jpa/src/test/java/org/baeldung/persistence/deletion/config/PersistenceJPAConfigDeletion.java, spring-jpa/src/test/java/org/baeldung/persistence/deletion/model/Bar.java, spring-jpa/src/test/java/org/baeldung/persistence/deletion/model/Baz.java, spring-jpa/src/test/java/org/baeldung/persistence/deletion/model/Foo.java, spring-jpa/src/test/java/org/baeldung/persistence/service/DeletionIntegrationTest.java
BAEL-446: Deleting objects with Hibernate.
=> BAEL-446: Deleting objects with Hibernate

spring-boot/pom.xml
- Reformatted to spaces
- Upped version of spring-boot to latest
=> Spring Boot Fat Jar

jackson-annotations/src/main/java/com/baeldung/jacksonannotation/format/User.java, jackson-annotations/src/test/java/com/baeldung/jacksonannotation/format/JsonFormatTest.java
Re-used existing class Person to derive User from -- demonstrates JsonFormat annotation.
=> Added demonstration of @JsonFormat and associated test.

imageprocessing/pom.xml, imageprocessing/src/main/java/com/baeldung/imageprocessing/imagej/ImageJRectExample.java, imageprocessing/src/main/java/com/baeldung/imageprocessing/openimaj/OpenIMAJRectExample.java, imageprocessing/src/main/java/com/baeldung/imageprocessing/swing/SwingRectExample.java
Rename packages and classes names for image processing. Add OpenIMAJ example.
=> refactor packages & introduce OpenIMAJ

pom.xml, spring-reactor/pom.xml, spring-reactor/src/main/java/com/baeldung/Application.java, spring-reactor/src/main/java/com/baeldung/consumer/NotificationConsumer.java, spring-reactor/src/main/java/com/baeldung/controller/NotificationController.java, spring-reactor/src/main/java/com/baeldung/doman/NotificationData.java, spring-reactor/src/main/java/com/baeldung/service/NotificationService.java, spring-reactor/src/main/java/com/baeldung/service/impl/NotificationServiceimpl.java
commiting spring reactor. article published on the wordpress
=> commiting spring reactor

core-java/src/main/java/com/baeldung/jmx/Game.java, core-java/src/main/java/com/baeldung/jmx/GameMBean.java, core-java/src/main/java/com/baeldung/jmx/JMXTutorialMainlauncher.java
wordpress link http://inprogress.baeldung.com/wp-admin/post.php?post=27628&action=edit
=> BAEL-538   Basic introduction to JMX technology

JGit/pom.xml, JGit/src/main/java/com/baeldung/jgit/CreateNewRepository.java, JGit/src/main/java/com/baeldung/jgit/OpenRepository.java, JGit/src/main/java/com/baeldung/jgit/helper/Helper.java, JGit/src/main/java/com/baeldung/jgit/porcelain/AddFile.java, JGit/src/main/java/com/baeldung/jgit/porcelain/CommitAll.java, JGit/src/main/java/com/baeldung/jgit/porcelain/CreateAndDeleteTag.java, JGit/src/main/java/com/baeldung/jgit/porcelain/Log.java, JGit/src/test/java/JGitBugTest.java, JGit/src/test/java/com/baeldung/jgit/JGitBugTest.java, JGit/src/test/java/com/baeldung/jgit/porcelain/PorcelainTest.java
This are the code snippets for the article : Guide to JGit
=> First Commit

pom.xml, solr-fulltext-search/pom.xml, solr-fulltext-search/src/main/java/com/baeldung/solr/fulltexh/search/model/Product.java, solr-fulltext-search/src/main/java/com/baeldung/solr/fulltexh/search/service/SolrSearchService.java
Please merge new module solr-fulltext-search
=> BAEL-347 - Full-text search with SOLR

core-java/src/test/java/com/baeldung/CharArrayToStringUnitTest.java, core-java/src/test/java/com/baeldung/StringToCharArrayUnitTest.java, core-java/src/test/java/org/baeldung/java/streams/ThreadPoolInParallelStream.java
Hi,
I'm done with the evaluation article. This is my pull request.
Thanks.
Regards,
=> String to char array and char array to String

spring-hibernate4/src/test/java/com/baeldung/hibernate/oneToMany/main/HibernateOneToManyAnnotationMainTest.java
Hi @maibin Please check it out.
=> Fixed Unit Test for hibernate one to many

metrics/src/test/java/com/baeldung/metrics/core/MetricsTest.java
=> BAEL-548: Intro to Dropwizard Metrics

spring-remoting/pom.xml, spring-remoting/remoting-hessian-burlap/client/pom.xml, spring-remoting/remoting-hessian-burlap/client/src/main/java/com/baeldung/client/BurlapClient.java, spring-remoting/remoting-hessian-burlap/client/src/main/java/com/baeldung/client/HessianClient.java, spring-remoting/remoting-hessian-burlap/pom.xml, spring-remoting/remoting-hessian-burlap/server/pom.xml, spring-remoting/remoting-hessian-burlap/server/src/main/java/com/baeldung/server/Server.java
Hi,
this is the PR for the "Spring Remoting with Hessian and Burlap" article.
Cheers.
=> BAEL-554 Spring Remoting with Hessian and Burlap

spring-remoting/remoting-hessian-burlap/client/pom.xml, spring-remoting/remoting-hessian-burlap/client/src/test/java/com/baeldung/client/CabBookingServiceTest.java, spring-remoting/remoting-hessian-burlap/client/src/test/resources/application.properties, spring-remoting/remoting-hessian-burlap/server/pom.xml, spring-remoting/remoting-hessian-burlap/server/src/main/java/com/baeldung/server/Server.java
Hi all,
PR related to the [BAEL-554](http://jira.baeldung.com/browse/BAEL-554) article about Spring Remote With Burlap and Hessian. As Grzegorz asked, I added a couple of JUnit tests that take care of running both the server and the clients.
=> BAEL-554 - JUnit test that run server and clients

log4j2/src/test/java/com/baeldung/logging/log4j2/tests/CustomLoggingTest.java, log4j2/src/test/resources/log4j2.xml
BAEL-41 - Log4J 2 Layout, Appenders, Filters
=> BAEL-41 - Log4J 2 Layout, Appenders, Filters

mockito2/.gitignore, mockito2/README.md, mockito2/pom.xml, mockito2/src/main/java/com/baeldung/mockito/java8/JobPosition.java, mockito2/src/main/java/com/baeldung/mockito/java8/JobService.java, mockito2/src/main/java/com/baeldung/mockito/java8/Person.java, mockito2/src/main/java/com/baeldung/mockito/java8/UnemploymentService.java, mockito2/src/main/java/com/baeldung/mockito/java8/UnemploymentServiceImpl.java, mockito2/src/test/java/com/baeldung/mockito/java8/ArgumentMatcherWithLambdaUnitTest.java, mockito2/src/test/java/com/baeldung/mockito/java8/ArgumentMatcherWithoutLambdaUnitTest.java, mockito2/src/test/java/com/baeldung/mockito/java8/CustomAnswerWithLambdaUnitTest.java, mockito2/src/test/java/com/baeldung/mockito/java8/CustomAnswerWithoutLambdaUnitTest.java, mockito2/src/test/java/com/baeldung/mockito/java8/JobServiceUnitTest.java, mockito2/src/test/java/com/baeldung/mockito/java8/UnemploymentServiceImplUnitTest.java, pom.xml
=> BAEL-632: Mockito's Java 8 features

spring-boot-auditing/.gitignore, spring-boot-auditing/pom.xml, spring-boot-auditing/src/main/java/org/baeldung/Application.java, spring-boot-auditing/src/main/java/org/baeldung/MvcConfig.java, spring-boot-auditing/src/main/java/org/baeldung/WebSecurityConfig.java, spring-boot-auditing/src/main/java/org/baeldung/auditing/ExposeAttemptedPathAuthorizationAuditListener.java, spring-boot-auditing/src/main/java/org/baeldung/auditing/LoginAttemptsLogger.java, spring-boot-auditing/src/main/resources/application.properties, spring-boot-auditing/src/main/resources/logback.xml, spring-boot-auditing/src/main/resources/templates/hello.html, spring-boot-auditing/src/main/resources/templates/home.html, spring-boot-auditing/src/main/resources/templates/login.html
Source code for http://inprogress.baeldung.com/wp-admin/post.php?post=35337&action=edit
=> BEAL-75 - Spring Boot Audit Support

core-java/src/test/java/com/baeldung/money/JavaMoneyTest.java
=> BAEL-606 - JSR 354 - Money

spring-cloud/spring-cloud-bootstrap/svc-book/src/main/java/com/baeldung/spring/cloud/bootstrap/svcbook/BookServiceApplication.java, spring-cloud/spring-cloud-bootstrap/zipkin/src/main/java/com/baeldung/spring/cloud/bootstrap/zipkin/ZipkinApplication.java
BAEL-574 - Removing redundant pattern check
=> BAEL-574 - Removing redundant pattern check

core-java/src/test/java/com/baeldung/money/JavaMoneyTest.java
=> ESG-606 - refining tests

algorithms/src/main/java/com/baeldung/automata/FiniteStateMachine.java, algorithms/src/main/java/com/baeldung/automata/RtFiniteStateMachine.java, algorithms/src/main/java/com/baeldung/automata/RtState.java, algorithms/src/main/java/com/baeldung/automata/RtTransition.java, algorithms/src/main/java/com/baeldung/automata/State.java, algorithms/src/main/java/com/baeldung/automata/Transition.java, algorithms/src/test/java/algorithms/RtFiniteStateMachineTest.java
Example code for [this](http://jira.baeldung.com/browse/BAEL-652) article
=> Finite automata example

spring-kafka/README.md, spring-kafka/pom.xml, spring-kafka/src/main/java/com/baeldung/spring/kafka/KafkaApplication.java, spring-kafka/src/main/java/com/baeldung/spring/kafka/KafkaConsumerConfig.java, spring-kafka/src/main/java/com/baeldung/spring/kafka/KafkaProducerConfig.java, spring-kafka/src/main/resources/application.properties
PR for BAEL-578 : Introduction to spring-kafka
=> BAEL-578: Add spring-kafka module

spring-kafka/README.md, spring-kafka/pom.xml, spring-kafka/src/main/java/com/baeldung/spring/kafka/Greeting.java, spring-kafka/src/main/java/com/baeldung/spring/kafka/KafkaApplication.java, spring-kafka/src/main/java/com/baeldung/spring/kafka/KafkaConsumerConfig.java, spring-kafka/src/main/java/com/baeldung/spring/kafka/KafkaProducerConfig.java, spring-kafka/src/main/resources/application.properties
update spring-kafka project with support for multiple partitions and JSON serializer
=> BAEL-578 : Updated pull request for Spring-Kafka article

core-java/src/main/java/com/baeldung/arraycopy/model/Address.java, core-java/src/main/java/com/baeldung/arraycopy/model/Employee.java, core-java/src/test/java/com/baeldung/arraycopy/ArrayCopyUtilTest.java
Added test scenarios for different method to copy an array in Java.
=> BAEL-746 How to Copy an Array in Java

spring-5/pom.xml, spring-5/src/main/java/com/baeldung/functional/RootServlet.java, spring-5/src/main/java/com/baeldung/web/FooController.java, spring-5/src/main/webapp/WEB-INF/web.xml
- the Reactor dependency problem seems to be fixed in the latest spring-boot-starter snapshot
- fix previous legacy FooController implementation error caused by latest CrudRepository change
- code added for standalone servlet container deployment of functions
=> BAEL-636: add standalone deployment

core-java/src/test/java/com/baeldung/enums/PizzaUnitTest.java
Tests related to converting a Java String into an Enum
=> BAEL-732: String to enum

guava21/src/main/java/com/baeldung/guava/tutorial/AtomicLongMapTutorials.java, guava21/src/main/java/com/baeldung/guava/tutorial/MonitorExample.java, guava21/src/test/java/AtomicLongMapTests.java, guava21/src/test/java/MonitorUnitTests.java
Code and Tests for common.util.concurrent package.
=> http://jira.baeldung.com/browse/BAEL-713 | Guide in Guava

spring-5/pom.xml
run `mvn clean package -Dmain-class=com.baeldung.functional.FunctionalSpringBootApplication` for BAEL-636
=> add a main-class variable on maven building and exclude IntegrationTests

spring-state-machine/pom.xml, spring-state-machine/src/main/java/com/baeldung/spring/statemachine/config/SimpleStateMachineConfiguration.java, spring-state-machine/src/test/java/com/baeldung/spring/statemachine/ForkJoinStateMachineTest.java, spring-state-machine/src/test/java/com/baeldung/spring/statemachine/HierarchicalStateMachineTest.java, spring-state-machine/src/test/java/com/baeldung/spring/statemachine/JunctionStateMachineTest.java, spring-state-machine/src/test/java/com/baeldung/spring/statemachine/StateEnumMachineTest.java, spring-state-machine/src/test/java/com/baeldung/spring/statemachine/StateMachineIntegrationTest.java
=> Spring State Machine x3

spring-boot/src/main/java/org/baeldung/jsoncomponent/User.java, spring-boot/src/main/java/org/baeldung/jsoncomponent/UserCombinedSerializer.java, spring-boot/src/main/java/org/baeldung/jsoncomponent/UserJsonDeserializer.java, spring-boot/src/main/java/org/baeldung/jsoncomponent/UserJsonSerializer.java, spring-boot/src/test/java/org/baeldung/jsoncomponent/UserJsonDeserializerTest.java, spring-boot/src/test/java/org/baeldung/jsoncomponent/UserJsonSerializerTest.java
Code for the article http://inprogress.baeldung.com/wp-admin/post.php?post=38976&action=edit
=> BAEL-87 - @JsonComponent in Spring Boot

jee7/pom.xml, jee7/src/main/java/com/baeldung/convListVal/ConvListVal.java, jee7/src/main/java/com/baeldung/convListVal/MyListener.java, jee7/src/main/java/com/baeldung/javaeeannotations/JavaEEAnnotationsSample/src/main/java/com/baeldung/javaeeannotations/AccountServlet.java, jee7/src/main/java/com/baeldung/javaeeannotations/JavaEEAnnotationsSample/src/main/java/com/baeldung/javaeeannotations/BankAppServletContextListener.java, jee7/src/main/java/com/baeldung/javaeeannotations/JavaEEAnnotationsSample/src/main/java/com/baeldung/javaeeannotations/LogInFilter.java, jee7/src/main/java/com/baeldung/javaeeannotations/JavaEEAnnotationsSample/src/main/java/com/baeldung/javaeeannotations/UploadCustomerDocumentsServlet.java, jee7/src/main/webapp/ConvListVal.xhtml, jee7/src/test/java/com/baeldung/jaxws/EmployeeServiceLiveTest.java
Converters, Listeners and Validators in Java EE 7
=> Converters, Listeners and Validators in Java EE 7

spring-5/pom.xml, spring-5/src/main/java/com/baeldung/jupiter/MethodParameterFactory.java, spring-5/src/main/java/com/baeldung/jupiter/ParameterAutowireUtils.java, spring-5/src/main/java/com/baeldung/jupiter/SpringExtension.java, spring-5/src/main/java/com/baeldung/jupiter/SpringJUnit5Config.java, spring-5/src/main/java/com/baeldung/jupiter/TestConfig.java, spring-5/src/main/java/com/baeldung/web/reactive/Task.java, spring-5/src/test/java/com/baeldung/functional/FunctionalWebApplicationIntegrationTest.java, spring-5/src/test/java/com/baeldung/jupiter/Spring5JUnit5ComposedAnnotationTests.java, spring-5/src/test/java/com/baeldung/jupiter/Spring5JUnit5ParallelTest.java, spring-5/src/test/java/com/baeldung/jupiter/Spring5JUnit5Tests.java, spring-5/src/test/java/com/baeldung/jupiter/Spring5Java8NewFeaturesTest.java, spring-5/src/test/java/com/baeldung/jupiter/Spring5ReactiveServerClientTest.java
=> Overview of Spring 5

spring-boot/src/main/java/org/baeldung/boot/boottest/EmployeeRestController.java, spring-boot/src/main/java/org/baeldung/boot/boottest/EmployeeServiceImpl.java, spring-boot/src/test/java/org/baeldung/boot/boottest/EmployeeRepositoryTest.java, spring-boot/src/test/java/org/baeldung/boot/boottest/EmployeeRestControllerIntTest.java, spring-boot/src/test/java/org/baeldung/boot/boottest/EmployeeRestControllerTest.java, spring-boot/src/test/java/org/baeldung/boot/boottest/EmployeeServiceImplTest.java
=> BAEL-88 Testing in Spring Boot

spring-boot-custom-starter/greeter-spring-boot-autoconfigure/pom.xml, spring-boot-custom-starter/greeter-spring-boot-autoconfigure/src/main/java/com/baeldung/greeter/autoconfigure/GreeterAutoConfiguration.java, spring-boot-custom-starter/greeter-spring-boot-autoconfigure/src/main/java/com/baeldung/greeter/autoconfigure/GreeterProperties.java, spring-boot-custom-starter/greeter-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories, spring-boot-custom-starter/greeter-spring-boot-sample-app/pom.xml, spring-boot-custom-starter/greeter-spring-boot-sample-app/src/main/java/com/baeldung/greeter/sample/GreeterSampleApplication.java, spring-boot-custom-starter/greeter-spring-boot-sample-app/src/main/resources/application.properties, spring-boot-custom-starter/greeter-spring-boot-sample-app/src/test/java/com/baeldung/greeter/sample/GreeterSampleApplicationTest.java, spring-boot-custom-starter/greeter-spring-boot-starter/pom.xml, spring-boot-custom-starter/greeter/README.md, spring-boot-custom-starter/greeter/pom.xml, spring-boot-custom-starter/greeter/src/main/java/com/baeldung/greeter/Greeter.java, spring-boot-custom-starter/greeter/src/main/java/com/baeldung/greeter/GreeterConfigParams.java, spring-boot-custom-starter/greeter/src/main/java/com/baeldung/greeter/GreetingConfig.java, spring-boot-custom-starter/greeter/src/test/java/com/baeldung/greeter/GreeterTest.java, spring-boot-custom-starter/pom.xml
Added a multi-module project for BAEL-762 (spring boot custom starters). It has four projects:
1. **greeter**:  A simple library to generate the greeting messages.
2. **greeter-spring-boot-autoconfigure**: Contains all the autoconfigure classes
3. **greeter-spring-boot-starter**: Contains the starter _pom_
4. **greeter-spring-boot-sample-app**: A sample app to demonstrate the usage of the starter
=> Added modules for spring boot custom starter BAEL-762

spring-boot/src/main/java/com/baeldung/autoconfiguration/MySQLAutoconfiguration.java
* BAEL-86
* Added Themes and Beans
* Improvements and fully tested locally
=> Spring autoconfiguration update

spring-data-redis/pom.xml
Hi. just want to upgrade spring-data-redis to 1.8.1. Spring to 4.3.7.
Tested and work fine with redis-3.2
Regards
=> upgrade version

core-java/src/test/java/org/baeldung/java/shell/JavaProcessUnitIntegrationTest.java
Anonymous new Consumer<String>() replaced with method reference.
=> minor java8 update

spring-boot/src/main/java/org/baeldung/properties/ConfigProperties.java, spring-boot/src/main/java/org/baeldung/properties/ConfigPropertiesDemoApplication.java, spring-boot/src/main/resources/configprops.properties, spring-boot/src/test/java/org/baeldung/properties/ConfigPropertiesIntegrationTest.java, spring-boot/src/test/java/org/baeldung/properties/ConfigPropertiesTest.java, spring-boot/src/test/resources/configprops-test.properties
Commits for A guide to @ConfigurationProperties in Spring Boot
=> Bael 697 - @ConfigurationProperties in Spring Boot

stripe/src/main/java/com/baeldung/stripe/ChargeController.java, stripe/src/main/java/com/baeldung/stripe/ChargeRequest.java
=> Simplify annotation usage

core-java/src/test/java/com/baeldung/java8/comparator/Employee.java, core-java/src/test/java/com/baeldung/java8/comparator/Java8ComparatorTest.java, libraries/myPersistence.xml, libraries/pom.xml, libraries/src/main/java/com/baeldung/jdo/GuideToJDO.java, libraries/src/main/java/com/baeldung/jdo/ProductXML.java
uncomment modified classes in core-java
=> uncomment classes in core-java

core-java/src/test/java/com/baeldung/java8/comparator/Employee.java, core-java/src/test/java/com/baeldung/java8/comparator/Java8ComparatorTest.java, libraries/myPersistence.xml, libraries/pom.xml, libraries/src/main/java/com/baeldung/jdo/GuideToJDO.java, libraries/src/main/java/com/baeldung/jdo/ProductXML.java
Add new content to JDO, including XML and querys
=> Add content to JDO

core-java/src/test/java/com/baeldung/string/SplitTest.java
=> String split tests

core-java/src/test/java/com/baeldung/stackoverflowerror/CyclicDependancyManualTest.java, core-java/src/test/java/com/baeldung/stackoverflowerror/InfiniteRecursionWithTerminationConditionManualTest.java, core-java/src/test/java/com/baeldung/stackoverflowerror/UnintendedInfiniteRecursionManualTest.java
Removing try-catch from tests and minor formatting - BAEL-876
=> Removing try-catch from tests and minor formatting

core-java/src/main/java/com/baeldung/stackoverflowerror/RecursionWithCorrectTerminationCondition.java, core-java/src/test/java/com/baeldung/stackoverflowerror/InfiniteRecursionWithTerminationConditionManualTest.java, core-java/src/test/java/com/baeldung/stackoverflowerror/RecursionWithCorrectTerminationConditionManualTest.java
Changes done in tests for BAEL-876
=> Changes done in tests for BAEL-876

core-java/src/main/java/com/baeldung/stream/StreamApi.java, core-java/src/test/java/com/baeldung/stream/StreamApiTest.java, spring-core/src/main/java/com/baeldung/beaninjection/FileReader.java, spring-core/src/main/java/com/baeldung/beaninjection/FtpReader.java, spring-core/src/main/java/com/baeldung/beaninjection/Location.java, spring-core/src/main/java/com/baeldung/beaninjection/ReaderApplicationConfig.java, spring-core/src/main/java/com/baeldung/beaninjection/ReaderManager.java, spring-core/src/main/java/com/baeldung/beaninjection/ReaderService.java, spring-core/src/main/resources/injectiontypes.xml, spring-core/src/test/java/com/baeldung/beaninjection/FileReaderTest.java, spring-core/src/test/java/com/baeldung/beaninjection/FtpReaderTest.java, spring-core/src/test/java/com/baeldung/beaninjection/ReaderManagerTest.java, spring-core/src/test/java/com/baeldung/beaninjection/ReaderServiceTest.java
ali.raza Added Code example for BAEL-833.
=> BAEL-833: How to get last element of a Stream in Java?

core-java/src/main/java/com/baeldung/concurrent/diningphilosophers/DiningPhilosophers.java, core-java/src/main/java/com/baeldung/concurrent/diningphilosophers/Philosopher.java
Code for the Dining Philosophers Problem
=> Dining Philosophers Problem

structurizr/pom.xml, structurizr/src/main/java/com/baeldung/structurizr/StructurizrSimple.java, structurizr/src/main/java/com/baeldung/structurizr/spring/GenericComponent.java, structurizr/src/main/java/com/baeldung/structurizr/spring/PaymentController.java, structurizr/src/main/java/com/baeldung/structurizr/spring/PaymentRepository.java
=> Structurizr

core-java/README.md
Fix the link now that the article is up.
=> Fix UUID article link

spring-5-mvc/pom.xml, spring-5-mvc/src/main/kotlin/com/baeldung/springbootkotlin/HelloController.kt, spring-5-mvc/src/main/kotlin/com/baeldung/springbootkotlin/HelloDto.kt, spring-5-mvc/src/main/kotlin/com/baeldung/springbootkotlin/HelloService.kt, spring-5-mvc/src/main/kotlin/com/baeldung/springbootkotlin/KotlinDemoApplication.kt, spring-5-mvc/src/test/kotlin/springbootkotlin/KotlinDemoApplicationIntegrationTest.kt
BAEL-755 - moving kotlin code to spring-5-mvc
=> BAEL-755 - moving kotlin code to spring-5-mvc

libraries/src/test/java/com/baeldung/stream/JoolMergeStreamsTest.java, libraries/src/test/java/com/baeldung/stream/StreamExMergeStreamsTest.java
Use the java.util.stream.Stream interface as much as possible
=> BAEL-885 - How to merge two Java streams?

libraries/pom.xml
set serenity dependency version to 1.4.0 instead of 1.4.1-rc
=> #BAEL-914 update dependency version

core-java/src/main/java/com/baeldung/reflection/BaeldungReflectionUtils.java, core-java/src/main/java/com/baeldung/reflection/Customer.java, core-java/src/test/java/com/baeldung/reflection/BaeldungReflectionUtilsTest.java
BAEL-869 - Java 8 example of listing null properties
=> BAEL-869 - Java 8 example of listing null properties

core-java-9/src/main/java/com/baeldung/java9/time/TimeApi.java, core-java-9/src/test/java/com/baeldung/java9/time/TimeApiTest.java
Pull Request for BAEL-924 from ali.raza.
=> BAEL-924: How to get all LocalDates between two dates?

algorithms/src/main/java/com/baeldung/algorithms/hillclimbing/HillClimbing.java
=> BAEL-875 code refactoring

liquibase/pom.xml, liquibase/src/main/resources/liquibase/db-changelog.xml, liquibase/src/main/resources/liquibase/liquibase.properties, pom.xml
added the sample liquibase rollback scripts
=> BAEL-791 Liquibase rollback

pom.xml, spring-vertx/pom.xml
BAEL-778 - removing vertx-core dep, included transitively by vertx-web
=> BAEL-778 - removing vertx-core dep, included transitively by vertx-web

spring-vertx/src/main/java/com/baeldung/vertxspring/VertxSpringApplication.java, spring-vertx/src/main/java/com/baeldung/vertxspring/verticles/ArticleRecipientVerticle.java, spring-vertx/src/main/java/com/baeldung/vertxspring/verticles/ServerVerticle.java
BAEL-778 - renaming service verticle
=> BAEL-778 - renaming service verticle

libraries/src/main/java/com/baeldung/quartz/JobA.java, libraries/src/main/java/com/baeldung/quartz/JobB.java, libraries/src/main/java/com/baeldung/quartz/QuartzExample.java, libraries/src/main/java/com/baeldung/quartz/SimpleJob.java
More code examples found in article "Introduction to Quartz"
=> Adding more examples to the Quartz project

core-java/src/main/java/com/baeldung/javanetworking/url/URLDemo.java, core-java/src/main/java/log4j.properties, core-java/src/test/java/com/baeldung/javanetworking/url/test/URLDemoTest.java
A new attempt without changing into pom.xml.
=> Bael-864, Networking, core-java.

algorithms/src/main/java/com/baeldung/algorithms/mcts/montecarlo/MonteCarloTreeSearch.java, algorithms/src/main/java/com/baeldung/algorithms/mcts/montecarlo/State.java, algorithms/src/main/java/com/baeldung/algorithms/mcts/montecarlo/UCT.java, algorithms/src/main/java/com/baeldung/algorithms/mcts/tictactoe/Board.java, algorithms/src/main/java/com/baeldung/algorithms/mcts/tictactoe/Position.java, algorithms/src/main/java/com/baeldung/algorithms/mcts/tree/Node.java, algorithms/src/main/java/com/baeldung/algorithms/mcts/tree/Tree.java, algorithms/src/test/java/algorithms/MCTSTest.java
BAEL-984 Implementation for Tic-Tac-Toe using Monte Carlo tree search
=> BAEL-984 Monte Carlo tree search 

pom.xml, spring-bom/README.md, spring-bom/pom.xml, spring-bom/src/main/java/com/baeldung/spring/bom/HelloWorldApp.java, spring-bom/src/main/java/com/baeldung/spring/bom/HelloWorldBean.java, spring-bom/src/main/java/com/baeldung/spring/bom/HelloWorldConfig.java
this PR related to the "Spring With Maven BOM" article
=> Spring With Maven BOM

spring-cloud/spring-cloud-bootstrap/gateway/src/main/java/com/baeldung/spring/cloud/bootstrap/gateway/client/book/BooksClient.java, spring-cloud/spring-cloud-bootstrap/gateway/src/main/java/com/baeldung/spring/cloud/bootstrap/gateway/client/rating/RatingsClient.java
BAEL-947 - moving from @GetMapping to @RequestMapping on account of https://github.com/spring-cloud/spring-cloud-netflix/issues/760
=> BAEL-947 - moving from @GetMapping to @RequestMapping on account of https://github.com/spring-cloud/spring-cloud-netflix/issues/760

core-java/src/main/java/com/baeldung/concurrent/cyclicbarrier/CyclicBarrierDemo.java
=> Cyclic Barriers demo

libraries/src/test/java/com/baeldung/commons/collections/orderedmap/OrderedMapUnitTest.java
Hi @KevinGilmore  now the PR is "able to merge". I had to delete my repository and downloading the module again. Is there a more practical way to do it?
Ignacio
=> for-loops changed to while-loops when appropiate user:igallegosagas email:ignaciogallego@gmail.com

junit5/pom.xml, junit5/src/test/java/com/baeldung/migration/junit4/AnnotationTestExampleTest.java, junit5/src/test/java/com/baeldung/migration/junit4/AssertionsExampleTest.java, junit5/src/test/java/com/baeldung/migration/junit4/RuleExampleTest.java, junit5/src/test/java/com/baeldung/migration/junit4/categories/Annotations.java, junit5/src/test/java/com/baeldung/migration/junit4/categories/JUnit4Tests.java, junit5/src/test/java/com/baeldung/migration/junit4/rules/TraceUnitTestRule.java, junit5/src/test/java/com/baeldung/migration/junit5/AnnotationTestExampleTest.java, junit5/src/test/java/com/baeldung/migration/junit5/AssertionsExampleTest.java, junit5/src/test/java/com/baeldung/migration/junit5/RuleExampleTest.java, junit5/src/test/java/com/baeldung/migration/junit5/extensions/TraceUnitExtension.java
http://jira.baeldung.com/browse/BAEL-902
=> BAEL-902: Migrating from JUnit 4 to JUnit5

libraries/src/test/java/com/baeldung/commons/collections/CollectionUtilsGuideTest.java
BAEL-965 - reverting to anonymous classes
=> BAEL-965 - reverting to anonymous classes

libraries/pom.xml, libraries/src/test/java/com/baeldung/commons/collections/MapUtilsTest.java
=> bael-964-map-util

libraries/src/test/java/com/baeldung/commons/collections/MapUtilsTest.java
BAEL-964 - printing directly to standard output
=> BAEL-964 - printing directly to standard output

libraries/pom.xml, libraries/src/main/java/com/baeldung/vaadin/BindData.java, libraries/src/main/java/com/baeldung/vaadin/VaadinUI.java
Vaadin server-push, data binding and validators.
=> Vaadin server-push, data binding and validators

libraries/src/main/java/com/baeldung/vaadin/VaadinUI.java
changed thread for ScheduledExecutorService
=> changed thread for ScheduledExecutorService

libraries/src/test/java/com/baeldung/commons/collections/MapUtilsTest.java
BAEL-964 - Changing assertions within invert test
=> BAEL-964 - Changing assertions within invert test

core-java/hashcode/pom.xml, core-java/hashcode/src/main/java/com/baeldung/application/Application.java, core-java/hashcode/src/main/java/com/baeldung/entities/User.java, core-java/hashcode/src/test/java/com/baeldung/application/ApplicationTest.java, core-java/hashcode/src/test/java/com/baeldung/entities/UserTest.java
- Initial Commit.
- Looking for an initial review.
=> Custom Efficient hashCode() Implementations - Alejandro Gervasio - alejandro.gervasio@gmail.com

asciidoctor/pom.xml, asciidoctor/src/docs/asciidoc/test.adoc, asciidoctor/src/themes/custom-theme.yml
- changed AsciiDoc document
- added new things in pom
=> - added custom theme for asciidoc book

core-java/src/main/java/com/baeldung/hashcode/application/Application.java, core-java/src/main/java/com/baeldung/hashcode/entities/User.java, core-java/src/test/java/com/baeldung/hashcode/application/ApplicationTest.java, core-java/src/test/java/com/baeldung/hashcode/entities/UserTest.java
=> Guide to hashCode() in Java  - Alejandro Gervasio | alejandro.gervasio@gmail.com

feign/README.md
=> Fix title formatting

kotlin/src/main/kotlin/com/baeldung/kotlin/delegates/Database.kt, kotlin/src/main/kotlin/com/baeldung/kotlin/delegates/DatabaseDelegate.kt, kotlin/src/main/kotlin/com/baeldung/kotlin/delegates/User.kt, kotlin/src/test/kotlin/com/baeldung/kotlin/delegates/DatabaseDelegatesTest.kt
This produces a fake Database representation - working in terms of
hardcoded data, a Delegate that loads values from this fake Database,
and then a class with fields delegated to the fake database.
=> BAEL-975: Delegated Properties in Kotlin

spring-core/src/main/java/com/baeldung/valuewithdefaults/ValuesWithDefaultsApp.java
These changes are for the code samples related to BAEL-1086
=> add valueswithdefaults example

core-java/pom.xml, core-java/src/main/java/com/baeldung/designpatterns/adapter/AdapterPatternDriver.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/LuxuryCarsSpeed.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/LuxuryCarsSpeedAdapter.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/LuxuryCarsSpeedAdapterImpl.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Blue.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/BridgePatternDriver.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Color.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Red.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Shape.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Square.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Triangle.java, core-java/src/main/java/com/baeldung/designpatterns/decorator/BubbleLights.java, core-java/src/main/java/com/baeldung/designpatterns/decorator/ChristmasTree.java, core-java/src/main/java/com/baeldung/designpatterns/decorator/ChristmasTreeImpl.java, core-java/src/main/java/com/baeldung/designpatterns/decorator/DecoratorPatternDriver.java, core-java/src/main/java/com/baeldung/designpatterns/decorator/Garland.java, core-java/src/main/java/com/baeldung/designpatterns/decorator/TreeDecorator.java, core-java/src/main/java/com/baeldung/designpatterns/proxy/ExpensiveObject.java, core-java/src/main/java/com/baeldung/designpatterns/proxy/ExpensiveObjectImpl.java, core-java/src/main/java/com/baeldung/designpatterns/proxy/ExpensiveObjectProxy.java, core-java/src/main/java/com/baeldung/designpatterns/proxy/ProxyPatternDriver.java, core-java/src/main/java/com/baeldung/designpatterns/util/LogerUtil.java, core-java/src/main/resources/log4jstructuraldp.properties, core-java/src/test/java/com/baeldung/designpatterns/AdapterPatternIntegrationTest.java, core-java/src/test/java/com/baeldung/designpatterns/BridgePatternIntegrationTest.java, core-java/src/test/java/com/baeldung/designpatterns/DecoratorPatternIntegrationTest.java, core-java/src/test/java/com/baeldung/designpatterns/ProxyPatternIntegrationTest.java, core-java/src/test/java/com/baeldung/designpatterns/TestAppenderDP.java
Explanation with examples and differences between Proxy, Decorator, Adapter, and Bridge Patterns
=> BAEL-1072 - Difference between Proxy, Decorator, Adapter, and Bridge Patterns

ejb/ejb-client/src/main/resources/jboss-ejb-client.properties, ejb/ejbclient/src/main/java/com/baeldung/ejbclient/application/TextApplication.java, ejb/ejbclient/src/main/resources/jboss-ejb-client.properties, ejb/ejbclient/src/test/java/com/baeldung/ejbclient/application/TextApplicationTest.java, ejb/ejbmodule/src/main/java/com/baeldung/ejbmodule/TextProcessorBean.java, ejb/ejbmodule/src/main/java/com/baeldung/ejbmodule/TextProcessorRemote.java, ejb/ejbmodule/src/test/java/com/baeldung/ejbmodule/TextProcessorBeanTest.java
This PR belongs to the following JIRA issue:
http://jira.baeldung.com/browse/BAEL-1117
=> Introduction to EJB JNDI Lookup on WildFly Application Server - Alejandro Gervasio | alejandro.gervasio@gmail.com

libraries/pom.xml, libraries/src/test/java/com/baeldung/commons/csv/CSVReaderWriterTest.java, libraries/src/test/resources/book.csv
=> BAEL 1105- Apache Commons CSV

algorithms/src/main/java/com/baeldung/algorithms/BinarySearch.java, algorithms/src/test/java/algorithms/BinarySearchTest.java
Code for binary search algorithm along with its test case.
=> Binary Search algorithm

core-java/src/main/java/com/baeldung/numberofdigits/Benchmarking.java, core-java/src/main/java/com/baeldung/numberofdigits/NumberOfDigits.java, core-java/src/main/java/com/baeldung/numberofdigits/NumberOfDigitsDriver.java, core-java/src/test/java/com/baeldung/numberofdigits/NumberOfDigitsIntegrationTest.java
Six different ways of getting the number of digits in an int and analysis of those algorithms.
=> BAEL-1076 How to get a number of digits in an int?

libraries/pom.xml, libraries/src/main/java/com/baeldung/commons/lang3/BuilderMethods.java, libraries/src/test/java/com/baeldung/commons/lang3/Lang3UtilsTest.java
BAEL-971 : Introduction to Apache Commons Lang3 Code changes
=> BAEL - 971 Code Changes

algorithms/src/main/java/com/baeldung/algorithms/string/search/StringSearchAlgorithms.java, algorithms/src/test/java/algorithms/StringSearchAlgorithmsTest.java
=> string search algorithms article

core-java/pom.xml, libraries/src/test/java/com/baeldung/java/io/JavaDirectoryDeleteUnitTest.java
Moved article code to libraries, added a null check and reverted change to core-java pom.xml
=> BAEL-1075 PR # 2

libraries/src/test/java/com/baeldung/java/io/JavaDirectoryDeleteUnitTest.java
=> BAEL-1075: PR # 3

spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/CustomAuthenticationProvider.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/MyLogoutSuccessHandler.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/MyUserDetailsService.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/RolesAuthoritiesApplication.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/config/MvcConfig.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/config/SecurityConfig.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/model/Privilege.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/model/Role.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/model/User.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/persistence/IUserService.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/persistence/PersistenceJPAConfig.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/persistence/PrivilegeRepository.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/persistence/RoleRepository.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/persistence/SetupDataLoader.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/persistence/UserRepository.java, spring-security-mvc-boot/src/main/java/org/baeldung/rolesauthorities/persistence/UserService.java, spring-security-mvc-boot/src/main/resources/application-rolesauthorities.properties, spring-security-mvc-boot/src/main/resources/persistence.properties, spring-security-mvc-boot/src/main/resources/templates/rolesauthorities/home.html, spring-security-mvc-boot/src/main/resources/templates/rolesauthorities/login.html, spring-security-mvc-boot/src/main/resources/templates/rolesauthorities/protectedbyauthority.html, spring-security-mvc-boot/src/main/resources/templates/rolesauthorities/protectedbynothing.html, spring-security-mvc-boot/src/main/resources/templates/rolesauthorities/protectedbyrole.html
Source code changes for Role vs Granted Authority example
=> import source per BAEL-1084

mustache/pom.xml, mustache/src/main/java/com/baeldung/springmustache/SpringMustacheApplication.java, mustache/src/main/java/com/baeldung/springmustache/controller/ArticleController.java, mustache/src/main/java/com/baeldung/springmustache/model/Article.java, mustache/src/main/resources/templates/error/error.html, mustache/src/main/resources/templates/index.html, mustache/src/main/resources/templates/layout/article.html, mustache/src/main/resources/templates/layout/footer.html, mustache/src/main/resources/templates/layout/header.html, mustache/src/test/java/com/baeldung/springmustache/SpringMustacheApplicationTests.java
BAEL-982 - Moving to mustache module
=> BAEL-982 - Moving to mustache module

javaxval/bean-validation/pom.xml, javaxval/bean-validation/src/main/java/com/baeldung/beanvalidation/application/Application.java, javaxval/bean-validation/src/main/java/com/baeldung/beanvalidation/container/IntegerContainer.java, javaxval/bean-validation/src/main/java/com/baeldung/beanvalidation/container/StringContainer.java, javaxval/bean-validation/src/main/java/com/baeldung/beanvalidation/model/User.java, javaxval/bean-validation/src/main/java/com/baeldung/beanvalidation/service/EntityService.java, javaxval/bean-validation/src/main/java/com/baeldung/beanvalidation/service/UserService.java, javaxval/bean-validation/src/test/java/com/baeldung/beanvalidation/ValidationTest.java
This PR belongs to the following JIRA issue:
http://jira.baeldung.com/browse/BAEL-1138
=> Java Beans Validation with Hibernate Validator - BAEL-1138 - Alejandro Gervasio - alejandro.gervasio@gmail.com

mustache/src/main/java/com/baeldung/springmustache/controller/ArticleController.java
=> BAEL-982 - reusing model

spring-all/src/main/java/org/baeldung/controller/controller/PassParametersController.java, spring-all/src/main/webapp/WEB-INF/view/viewPage.jsp, spring-all/src/test/java/org/baeldung/controller/PassParametersControllerTest.java
Controller methods are written. Test methods are written based on the controller methods and the view is created as an example.
=> BAEL-1088 Model, ModelMap and ModelView in Spring MVC

libraries/src/main/java/com/baeldung/commons/lang3/SampleLazyInitializer.java, libraries/src/main/java/com/baeldung/commons/lang3/SampleObject.java, libraries/src/test/java/com/baeldung/commons/lang3/Lang3UtilsTest.java
Added a new test for ConcurrentException and updated other exception with Lambda
=> Updated Lang3Utils.java

vavr/src/test/java/com/baeldung/vavr/collections/CollectionFactoryMethodsTest.java, vavr/src/test/java/com/baeldung/vavr/collections/CollectionFactoryMethodsUnitTest.java
The PR containing the test class for the mini-article "Collection Factory Methods for Vavr" by Ignacio Gallego Sagastume
=> JIRA issue : BAEL-960. Collection Factory Methods for Vavr. User: ignaciogallego@gmail.com

core-java/src/main/java/com/baeldung/designpatterns/adapter/AdapterPatternDriver.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/AstonMartin.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/BugattiVeyron.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/LuxuryCars.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/LuxuryCarsAdapter.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/LuxuryCarsAdapterImpl.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/McLaren.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/Movable.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/MovableAdapter.java, core-java/src/main/java/com/baeldung/designpatterns/adapter/MovableAdapterImpl.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Blue.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/BridgePatternDriver.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Color.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Red.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Shape.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Square.java, core-java/src/main/java/com/baeldung/designpatterns/bridge/Triangle.java, core-java/src/main/java/com/baeldung/designpatterns/decorator/ChristmasTree.java, core-java/src/main/java/com/baeldung/designpatterns/proxy/ExpensiveObject.java, core-java/src/test/java/com/baeldung/designpatterns/AdapterPatternIntegrationTest.java, core-java/src/test/java/com/baeldung/designpatterns/BridgePatternIntegrationTest.java, core-java/src/test/java/com/baeldung/designpatterns/DecoratorPatternIntegrationTest.java
Made changes as per the last review.
=> BAEL-1072 Difference between Proxy, Decorator, Adapter, and Bridge Patterns

vavr/pom.xml, vavr/src/test/java/com/baeldung/vavr/collections/CollectionFactoryMethodsTest.java, vavr/src/test/java/com/baeldung/vavr/collections/CollectionFactoryMethodsUnitTest.java
Changed the version of vavr dependency to 0.9.1
=> author: ignaciogallego@gmail.com article:Collection Factory Methods for Vavr

libraries/src/test/java/com/baeldung/commons/collections4/BagTests.java
This is my PR for the JIRA task: BAEL-962 and the article on Apache Bags
=> Code examples for the article on Apache bags

spring-5/src/main/java/com/baeldung/jsonb/Person.java, spring-5/src/main/java/com/baeldung/jsonb/PersonController.java, spring-5/src/test/java/com/baeldung/jsonb/JsonbIntegrationTest.java, spring-5/src/test/java/com/baeldung/jsonb/JsonbTest.java
Update Person class to use property "id" like identifier. (BAEL-1121)
=> Update Person class to use property "id" like identifier. (BAEL-1121) 

metrics/pom.xml, metrics/src/test/java/com/baeldung/metrics/micrometer/MicrometerAtlasTest.java
according to @pivovarit 's note, extracted complex collectors to separate methods and updated the micrometer dependency version to the latest release.
=> BAEL-1064 extract collectors and update micrometer dependency version

mockito/src/test/java/org/baeldung/mockito/MockitoVoidMethodsTest.java, mockito/src/test/java/org/baeldung/mockito/MyList.java
PR for Mockito void tutorials.
=> BAEL-1195 - Add Mockito tutorial for void methods

libraries/pom.xml, libraries/src/main/java/com/baeldung/jdo/query/MyApp.java, libraries/src/main/java/com/baeldung/jdo/query/ProductItem.java, libraries/src/main/resources/META-INF/package.jdo
MyApp.java class
ProductItem.java class
modify:
package.jdo to add a named query
pom.xml to add datanucleus-jdo-query.jar
=> Intro to JDO Queries 2/2 article

guest/spring-mvc/src/main/java/com/forketyfork/guest/springmvc/web/InternalsController.java, guest/spring-mvc/src/main/java/com/forketyfork/guest/springmvc/web/MyInputResource.java, guest/spring-mvc/src/main/java/com/forketyfork/guest/springmvc/web/MyOutputResource.java, guest/spring-mvc/src/main/java/com/forketyfork/guest/springmvc/web/RestfulWebServiceController.java
Added examples for a RESTful controller.
=> BAEL-1221: How Spring MVC Really Works

hibernate5/pom.xml, hibernate5/src/main/java/com/baeldung/hibernate/HibernateMultiTenantUtil.java, hibernate5/src/main/java/com/baeldung/hibernate/HibernateUtil.java, hibernate5/src/main/java/com/baeldung/hibernate/pojo/Employee.java, hibernate5/src/main/java/com/baeldung/hibernate/pojo/EntityDescription.java, hibernate5/src/main/java/com/baeldung/hibernate/pojo/Phone.java, hibernate5/src/main/java/com/baeldung/hibernate/pojo/package-info.java, hibernate5/src/test/java/com/baeldung/hibernate/DynamicMappingIntegrationTest.java, hibernate5/src/test/java/com/baeldung/hibernate/DynamicMappingTest.java, hibernate5/src/test/resources/hibernate-multitenancy.properties
=> BAEL-1280: Mapping Dynamic Values (@Formula, @Filter, @Any, @Where)

ejb/wildfly/wildfly-jpa/src/main/resources/META-INF/persistence.xml, ejb/wildfly/wildfly-jpa/src/main/resources/data.sql
=> BAEL-624 How to setup WildFly

core-java/templatemethodpattern/src/main/java/com/baeldung/templatemethodpattern/application/Application.java, core-java/templatemethodpattern/src/main/java/com/baeldung/templatemethodpattern/model/Computer.java, core-java/templatemethodpattern/src/main/java/com/baeldung/templatemethodpattern/model/HighEndComputer.java, core-java/templatemethodpattern/src/main/java/com/baeldung/templatemethodpattern/model/StandardComputer.java, core-java/templatemethodpattern/src/test/java/com/baeldung/templatemethodpatterntest/TemplateMethodPatternTest.java
This PR belongs to http://jira.baeldung.com/browse/BAEL-1289
=> Implementing the Template Method Pattern in Java - BAEL-1289

junit5/src/main/java/com/baeldung/junit5/Greetings.java, junit5/src/main/java/com/baeldung/junit5/mockito/Greetings.java, junit5/src/test/java/com/baeldung/GreetingsTest.java
Article in progress:
http://inprogress.baeldung.com/wp-admin/post.php?post=59988&action=edit
=> @RunWith in JUnit5

ejb/wildfly/widlfly-web/src/main/java/TestEJBServlet.java
=> [BAEL-624] list of users in servlet

guest/spring-mvc/README.md, hibernate5/src/main/java/com/baeldung/hibernate/HibernateUtil.java, hibernate5/src/main/java/com/baeldung/hibernate/pojo/TemporalValues.java, hibernate5/src/test/java/com/baeldung/hibernate/TemporalValuesTest.java
Added README.md with build and run instructions.
=> BAEL-1221: Added README.md with build and run instructions

spring-aop/src/main/java/org/baeldung/performancemonitor/AopConfiguration.java
Now pointcuts work and AopConfiguration starts.
Thx for your example
=> Fixed error on AopConfiguration

hibernate5/src/main/java/com/baeldung/hibernate/HibernateUtil.java, hibernate5/src/main/java/com/baeldung/hibernate/pojo/TemporalValues.java, hibernate5/src/test/java/com/baeldung/hibernate/TemporalValuesTest.java
Code samples for the article "Mapping Date and Time Values in Hibernate"
=> BAEL-1281: Hibernate - Mapping Date/Time values

spring-boot-admin/pom.xml, spring-boot-admin/spring-boot-admin-client/pom.xml, spring-boot-admin/spring-boot-admin-server/pom.xml
@maibin hope this fixes the problem.
=> spring-boot-admin module

pom.xml, spring-rest-embedded-tomcat/pom.xml, spring-rest-embedded-tomcat/src/main/java/org/baeldung/embedded/configuration/AppInitializer.java, spring-rest-embedded-tomcat/src/main/java/org/baeldung/embedded/configuration/UserConfiguration.java, spring-rest-embedded-tomcat/src/main/java/org/baeldung/embedded/controller/UserController.java, spring-rest-embedded-tomcat/src/main/java/org/baeldung/embedded/domain/User.java, spring-rest-embedded-tomcat/src/main/java/org/baeldung/embedded/service/UserService.java, spring-rest-embedded-tomcat/src/test/java/org/baeldung/embedded/EmbeddedTomcatApp.java, spring-rest-embedded-tomcat/src/test/java/org/baeldung/embedded/EmbeddedTomcatRunner.java, spring-rest-embedded-tomcat/src/test/java/org/baeldung/embedded/UserIntegrationTest.java
Draft ready for Editor's review. 
Link to draft article: http://inprogress.baeldung.com/wp-admin/post.php?post=60478&action=edit
=> BAEL-1267 spring rest project through tomcat created in java

guest/spring-security/README.md, guest/spring-security/pom.xml, guest/spring-security/src/main/java/com/stackify/guest/springsecurity/Application.java, guest/spring-security/src/main/java/com/stackify/guest/springsecurity/config/WebMvcConfiguration.java, guest/spring-security/src/main/java/com/stackify/guest/springsecurity/config/WebSecurityConfig.java, guest/spring-security/src/main/resources/data.sql, guest/spring-security/src/main/resources/schema.sql, guest/spring-security/src/main/resources/static/css/styles.css, guest/spring-security/src/main/resources/templates/customLogin.html, guest/spring-security/src/main/resources/templates/index.html
Source code for the article "Hit the Ground Running with the Spring Security Java Configuration".
=> BAEL-1222: Hit the Ground Running with the Spring Security Java Configuration

ejb/wildfly/widlfly-web/src/main/java/TestEJBServlet.java
Format the Servlet EJBTest and remove serialVersionUID from code.
=> BAEL-624: Formating code

spring-jpa/src/main/java/org/baeldung/sqlfiles/Country.java, spring-jpa/src/main/resources/data.sql, spring-jpa/src/main/resources/schema.sql, spring-jpa/src/main/resources/sqlfiles.properties
Quick Guide on Data.sql and Schema.sql Files in Spring
=> BAEL-1319 Quick Guide on Data.sql and Schema.sql Files in Spring

patterns/template-method/src/main/java/com/baeldung/templatemethodpattern/model/Computer.java, patterns/template-method/src/main/java/com/baeldung/templatemethodpattern/model/ComputerBuilder.java, patterns/template-method/src/main/java/com/baeldung/templatemethodpattern/model/HighEndComputer.java, patterns/template-method/src/main/java/com/baeldung/templatemethodpattern/model/StandardComputer.java, patterns/template-method/src/test/java/com/baeldung/templatemethodpatterntest/TemplateMethodPatternTest.java
Reverts eugenp/tutorials#3038
Does not build.
Is not a module of the patterns parent
=> Revert "Implementing the Template Method Pattern with Java - BAEL-1289"

ejb/wildfly/widlfly-web/src/main/java/TestEJBServlet.java
added simple print out in servlet.
=> [BAEL-624]: simple printing in servlet

spring-5/pom.xml, spring-5/src/main/java/com/baeldung/SpringSecurity5Application.java, spring-5/src/main/java/com/baeldung/security/GreetController.java, spring-5/src/main/java/com/baeldung/security/GreetService.java, spring-5/src/main/java/com/baeldung/security/SecurityConfig.java, spring-5/src/main/resources/application.properties, spring-5/src/test/java/com/baeldung/security/SecurityTest.java, spring-5/src/test/java/com/baeldung/web/client/WebTestClientTest.java
=> BAEL-1311: Spring Security 5 - Security for Reactive Applications

spring-cloud/pom.xml, spring-cloud/spring-cloud-aws/README.md, spring-cloud/spring-cloud-aws/pom.xml, spring-cloud/spring-cloud-aws/src/main/java/com/baeldung/spring/cloud/aws/SpringCloudAwsApplication.java, spring-cloud/spring-cloud-aws/src/main/java/com/baeldung/spring/cloud/aws/config/SpringCloudAwsConfig.java, spring-cloud/spring-cloud-aws/src/main/java/com/baeldung/spring/cloud/aws/s3/SpringCloudS3.java, spring-cloud/spring-cloud-aws/src/main/java/com/baeldung/spring/cloud/aws/sns/SNSEndpointController.java, spring-cloud/spring-cloud-aws/src/main/java/com/baeldung/spring/cloud/aws/sns/SNSMessageSender.java, spring-cloud/spring-cloud-aws/src/main/java/com/baeldung/spring/cloud/aws/sqs/SpringCloudSQS.java, spring-cloud/spring-cloud-aws/src/main/resources/application.properties, spring-cloud/spring-cloud-aws/src/test/java/com/baeldung/spring/cloud/aws/SpringCloudAwsTestUtil.java, spring-cloud/spring-cloud-aws/src/test/java/com/baeldung/spring/cloud/aws/rds/SpringCloudRDSIntegrationTest.java, spring-cloud/spring-cloud-aws/src/test/java/com/baeldung/spring/cloud/aws/s3/SpringCloudS3IntegrationTest.java, spring-cloud/spring-cloud-aws/src/test/java/com/baeldung/spring/cloud/aws/sns/SNSEndpointControllerUnitTest.java, spring-cloud/spring-cloud-aws/src/test/java/com/baeldung/spring/cloud/aws/sns/SpringCloudSNSIntegrationTest.java, spring-cloud/spring-cloud-aws/src/test/java/com/baeldung/spring/cloud/aws/sqs/Greeting.java, spring-cloud/spring-cloud-aws/src/test/java/com/baeldung/spring/cloud/aws/sqs/SpringCloudSQSIntegrationTest.java, spring-cloud/spring-cloud-aws/src/test/resources/application-test.properties
Adding the module spring-cloud-aws for the Article BAEL-1173 - A Quick Guide to Spring Cloud AWS
=> BAEL-1173 - Add spring-cloud-aws module

core-java-8/src/main/java/com/baeldung/annotations/ClassWithAnnotation.java, core-java-8/src/main/java/com/baeldung/annotations/ClassWithDeprecatedMethod.java, core-java-8/src/main/java/com/baeldung/annotations/ClassWithSafeVarargs.java, core-java-8/src/main/java/com/baeldung/annotations/ClassWithSuppressWarnings.java, core-java-8/src/main/java/com/baeldung/annotations/IntConsumer.java, core-java-8/src/main/java/com/baeldung/annotations/Interval.java, core-java-8/src/main/java/com/baeldung/annotations/IntervalUsage.java, core-java-8/src/main/java/com/baeldung/annotations/Intervals.java, core-java-8/src/main/java/com/baeldung/annotations/MyAnnotation.java, core-java-8/src/main/java/com/baeldung/annotations/MyAnnotationTarget.java, core-java-8/src/main/java/com/baeldung/annotations/MyOperation.java, core-java-8/src/main/java/com/baeldung/annotations/MyOperationImpl.java
=> adding built-in java annotation examples

core-java/src/main/java/com/baeldung/loops/LoopsInJava.java, core-java/src/test/java/com/baeldung/loops/WhenUsingLoops.java
Hi @pivovarit this can be reviewed now. Kindly let me know in case of any concerns.
=> BAEL-1305: A Simple Guide to Java Loops.

osgi/pom.xml
IP: http://inprogress.baeldung.com/?p=58078&preview=true
Jira: http://jira.baeldung.com/browse/BAEL-728
https://github.com/eugenp/tutorials/pull/3141
=> BAEL-728: upgraded to OSGi 6.0.0 & maven-bundle-plugin 3.3.0

apache-poi/src/main/java/com/baeldung/poi/powerpoint/PowerPointHelper.java, apache-poi/src/test/java/com/baeldung/poi/powerpoint/PowerPointIntegrationTest.java
Code sample for the create/alter of a Microsoft PowerPoint presentation.
=> Apache POI PowerPoint

guest/remote-debugging/README.md, guest/remote-debugging/pom.xml, guest/remote-debugging/src/main/java/com/stackify/debug/JavaRemoteDebuggingApplication.java, guest/remote-debugging/src/main/java/com/stackify/debug/config/WebInitializer.java, guest/remote-debugging/src/main/java/com/stackify/debug/rest/HelloController.java
=> BAEL-1128: A Practical Guide to Java Remote Debugging

core-java/src/main/java/com/baeldung/array/ArrayBenchmarkRunner.java, core-java/src/main/java/com/baeldung/array/SearchArrayTest.java
Changes for array search benchmarks.
=> BAEL-1374 - use JMH. Move out of test area.

core-java/src/main/java/com/baeldung/interfaces/CommaSeparatedCustomers.java, core-java/src/main/java/com/baeldung/interfaces/Customer.java, core-java/src/test/java/com/baeldung/interfaces/InnerInterfaceTests.java
Code samples for inner interfaces tutorial.
=> BAEL-1378 inner interface examples added

core-java-8/src/test/java/com/baeldung/stringjoiner/StringJoinerUnitTest.java
http://jira.baeldung.com/browse/BAEL-1340
=> PR for BAEL-1340 - Java StringJoiner class

core-java/src/test/java/com/baeldung/threadlocalrandom/ThreadLocalRandomTest.java
This pull request contains BDD style tests for generating random values using ThreadLocalRandom
=> BAEL-1422 Guide to ThreadLocalRandom in Java [tarangbhalodia@gmail.com]

jenkins/hello-world/pom.xml, jenkins/hello-world/src/main/java/com/baeldung/jenkins/helloworld/ProjectStats.java, jenkins/hello-world/src/main/java/com/baeldung/jenkins/helloworld/ProjectStatsBuildWrapper.java, jenkins/hello-world/src/main/resources/stats.html
A sample Jenkins plugin which
builds basic project stats
=> BAEL-1451 Writing a Jenkins plugin

influxdb/src/test/java/com/baeldung/influxdb/InfluxDBConnectionLiveTest.java, persistence-modules/redis/README.md, persistence-modules/redis/pom.xml, persistence-modules/redis/src/test/java/com/baeldung/LettuceIntegrationLiveTest.java
Code for Lettuce tutorial. Added a missing quote in a comment in InfluxDb code.
=> Bael-1364 - Introduction to Lettuce

spring-cloud/spring-cloud-zuul-eureka-integration/eureka-client/src/main/java/com/baeldung/spring/cloud/eureka/client/EurekaClientApplication.java, spring-cloud/spring-cloud-zuul-eureka-integration/eureka-client/src/main/resources/application.yml
BAEL-1357 : Added port number to response to show how load balancing works with Zuul
=> Added port number to response - BAEL-1357

guest/deep-jsf/README.md, guest/deep-jsf/pom.xml, guest/deep-jsf/src/main/java/com/stackify/deepjsf/GreetControllerBean.java, guest/deep-jsf/src/main/java/com/stackify/deepjsf/PhaseListenerBean.java, guest/deep-jsf/src/main/java/com/stackify/deepjsf/UserBean.java, guest/deep-jsf/src/main/java/com/stackify/deepjsf/UserControllerBean.java, guest/deep-jsf/src/main/webapp/WEB-INF/faces-config.xml, guest/deep-jsf/src/main/webapp/greet.xhtml, guest/deep-jsf/src/main/webapp/hello.xhtml, guest/deep-jsf/src/main/webapp/index.xhtml, guest/deep-jsf/src/main/webapp/register.xhtml
=> BAEL-1414 Learn to Fully Leverage Java Server Faces

core-java-concurrency/src/main/java/com/baeldung/concurrent/waitandnotify/Data.java, core-java-concurrency/src/main/java/com/baeldung/concurrent/waitandnotify/Receiver.java, core-java-concurrency/src/main/java/com/baeldung/concurrent/waitandnotify/Sender.java, core-java-concurrency/src/test/java/com/baeldung/concurrent/waitandnotify/NetworkIntegrationTest.java
Logged InterruptedException instead of ignoring it
=> BAEL-1327 Java Threads: notify and wait

guava/src/main/java/org/baeldung/guava/memoizer/CostlySupplier.java, guava/src/main/java/org/baeldung/guava/memoizer/Factorial.java, guava/src/main/java/org/baeldung/guava/memoizer/FibonacciSequence.java, guava/src/test/java/org/baeldung/guava/GuavaMemoizerUnitTest.java
Sample codes for Guava Memoizer article.
=> BAEL-1464 Guava Memoizer

guava/src/test/java/org/baeldung/guava/GuavaMemoizerUnitTest.java
=> BAEL-1464 Guava Memoizer (2)

influxdb/README.md, influxdb/src/test/java/com/baeldung/influxdb/InfluxDBConnectionLiveTest.java, jgroups/README.md, jgroups/pom.xml, jgroups/src/main/java/com/baeldung/jgroups/JGroupsMessenger.java, jgroups/src/main/resources/udp.xml, pom.xml
=> BAEL-1486 - sample code for JGroups. Fixed a typo in InfluxDB.

hibernate5/src/main/java/com/baeldung/hibernate/HibernateUtil.java, hibernate5/src/main/java/com/baeldung/hibernate/converters/PersonNameConverter.java, hibernate5/src/main/java/com/baeldung/hibernate/pojo/Person.java, hibernate5/src/main/java/com/baeldung/hibernate/pojo/PersonName.java, hibernate5/src/test/java/com/baeldung/hibernate/converter/PersonNameConverterTest.java
IP: http://inprogress.baeldung.com/wp-admin/post.php?post=72981&action=edit
=> BAEL-1509 - JPA  Attribute Converters

spring-batch/pom.xml, spring-batch/src/main/java/org/baeldung/taskletsvschunks/chunks/LineProcessor.java, spring-batch/src/main/java/org/baeldung/taskletsvschunks/chunks/LineReader.java, spring-batch/src/main/java/org/baeldung/taskletsvschunks/chunks/LinesWriter.java, spring-batch/src/main/java/org/baeldung/taskletsvschunks/model/Line.java, spring-batch/src/main/java/org/baeldung/taskletsvschunks/tasklets/LinesProcessor.java, spring-batch/src/main/java/org/baeldung/taskletsvschunks/tasklets/LinesReader.java, spring-batch/src/main/java/org/baeldung/taskletsvschunks/tasklets/LinesWriter.java, spring-batch/src/main/java/org/baeldung/taskletsvschunks/utils/FileUtils.java, spring-batch/src/main/resources/logback.xml, spring-batch/src/main/resources/taskletsvschunks/chunks.xml, spring-batch/src/main/resources/taskletsvschunks/input/tasklets-vs-chunks.csv, spring-batch/src/main/resources/taskletsvschunks/tasklets.xml, spring-batch/src/test/java/org/baeldung/taskletsvschunks/chunks/ChunksTest.java, spring-batch/src/test/java/org/baeldung/taskletsvschunks/tasklets/TaskletsTest.java
=> Bael 1543 2

spring-batch/src/main/resources/logback.xml
@lor6 please review. Sorry I missed this!
=> BAEL-1543: Logging to console instead of file.

libraries/src/main/resources/Greeting.sol
Adding solidity smart contract.
Article "Creating Smart Contracts with Solidity" - BAEL-1460
=> Adding solidity example file

core-java/src/test/java/com/baeldung/string/StringComparisonTest.java
example for different ways of comparing strings in Java.
=> BAEL-1526 : Comparing strings in Java

persistence-modules/spring-data-dynamodb/pom.xml, persistence-modules/spring-data-dynamodb/src/test/java/com/baeldung/spring/data/dynamodb/repository/ProductInfoRepositoryIntegrationTest.java, persistence-modules/spring-data-dynamodb/src/test/java/com/baeldung/spring/data/dynamodb/repository/rule/LocalDbCreationRule.java
=> BAEL-681 (2)

spring-mvc-kotlin/pom.xml, spring-mvc-kotlin/src/main/kotlin/com/baeldung/kotlin/jpa/Person.kt, spring-mvc-kotlin/src/test/kotlin/com/baeldung/kotlin/jpa/HibernateKotlinIntegrationTest.kt, spring-mvc-kotlin/src/test/resources/hibernate.properties
Sample code for BAEL-1159 - Working with Kotlin and JPA - earth001@gmail.com
=> Sample code for BAEL-1159 - Working with Kotlin and JPA - earth001@gmail.com

guava/README.md
Add link to Guava Memoizer article
=> BAEL-1464-README

hibernate5/src/main/java/com/baeldung/hibernate/converters/PersonNameConverter.java, hibernate5/src/test/java/com/baeldung/hibernate/converter/PersonNameConverterTest.java
IP: http://inprogress.baeldung.com/wp-admin/post.php?post=72981&action=edit
=> BAEL-1509 jpa attribute converters

spring-5/pom.xml
* updated spring boot dependency to 2.0.0.RELEASE
* tidied up pom.xml
=> BAEL-1533 session attributes in spring mvc

testing-modules/mockito/pom.xml, testing-modules/mockito/src/test/java/org/baeldung/hamcrest/HamcrestNumberUnitTest.java
@eugenp @pivovarit please review.
=> Bael 1580 2

rxjava/src/test/java/com/baeldung/rxjava/MaybeTest.java
Accompanying sample code for RxJava Maybe mini-article.
=> RxJava Maybe samples added.

testing-modules/mockito/src/main/java/org/baeldung/hamcrest/City.java, testing-modules/mockito/src/main/java/org/baeldung/hamcrest/Location.java, testing-modules/mockito/src/test/java/org/baeldung/hamcrest/HamcrestBeansUnitTest.java, testing-modules/mockito/src/test/java/org/baeldung/hamcrest/HamcrestObjectUnitTest.java
=> BAEL-1578: Hamcrest Object and Beans matchers.

rxjava/src/test/java/com/baeldung/rxjava/combine/ObservableCombineUnitTest.java
* Simplified examples and lambda expressions
=> BAEL-1510 - RxJava - Combining Observables

spring-ejb/pom.xml, spring-ejb/singleton-ejb-bean/pom.xml, spring-ejb/singleton-ejb-bean/src/main/java/com/baeldung/singletonbean/CountryState.java, spring-ejb/singleton-ejb-bean/src/main/java/com/baeldung/singletonbean/CountryStateCacheBean.java, spring-ejb/singleton-ejb-bean/src/test/java/com/baeldung/singletonbean/CountryStateCacheBeanTest.java
Code for BAEL-717: Singleton EJB Bean.
=> BAEL - 717 : Singleton EJB Beans.

core-java-8/src/test/java/com/baeldung/internationalization/NumbersCurrenciesFormattingUnitTest.java
BigDecimal for currency formatting.
=> BAEL-1600 Internationalization in Java 8

libraries/pom.xml, libraries/src/main/java/com/baeldung/jnats/NatsClient.java, libraries/src/test/java/com/baeldung/jnats/NatsClientLiveTest.java
Using Nats Java Client to Publish and Receive Messages
=> BAEL-1545 - Nats Tutorial

spring-boot-cli/README.md, spring-boot-cli/bash/groovy.sh, spring-boot-cli/bash/setup.sh, spring-boot-cli/groovy/data/DataConfig.groovy, spring-boot-cli/groovy/security/Security.groovy, spring-boot-cli/groovy/test/Test.groovy, spring-boot-cli/groovy/yml/Application.groovy, spring-boot-cli/groovy/yml/config/application.yml, spring-cloud-cli/install.sh
Also an improved installation script for Spring Cloud CLI using SDKMAN.
=> BAEL-1635: Spring Boot CLI

core-kotlin/src/main/kotlin/com/baeldung/filesystem/FileReader.kt, core-kotlin/src/test/kotlin/com/baeldung/filesystem/FileReaderTest.kt, core-kotlin/src/test/resources/Kotlin.in
http://jira.baeldung.com/browse/BAEL-1676
=> [BAEL-1676] Kotlin Read from File

spring-5-security/pom.xml, spring-5-security/src/main/java/com/baeldung/passwordstorage/PasswordStorageWebSecurityConfigurer.java
Minor code changes for the examples.
=> BAEL-1489: Password storage in Spring Security 5

testing-modules/mockito/src/main/java/org/baeldung/hamcrest/custommatchers/IsDivisibleBy.java, testing-modules/mockito/src/main/java/org/baeldung/hamcrest/custommatchers/IsOnlyDigits.java, testing-modules/mockito/src/test/java/org/baeldung/hamcrest/HamcrestCustomUnitTest.java
@maibin @pivovarit please review.
=> BAEL-1579: Renaming custom matcher and handling corner case.

spring-boot/src/main/java/com/baeldung/bootcustomfilters/SpringBootFiltersApplication.java, spring-boot/src/main/java/com/baeldung/bootcustomfilters/controller/UserController.java, spring-boot/src/main/java/com/baeldung/bootcustomfilters/filters/RequestResponseLoggingFilter.java, spring-boot/src/main/java/com/baeldung/bootcustomfilters/filters/TransactionFilter.java, spring-boot/src/main/java/com/baeldung/bootcustomfilters/model/User.java
A few additional config if required would be 
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
=> Added the code snippets 

spring-5/src/main/java/com/baeldung/assertions/Car.java, spring-5/src/main/java/com/baeldung/assertions/CarBattery.java
=> BAEL-1645 fix

spring-5-reactive/src/main/java/com/baeldung/reactive/filters/ExampleHandlerFilterFunction.java, spring-5-reactive/src/main/java/com/baeldung/reactive/filters/ExampleWebFilter.java, spring-5-reactive/src/main/java/com/baeldung/reactive/filters/PlayerHandler.java, spring-5-reactive/src/main/java/com/baeldung/reactive/filters/PlayerRouter.java, spring-5-reactive/src/main/java/com/baeldung/reactive/filters/UserController.java, spring-5-reactive/src/test/java/com/baeldung/reactive/filters/PlayerHandlerTest.java, spring-5-reactive/src/test/java/com/baeldung/reactive/filters/UserControllerTest.java
PR for [this article](http://inprogress.baeldung.com/?p=72093&preview=true).
=> BAEL-1505: Spring WebFlux Filters Refatoring

core-java/src/main/java/com/baeldung/assertion/Assertion.java
Make sure to run with _-ea_ to enable assertions.
=> Demonstration of Java assert

spring-boot/src/main/java/com/baeldung/servletinitializer/WarInitializerApplication.java, spring-boot/src/test/java/com/baeldung/servletinitializer/WarInitializerApplicationTest.java
BAEL-1624
A Quick Intro to the SpringBootServletInitializer, extension of  WebApplicationInitializer needed to run Spring Boot app from a war deployment.
=> A Quick Intro to the SpringBootServletInitializer

autovalue/pom.xml, autovalue/src/main/java/com/baeldung/autofactory/App.java, autovalue/src/main/java/com/baeldung/autofactory/CustomStorage.java, autovalue/src/main/java/com/baeldung/autofactory/custom/AbstractFactory.java, autovalue/src/main/java/com/baeldung/autofactory/custom/CustomPhone.java, autovalue/src/main/java/com/baeldung/autofactory/custom/SmartPhone.java, autovalue/src/main/java/com/baeldung/autofactory/model/Camera.java, autovalue/src/main/java/com/baeldung/autofactory/model/ClassicPhone.java, autovalue/src/main/java/com/baeldung/autofactory/model/Phone.java, autovalue/src/main/java/com/baeldung/autofactory/modules/SonyCameraModule.java, autovalue/src/main/java/com/baeldung/autofactory/provided/IntermediateAssembler.java, autovalue/src/main/java/com/baeldung/autofactory/provider/SonyCameraProvider.java, spring-all/src/main/java/org/baeldung/order/Average.java, spring-all/src/main/java/org/baeldung/order/Excellent.java, spring-all/src/main/java/org/baeldung/order/Good.java, spring-all/src/main/java/org/baeldung/order/Rating.java, spring-all/src/test/java/org/baeldung/order/RatingRetrieverTest.java, spring-all/src/test/java/org/baeldung/order/RatingRetrieverUnitTest.java
Changes related to @Order annotation guide.
=> tinoymthms@gmail.com

core-kotlin/src/main/kotlin/com/baeldung/filesystem/FileWriter.kt, core-kotlin/src/test/kotlin/com/baeldung/filesystem/FileWriterTest.kt
http://jira.baeldung.com/browse/BAEL-1675
=> [BAEL-1675] Write to a File in Kotlin

logging-modules/README.md, logging-modules/logback/src/test/java/com/baeldung/logback/LogbackTests.java, logging-modules/logback/src/test/resources/logback-guide.xml
=> BAEL-1710 - A Guide to Logback

mapstruct/src/main/java/com/baeldung/dto/TransactionDTO.java, mapstruct/src/main/java/com/baeldung/entity/Transaction.java, mapstruct/src/main/java/com/baeldung/mapper/TransactionMapper.java
* Added POJO,
* Added DTO,
* Added Mapper
=> Add sources for BAEL-468

hibernate5/src/main/java/com/baeldung/hibernate/HibernateUtil.java, hibernate5/src/main/java/com/baeldung/hibernate/pessimisticlocking/Address.java, hibernate5/src/main/java/com/baeldung/hibernate/pessimisticlocking/Customer.java, hibernate5/src/main/java/com/baeldung/hibernate/pessimisticlocking/Individual.java, hibernate5/src/main/java/com/baeldung/hibernate/pessimisticlocking/PessimisticLockingCourse.java, hibernate5/src/main/java/com/baeldung/hibernate/pessimisticlocking/PessimisticLockingEmployee.java, hibernate5/src/main/java/com/baeldung/hibernate/pessimisticlocking/PessimisticLockingStudent.java, hibernate5/src/test/java/com/baeldung/hibernate/pessimisticlocking/BasicPessimisticLockingIntegrationTest.java, hibernate5/src/test/java/com/baeldung/hibernate/pessimisticlocking/PessimisticLockScopesIntegrationTest.java, hibernate5/src/test/resources/hibernate-pessimistic-locking.properties, persistence-modules/spring-data-eclipselink/src/main/java/com/baeldung/eclipselink/springdata/pessimisticlocking/Address.java, persistence-modules/spring-data-eclipselink/src/main/java/com/baeldung/eclipselink/springdata/pessimisticlocking/Course.java, persistence-modules/spring-data-eclipselink/src/main/java/com/baeldung/eclipselink/springdata/pessimisticlocking/Customer.java, persistence-modules/spring-data-eclipselink/src/main/java/com/baeldung/eclipselink/springdata/pessimisticlocking/Employee.java, persistence-modules/spring-data-eclipselink/src/main/java/com/baeldung/eclipselink/springdata/pessimisticlocking/Individual.java, persistence-modules/spring-data-eclipselink/src/main/java/com/baeldung/eclipselink/springdata/pessimisticlocking/Student.java, persistence-modules/spring-data-eclipselink/src/main/resources/application.properties, persistence-modules/spring-data-eclipselink/src/test/java/com/baeldung/eclipselink/springdata/pessimisticlocking/PessimisticLockScopesIntegrationTest.java
=> BAEL-1713: Pessimistic Locking in JPA

vavr/src/test/java/com/baeldung/vavr/interoperability/CollectionsInteroperabilityUnitTest.java
=> BAEL-998:- Java Vavr interoperability

pom.xml, spring-boot-tomcat/pom.xml, spring-boot-tomcat/src/main/java/com/baeldung/springbootsimple/SpringBootTomcatApplication.java, spring-boot-tomcat/src/main/java/com/baeldung/springbootsimple/TomcatController.java, spring-boot-tomcat/src/test/java/com/baeldung/springbootsimple/SpringBootTomcatApplicationTests.java
PR for the code at http://inprogress.baeldung.com/?p=85565&preview=true
- Adds a new project for spring-boot-tomcat setup
=> BAEL-1696 Initial setup in a workable state

vavr/src/test/java/com/baeldung/vavr/interoperability/CollectionsInteroperabilityUnitTest.java
Changes suggested for BAEL-998
=> Changes for suggestions on BAEL-998

spring-rest/src/main/java/org/baeldung/interceptors/RestTemplateLoggingInterceptor.java
=> Review comments incorporated - BAEL 1756

core-java/src/main/java/com/baeldung/nan/NaNExample.java
=> Nan in Java

core-java/src/main/java/com/baeldung/loops/InfiniteLoops.java
Link to the article - http://inprogress.baeldung.com/?p=88127&preview=true
Link to the Jira ticket - http://jira.baeldung.com/browse/BAEL-1796
@thombergs Please have a look.
=> [BAEL-1796] Infinite loop using Java

core-java-8/src/test/java/com/baeldung/hashtable/HashtableUnitTest.java
=> BAEL-1736 fix

core-java/src/main/java/com/baeldung/extension/Extension.java, core-java/src/test/java/com/baeldung/extension/ExtensionTest.java
Add three methods to find file extension:
1. Using Apache Commons IO Library
2. Using String Handler
3. Using Guava Library
=> BAEL-1734 add different methods to find file extension

core-java-collections/src/main/java/com/baeldung/java/iterable/IterableSize.java, core-java-collections/src/test/java/com/baeldung/java/iterable/IterableSizeTest.java
http://jira.baeldung.com/browse/BAEL-1775
=> [BAEL-1775] Getting size of Iterable in Java

spring-thymeleaf/src/main/java/com/baeldung/thymeleaf/controller/BookController.java, spring-thymeleaf/src/main/java/com/baeldung/thymeleaf/model/Book.java, spring-thymeleaf/src/main/java/com/baeldung/thymeleaf/model/Page.java, spring-thymeleaf/src/main/java/com/baeldung/thymeleaf/utils/BookUtils.java, spring-thymeleaf/src/main/resources/messages_en.properties, spring-thymeleaf/src/main/webapp/WEB-INF/views/home.html, spring-thymeleaf/src/main/webapp/WEB-INF/views/listBooks.html
=> BAEL-1793 Spring with Thymeleaf Pagination for a List

README.md, core-java-8/README.md, core-java-9/README.md, core-java/README.md, javax-servlets/README.md, msf4j/README.md, patterns/design-patterns/README.md, performance-tests/README.md, spring-5-reactive/README.md, spring-boot-ops/README.md, spring-core/README.md, spring-data-rest-querydsl/README.md, spring-mockito/README.md, spring-mvc-java/README.md, testing-modules/junit-5/README.md
Full details of 15 commits
1. https://github.com/eugenp/tutorials/tree/master/spring-boot-ops - add 7 links
http://www.baeldung.com/spring-boot-dependency-management-custom-parent
http://www.baeldung.com/spring-mvc-custom-data-binder
http://www.baeldung.com/deployable-fat-jar-spring-boot
http://www.baeldung.com/maven-webjars
http://www.baeldung.com/spring-boot-starters 
http://www.baeldung.com/maven-wrapper
http://www.baeldung.com/spring-boot-shutdown
2. https://github.com/eugenp/tutorials - add 1 link
http://www.baeldung.com/design-a-user-friendly-java-library
3. https://github.com/eugenp/tutorials/tree/master/msf4j - fix 1 link
http://www.baeldung.com/msf4j
4. https://github.com/eugenp/tutorials/tree/master/spring-mvc-java - add 3 links …
=> Update 13 README.md and create 2 README.md

hibernate5/src/main/java/com/baeldung/hibernate/HibernateUtil.java, hibernate5/src/main/java/com/baeldung/hibernate/optimisticlocking/OptimisticLockingCourse.java, hibernate5/src/main/java/com/baeldung/hibernate/optimisticlocking/OptimisticLockingStudent.java, hibernate5/src/test/java/com/baeldung/hibernate/optimisticlocking/OptimisticLockingIntegrationTest.java
=> BAEL-1730: Optimistic Locking in JPA

spring-boot/src/main/java/com/baeldung/shutdownhooks/ShutdownHookApplication.java, spring-boot/src/main/java/com/baeldung/shutdownhooks/beans/Bean1.java, spring-boot/src/main/java/com/baeldung/shutdownhooks/beans/Bean2.java, spring-boot/src/main/java/com/baeldung/shutdownhooks/beans/Bean3.java, spring-boot/src/main/java/com/baeldung/shutdownhooks/config/ExampleServletContextListener.java, spring-boot/src/main/java/com/baeldung/shutdownhooks/config/ShutdownHookConfiguration.java
Spring shutdown callback methodologies - BAEL 1831
=> Spring shutdown callback methodologies - BAEL 1831

json-path/src/main/resources/online_store.json, json-path/src/test/java/com/baeldung/jsonpath/introduction/JsonPathUnitTest.java
Link to Article: http://inprogress.baeldung.com/?p=91625&preview=true
Link to JIRA: http://jira.baeldung.com/browse/BAEL-1631
@thombergs please review :)
=> [BAEL-1631] Count with JsonPath

core-java/src/main/java/com/baeldung/extension/Extension.java, core-java/src/test/java/com/baeldung/extension/ExtensionUnitTest.java
change method to return Optionals
=> change method to return Optionals

javax-servlets/src/main/java/com/baeldung/servlets/ErrorHandlerServlet.java, javax-servlets/src/main/java/com/baeldung/servlets/RandomErrorServlet.java, javax-servlets/src/main/webapp/WEB-INF/web.xml, javax-servlets/src/main/webapp/error-404.html, spring-boot-ops/README.MD
=> Added error handling policies for javax-servlets module

core-java-8/src/main/java/com/baeldung/datetime/UseLocalDate.java, core-java-8/src/main/java/com/baeldung/datetime/UseLocalDateTime.java, core-java-8/src/main/java/com/baeldung/datetime/UseZonedDateTime.java, core-java-8/src/test/java/com/baeldung/datetime/UseLocalDateTimeUnitTest.java, core-java-8/src/test/java/com/baeldung/datetime/UseLocalDateUnitTest.java, core-java-8/src/test/java/com/baeldung/datetime/UseZonedDateTimeUnitTest.java
Draft Article: http://inprogress.baeldung.com/?p=93931&preview=true
=> [BAEL-1899] java-core-8 Get Start and End of a Day

core-java/src/main/java/com/baeldung/datetime/DateExtractYearMonthDayIntegerValues.java, core-java/src/main/java/com/baeldung/datetime/LocalDateExtractYearMonthDayIntegerValues.java, core-java/src/main/java/com/baeldung/datetime/LocalDateTimeExtractYearMonthDayIntegerValues.java, core-java/src/main/java/com/baeldung/datetime/OffsetDateTimeExtractYearMonthDayIntegerValues.java, core-java/src/main/java/com/baeldung/datetime/ZonedDateTimeExtractYearMonthDayIntegerValues.java, core-java/src/test/java/com/baeldung/datetime/DateExtractYearMonthDayIntegerValuesUnitTest.java, core-java/src/test/java/com/baeldung/datetime/LocalDateExtractYearMonthDayIntegerValuesUnitTest.java, core-java/src/test/java/com/baeldung/datetime/LocalDateTimeExtractYearMonthDayIntegerValuesUnitTest.java, core-java/src/test/java/com/baeldung/datetime/OffsetDateTimeExtractYearMonthDayIntegerValuesUnitTest.java, core-java/src/test/java/com/baeldung/datetime/ZonedDateTimeExtractYearMonthDayIntegerValuesUnitTest.java
-Added classes to show case how to extract values from classes Date and Calendar, and LocalDate, LocalDateTime, ZonedDateTime and OffSetDateTime
-Added unit test cases for all classes
=> BAEL-1892 Get Integer Values from Date

core-kotlin/src/main/kotlin/com/baeldung/stringtemplates/Templates.kt
Created a package `package com.baeldung.stringtemplates` in the module `core-kotlin`.
The package contains just one file `Templates.kt` with the examples.
=> Code snippets for the article "Kotlin String Templates"

core-java-collections/src/main/java/com/baeldung/java/list/ReverseIterator.java, core-java-collections/src/test/java/com/baeldung/java/list/ReverseIteratorUnitTest.java
http://jira.baeldung.com/browse/BAEL-1847
The unit test doesn't do anything except invoke the methods and print the output. Thought it was better than the Main method.
=> [BAEL-1847] Iterate Backwards through a List

spring-boot/.factorypath, spring-boot/pom.xml, spring-boot/src/main/java/com/baeldung/mongodb/Application.java, spring-boot/src/test/java/com/baeldung/mongodb/ManualEmbeddedMongoDbIntegrationTest.java, spring-boot/src/test/java/com/baeldung/mongodb/MongoDbSpringIntegrationTest.java
Code samples for BAEL-1919 [Spring Boot Integration Testing with Embedded MongoDB](http://inprogress.baeldung.com/?p=92261&preview=true) article.
=> Add BAEL-1919 embedded MongoDB test samples

core-java-io/src/main/java/com/baeldung/symlink/SymLinkExample.java, core-java-io/src/test/java/com/baeldung/symlink/SymLinkExampleTest.java, core-java-io/src/test/java/com/baeldung/symlink/SymLinkExampleUnitTest.java
Code for article BAEL-1933 Java - Create symbolic links
=> BAEL-1933 Added code examples and unit tests for creating symbolic links

.gitmodules, core-java/src/main/java/com/baeldung/encrypt/FileEncrypterDecrypter.java, core-java/src/test/java/com/baeldung/encrypt/FileEncrypterDecrypterIntegrationTest.java
PR for post http://jira.baeldung.com/browse/BAEL-1930
=> [BAEL-1930] Encryption and decryption of files using JDK

spring-5-reactive/src/main/java/com/baeldung/reactive/responseheaders/controllers/ResponseHeaderController.java, spring-5-reactive/src/main/java/com/baeldung/reactive/responseheaders/filter/AddResponseHeaderWebFilter.java, spring-5-reactive/src/main/java/com/baeldung/reactive/responseheaders/functional/handlers/ResponseHeaderHandler.java, spring-5-reactive/src/main/java/com/baeldung/reactive/responseheaders/functional/routers/ResponseHeadersRouterFunctions.java, spring-5-reactive/src/test/java/com/baeldung/reactive/responseheaders/ResponseHeaderLiveTest.java, spring-rest/src/main/java/com/baeldung/responseheaders/ResponseHeadersApplication.java, spring-rest/src/main/java/com/baeldung/responseheaders/controllers/FilterResponseHeaderController.java, spring-rest/src/main/java/com/baeldung/responseheaders/controllers/ResponseHeaderController.java, spring-rest/src/main/java/com/baeldung/responseheaders/filter/AddResponseHeaderFilter.java, spring-rest/src/test/java/com/baeldung/responseheaders/ResponseHeaderLiveTest.java
Jira issue: http://jira.baeldung.com/browse/BAEL-1972
IP: http://inprogress.baeldung.com/wp-admin/post.php?post=95521&action=edit
=> [BAEL-1972] | spring-rest & spring-5-reactive | Set Header to Responses

ethereum/pom.xml
Cleaned up pom.xml - switched to BOM for better top-level management
=> BAEL-1461: POM to BOM

core-java/src/main/java/com/baeldung/exceptions/Arithmetic.java, core-java/src/main/java/com/baeldung/exceptions/ArrayIndexOutOfBounds.java, core-java/src/main/java/com/baeldung/exceptions/ClassCast.java, core-java/src/main/java/com/baeldung/exceptions/FileNotFound.java, core-java/src/main/java/com/baeldung/exceptions/GlobalExceptionHandler.java, core-java/src/main/java/com/baeldung/exceptions/IllegalArgument.java, core-java/src/main/java/com/baeldung/exceptions/IllegalState.java, core-java/src/main/java/com/baeldung/exceptions/InterruptedExceptionExample.java, core-java/src/main/java/com/baeldung/exceptions/MalformedURL.java, core-java/src/main/java/com/baeldung/exceptions/NullPointer.java, core-java/src/main/java/com/baeldung/exceptions/NumberFormat.java, core-java/src/main/java/com/baeldung/exceptions/ParseExceptionExample.java, core-java/src/main/java/com/baeldung/exceptions/StringIndexOutOfBounds.java, core-java/src/test/java/com/baeldung/exceptions/GlobalExceptionHandlerUnitTest.java
This PR is for the upcoming article BAEL-1921 - Java Global Exception Handler
=> BAEL-1921 - added example code and unit test for GlobalExceptionHandler

core-java/README.md, core-kotlin/README.md, maven-archetype/README.md, spring-boot-bootstrap/README.md, spring-boot-mvc/README.md, spring-boot-ops/README.md, spring-boot-persistence/README.MD, spring-thymeleaf/README.md, spring-webflux-amqp/README.md, testing-modules/mockito/README.md
1. Guide to the Favicon in Spring Boot
http://www.baeldung.com/spring-boot-favicon
https://github.com/eugenp/tutorials/tree/master/spring-boot-mvc - to add here
2. Thin JARs with Spring Boot
http://www.baeldung.com/spring-boot-thin-jar
https://github.com/eugenp/tutorials/tree/master/spring-boot-bootstrap - to add here
3. Guide to the java.util.Arrays Class
http://www.baeldung.com/java-util-arrays
https://github.com/eugenp/tutorials/tree/master/core-java - to add here
4. Working with Enums in Kotlin
http://www.baeldung.com/kotlin-enum
https://github.com/eugenp/tutorials/tree/master/core-kotlin - to add here
5. Spring Boot with Multiple SQL Import Files
http://www.baeldung.com/spring-boot-sql-import-files
https://github.com/eugenp/tutorials/tree/master/spring-boot-persistence - to fix link …
=> BAEL-7390 - add/fix links

core-kotlin/pom.xml, core-kotlin/src/test/kotlin/com/baeldung/kotlin/LazyUnitTest.kt, pom.xml
-Fixed test failure in core-kotlin project, include core-kotlin back in parent pom
=> BAEL-1987 Fix Tests and Compilation In All Projects

spring-security-angular/server/src/main/java/com/baeldung/springbootsecurityrest/controller/UserController.java
=> BAEL - 1916

spring-rest-hal-browser/pom.xml, spring-rest-hal-browser/src/main/java/com/baeldung/App.java, spring-rest-hal-browser/src/main/java/com/baeldung/config/DBLoader.java, spring-rest-hal-browser/src/main/java/com/baeldung/config/RestConfig.java, spring-rest-hal-browser/src/main/java/com/baeldung/data/BookRepository.java, spring-rest-hal-browser/src/main/java/com/baeldung/model/Book.java
Code for the BAEL-111 article on the HAL browser.
=> [BAEL-111] The HAL Browser with Spring REST 

spring-rest-template/.gitignore, spring-rest-template/README.md, spring-rest-template/checkstyle.xml, spring-rest-template/pom.xml, spring-rest-template/src/main/java/com/baeldung/web/upload/client/MultipartFileUploadClient.java
Spun off RestTemplate client example in separate module namely spring-rest-template
=> Added spring-rest-template module

core-java/pom.xml, core-java/src/main/java/com/baeldung/instrumentation/agent/AtmTransformer.java, core-java/src/main/java/com/baeldung/instrumentation/agent/MyInstrumentationAgent.java, core-java/src/main/java/com/baeldung/instrumentation/application/AgentLoader.java, core-java/src/main/java/com/baeldung/instrumentation/application/Launcher.java, core-java/src/main/java/com/baeldung/instrumentation/application/MyAtm.java, core-java/src/main/java/com/baeldung/instrumentation/application/MyAtmApplication.java, core-java/src/main/resources/META-INF/MANIFEST.MF, core-java/src/main/resources/log4j2.xml
To build the agent, agentLoader and the application  the core-java module needs to be executed 3 times, each time with one of the profiles buildAgentLoader,buildApplication and buildAgent.
After that we'll have the 3 required jar files and can run the example shown in the article.
=> BAEL-1728: add java instrumentation

logging-modules/log4j2/pom.xml, logging-modules/log4j2/src/main/java/com/baeldung/logging/log4j2/appender/MapAppender.java, logging-modules/log4j2/src/test/java/com/baeldung/logging/log4j2/appender/MapAppenderIntegrationTest.java, logging-modules/log4j2/src/test/resources/log4j2.xml
=> BAEL-1960: Custom appender for log4j

core-java/src/main/java/com/baeldung/logging/LogUsingSlf4J.java
Jira Ticket: BAEL-1958
http://jira.baeldung.com/browse/BAEL-1958
http://inprogress.baeldung.com/wp-admin/post.php?post=98113&action=edit
=> BAEL-1958 Log using SLF4J

libraries/.gitignore, libraries/pom.xml, libraries/src/main/java/com/baeldung/snakeyaml/Address.java, libraries/src/main/java/com/baeldung/snakeyaml/Contact.java, libraries/src/main/java/com/baeldung/snakeyaml/Customer.java, libraries/src/test/java/com/baeldung/snakeyaml/JavaToYAMLSerializationUnitTest.java, libraries/src/test/java/com/baeldung/snakeyaml/YAMLToJavaDeserialisationUnitTest.java, libraries/src/test/resources/yaml/customer.yaml, libraries/src/test/resources/yaml/customer_with_contact_details.yaml, libraries/src/test/resources/yaml/customer_with_contact_details_and_address.yaml, libraries/src/test/resources/yaml/customer_with_contact_details_and_tags.yaml, libraries/src/test/resources/yaml/customer_with_type.yaml, libraries/src/test/resources/yaml/customers.yaml, pom.xml, spring-core/src/main/java/com/baeldung/config/scope/AppConfigFunctionBean.java, spring-core/src/main/java/com/baeldung/scope/AppConfig.java, spring-core/src/main/java/com/baeldung/scope/AppProxyScopeConfig.java, spring-core/src/main/java/com/baeldung/scope/prototype/PrototypeBean.java, spring-core/src/main/java/com/baeldung/scope/singletone/SingletonFunctionBean.java, spring-core/src/test/java/com/baeldung/scope/PrototypeBeanInjectionIntegrationTest.java, spring-core/src/test/java/com/baeldung/scope/PrototypeFunctionBeanIntegrationTest.java, testing-modules/junit-abstract/pom.xml, testing-modules/junit-abstract/src/test/java/org/baeldung/testing/abstractclass/abstractmethod/AbstractMethodCallingUnitTest.java, testing-modules/junit-abstract/src/test/java/org/baeldung/testing/abstractclass/indepedentmethod/AbstractIndependentUnitTest.java, testing-modules/junit-abstract/src/test/java/org/baeldung/testing/abstractclass/instancefields/AbstractInstanceFieldsUnitTest.java, testing-modules/junit-abstract/src/test/java/org/baeldung/testing/abstractclass/privatemethod/AbstractPrivateMethodsUnitTest.java
There is still one test file that is working as per Junit 4 as there is no alternative available with Junit5.
=> Bael 1852 - Test case code is aligned to support Junit5

core-java/src/test/java/com/baeldung/array/RemoveFirstElementUnitTest.java
PR for article Remove the first element from an array
http://jira.baeldung.com/browse/BAEL-2029
I wasn't 100% sure where to put the code since it's a very simple example.
=> Example for removing first element of array (BAEL-2029)

spring-5-security/src/main/java/com/baeldung/oauth2extractors/ExtractorsApplication.java, spring-5-security/src/main/java/com/baeldung/oauth2extractors/configuration/SecurityConfig.java, spring-5-security/src/main/java/com/baeldung/oauth2extractors/extractor/custom/BaeldungAuthoritiesExtractor.java, spring-5-security/src/main/java/com/baeldung/oauth2extractors/extractor/custom/BaeldungPrincipalExtractor.java, spring-5-security/src/main/java/com/baeldung/oauth2extractors/extractor/github/GithubAuthoritiesExtractor.java, spring-5-security/src/main/java/com/baeldung/oauth2extractors/extractor/github/GithubPrincipalExtractor.java, spring-5-security/src/main/resources/application-oauth2-extractors-baeldung.properties, spring-5-security/src/main/resources/application-oauth2-extractors-github.properties, spring-5-security/src/test/java/com/baeldung/oauth2extractors/ExtractorsUnitTest.java, spring-security-sso/spring-security-sso-auth-server/src/main/java/org/baeldung/config/AuthServerConfig.java
refactor and added example using custom authorization server
=> OAuth2 Principal and Authorities example 

apache-avro/README.md, core-java-10/README.md, core-java-8/README.md, core-java-collections/README.md, core-java-concurrency/README.md, core-java/README.md, core-kotlin/README.md, ejb/README.md, jnosql/README.md, libraries-data/README.md, maven/README.md, micronaut/README.md, spring-5-reactive/README.md, spring-5/README.md, spring-all/README.md, spring-batch/README.md, spring-boot-vue/README.md, spring-boot/README.MD, spring-reactive-kotlin/README.md, spring-rest-hal-browser/README.md, spring-rest-simple/README.md, spring-rest-template/README.md, spring-security-mvc-login/README.md, spring-session/README.md, spring-session/spring-session-jdbc/README.MD
1. http://www.baeldung.com/java-runnable-callable
Runnable vs. Callable in Java
https://github.com/eugenp/tutorials/tree/master/core-java-concurrency - to add here
2. http://www.baeldung.com/spring-security-5-oauth2-login
Spring Security 5 – OAuth2 Login
https://github.com/eugenp/tutorials/tree/master/spring-5 - to add here
3. http://www.baeldung.com/maven-ignore-test-results
Build a Jar with Maven and Ignore the Test Results
https://github.com/eugenp/tutorials/tree/master/maven - to add here
4. http://www.baeldung.com/curl-rest
Test a REST API with curl
https://github.com/eugenp/tutorials/tree/master/spring-rest-simple - to add here
5. http://www.baeldung.com/jmapper
Guide to JMapper
https://github.com/eugenp/tutorials/tree/master/libraries-data - to add here
6. …
=> add/fix links - team BAEL-7962

spring-cloud/pom.xml, spring-cloud/spring-cloud-archaius/README.md, spring-cloud/spring-cloud-archaius/additional-sources-simple/pom.xml, spring-cloud/spring-cloud-archaius/additional-sources-simple/src/main/java/com/baeldung/spring/cloud/archaius/additionalsources/AdditionalSourcesSimpleApplication.java, spring-cloud/spring-cloud-archaius/additional-sources-simple/src/main/java/com/baeldung/spring/cloud/archaius/additionalsources/config/ApplicationPropertiesConfigurations.java, spring-cloud/spring-cloud-archaius/additional-sources-simple/src/main/java/com/baeldung/spring/cloud/archaius/additionalsources/controller/ConfigPropertiesController.java, spring-cloud/spring-cloud-archaius/additional-sources-simple/src/main/resources/application.properties, spring-cloud/spring-cloud-archaius/additional-sources-simple/src/main/resources/config.properties, spring-cloud/spring-cloud-archaius/additional-sources-simple/src/main/resources/other-config.properties, spring-cloud/spring-cloud-archaius/additional-sources-simple/src/test/java/com/baeldung/spring/cloud/archaius/additionalsources/ArchaiusAdditionalSourcesLiveTest.java, spring-cloud/spring-cloud-archaius/basic-config/pom.xml, spring-cloud/spring-cloud-archaius/basic-config/src/main/java/com/baeldung/spring/cloud/archaius/basic/BasicArchaiusApplication.java, spring-cloud/spring-cloud-archaius/basic-config/src/main/java/com/baeldung/spring/cloud/archaius/basic/controller/ConfigPropertiesController.java, spring-cloud/spring-cloud-archaius/basic-config/src/main/resources/application.properties, spring-cloud/spring-cloud-archaius/basic-config/src/main/resources/config.properties, spring-cloud/spring-cloud-archaius/basic-config/src/main/resources/other.properties, spring-cloud/spring-cloud-archaius/basic-config/src/test/java/com/baeldung/spring/cloud/archaius/basic/ArchaiusBasicConfigurationIntegrationTest.java, spring-cloud/spring-cloud-archaius/basic-config/src/test/java/com/baeldung/spring/cloud/archaius/basic/ArchaiusBasicConfigurationLiveTest.java, spring-cloud/spring-cloud-archaius/basic-config/src/test/resources/config.properties, spring-cloud/spring-cloud-archaius/extra-configs/pom.xml, spring-cloud/spring-cloud-archaius/extra-configs/src/main/java/com/baeldung/spring/cloud/archaius/extraconfigs/ExtraConfigsApplication.java, spring-cloud/spring-cloud-archaius/extra-configs/src/main/java/com/baeldung/spring/cloud/archaius/extraconfigs/controllers/ConfigPropertiesController.java, spring-cloud/spring-cloud-archaius/extra-configs/src/main/resources/application.properties, spring-cloud/spring-cloud-archaius/extra-configs/src/main/resources/other-config-dir/extra.properties, spring-cloud/spring-cloud-archaius/extra-configs/src/main/resources/other.properties, spring-cloud/spring-cloud-archaius/extra-configs/src/test/java/com/baeldung/spring/cloud/archaius/extraconfigs/ArchaiusExtraConfigsLiveTest.java, spring-cloud/spring-cloud-archaius/pom.xml
* added examples for archaius introduction, with basic configurationm, extra configurations, and setting up an additional config source
IP: http://inprogress.baeldung.com/wp-admin/post.php?post=101732&action=edit
JIRA: http://jira.baeldung.com/browse/BAEL-395
=>  geroza/BAEL-395-Archaius_With_Spring_Cloud_Introduction 

gson/src/main/java/org/baeldung/gson/entities/User.java, gson/src/test/java/org/baeldung/gson/serialization/test/JsonFileUnitTest.java
Draft: http://inprogress.baeldung.com/wp-admin/post.php?post=102180&action=edit
Jira: http://jira.baeldung.com/browse/BAEL-2085
=> Code sample for BAEL-2085

testing-modules/streams-ordering/pom.xml, testing-modules/streams-ordering/src/test/java/StreamsOrderingTest.java, testing-modules/streams-ordering/src/test/java/benchmarking/TestBenchmark.java
Code for the stream ordering article
=> BAEL-2033 Stream-Ordering

jackson/pom.xml
- Upgraded dependencies in jackson module
=> BAEL-8508 Let's upgrade these Jackson articles

cdi/src/test/java/com/baeldung/test/dependencyinjection/ImageProcessorUnitTest.java
- Fixed assertion of local time logic
=> BAEL-8506 Test in CDI project failing

java-strings/src/test/java/com/baeldung/string/SubstringUnitTest.java
This PR addresses http://jira.baeldung.com/browse/BAEL-2138
Draft: http://inprogress.baeldung.com/wp-admin/post.php?post=105460&action=edit
=> [BAEL-2138] Add examples for substring operations

spring-freemarker/pom.xml
- Updated freemarker module's spring and freemarker version to latest
=> BAEL-8842 Update spring-freemarker project

spring-data-jpa/pom.xml, spring-data-jpa/src/main/java/com/baeldung/Application.java, spring-data-jpa/src/main/java/com/baeldung/ddd/event/Aggregate.java, spring-data-jpa/src/main/java/com/baeldung/ddd/event/Aggregate2.java, spring-data-jpa/src/main/java/com/baeldung/ddd/event/Aggregate2Repository.java, spring-data-jpa/src/main/java/com/baeldung/ddd/event/Aggregate3.java, spring-data-jpa/src/main/java/com/baeldung/ddd/event/Aggregate3Repository.java, spring-data-jpa/src/main/java/com/baeldung/ddd/event/AggregateRepository.java, spring-data-jpa/src/main/java/com/baeldung/ddd/event/DddConfig.java, spring-data-jpa/src/main/java/com/baeldung/ddd/event/DomainEvent.java, spring-data-jpa/src/main/java/com/baeldung/ddd/event/DomainService.java, spring-data-jpa/src/main/resources/ddd.properties, spring-data-jpa/src/main/resources/persistence-multiple-db.properties, spring-data-jpa/src/main/resources/persistence.properties, spring-data-jpa/src/test/java/com/baeldung/ddd/event/Aggregate2EventsIntegrationTest.java, spring-data-jpa/src/test/java/com/baeldung/ddd/event/Aggregate3EventsIntegrationTest.java, spring-data-jpa/src/test/java/com/baeldung/ddd/event/AggregateEventsIntegrationTest.java, spring-data-jpa/src/test/java/com/baeldung/ddd/event/TestEventHandler.java
Add BAEL-2067 examples for the "DDD aggregates and @DomainEvents" article.
=> Add BAEL-2067 DomainEvents examples

metrics/pom.xml, metrics/src/test/java/com/baeldung/metrics/micrometer/MicrometerAtlasIntegrationTest.java, metrics/src/test/java/com/baeldung/metrics/servo/AtlasObserverLiveTest.java, metrics/src/test/java/com/baeldung/metrics/servo/MetricTypeManualTest.java
=> BAEL-8902 Metrics Project Test Fails

spring-boot-mvc/src/main/java/com/baeldung/springbootmvc/nosuchbeandefinitionexception/BeanA.java, spring-boot-mvc/src/main/java/com/baeldung/springbootmvc/nosuchbeandefinitionexception/BeanB.java, spring-boot-mvc/src/main/java/com/baeldung/springbootmvc/nosuchbeandefinitionexception/NoSuchBeanDefinitionDemoApp.java
- Added example for no such bean definition example.
=> BAEL-8964 Add a section in "NoSuchBeanDefinition" article

spring-all/pom.xml, spring-all/src/main/java/org/baeldung/scopes/ScopesController.java, spring-all/src/main/java/org/baeldung/spring/config/ScopesConfig.java, spring-all/src/main/webapp/WEB-INF/view/scopesExample.jsp
- Updated changes for new spring bean scopes examples
=> BAEL-8965 Update "Spring Bean Scopes" article

java-strings/pom.xml, java-strings/src/test/java/com/baeldung/string/StringEmptyUnitTest.java
http://jira.baeldung.com/browse/BAEL-2128
=> [BAEL-2128] Check String is not empty

spring-cloud/spring-cloud-archaius/dynamodb-config/pom.xml, spring-cloud/spring-cloud-archaius/dynamodb-config/src/main/java/com/baeldung/spring/cloud/archaius/dynamosources/DynamoSourcesApplication.java, spring-cloud/spring-cloud-archaius/dynamodb-config/src/main/java/com/baeldung/spring/cloud/archaius/dynamosources/config/ApplicationPropertiesConfigurations.java, spring-cloud/spring-cloud-archaius/dynamodb-config/src/main/java/com/baeldung/spring/cloud/archaius/dynamosources/config/DynamoDbConfiguration.java, spring-cloud/spring-cloud-archaius/dynamodb-config/src/main/java/com/baeldung/spring/cloud/archaius/dynamosources/controller/ConfigPropertiesController.java, spring-cloud/spring-cloud-archaius/dynamodb-config/src/main/java/com/baeldung/spring/cloud/archaius/dynamosources/dynamodb/ArchaiusProperties.java, spring-cloud/spring-cloud-archaius/dynamodb-config/src/main/java/com/baeldung/spring/cloud/archaius/dynamosources/dynamodb/ArchaiusPropertiesRepository.java, spring-cloud/spring-cloud-archaius/dynamodb-config/src/main/resources/application.properties, spring-cloud/spring-cloud-archaius/dynamodb-config/src/test/java/com/baeldung/spring/cloud/archaius/dynamosources/ArchaiusDynamoDbLiveTest.java, spring-cloud/spring-cloud-archaius/jdbc-config/pom.xml, spring-cloud/spring-cloud-archaius/jdbc-config/src/main/java/com/baeldung/spring/cloud/archaius/jdbconfig/JdbcSourcesApplication.java, spring-cloud/spring-cloud-archaius/jdbc-config/src/main/java/com/baeldung/spring/cloud/archaius/jdbconfig/config/ApplicationPropertiesConfigurations.java, spring-cloud/spring-cloud-archaius/jdbc-config/src/main/java/com/baeldung/spring/cloud/archaius/jdbconfig/controller/ConfigPropertiesController.java, spring-cloud/spring-cloud-archaius/jdbc-config/src/main/java/com/baeldung/spring/cloud/archaius/jdbconfig/jdbc/Properties.java, spring-cloud/spring-cloud-archaius/jdbc-config/src/main/resources/application.properties, spring-cloud/spring-cloud-archaius/jdbc-config/src/main/resources/data.sql, spring-cloud/spring-cloud-archaius/jdbc-config/src/test/java/com/baeldung/spring/cloud/archaius/jdbconfig/ArchaiusJDBCSourceLiveTest.java, spring-cloud/spring-cloud-archaius/pom.xml, spring-cloud/spring-cloud-archaius/zookeeper-config/pom.xml, spring-cloud/spring-cloud-archaius/zookeeper-config/src/main/java/com/baeldung/spring/cloud/archaius/zookeeperconfig/ZookeeperConfigApplication.java, spring-cloud/spring-cloud-archaius/zookeeper-config/src/main/java/com/baeldung/spring/cloud/archaius/zookeeperconfig/config/ZookeeperConfigsInitializer.java, spring-cloud/spring-cloud-archaius/zookeeper-config/src/main/java/com/baeldung/spring/cloud/archaius/zookeeperconfig/controller/ConfigPropertiesController.java, spring-cloud/spring-cloud-archaius/zookeeper-config/src/main/resources/application.properties, spring-cloud/spring-cloud-archaius/zookeeper-config/src/test/java/com/baeldung/spring/cloud/archaius/zookeeperconfig/ArchaiusZookeeperLiveTest.java
JIRA: http://jira.baeldung.com/browse/BAEL-2115
IP: http://inprogress.baeldung.com/wp-admin/post.php?post=108379&action=edit
=> [BAEL-2115] spring-cloud | Configuring Netflix Archaius

spring-5-reactive-security/src/main/java/com/baeldung/reactive/functional/EmployeeFunctionalConfig.java, spring-5-reactive-security/src/test/java/com/baeldung/reactive/functional/EmployeeSpringFunctionalIntegrationTest.java
- Updated tests and minor spell fix
=> BAEL-2304 Improve functional webflux article

spring-boot-bootstrap/pom.xml, spring-boot-bootstrap/src/main/appengine/app.yaml, spring-boot-bootstrap/src/main/resources/application-gcp.properties, spring-boot-bootstrap/src/main/resources/application.properties, spring-boot-bootstrap/src/main/resources/logback-gcp.xml, spring-boot-bootstrap/src/main/resources/spring-cloud-bootstrap.properties
Added configuration for Deploying to Google Cloud Platform - App Engine
=> BAEL-2103: Added configuration for Deploying to GCP App Engine

algorithms/README.md, core-java-collections/README.md, core-java-io/README.md, core-java/README.md, core-kotlin/README.md, hibernate5/README.md, java-strings/README.md, jersey/README.md, jta/README.md, lombok/README.md, optaplanner/README.md, ratpack/README.md, spring-5-reactive/README.md, spring-boot-bootstrap/README.md, spring-boot-security/README.md, spring-boot/README.MD, spring-data-jpa/README.md, spring-mvc-java/README.md, spring-security-mvc-boot/README.MD, spring-security-mvc-socket/README.md, spring-vault/README.md
Details for the 21 commits 
1.
https://www.baeldung.com/kotlin-ktor 
Kotlin with Ktor
https://github.com/eugenp/tutorials/tree/master/core-kotlin - to add here
https://www.baeldung.com/kotlin-fuel 
Fuel HTTP Library with Kotlin
https://github.com/eugenp/tutorials/tree/master/core-kotlin - to add here
https://www.baeldung.com/kotlin-kovenant 
Introduction to Kovenant Library for Kotlin
https://github.com/eugenp/tutorials/tree/master/core-kotlin - to add here
2.
https://www.baeldung.com/java-synthetic 
Synthetic Constructs in Java
https://github.com/eugenp/tutorials/tree/master/core-java - to add here
3.
https://www.baeldung.com/java-file-to-arraylist 
Read a File into an ArrayList
https://github.com/eugenp/tutorials/tree/master/core-java-io - to add here
4. …
=> To add/fix links (Team Jira BAEL-9015)

pom.xml, spring-5-data-reactive/pom.xml, spring-cloud-bus/pom.xml, spring-cloud-bus/spring-cloud-config-client/pom.xml, spring-cloud-bus/spring-cloud-config-server/pom.xml, spring-cloud-bus/spring-cloud-config-server/src/test/java/com/baeldung/SpringCloudConfigServerApplicationIntegrationTest.java, spring-cloud/pom.xml, spring-cloud/spring-cloud-config/client/pom.xml, spring-cloud/spring-cloud-config/server/pom.xml, spring-cloud/spring-cloud-stream-starters/twitterhdfs/pom.xml, spring-cloud/spring-cloud-task/pom.xml, spring-cloud/spring-cloud-task/springcloudtaskbatch/pom.xml, spring-cloud/spring-cloud-task/springcloudtasksink/pom.xml, spring-cloud/spring-cloud-task/springcloudtasksink/src/test/java/com/baeldung/SpringCloudTaskFinal/SpringCloudTaskSinkApplicationIntegrationTest.java, spring-data-keyvalue/pom.xml, spring-mustache/pom.xml, spring-mustache/src/test/java/com/baeldung/springmustache/SpringMustacheApplicationIntegrationTest.java
- Surefire config fixes
- pom fixes and standardization
- test names standardization
- added packaging pom at spring-cloud-bus and spring-cloud/spring-cloud-task level
=> BAEL-8962 Fix surefire configs of twitterhdfs, spring cloud projects

core-java/src/main/java/com/baeldung/nth/root/calculator/NthRootCalculator.java, core-java/src/main/java/com/baeldung/nth/root/main/Main.java, core-java/src/test/java/com/baeldung/nth/root/calculator/NthRootCalculatorUnitTest.java, core-java/src/test/java/com/baeldung/nth/root/main/MainUnitTest.java
http://jira.baeldung.com/browse/BAEL-2150
=> [BAEL2150] Nth root in Java

core-kotlin/src/main/kotlin/com/baeldung/datastructures/Main.kt, core-kotlin/src/main/kotlin/com/baeldung/datastructures/Node.kt, core-kotlin/src/test/kotlin/com/baeldung/datastructures/NodeTest.kt
It is added a new package **datastructures** in the module **core-kotlin**.
The package contains a class with an implementation of basic operations on a binary search tree.
=> Implement a binary tree

.travis.yml, pom.xml
-Modified travis.yml to execute both default-first and default-second profile
=> BAEL-9654 Activating multiple profiles for Travis CI

spring-rest-simple/src/main/java/org/baeldung/web/controller/FooController.java, spring-resttemplate/src/test/java/org/baeldung/client/RestTemplateBasicLiveTest.java
Add Controller Method to accept form data
Add Test method in RestTemplateBasicLiveTest
=> [BAEL-2248] Spring Rest Template - Accept form data 

spring-resttemplate/src/main/java/org/baeldung/web/service/BarConsumerService.java
Fixed assignment of restTemplate
=> Fixed assignment of restTemplate

algorithms/README.md, apache-geode/README.md, core-java-collections/README.md, core-java-io/README.md, core-java/README.md, core-kotlin/README.md, hibernate5/README.md, java-collections-maps/README.md, java-dates/README.md, java-numbers/README.md, libraries-security/README.md, maven-polyglot/README.md, maven/README.md, spring-5-reactive-security/README.md, spring-boot-mvc/README.md, spring-boot/README.MD, testing-modules/testng/README.md, xml/README.md
1. https://www.baeldung.com/junit-vs-testng
A Quick JUnit vs TestNG Comparison
https://github.com/eugenp/tutorials/tree/master/testing-modules/testng - to add here
2. 
https://www.baeldung.com/maven-directory-structure
Apache Maven Standard Directory Layout
https://github.com/eugenp/tutorials/tree/master/maven - to add here
https://www.baeldung.com/maven
Apache Maven Tutorial
https://github.com/eugenp/tutorials/tree/master/maven - to add here
https://www.baeldung.com/maven-dependency-latest-version
Use the Latest Version of a Dependency in Maven
https://github.com/eugenp/tutorials/tree/master/maven - to add here
3. https://www.baeldung.com/maven-polyglot
Maven Polyglot
https://github.com/eugenp/tutorials/tree/master/maven-polyglot - to add here
4. …
=> Bi-monthly fix (BAEL-9663)

spring-zuul/pom.xml
Fix #5090 class not found ServletRegistrationBean error, seems spring cloud 1.2.3.RELEASE was not working with spring boot 1.5.15.RELEASE
=> Bump spring-cloud dependency version to fix project startup

testing-modules/rest-assured/src/test/java/com/baeldung/restassured/Odd.java, testing-modules/rest-assured/src/test/java/com/baeldung/restassured/RestAssured2IntegrationTest.java
-Add new POST with body example
=> BAEL-9041 Let's add some examples to the rest-assured tutorial

parent-kotlin/pom.xml
=> BAEL-10181 Fix tutorial-build-second | Issue with spring-mvc-kotlin

ddd/README.md
=> BAEL-2272 Persisting DDD Aggregates

java-strings/src/test/java/com/baeldung/string/SubstringUnitTest.java
Added examples with:
* `lastIndexOf`
* `indexOf` with a `String` as a parameter
=> BAEL-2365: added 2 further examples with substring and indexOf

core-java/pom.xml
-Removed corrupted surefire config from core-java module
=> BAEL-10313 Help with test fixes in Abstract Classes and SimpleDateFormat

persistence-modules/java-jpa/src/main/java/com/baeldung/jpa/stringcast/Message.java, persistence-modules/java-jpa/src/main/resources/META-INF/persistence.xml, persistence-modules/java-jpa/src/test/java/com/baeldung/jpa/stringcast/SpringCastUnitTest.java, persistence-modules/java-jpa/src/test/resources/persistence.xml
DummyEntity renamed to Message
IP: http://inprogress.baeldung.com/wp-admin/post.php?post=116693&action=edit
=> BAEL-2239 - JPA error "java.lang.String cannot be cast to [Ljava.lang.String;"

core-java-arrays/src/main/java/com/baeldung/array/operations/ArrayOperations.java, core-java-arrays/src/test/java/com/baeldung/array/operations/IntersectionUnitTest.java
* Adds a simple intersection implementation
* Adds an intersection implementation according to set definition
* Adds an intersection implementation according to multiset definition
=> BAEL-2305 Adds array intersection operations

algorithms-miscellaneous-2/README.md, core-java-10/README.md, core-java-8/README.md, core-java-collections/README.md, core-java-io/README.md, core-java/README.md, java-dates/README.md, persistence-modules/spring-boot-persistence/README.MD, persistence-modules/spring-data-jpa/README.md, persistence-modules/spring-data-mongodb/README.md, spring-5-reactive-oauth/README.md, spring-all/README.md, spring-cloud/README.md, spring-rest-template/README.md, spring-rest/README.md
1. https://www.baeldung.com/spring-request-response-body
Spring’s RequestBody and ResponseBody Annotations
https://github.com/eugenp/tutorials/tree/master/spring-rest - to add here
2. https://www.baeldung.com/java-floating-point-sum-order
Changing the Order in a Sum Operation Can Produce Different Results?
https://github.com/eugenp/tutorials/tree/master/core-java - to add here
https://www.baeldung.com/java-try-with-resources
Java – Try with Resources
https://github.com/eugenp/tutorials/tree/master/core-java - to add here
3. https://www.baeldung.com/java-replace-if-statements
How to Replace Many if Statements in Java
https://github.com/eugenp/tutorials/tree/master/core-java-8 - to add here
4. https://www.baeldung.com/graal-java-jit-compiler
Deep Dive Into the New Java JIT Compiler – Graal …
=> Bi-monthly test failure - fix (BAEL-10330)

pom.xml
=> Add load-testing-comparison to Build

core-java-lang/src/test/java/com/baeldung/compoundoperators/CompoundOperatorsTest.java, core-java-lang/src/test/java/com/baeldung/compoundoperators/CompoundOperatorsUnitTest.java
BAEL-2347: Added test examples for Compound Assignment Operators.
=> BAEL-2347: Added test examples for Coupound Assignment Operators.

core-kotlin/src/main/kotlin/com/baeldung/functions/Inline.kt
Companion sample codes for BAEL-2377.
=> Added a simple function for bytecode inspection.

libraries/src/test/java/com/baeldung/fj/FunctionalJavaUnitTest.java
Something went wrong during the previous merge, I guess. Redoing it.
=> BAEL-1049: Re-merge changes.

.travis.yml, pom.xml
- Removed geotools module causing build to hang
- Removed -q parameter from travis to see full logs while building
=> BAEL-10829 Cleanup parent pom.xml

java-dates/src/test/java/com/baeldung/date/DateDiffUnitTest.java
Added two tests for time difference calculation in terms of seconds!
=> BAEL 2428: Calculate Time Duration in Seconds

persistence-modules/hibernate-ogm/README.md, persistence-modules/hibernate-ogm/pom.xml, persistence-modules/hibernate-ogm/src/main/java/com/baeldung/hibernate/ogm/Article.java, persistence-modules/hibernate-ogm/src/main/java/com/baeldung/hibernate/ogm/Author.java, persistence-modules/hibernate-ogm/src/main/java/com/baeldung/hibernate/ogm/Editor.java, persistence-modules/hibernate-ogm/src/main/resources/META-INF/persistence.xml, persistence-modules/hibernate-ogm/src/test/java/com/baeldung/hibernate/ogm/EditorUnitTest.java, pom.xml
This pull request adds an additional module under persistence-modules\hibernate-ogm with corresponding additions to the master POM (selected profiles only). Please verify as necessary.
=> Adding files for the tutorial BAEL-1877: A Guide to Hibernate OGM

core-java-lang/src/main/java/com/baeldung/controlstructures/ConditionalBranches.java, core-java-lang/src/main/java/com/baeldung/controlstructures/Loops.java
=> [BAEL-2432] - Java Control Structures

java-strings/README.md, java-strings/src/main/java/com/baeldung/string/ReplaceCharacterInString.java, java-strings/src/test/java/com/baeldung/string/ReplaceCharInStringTest.java, java-strings/src/test/java/com/baeldung/string/ReplaceCharInStringUnitTest.java
Please review the code of the mini-article - http://inprogress.baeldung.com/wp-admin/post.php?post=118110
=> Added the code of Replace char in a string at specific index

core-kotlin/src/main/kotlin/com/baeldung/contract/CallsInPlaceEffect.kt, core-kotlin/src/main/kotlin/com/baeldung/contract/ReturnsEffect.kt, parent-kotlin/pom.xml
* upgraded kotlin version to 1.3.10
* added contract examples
=> BAEL-2373 Kotlin Contracts

core-java-lang/src/main/java/com/baeldung/controlstructures/Loops.java
=> Two More Examples for Break and Continue

java-strings/src/test/java/com/baeldung/StringConcatenationUnitTest.java
Added code for BAEL-2419 String Concatenation Article.
=> BAEL-2419: Added String Concatenation Unit Tests

core-java/src/main/java/com/baeldung/http/FullResponseBuilder.java, core-java/src/test/java/com/baeldung/http/HttpRequestLiveTest.java
Add examples for reading response content on failed requests. Add an example on how to build full response string as well.
=> BAEL-2454 Add new section in Java Http Request article

core-java-11/src/test/java/com/baeldung/optional/OptionalUnitTest.java
Added a test for Optional#isEmpty.
=> BAEL-2385: Add a section in Optional article

java-strings/src/test/java/com/baeldung/string/interview/LocaleUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringAnagramUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringChangeCaseUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringCountOccurrencesUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringFormatUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringInternUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringJoinerUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringPalindromeUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringReverseUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringSplitUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringToByteArrayUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringToCharArrayUnitTest.java, java-strings/src/test/java/com/baeldung/string/interview/StringToIntegerUnitTest.java
BAEL-2392_Java_String_interview_questions second commit
=> BAEL-2392_Java_String_interview_questions second commit

pom.xml, spring-ehcache/.gitignore, spring-ehcache/README.md, spring-ehcache/checkstyle.xml, spring-ehcache/pom.xml, spring-ehcache/src/main/java/com/baeldung/cachetest/Application.java, spring-ehcache/src/main/java/com/baeldung/cachetest/config/CacheConfig.java, spring-ehcache/src/main/java/com/baeldung/cachetest/config/CacheEventLogger.java, spring-ehcache/src/main/java/com/baeldung/cachetest/rest/NumberController.java, spring-ehcache/src/main/java/com/baeldung/cachetest/service/NumberService.java
ehcache example for http://jira.baeldung.com/browse/BAEL-2450
=> spring-boot ehcache example added

spring-boot-bootstrap/pom.xml, spring-boot-bootstrap/src/main/resources/application-beanstalk.properties
=> BAEL-2104: Spring Boot deployment to AWS Beanstalk

core-java-security/src/main/java/com/baeldung/ssl/EnableTLSv12.java
How to enable TLS 1.2 in Java 7
=> BAEL-2500 || Changes to enable TLSv1.2 on Java 7.

core-java-collections/src/main/java/com/baeldung/queueInterface/CustomBaeldungQueue.java, core-java-collections/src/test/java/com/baeldung/queueInterface/CustomBaeldungQueueTest.java, core-java-collections/src/test/java/com/baeldung/queueInterface/PriorityQueueUnitTest.java, core-java-collections/src/test/java/com/baeldung/queueinterface/CustomBaeldungQueueUnitTest.java
code for Baeldung article BAEL-2526
=> BAEL2526 queue interface code

core-java-io/src/main/java/com/baeldung/csv/WriteCsvFileExample.java, core-java-io/src/test/java/com/baeldung/csv/WriteCsvFileExampleUnitTest.java, core-java-io/src/test/resources/exampleOutput.csv
Here's the pull request for the article I'm working on BAEL-2499 Write to CSV in Java
=> example code for Article How to Write to a CSV File in Java

core-java/src/test/java/com/baeldung/curltojava/JavaCurlExamplesLiveTest.java
BAEL-2452: Using curl from Java
http://jira.baeldung.com/browse/BAEL-2452
Renamed from Unit Test to Live Test
=> BAEL-2452: Using curl from Java

java-streams/src/main/java/com/baeldung/stream/filter/Customer.java, java-streams/src/test/java/com/baeldung/stream/filter/StreamCountUnitTest.java, java-streams/src/test/java/com/baeldung/stream/filter/StreamFilterUnitTest.java
* Added some examples to the method Stream.count()
* renamed the method: _hasOverThousandPoints_ -> _hasOveHundredPoints_ according to its content
=> BAEL-2546: Stream.count

testing-modules/junit-5/pom.xml, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/BlankStringsArgumentsProvider.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/EnumsUnitTest.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/LocalDateUnitTest.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/Numbers.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/NumbersUnitTest.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/Person.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/PersonAggregator.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/PersonUnitTest.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/SlashyDateConverter.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/StringParams.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/Strings.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/StringsUnitTest.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/VariableArgumentsProvider.java, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/VariableSource.java, testing-modules/junit-5/src/test/resources/data.csv
=> Added sample tests for JUnit 5 parameterized tests.

core-java-io/src/test/java/com/baeldung/file/FilesClearDataManualTest.java, core-java-io/src/test/java/com/baeldung/file/FilesClearDataUnitTest.java, core-java-io/src/test/resources/fileexample.txt
This merge request is to add code for showing how to delete file content using Java.
=> BAEL-2525 - Clear a text file without deleting in Java

spring-security-mvc-login/src/main/resources/RedirectionWebSecurityConfig.xml
Fixing failing test:
* fixed typo in bean definition
* added the own class SecuredResourceController to the test context
* added the Spring class NoOpPasswordEncoder to the text context
=> Fix tests mvc login

core-java-security/pom.xml, core-java-security/src/main/java/com/baeldung/hashing/DigestAlgorithms.java, core-java-security/src/main/java/com/baeldung/hashing/Keccak256Hashing.java, core-java-security/src/main/java/com/baeldung/hashing/SHA256Hashing.java, core-java-security/src/main/java/com/baeldung/hashing/SHA3Hashing.java, core-java-security/src/main/java/com/baeldung/hashing/SHACommonUtils.java, core-java-security/src/test/java/com/baeldung/hashing/Keccak256HashingUnitTest.java, core-java-security/src/test/java/com/baeldung/hashing/SHA256HashingUnitTest.java, core-java-security/src/test/java/com/baeldung/hashing/SHA3HashingUnitTest.java
- added sha3 relevant tests
- upgraded commons-codec to 1.11 and bouncy-castle to 1.60 (the latest release)
=> BAEL-2501 add a new section in SHA-256 article

core-groovy/src/main/groovy/com/baeldung/strings/Concatenate.groovy, core-groovy/src/test/groovy/com/baeldung/strings/ConcatenateTest.groovy
This code is for article Concatenate Strings in Groovy
=> BAEL-2666 - concatenate strings in Groovy

core-kotlin/src/test/kotlin/com/baeldung/kotlin/junit5/CalculatorTest5.kt, core-kotlin/src/test/kotlin/com/baeldung/kotlin/junit5/SimpleTest5.kt
=> Refactored the test names and used backtick identifiers.

spring-boot-rest/README.md, spring-boot-rest/pom.xml, spring-boot-rest/src/main/java/com/baeldung/persistence/model/Foo.java, spring-boot-rest/src/main/java/com/baeldung/spring/WebConfig.java, spring-boot-rest/src/main/resources/WEB-INF/api-servlet.xml, spring-rest/README.md, spring-rest/pom.xml, spring-rest/src/main/java/com/baeldung/sampleapp/config/WebConfig.java, spring-rest/src/main/java/com/baeldung/sampleapp/web/dto/Foo.java, spring-rest/src/main/webapp/WEB-INF/api-servlet.xml
* moved code (mostly commented out) from spring-rest to spring-boot-rest
* changed readme file
* added spring boot example simply adding a bean, for xml too
=> [BAEL-11405] Move and Update Rest and Http Message Converter Article

spring-boot-rest/README.md
JIRA: http://team.baeldung.com/browse/BAEL-11600
copied-down draft IP:http://inprogress.baeldung.com/wp-admin/post.php?post=134549&action=edit
Note: Didnt remove the code in spring-rest since its used also in [other article](https://www.baeldung.com/spring-rest-custom-media-type)
EDIT: As per the discussion in the Jira ticket, we won't be moving this code to the new module. instead, we added a link to the article to the tutorial that did contain the actual code.
Note: the article's link was not included in the rest-spring readme file
=> [BAEL-11600] Move and update 'Versioning a REST API article

core-kotlin/src/main/kotlin/com/baeldung/kotlin/dsl/SqlDsl.kt, core-kotlin/src/test/kotlin/com/baeldung/kotlin/dsl/SqlDslTest.kt
* added basic SQL DSL
* basic SQL DSL tests
=> BAEL-2582 Building DSLs in Kotlin

testing-modules/junit-5/src/test/java/com/baeldung/conditional/ConditionalAnnotationsTest.java, testing-modules/junit-5/src/test/java/com/baeldung/conditional/ConditionalAnnotationsUnitTest.java
about http://jira.baeldung.com/browse/BAEL-2583
=> BAEL-2583 JUnit 5: Conditional Test Execution

parent-boot-2/pom.xml, spring-boot-bootstrap/pom.xml, spring-boot-bootstrap/src/main/java/com/baeldung/Application.java, spring-boot-bootstrap/src/main/resources/templates/error.html, spring-boot-bootstrap/src/main/resources/templates/home.html
=> Issue 6427 fix incompatible dependencies

pom.xml
-Included project in the main pom.xml
=> BAEL-10995 Fix integration build of spring-data-elasticsearch module

core-java/src/main/java/com/baeldung/urlconnection/PostJSONWithHttpURLConnection.java
@pivovarit I created a new pull request for BAEL-2737 (HttpUrlConnection POST Request with JSON). Please review the same
=> An example program to make JSON Post request with HttpURLConnection

core-groovy/src/test/groovy/com/baeldung/lists/ListTest.groovy
Added list manipulation operations
=> BAEL-2725 Lists in Groovy

parent-spring-5/pom.xml, spring-mvc-simple/pom.xml, spring-security-mvc-custom/pom.xml, spring-security-mvc-jsonview/pom.xml, spring-security-mvc-login/pom.xml, spring-security-rest/pom.xml, spring-static-resources/pom.xml
JIRA: http://team.baeldung.com/browse/BAEL-12777
* Migrated parent-spring-5 version (spring-core and spring-security)
* Cleaned spring-security version being used in some modules. Now using the parent version
=> BAEL-12777 Upgrade parent-spring-5 version:

spring-all/pom.xml, spring-all/src/main/java/org/baeldung/properties/spring/PropertiesWithJavaConfig.java, spring-all/src/main/resources/configForProperties.xml, spring-all/src/test/java/org/baeldung/properties/multiple/MultiplePropertiesJavaConfigIntegrationTest.java, spring-all/src/test/java/org/baeldung/properties/multiple/MultiplePropertiesXmlConfigIntegrationTest.java
Added sample code for BAEL-1122
=> BAEL-1122 - Sample code 

rxjava-2/src/test/java/com/baeldung/rxjava/RxJavaHooksManualTest.java, rxjava-2/src/test/java/com/baeldung/rxjava/RxJavaHooksUnitTest.java
=> BAEL - 1060

core-kotlin-2/src/main/kotlin/com/baeldung/annotations/Annotations.kt, core-kotlin-2/src/main/kotlin/com/baeldung/annotations/Item.kt, core-kotlin-2/src/main/kotlin/com/baeldung/annotations/Main.kt, core-kotlin-2/src/main/kotlin/com/baeldung/annotations/Validator.kt, core-kotlin-2/src/test/kotlin/com/baeldung/annotations/ValidationTest.kt, core-kotlin-2/src/test/kotlin/com/baeldung/annotations/ValidationUnitTest.kt
Module core-kotlin-2 in which the code has been moved uses JUnit 4. Therefore, the code has been adjusted accordingly.
=> Adjust the unit test

lombok/src/main/java/com/baeldung/lombok/builder/singular/Person.java, lombok/src/main/java/com/baeldung/lombok/builder/singular/Sea.java, lombok/src/test/java/com/baeldung/lombok/builder/singular/BuilderWithSingularSupportForCollectionsUnitTest.java
Two classes, plus tests, demonstrating use of @Singular for the mini-article
=> Bael 2712 lombok builder singular

spring-boot-angular-ecommerce/src/main/frontend/package.json
Fix for `npm run build` described in #6594
=> Fix for Issue #6594

core-java-8-2/README.md, core-java-8-2/pom.xml, core-java-8-2/src/main/java/com/baeldung/anonymous/Book.java, core-java-8-2/src/main/java/com/baeldung/anonymous/Main.java, core-java-8-2/src/test/java/com/baeldung/AppTest.java, core-java-8-2/src/test/java/com/baeldung/UnitTest.java, pom.xml
Add a code snippet about anonymous classes (BAEL-2833)
Create module core-java-8-2 and move 'anonymous' package there
=> Add a code snippet for anonymous classes (BAEL-2833)

spring-cloud/spring-cloud-config/client/src/test/java/com/baeldung/spring/cloud/config/client/SpringContextLiveTest.java, spring-cloud/spring-cloud-config/server/src/test/java/com/baeldung/spring/cloud/config/server/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-config/server/src/test/resources/application.properties, spring-cloud/spring-cloud-connectors-heroku/src/main/resources/application.properties, spring-cloud/spring-cloud-connectors-heroku/src/test/java/com/baeldung/spring/cloud/connectors/heroku/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-connectors-heroku/src/test/resources/application.properties, spring-cloud/spring-cloud-consul/src/test/java/com/baeldung/spring/cloud/consul/SpringContextLiveTest.java, spring-cloud/spring-cloud-rest/spring-cloud-rest-books-api/src/test/java/org/baeldung/SpringContextLiveTest.java, spring-cloud/spring-cloud-rest/spring-cloud-rest-discovery-server/src/test/java/org/baeldung/SpringContextLiveTest.java, spring-cloud/spring-cloud-rest/spring-cloud-rest-reviews-api/src/test/java/org/baeldung/SpringContextLiveTest.java, spring-cloud/spring-cloud-stream-starters/twitterhdfs/src/test/java/com/baeldung/twitterhdfs/aggregate/SpringContextIntegrationTest.java
Jira: http://team.baeldung.com/browse/BAEL-9494
=> [BAEL-9494] fix spring-cloud context integration tests - part 2

spring-core/pom.xml
DO NOT MERGE (probably!)
This was done as work on BAEL-2618 (updating https://www.baeldung.com/constructor-injection-in-spring) but the change affects a number of other articles, as listed in the README. Need clarification on how we go about updating them, or determining if they need updating, even...
=> moved spring core to spring 5 parent, all tests still pass

testing-modules/rest-assured/pom.xml, testing-modules/rest-assured/src/test/java/com/baeldung/restassured/authentication/BasicAuthenticationLiveTest.java, testing-modules/rest-assured/src/test/java/com/baeldung/restassured/authentication/BasicPreemtiveAuthenticationLiveTest.java, testing-modules/rest-assured/src/test/java/com/baeldung/restassured/authentication/DigestAuthenticationLiveTest.java, testing-modules/rest-assured/src/test/java/com/baeldung/restassured/authentication/FormAuthenticationLiveTest.java, testing-modules/rest-assured/src/test/java/com/baeldung/restassured/authentication/FormAutoconfAuthenticationLiveTest.java, testing-modules/rest-assured/src/test/java/com/baeldung/restassured/authentication/OAuth2AuthenticationLiveTest.java, testing-modules/rest-assured/src/test/java/com/baeldung/restassured/authentication/OAuthAuthenticationLiveTest.java
JIRA: http://jira.baeldung.com/browse/BAEL-2735
IP: http://inprogress.baeldung.com/wp-admin/post.php?post=141280&action=edit&classic-editor
=> [BAEL-2735] REST-Assured Authentication article

core-java-8/src/test/java/com/baeldung/reduceIfelse/CalculatorUnitTest.java
add test case for reduceIfElse by using factory pattern
=> add calculateUsingFactory test case

autovalue/src/main/java/com/baeldung/autofactory/provided/IntermediateAssembler.java
Fixed the compilation issues for Autovalue module.
=> Autovalue fix

java-strings-2/pom.xml, java-strings-2/src/main/java/com/baeldung/string/search/performance/SubstringSearchPerformanceComparison.java, java-strings-2/src/main/resources/logback.xml, java-strings-2/src/test/java/com/baeldung/string/search/SubstringSearch.java, java-strings-2/src/test/resources/.gitignore, pom.xml
- Added tests and benchmark in a new module, java-strings-2
- Edited main pom.xml and added a new module
=> BAEL-2832: Check if a String contains a Substring

testing-modules/junit-5/pom.xml, testing-modules/junit-5/src/test/java/com/baeldung/parameterized/StringsUnitTest.java
=> Bael 2915: Null and Empty Sources for JUnit 5

persistence-modules/spring-data-jpa-2/src/main/java/com/baeldung/entitygraph/model/Characteristic.java, persistence-modules/spring-data-jpa-2/src/main/java/com/baeldung/entitygraph/model/Item.java, persistence-modules/spring-data-jpa-2/src/main/java/com/baeldung/entitygraph/repository/CharacteristicsRepository.java, persistence-modules/spring-data-jpa-2/src/main/java/com/baeldung/entitygraph/repository/ItemRepository.java, persistence-modules/spring-data-jpa-2/src/test/java/com/baeldung/entitygraph/EntityGraphIntegrationTest.java, persistence-modules/spring-data-jpa-2/src/test/resources/entitygraph-data.sql
=> BAEL - 2823

core-java-reflection/pom.xml, core-java-reflection/src/main/java/com/baeldung/reflection/voidtype/Action.java, core-java-reflection/src/main/java/com/baeldung/reflection/voidtype/Calculator.java, core-java-reflection/src/main/java/com/baeldung/reflection/voidtype/Defer.java, core-java-reflection/src/main/java/com/baeldung/reflection/voidtype/MyOwnDefer.java, core-java-reflection/src/test/java/com/baeldung/reflection/voidtype/CalculatorUnitTest.java, core-java-reflection/src/test/java/com/baeldung/reflection/voidtype/DeferUnitTest.java, core-java-reflection/src/test/java/com/baeldung/reflection/voidtype/MyOwnDeferUnitTest.java, pom.xml
=> dupirefr/dupire.francois+pro@gmail.com [BAEL-2506] Moved Java Void Type examples into a new core-java-reflection module

spring-cloud/spring-cloud-eureka/pom.xml, spring-cloud/spring-cloud-eureka/spring-cloud-eureka-client/pom.xml, spring-cloud/spring-cloud-eureka/spring-cloud-eureka-feign-client/pom.xml, spring-cloud/spring-cloud-eureka/spring-cloud-eureka-server/pom.xml
Jira: http://team.baeldung.com/browse/BAEL-10129
Upgraded spring Cloud Eureka article code to the latest versions
=> [BAEL-10129] Update Spring Cloud Eureka article

pom.xml, testing-modules/junit-5/pom.xml, testing-modules/junit-5/src/test/java/com/baeldung/MultipleExtensionsUnitTest.java, testing-modules/junit-5/src/test/java/com/baeldung/ProgrammaticEmployeesUnitTest.java, testing-modules/junit-5/src/test/java/com/baeldung/extensions/EmployeeDatabaseSetupExtension.java, testing-modules/junit-5/src/test/java/com/baeldung/helpers/EmployeeJdbcDao.java, testing-modules/junit-5/src/test/java/com/baeldung/helpers/JdbcConnectionUtil.java, testing-modules/junit5-migration/src/test/java/com/baeldung/junit5/AssertionUnitTest.java
=> Bael 2916: Ordering Extension Registrations

core-java-modules/core-java-exceptions/src/test/java/com/baeldung/exception/numberformat/NumberFormatExceptionUnitTest.java
=> Final review changes for: JIRA - BAEL-2773 (The Java NumberFormatException)

spring-rest-full/src/main/java/org/baeldung/web/util/RestPreconditions.java
=> Updating javadoc

spring-resttemplate/src/test/java/org/baeldung/resttemplate/LargeFileDownloadIntegrationTest.java
Implement methods to download a large file through Spring RestTemplate
=> #BAEL-2461

core-java-modules/core-java-lambdas/README.md
Deleted duplicated readme file. It was generating issues in case insensitive os
=> Deleted duplicated readme file

spring-core/pom.xml, spring-core/src/main/resources/constructordi.xml, spring-core/src/test/java/com/baeldung/constructordi/ConstructorDependencyInjectionIntegrationTest.java
JIRA: http://team.baeldung.com/browse/BAEL-10130
* Added test for constructor dependency injection article
* removed spring version in xml file
=> [BAEL-10130] spring-core | Update Constructor Injection article

persistence-modules/java-jpa/pom.xml, persistence-modules/java-jpa/src/main/java/com/baeldung/jpa/queryparams/Employee.java, persistence-modules/java-jpa/src/main/resources/META-INF/persistence.xml, persistence-modules/java-jpa/src/test/java/com/baeldung/jpa/queryparams/JPAQueryParamsUnitTest.java, persistence-modules/java-jpa/src/test/resources/employees2.sql
This is the code behind the JPA Query Parameters Usage tutorial. Within
these examples you can find the way to use named and positional query
parameters either using plain JPQL or criteria queries.
=> BAEL-2804 JPA Query Parameters Usage

core-java-modules/core-java-lang-oop-2/src/main/java/com/baeldung/rawtype/RawTypeDemo.java
This PR has the code demonstrating the disadvantages of using a raw type.
=> Mini article raw type in java

algorithms-miscellaneous-3/pom.xml, algorithms-miscellaneous-3/src/main/java/com/baeldung/algorithms/checksortedlist/Employee.java, algorithms-miscellaneous-3/src/main/java/com/baeldung/algorithms/checksortedlist/SortedListChecker.java, algorithms-miscellaneous-3/src/test/java/com/baeldung/algorithms/checksortedlist/SortedListCheckerUnitTest.java
Code example: Checking If a List Is Sorted in Java
=> Code example: Checking If a List Is Sorted in Java

algorithms-miscellaneous-3/src/main/java/com/baeldung/algorithms/checksortedlist/SortedListChecker.java
BAEL-3020: Updated the previous variable in loop
=> BAEL-3020: Updated the previous variable in loop

java-strings-2/README.MD, java-strings-2/pom.xml, java-strings-2/src/main/java/com/baeldung/string/emptystrings/EmptyStringCheck.java, java-strings-2/src/main/java/com/baeldung/string/emptystrings/Java5EmptyStringCheck.java, java-strings-2/src/main/java/com/baeldung/string/emptystrings/PlainJavaBlankStringCheck.java, java-strings-2/src/main/java/com/baeldung/string/emptystrings/SomeClassWithValidations.java, java-strings-2/src/test/java/com/baeldung/string/emptystrings/EmptyStringsUnitTest.java
@jzheaux Sample code for BAEL-3019 empty strings mini-article
=> [BAEL-3019] Add sample code for empty and blank string checks

spring-security-mvc-boot/pom.xml, spring-security-mvc-boot/src/main/java/org/baeldung/custom/config/SecurityConfig.java, spring-security-mvc-boot/src/main/java/org/baeldung/custom/web/MainController.java, spring-security-mvc-boot/src/test/java/org/baeldung/web/CustomUserDetailsServiceIntegrationTest.java
Jira: http://team.baeldung.com/browse/BAEL-15425
update IP: http://inprogress.baeldung.com/wp-admin/post.php?post=148983&action=edit&classic-editor
=> [BAEL-15425] Update Spring Security Database article

algorithms-miscellaneous-3/README.md, core-java-modules/core-java-11/src/main/java/com/baeldung/predicate/not/README.md, core-java-modules/core-java-12/README.md, core-java-modules/core-java-concurrency-basic/README.md, core-java-modules/core-java-exceptions/README.md, core-java-modules/core-java-lambdas/README.md, java-strings-2/README.MD, persistence-modules/java-jpa/README.md, persistence-modules/jpa-hibernate-cascade-type/README.md, persistence-modules/spring-data-jpa-2/README.md, quarkus/README.md, spf4j/README.md
=> BAEL-15902

core-java-modules/core-java-os/src/main/java/com/baeldung/core/pwd/CurrentDirectoryFetcher.java, core-java-modules/core-java-os/src/test/java/com/baeldung/core/pwd/CurrentDirectoryFetcherTest.java
Code for BAEL-3078 (Get Current Directory Using Java)
=> Get Current Directory Using Java

spring-boot-logging-log4j2/pom.xml, spring-boot-logging-log4j2/src/main/java/com/baeldung/springbootlogging/LombokLoggingController.java
The PR has the code changes introduced to do logging with Lombok.
=> Lombok related code changes

spring-quartz/pom.xml, spring-quartz/src/main/java/org/baeldung/springquartz/basics/scheduler/QrtzScheduler.java, spring-quartz/src/main/java/org/baeldung/springquartz/basics/scheduler/SampleJob.java, spring-quartz/src/main/java/org/baeldung/springquartz/basics/scheduler/SpringQrtzScheduler.java, spring-quartz/src/main/java/org/baeldung/springquartz/basics/service/SampleJobService.java, spring-quartz/src/main/resources/application.properties, spring-quartz/src/main/resources/quartz.properties, spring-quartz/src/test/java/org/baeldung/SpringContextIntegrationTest.java
Please see http://jira.baeldung.com/browse/BAEL-2798
=> BAEL-2798 Update to 'Scheduling in Spring with Quartz' article to add JDBC examples.

testing-modules/junit-5-advanced/src/main/java/com/baeldung/failure_vs_error/SimpleCalculator.java, testing-modules/junit-5-advanced/src/test/java/com/baeldung/failure_vs_error/SimpleCalculatorUnitTest.java
Example code for BAEL-3082 is done.
=> added example code for BAEL-3082

spring-boot-autoconfiguration/pom.xml, spring-boot-autoconfiguration/src/main/java/com/baeldung/autoconfiguration/annotationprocessor/AnnotationProcessorApplication.java, spring-boot-autoconfiguration/src/main/java/com/baeldung/autoconfiguration/annotationprocessor/DatabaseProperties.java, spring-boot-autoconfiguration/src/test/java/com/baeldung/autoconfiguration/annotationprocessor/DatabasePropertiesIntegrationTest.java, spring-boot-autoconfiguration/src/test/resources/databaseproperties-test.properties
Implemented the examples for Configuration Processor
=> Bael 2997 spring boot configuration processor

spring-boot-properties/.gitignore, spring-boot-properties/README.md, spring-boot-properties/extra.properties, spring-boot-properties/extra2.properties, spring-boot-properties/pom.xml, spring-boot-properties/src/main/java/com/baeldung/properties/SpringBootPropertiesApplication.java, spring-boot-properties/src/main/java/com/baeldung/properties/configs/PropertiesException.java, spring-boot-properties/src/main/java/com/baeldung/properties/configs/ReloadableProperties.java, spring-boot-properties/src/main/java/com/baeldung/properties/configs/ReloadablePropertySource.java, spring-boot-properties/src/main/java/com/baeldung/properties/configs/ReloadablePropertySourceConfig.java, spring-boot-properties/src/main/java/com/baeldung/properties/configs/ReloadablePropertySourceFactory.java, spring-boot-properties/src/main/resources/application.properties, spring-boot-properties/src/test/java/com/baeldung/properties/PropertiesReloadIntegrationTest.java, spring-boot-properties/src/test/java/com/baeldung/properties/SpringBootPropertiesTestApplication.java, spring-boot-properties/src/test/java/com/baeldung/properties/beans/ConfigurationPropertiesRefreshConfigBean.java, spring-boot-properties/src/test/java/com/baeldung/properties/beans/EnvironmentConfigBean.java, spring-boot-properties/src/test/java/com/baeldung/properties/beans/PropertiesConfigBean.java, spring-boot-properties/src/test/java/com/baeldung/properties/beans/ValueRefreshConfigBean.java, spring-boot-properties/src/test/resources/application.properties
Complete code samples for "Reloading Properties Files in Spring".
=> #BAEL-2888- Reloading Properties Files in Spring

spring-security-mvc/src/test/java/com/baeldung/session/SessionConfigurationLiveTest.java
Jira: http://team.baeldung.com/browse/BAEL-10220
=> [BAEL-10220] Update Spring Session article - fix test name

patterns/backoff-jitter/README.md, patterns/backoff-jitter/pom.xml, patterns/backoff-jitter/src/test/java/com/baeldung/backoff/jitter/BackoffWithJitterTest.java, patterns/pom.xml
http://jira.baeldung.com/browse/BAEL-3087
=> BAEL 3087: Exponential Backoff with Jitter

core-java-modules/core-java-io/src/main/java/com/baeldung/files/Main.java, core-java-modules/core-java-io/src/main/java/com/baeldung/files/NumberOfLineFinder.java, core-java-modules/core-java-io/src/test/java/com/baeldung/file/NumberOfLineFinderUnitTest.java
Added source for finding number of lines in a file
=> [BAEL-3121] Added source for finding number of lines in a file

javax-servlets/src/main/java/com/baeldung/servlets/MyHttpServlet.java
BAEL-2856
Difference between getRequestURI and getPathInfo in HttpServletRequest
=> BAEL-2856 Difference between getRequestURI and getPathInfo in HttpServletRequest

twitter4j/src/test/java/com/baeldung/ApplicationLiveTest.java
… to reflect test requirements
=> [BAEL-9020] updated ApplicationIntegrationTest to ApplicationLiveTest

xml/src/main/java/com/baeldung/xml/attribute/Dom4jTransformer.java, xml/src/main/java/com/baeldung/xml/attribute/JaxpTransformer.java, xml/src/main/java/com/baeldung/xml/attribute/jmh/AttributeBenchMark.java, xml/src/test/java/com/baeldung/xml/attribute/Dom4jProcessorUnitTest.java, xml/src/test/java/com/baeldung/xml/attribute/JaxpProcessorUnitTest.java, xml/src/test/java/com/baeldung/xml/attribute/JooxProcessorUnitTest.java, xml/src/test/resources/xml/xee_attribute.xml
UPDATE Added additional tests, security config, and fix format issues
=> BAEL 2539 - Update from sample code

algorithms-sorting/src/main/java/com/baeldung/algorithms/selectionsort/SelectionSort.java, algorithms-sorting/src/test/java/com/baeldung/algorithms/selectionsort/SelectionSortUnitTest.java
This PR has the code for Selection Sort algorithm.
=> Selection Sort Implementation

mapstruct/src/main/java/com/baeldung/dto/CarDTO.java, mapstruct/src/main/java/com/baeldung/dto/FuelType.java, mapstruct/src/main/java/com/baeldung/entity/BioDieselCar.java, mapstruct/src/main/java/com/baeldung/entity/ElectricCar.java, mapstruct/src/main/java/com/baeldung/mapper/CarsMapper.java, mapstruct/src/test/java/com/baeldung/mapper/CarsMapperUnitTest.java
http://jira.baeldung.com/browse/BAEL-3092
=> Adds after / before mapping example

core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGenerator.java, core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGeneratorUsingMonitor.java, core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGeneratorUsingReentrantLock.java, core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGeneratorUsingSemaphore.java, core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGeneratorUsingSynchronizedBlock.java, core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGeneratorUsingSynchronizedMethod.java, core-java-modules/core-java-concurrency-basic/src/test/java/com/baeldung/concurrent/mutex/MutexUnitTest.java
Code example: Using a Mutex Object in Java
=> Code example: Using a Mutex Object in Java

algorithms-miscellaneous-3/src/main/java/com/baeldung/algorithms/interpolationsearch/InterpolationSearch.java, algorithms-miscellaneous-3/src/test/java/com/baeldung/algorithms/interpolationsearch/InterpolationSearchUnitTest.java
http://inprogress.baeldung.com/wp-admin/post.php?post=157451&action=edit&classic-editor
=> BAEL-3196 Interpolation Search in Java

java-strings-3/src/main/java/com/baeldung/string/README.md, java-strings-3/src/main/java/com/baeldung/string/wordcount/WordCounter.java, java-strings-3/src/test/java/com/baeldung/string/wordcount/WordCountUnitTest.java
=> BAEL-3120 alfred.samanga@gmail.com 

algorithms-sorting/README.md, algorithms-sorting/src/main/java/com/baeldung/algorithms/counting/CountingSort.java, algorithms-sorting/src/test/java/com/baeldung/algorithms/counting/CountingSortUnitTest.java
=> Sample Codes for Counting Sort in Java

core-java-modules/core-java-io-2/.gitignore, core-java-modules/core-java-io-2/pom.xml, core-java-modules/core-java-io-2/src/main/java/com/baeldung/filereader/FileReaderExample.java, core-java-modules/core-java-io-2/src/test/java/com/baeldung/filereader/FileReaderExampleUnitTest.java, core-java-modules/core-java-io-2/src/test/resources/HelloWorld.txt
- The tutorial covers the following:
- Introduction to the concept of a Reader
- How to use FileReader to read text from a file
- Limitations of FileReader
- Reference: [BAEL-3215](http://jira.baeldung.com/browse/BAEL-3215)
=> BAEL-3215: A Guide to the Java FileReader Class

spring-5-reactive-client/pom.xml, spring-5-reactive-client/src/test/java/com/baeldung/reactive/logging/WebClientLoggingIntegrationTest.java, spring-5-reactive-client/src/test/java/com/baeldung/reactive/logging/filters/LogFilters.java, spring-5-reactive-client/src/test/java/com/baeldung/reactive/logging/jetty/RequestLogEnhancer.java, spring-5-reactive-client/src/test/java/com/baeldung/reactive/logging/netty/CustomLogger.java, spring-5-reactive-client/src/test/resources/logback-test.xml
BAEL-3009:
Logging Spring WebClient calls.
=> BAEL-3009: Logging Spring WebClient calls

spring-rest-compress/src/main/java/org/baeldung/spring/rest/compress/GzipUtils.java
Updated GzipUtils code following editor review.
See http://jira.baeldung.com/browse/BAEL-3188?focusedCommentId=106310&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-106310
**Please note that the link to the article in the README.md needs to be added.**
=> BAEL-3188 How to compress requests using the Spring RestTemplate.

spring-boot-admin/pom.xml, spring-boot-admin/spring-boot-admin-client/pom.xml, spring-boot-admin/spring-boot-admin-client/src/main/resources/application.properties, spring-boot-admin/spring-boot-admin-server/pom.xml, spring-boot-admin/spring-boot-admin-server/src/main/java/com/baeldung/springbootadminserver/SpringBootAdminServerApplication.java, spring-boot-admin/spring-boot-admin-server/src/main/java/com/baeldung/springbootadminserver/configs/HazelcastConfig.java, spring-boot-admin/spring-boot-admin-server/src/main/java/com/baeldung/springbootadminserver/configs/NotifierConfiguration.java, spring-boot-admin/spring-boot-admin-server/src/main/java/com/baeldung/springbootadminserver/configs/WebSecurityConfig.java, spring-boot-admin/spring-boot-admin-server/src/main/resources/application.properties, spring-boot-admin/spring-boot-admin-server/src/test/java/com/baeldung/springbootadminserver/NotifierConfigurationIntegrationTest.java, spring-boot-management/pom.xml, spring-boot-management/src/main/java/com/baeldung/spring/boot/management/logging/LoggingApplication.java, spring-boot-management/src/main/java/com/baeldung/spring/boot/management/logging/LoggingController.java, spring-boot-management/src/main/java/com/baeldung/spring/boot/management/logging/SecurityConfig.java, spring-boot-management/src/main/resources/application.properties, spring-boot-management/src/main/resources/logback.xml
Example code for BAEL-3222, but also updated spring-boot-admin article example to latest version of Spring Boot and Spring-Boot-Admin to make compatible with code for this article.
=> BAEL-3222 Example Code and update to spring-boot-admin examples

testing-modules/mockito/pom.xml, testing-modules/mockito/src/test/java/com/baeldung/powermockito/introduction/LuckyNumberGeneratorUnitTest.java, testing-modules/mockito/src/test/java/com/baeldung/powermockito/introduction/PowerMockitoUnitTest.java, testing-modules/mockito/src/test/java/org/baeldung/bddmockito/BDDMockitoUnitTest.java, testing-modules/mockito/src/test/java/org/baeldung/mockito/MockFinalsUnitTest.java, testing-modules/mockito/src/test/java/org/baeldung/mockito/MockitoAnnotationUnitTest.java, testing-modules/mockito/src/test/java/org/baeldung/mockito/MockitoConfigExamplesUnitTest.java, testing-modules/mockito/src/test/java/org/baeldung/mockito/MockitoExceptionUnitTest.java, testing-modules/mockito/src/test/java/org/baeldung/mockito/MockitoMockUnitTest.java, testing-modules/mockito/src/test/java/org/baeldung/mockito/MockitoVerifyExamplesUnitTest.java, testing-modules/mockito/src/test/java/org/baeldung/mockito/spy/MockitoSpyUnitTest.java
- Upgraded power-mockito api 2 jar
- Renamed many IntegrationTests back to UnitTests as they do not require any integration components
=> BAEL-17703 Fix the integrations tests in mockito

spring-boot-properties/extra.properties
- Committing initial value correctly
=> BAEL-17355 Fix the integrations tests in spring-boot-properties

spring-boot-custom-starter/README.md, spring-boot-disable-console-logging/README.md, spring-boot-gradle/README.md, spring-boot-jasypt/README.md, spring-boot-keycloak/README.md, spring-boot-kotlin/README.md, spring-boot-logging-log4j2/README.md, spring-boot-management/README.md, spring-boot-mvc-2/README.md, spring-boot-mvc-birt/README.md, spring-boot-mvc/README.md
spring-boot-custom-starter
spring-boot-disable-console-logging
spring-boot-gradle
spring-boot-jasypt
spring-boot-keycloak
spring-boot-kotlin
spring-boot-logging-log4j2
spring-boot-management
spring-boot-mvc
spring-boot-mvc-birt
=> [BAEL-17489] Adding README descriptions to the following modules:

libraries-testing/pom.xml, libraries-testing/src/test/java/com/baeldung/hamcrest/Animal.java, libraries-testing/src/test/java/com/baeldung/hamcrest/Cat.java, libraries-testing/src/test/java/com/baeldung/hamcrest/HamcrestMatcherUnitTest.java, libraries-testing/src/test/java/com/baeldung/hamcrest/IsPositiveInteger.java, libraries-testing/src/test/java/com/baeldung/hamcrest/Person.java
-Fixing serenity tests failing due to mismatching libraries
=> BAEL-17945 Fix the integrations tests in libraries

cdi/src/main/java/com/baeldung/cdi2observers/application/BootstrappingApplication.java, cdi/src/main/java/com/baeldung/cdi2observers/events/ExampleEvent.java, cdi/src/main/java/com/baeldung/cdi2observers/events/ExampleEventSource.java, cdi/src/main/java/com/baeldung/cdi2observers/observers/AnotherExampleEventObserver.java, cdi/src/main/java/com/baeldung/cdi2observers/observers/ExampleEventObserver.java, cdi/src/main/java/com/baeldung/cdi2observers/services/TextService.java, cdi/src/main/resources/META-INF/beans.xml, cdi/src/test/java/com/baeldung/test/cdi2observers/tests/TextServiceUnitTest.java, cdi/src/test/java/com/baeldung/test/dependencyinjection/TimeLoggerFactoryUnitTest.java
Current files use incorrect package `com.baeldung.cdi.cdi2observers`. Files are located under `com.baeldung.cdi2observers`
=> Fix CDI package names

spring-mvc-simple-2/src/main/java/com/baeldung/exclude_urls_filter/Application.java, spring-mvc-simple-2/src/main/java/com/baeldung/exclude_urls_filter/controller/FAQController.java, spring-mvc-simple-2/src/main/java/com/baeldung/exclude_urls_filter/controller/Ping.java, spring-mvc-simple-2/src/main/java/com/baeldung/exclude_urls_filter/filter/FilterRegistrationConfig.java, spring-mvc-simple-2/src/main/java/com/baeldung/exclude_urls_filter/filter/HeaderValidatorFilter.java, spring-mvc-simple-2/src/main/java/com/baeldung/exclude_urls_filter/filter/LogFilter.java, spring-mvc-simple-2/src/main/java/com/baeldung/exclude_urls_filter/service/FAQService.java, spring-mvc-simple-2/src/main/java/com/baeldung/exclude_urls_filter/service/FAQServiceImpl.java
- Add source code for a tutorial on Excluding URLs for a Filter in a Spring Web Application:
- Sample Spring Web Application using Custom Filters
- Custom Logic in Filters to Exclude URLs
- Reference: [BAEL-3223](http://jira.baeldung.com/browse/BAEL-3223)
=> BAEL-3223: Excluding URLs from a Spring Filter

spring-boot/src/test/java/com/baeldung/jsondateformat/ContactAppUnitTest.java, spring-boot/src/test/java/com/baeldung/jsondateformat/ContactAppWithObjectMapperCustomizerUnitTest.java
-Modified tests to used Random Port instead of Defined Port to avoid port conflicts
=> BAEL-18132 Fix the integrations tests in spring-boot

javaxval/README.md, javaxval/src/main/java/org/baeldung/javaxval/enums/CustomerTypeSubSetValidator.java, javaxval/src/main/java/org/baeldung/javaxval/enums/EnumNamePatternValidator.java, javaxval/src/main/java/org/baeldung/javaxval/enums/EnumSubSetValidator.java, javaxval/src/main/java/org/baeldung/javaxval/enums/InheritedCustomerTypeSubSetValidator.java, javaxval/src/main/java/org/baeldung/javaxval/enums/ValueOfEnumValidator.java, javaxval/src/main/java/org/baeldung/javaxval/enums/constraints/CustomerTypeSubset.java, javaxval/src/main/java/org/baeldung/javaxval/enums/constraints/EnumNamePattern.java, javaxval/src/main/java/org/baeldung/javaxval/enums/constraints/ValueOfEnum.java, javaxval/src/main/java/org/baeldung/javaxval/enums/demo/Customer.java, javaxval/src/main/java/org/baeldung/javaxval/enums/demo/CustomerType.java, javaxval/src/test/java/org/baeldung/javaxval/enums/CustomerTypeSubSetValidatorUnitTest.java, javaxval/src/test/java/org/baeldung/javaxval/enums/EnumNamePatternValidatorUnitTest.java, javaxval/src/test/java/org/baeldung/javaxval/enums/ValueOfEnumValidatorUnitTest.java, javaxval/src/test/java/org/baeldung/javaxval/enums/demo/CustomerUnitTest.java
Added code belonging to the blog validations for Enum types.
=> [BAEL-3306] Validations for Enum types

oauth2-framework-impl/README.md, reactor-core/README.md, resteasy/README.md, restx/README.md, rsocket/README.md, rule-engines/README.md, rxjava-2/README.md, rxjava/README.md, spf4j/README.md, spring-boot-performance/README.md, spring-boot-properties/README.md, spring-mvc-basics/README.md, twitter4j/README.md
=> #BAEL-17527 add README descriptions

core-java-modules/core-java-collections-list-2/src/main/java/com/baeldung/findastring/FindAStringInGivenList.java, core-java-modules/core-java-collections-list-2/src/test/java/com/baeldung/findastring/FindAStringInListUnitTest.java
This is the proposed example for the article specified in BAEL-3083.
=> Example added for BAEL-3083

animal-sniffer-mvn-plugin/pom.xml, apache-avro/pom.xml, apache-fop/pom.xml, apache-geode/pom.xml, apache-meecrowave/pom.xml, apache-olingo/olingo2/pom.xml, apache-pulsar/pom.xml, apache-solrj/pom.xml, apache-spark/pom.xml, apache-velocity/pom.xml, aws-lambda/pom.xml, aws/pom.xml, axon/pom.xml, azure/pom.xml, parent-java/pom.xml, parent-kotlin/pom.xml, parent-spring-4/pom.xml, parent-spring-5/pom.xml
=> BAEL-17684 POM Properties Cleanup

pom.xml, spring-boot-configuration/README.md, spring-boot-configuration/data-jpa-application/pom.xml, spring-boot-configuration/data-jpa-application/src/main/java/com/baeldung/data/jpa/ApplicationFound.java, spring-boot-configuration/data-jpa-application/src/main/java/com/baeldung/data/jpa/application/ApplicationNotFound.java, spring-boot-configuration/data-jpa-application/src/test/java/com/baeldung/data/jpa/DataJpaUnitTest.java, spring-boot-configuration/data-jpa-library/pom.xml, spring-boot-configuration/data-jpa-library/src/main/java/com/baeldung/data/jpa/libarary/model/Example.java, spring-boot-configuration/data-jpa-library/src/test/java/com/baeldung/data/jpa/TestApplication.java, spring-boot-configuration/data-jpa-library/src/test/java/com/baeldung/data/jpa/libarary/DataJpaUnitTest.java, spring-boot-configuration/pom.xml, spring-boot-exceptions/README.md
Add a simple example to show the correct (package) structure for using @DataJpaTest
=> BAEL-2350 - DataJpaTest Configuration not found

core-kotlin/src/main/kotlin/com/baeldung/builder/FoodOrder.kt
Made the class constructor private!
=> BAEL-3294: Builder Pattern in Kotlin

algorithms-miscellaneous-3/src/main/java/com/baeldung/algorithms/breadthfirstsearch/BreadthFirstSearchAlgorithm.java, algorithms-miscellaneous-3/src/main/java/com/baeldung/algorithms/breadthfirstsearch/Node.java, algorithms-miscellaneous-3/src/main/java/com/baeldung/algorithms/breadthfirstsearch/Tree.java, algorithms-miscellaneous-3/src/test/java/com/baeldung/algorithms/breadthfirstsearch/BreadthFirstSearchAlgorithmUnitTest.java
* Added Tree and algorithm tests for trees
* Implemented algorithm for trees
* Added algorithm for graphs
* Bidirectional graph
* Minor updates
* Readibility changes
=> dupirefr/dupire.francois+pro@gmail.com [BAEL-3128] Breadth-First Search Algorithm in Java

spring-cloud/pom.xml, spring-cloud/spring-cloud-zuul-fallback/README.md, spring-cloud/spring-cloud-zuul-fallback/api-gateway/pom.xml, spring-cloud/spring-cloud-zuul-fallback/api-gateway/src/main/java/com/baeldung/spring/cloud/apigateway/ApiGatewayApplication.java, spring-cloud/spring-cloud-zuul-fallback/api-gateway/src/main/java/com/baeldung/spring/cloud/apigateway/fallback/GatewayClientResponse.java, spring-cloud/spring-cloud-zuul-fallback/api-gateway/src/main/java/com/baeldung/spring/cloud/apigateway/fallback/GatewayServiceFallback.java, spring-cloud/spring-cloud-zuul-fallback/api-gateway/src/main/java/com/baeldung/spring/cloud/apigateway/fallback/WeatherServiceFallback.java, spring-cloud/spring-cloud-zuul-fallback/api-gateway/src/main/resources/application.yml, spring-cloud/spring-cloud-zuul-fallback/api-gateway/src/test/java/com/baeldung/spring/cloud/apigateway/ApiGatewayApplicationIntegrationTest.java, spring-cloud/spring-cloud-zuul-fallback/api-gateway/src/test/java/com/baeldung/spring/cloud/apigateway/fallback/GatewayServiceFallbackUnitTest.java, spring-cloud/spring-cloud-zuul-fallback/api-gateway/src/test/java/com/baeldung/spring/cloud/apigateway/fallback/WeatherServiceFallbackUnitTest.java, spring-cloud/spring-cloud-zuul-fallback/pom.xml, spring-cloud/spring-cloud-zuul-fallback/weather-service/pom.xml, spring-cloud/spring-cloud-zuul-fallback/weather-service/src/main/java/com/baeldung/spring/cloud/weatherservice/WeatherController.java, spring-cloud/spring-cloud-zuul-fallback/weather-service/src/main/java/com/baeldung/spring/cloud/weatherservice/WeatherServiceApplication.java, spring-cloud/spring-cloud-zuul-fallback/weather-service/src/main/resources/application.yml, spring-cloud/spring-cloud-zuul-fallback/weather-service/src/test/java/com/baeldung/spring/cloud/weatherservice/WeatherControllerIntegrationTest.java, spring-cloud/spring-cloud-zuul-fallback/weather-service/src/test/java/com/baeldung/spring/cloud/weatherservice/WeatherServiceApplicationIntegrationTest.java
BAEL-1363 Fallback for Zuul Routes
=> BAEL-1363 Fallback for Zuul Routes

persistence-modules/spring-persistence-simple/src/test/java/com/baeldung/persistence/service/transactional/FooTransactionalUnitTest.java, persistence-modules/spring-persistence-simple/src/test/java/com/baeldung/persistence/service/transactional/PersistenceTransactionalTestConfig.java
Unit tests for Transaction Propagation and Isolation in Spring @Transactional
=> #BAEL-3228: Unit tests for Transaction Propagation and Isolation in Spring

spring-integration/src/main/java/com/baeldung/dsl/JavaDSLFileCopyConfig.java
=> Spring Integration Java DSL - Github Issue 7885

core-java-modules/core-java-8/src/main/java/com/baeldung/java_8_features/groupingby/Tuple.java, core-java-modules/core-java-8/src/test/java/com/baeldung/java_8_features/groupingby/Java8GroupingByCollectorUnitTest.java
The Tuple had to be changed because it required an equals/hashcode
Also: formatted with eclipse profile
=> [BAEL-3292] Add missing code snippets from the Java 8 groupingBy article

spring-scheduling/README.md, spring-scheduling/src/main/java/org/baeldung/scheduling/ScheduledAnnotationExample.java, spring-scheduling/src/main/resources/springScheduled-config.xml
All the samples still existed with some slight variation, I updated where applicable
Main thing is that the link in the article has to be corrected
=> [BAEL-3289] Add missing code snippets from the Spring Scheduled article

java-dates-2/src/main/java/com/baeldung/date/conversion/ConvertToOffsetDateTime.java, java-dates-2/src/test/java/com/baeldung/date/conversion/ConvertToOffsetDateTimeUnitTest.java
http://inprogress.baeldung.com/wp-admin/post.php?post=161709&action=edit&classic-editor
=> BAEL-3310 Converting Java Date to OffsetDateTime

spring-rest/src/main/java/com/baeldung/resttemplate/lists/client/EmployeeClient.java
changes for http://jira.baeldung.com/browse/BAEL-3062
=> changes for handling arrays

spring-5-data-reactive/src/main/java/com/baeldung/r2dbc/configuration/R2DBCConfiguration.java, spring-5-data-reactive/src/main/java/com/baeldung/r2dbc/model/Player.java, spring-5-data-reactive/src/test/java/com/baeldung/r2dbc/R2dbcApplicationIntegrationTest.java
- Several fixes to fix the project setup in case of multiple spring data reactive repositories and fix assertion failures
=> BAEL-18211 Fix the integrations tests in spring-5-data-reactive

persistence-modules/spring-data-redis/src/main/java/com/baeldung/spring/data/redis/queue/RedisMessageSubscriber.java, persistence-modules/spring-data-redis/src/test/java/com/baeldung/spring/data/redis/RedisMessageListenerIntegrationTest.java
=> Revert "BAEL-3275: Using blocking queue for pub-sub"

spring-mvc-simple-2/src/main/java/com/baeldung/flash_attributes/Application.java, spring-mvc-simple-2/src/main/java/com/baeldung/flash_attributes/controllers/PoemSubmission.java, spring-mvc-simple-2/src/main/java/com/baeldung/flash_attributes/model/Poem.java, spring-mvc-simple-2/src/main/resources/application.properties, spring-mvc-simple-2/src/main/resources/templates/submit.html, spring-mvc-simple-2/src/main/resources/templates/success.html
- [BAEL-3284](http://jira.baeldung.com/browse/BAEL-3284)
=> BAEL-3284: Guide to Flash Attributes in a Spring Web Application

core-java-modules/core-java-streams-3/src/main/java/com/baeldung/streams/debug/entity/Customer.java, core-java-modules/core-java-streams-3/src/test/java/com/baeldung/streams/debug/Example1.java, core-java-modules/core-java-streams-3/src/test/java/com/baeldung/streams/debug/Example2.java
Add code samples for BAEL-3392 Debugging Java 8 Streams with IntelliJ
=> [BAEL-3392] Debugging Java 8 Streams with IntelliJ

httpclient/README.md, jackson/README.md, java-jdi/README.md, mapstruct/README.md, persistence-modules/spring-data-cassandra-reactive/README.md, spring-cloud/spring-cloud-stream-starters/README.md, spring-mvc-xml/README.md, spring-security-mvc-custom/README.md, spring-security-mvc-digest-auth/README.md, spring-security-mvc-ldap/README.md, spring-security-mvc-persisted-remember-me/README.md, spring-security-mvc/README.md, spring-security-rest-basic-auth/README.md, spring-security-rest-custom/README.md, testing-modules/rest-assured/README.md, testing-modules/rest-testing/README.md, testing-modules/xmlunit-2/README.md
Corrected sections without spaces
Best practice: add newline after section header
=> Some README rendering corrections

core-java-modules/core-java-lang-math/src/main/java/com/baeldung/strictfpUsage/Circle.java, core-java-modules/core-java-lang-math/src/main/java/com/baeldung/strictfpUsage/ScientificCalculator.java, core-java-modules/core-java-lang-math/src/test/java/com/baeldung/strictfpUsage/ScientificCalculatorUnitTest.java
Not deleted oop-4 module as it is already being used by other articles now
=> BAEL-3404 Review comments

twitter4j/src/test/java/com/baeldung/ApplicationManualTest.java
- Renaming ApplicationIntegrationTest.java to ApplicationManualTest.java
=> BAEL-19173 Fix the integrations tests in Twitter4J

spring-cloud/spring-cloud-eureka-self-preservation/pom.xml, spring-cloud/spring-cloud-eureka-self-preservation/spring-cloud-eureka-client/pom.xml, spring-cloud/spring-cloud-eureka-self-preservation/spring-cloud-eureka-client/src/main/java/com/baeldung/spring/cloud/eureka/client/EurekaClientApplication.java, spring-cloud/spring-cloud-eureka-self-preservation/spring-cloud-eureka-client/src/main/resources/application.properties, spring-cloud/spring-cloud-eureka-self-preservation/spring-cloud-eureka-server/pom.xml, spring-cloud/spring-cloud-eureka-self-preservation/spring-cloud-eureka-server/src/main/java/com/baeldung/spring/cloud/eureka/server/EurekaServerApplication.java, spring-cloud/spring-cloud-eureka-self-preservation/spring-cloud-eureka-server/src/main/resources/application.properties
=> BAEL - 1836

aws/src/test/java/com/baeldung/dynamodb/rule/LocalDbCreationRule.java
=> Update LocalDbCreationRule to respect shareDb parameter for embedded DynamoDB

spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/customfilters/filters/factories/ChainRequestGatewayFilterFactory.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/customfilters/filters/factories/LoggingGatewayFilterFactory.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/customfilters/filters/factories/ModifyRequestGatewayFilterFactory.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/customfilters/filters/global/FirstPreLastPostGlobalFilter.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/customfilters/filters/global/LoggingGlobalFiltersConfigurations.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/customfilters/filters/global/LoggingGlobalPreFilter.java, spring-cloud/spring-cloud-gateway/src/main/resources/customfilters-global-application.properties, spring-cloud/spring-cloud-gateway/src/test/java/com/baeldung/springcloudgateway/customfilters/CustomFiltersLiveTest.java
Jira: http://jira.baeldung.com/browse/BAEL-3313
IP: http://inprogress.baeldung.com/wp-admin/post.php?post=167975&action=edit&classic-editor
Addressed comments:
* Removed Global filter bean with @Order annotation, now using class that implements Ordered
* Added logic to actually mutate the request entity (and the exchange) for the Modify Request example
* changed endpoint for languageServiceEndpoint in the chain requests example
=> [BAEL-3313] spring-cloud/spring-cloud-gateway | Writing custom Spring Cloud Gateway Filters -- address comments

json/pom.xml, kotlin-libraries/pom.xml, libraries-3/pom.xml, libraries-apache-commons/pom.xml, libraries-data-2/pom.xml, libraries-data-db/pom.xml, libraries-data-io/pom.xml, libraries-data/pom.xml, libraries-http/pom.xml, libraries-primitive/pom.xml, libraries-security/pom.xml, libraries-server/pom.xml, libraries/pom.xml, linkrest/pom.xml, lucene/pom.xml, maven-all/maven/pom.xml, maven-polyglot/maven-polyglot-json-extension/pom.xml, mesos-marathon/pom.xml, metrics/pom.xml, microprofile/pom.xml, mustache/pom.xml, mybatis/pom.xml
- Properties cleanup of projects starting with k,l and m
=> BAEL-18777 POM Properties Cleanup #8234

spring-mvc-simple-2/src/main/java/com/baeldung/form_submission/Application.java, spring-mvc-simple-2/src/main/java/com/baeldung/form_submission/controllers/FeedbackForm.java, spring-mvc-simple-2/src/main/java/com/baeldung/form_submission/model/Feedback.java, spring-mvc-simple-2/src/main/resources/templates/feedback.html
- References:
- [BAEL-3307](http://jira.baeldung.com/browse/BAEL-3307)
=> Handling URL Encoded Data in Form Submission in a Spring REST Service

algorithms-miscellaneous-4/src/test/java/com/baeldung/algorithms/smallestinteger/SmallestMissingPositiveIntegerUnitTest.java
=> dupirefr/dupire.francois+pro@gmail.com [BAEL-3348] Added test using array from article comment

core-java-modules/core-java-jvm/src/main/java/com/baeldung/exitvshalt/JvmExitAndHaltDemo.java, core-java-modules/core-java-jvm/src/test/java/com/baeldung/exitvshalt/JvmExitDemoUnitTest.java, core-java-modules/core-java-jvm/src/test/java/com/baeldung/exitvshalt/JvmHaltDemoUnitTest.java
=> BAEL-3525: System.exit() vs Runtime.getRuntime().halt()

algorithms-miscellaneous-5/src/main/java/com/baeldung/algorithms/prim/Edge.java, algorithms-miscellaneous-5/src/main/java/com/baeldung/algorithms/prim/Prim.java, algorithms-miscellaneous-5/src/main/java/com/baeldung/algorithms/prim/Vertex.java, algorithms-miscellaneous-5/src/test/java/com/baeldung/algorithms/prim/PrimTest.java, algorithms-miscellaneous-5/src/test/java/com/baeldung/algorithms/prim/PrimUnitTest.java
=> BAEL-3561 Prim's Algorithm

core-java-modules/core-java-lang-math/src/main/java/com/baeldung/overflow/Overflow.java, core-java-modules/core-java-lang-math/src/test/java/com/baeldung/math/OverflowUnitTest.java, core-java-modules/core-java-lang-math/src/test/java/com/baeldung/overflow/OverflowUnitTest.java
Move test class to correct package
=> BAEL-3130 overflow and underflow in java

core-java-modules/core-java-io-apis/src/test/java/com/baeldung/file/FileClassUnitTest.java
I'm adding a few log statements to figure out why the test is failing on jenkins, whereas it's running fine locally.
=> BAEL-3651: Fix failing test in core-java-io-apis

core-java-modules/core-java-strings/src/test/java/com/baeldung/randomstrings/RandomStringsUnitTest.java
=> BAEL-3589 : Improvement: Java Generate Random String

parent-kotlin/pom.xml, persistence-modules/r2dbc/pom.xml, spring-5-data-reactive/pom.xml, spring-5-data-reactive/src/main/java/com/baeldung/r2dbc/repository/PlayerRepository.java, spring-5-data-reactive/src/test/java/com/baeldung/r2dbc/R2dbcApplicationIntegrationTest.java, spring-5-webflux/pom.xml, spring-boot-mvc-2/pom.xml
- Removed spring milestone repositories dependencies, used Central GA releases as a fix
=> BAEL-19376 Do we have any Spring Milestone/RC repos defined?

core-java-modules/core-java-datetime-java8/src/main/java/com/baeldung/datebasics/CreateDate.java, core-java-modules/core-java-datetime-java8/src/test/java/com/baeldung/datebasics/CreateDateUnitTest.java
Added Create Date class & Unit Tests for all the cases
=> vijay-sassy: Creating Date in java 8

java-numbers-2/pom.xml, java-numbers-2/src/main/java/com/baeldung/randomnumbers/RandomNumbersGenerator.java, java-numbers-2/src/test/java/com/baeldung/randomnumbers/RandomNumbersGeneratorUnitTest.java
=> BAEL-3678 - Generating Random Numbers - Initial commit

java-numbers-2/pom.xml, java-numbers-3/pom.xml, java-numbers-3/src/main/java/com/baeldung/randomnumbers/RandomNumbersGenerator.java, java-numbers-3/src/test/java/com/baeldung/randomnumbers/RandomNumbersGeneratorUnitTest.java
Moving code and examples to java-numbers-3 modules.
Added new methods and tests.
=> BAEL-3678 - Moving from java-numbers-2 to java-numbers-3

spring-cloud/spring-cloud-gateway/pom.xml, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/custompredicates/CustomPredicatesApplication.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/custompredicates/CustomRoutersGatewayApplication.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/custompredicates/config/CustomPredicatesConfig.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/custompredicates/factories/GoldenCustomerRoutePredicateFactory.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/custompredicates/service/GoldenCustomerService.java, spring-cloud/spring-cloud-gateway/src/main/resources/application-customroutes.yml, spring-cloud/spring-cloud-gateway/src/test/java/com/baeldung/springcloudgateway/customfilters/gatewayapp/CustomFiltersLiveTest.java, spring-cloud/spring-cloud-gateway/src/test/java/com/baeldung/springcloudgateway/custompredicates/CustomPredicatesApplicationLiveTest.java
Article Link: http://inprogress.baeldung.com/wp-admin/post.php?post=175639&action=edit&classic-editor
=> [BAEL-3311] Spring Cloud Gateway Routing Predicate Factories

netflix-modules/genie/pom.xml, netflix-modules/pom.xml, osgi/pom.xml, patterns/design-patterns-architectural/pom.xml, patterns/design-patterns-behavioral-2/pom.xml, patterns/design-patterns-behavioral/pom.xml, patterns/design-patterns-cloud/pom.xml, patterns/design-patterns-creational/pom.xml, patterns/design-patterns-functional/pom.xml, patterns/design-patterns-structural/pom.xml, patterns/dip/pom.xml, patterns/front-controller/pom.xml, patterns/intercepting-filter/pom.xml, patterns/pom.xml, patterns/solid/pom.xml, performance-tests/src/main/java/com/baeldung/performancetests/MappingFrameworksPerformance.java
- Cleaning properties of project starting with name n,o and p
=> BAEL-20759 CLONE - Week 2 | POM Properties Cleanup

quarkus-extension/pom.xml, quarkus-extension/quarkus-app/pom.xml, quarkus-extension/quarkus-liquibase/pom.xml, quarkus-extension/quarkus-liquibase/runtime/pom.xml, quarkus/pom.xml, rabbitmq/pom.xml, ratpack/pom.xml, restx/pom.xml, rsocket/pom.xml, rule-engines/easy-rules/pom.xml, rule-engines/openl-tablets/pom.xml, rule-engines/pom.xml, rule-engines/rulebook/pom.xml
- Cleaning pom.xml for project names starting with p,q and r
=> BAEL-21545 POM Properties Cleanup

core-java-modules/core-java-exceptions-2/src/main/java/com/baeldung/socketexception/SocketClient.java, core-java-modules/core-java-exceptions-2/src/main/java/com/baeldung/socketexception/SocketServer.java, core-java-modules/core-java-exceptions-2/src/test/java/com/baeldung/socketexception/SocketExceptionHandlingUnitTest.java
java.net.SocketException: Connection reset
=> java.net.SocketException: Connection reset

persistence-modules/redis/src/main/java/com/baeldung/redis_scan/client/RedisClient.java, persistence-modules/redis/src/test/java/com/baeldung/redis_scan/NaiveApproachIntegrationTest.java, persistence-modules/redis/src/test/java/com/baeldung/redis_scan/ScanStrategyIntegrationTest.java
- Resolves a race condition where a client instance is closed
before it can be used by another test
=> Resolve Redis Client Connection Issue in Integration Test

persistence-modules/java-mongodb/src/test/java/com/baeldung/aggregation/AggregationLiveTest.java
Added test for languages, removed for regionalBlocs
=> BAEL-2972 : MongoDB Aggregations Using Java

testing-modules/junit5-annotations/pom.xml, testing-modules/junit5-annotations/src/test/java/com/baeldung/junit5/conditional/ConditionalAnnotationsUnitTest.java
Added two tests and removed a few deprecated stuff.
=> Bael 3850: EnabledForJRERange and DisabledForJRERange JUnit Annotations

spring-core-3/static-value-injection/README.md, spring-core-3/static-value-injection/pom.xml, spring-core-3/static-value-injection/src/main/java/com/baeldung/Application.java, spring-core-3/static-value-injection/src/main/java/com/baeldung/controller/PropertyController.java, spring-core-3/static-value-injection/src/main/resources/application.properties, spring-core-3/static-value-injection/src/test/java/com/baeldung/ApplicationTests.java
**JIRA:**
http://jira.baeldung.com/browse/BAEL-3835
**Article:**
http://inprogress.baeldung.com/?p=180479&preview=true
**Name:**
Georgios Charitakis
=> BAEL-3835: Inject a value to a static field

spring-5-webflux/src/main/java/com/baeldung/spring/serverconfig/TimeoutController.java, spring-5-webflux/src/test/java/com/baeldung/spring/serverconfig/TimeoutLiveTest.java
- Add controller and unit test showing how to set timeouts
=> BAEL-2552 - spatialguru.net@gmail.com

libraries/pom.xml, libraries/src/main/java/com/baeldung/nullaway/NullAwayExample.java
PR from new cloned repository.
=> BAEL-3461 NullAwayExample

gson/src/test/java/com/baeldung/gson/jsoncompare/JsonCompareUnitTest.java
Compare Two JSON Objects with Gson article
=> How to compare json objects using gson article

core-java-modules/core-java-string-operations-2/README.md, core-java-modules/core-java-string-operations-2/pom.xml, core-java-modules/core-java-string-operations-2/src/main/java/com/baeldung/trim/LTrimRTrim.java, core-java-modules/core-java-string-operations-2/src/test/java/com/baeldung/trim/LTrimRTrimUnitTest.java
- Add LTrim and RTrim alternatives for Java
- Include Unit Testings
- Modify the README file to fix an old reference
- [] Refactoring (no functional changes, no api changes)
- It includes examples of how to support LTrim and RTrim functionality
- Modify the README file to link to the article fixing and old reference
=> [BAEL 3755] - LTrim and RTrim Alternatives in Java

libraries-3/src/main/java/com/baeldung/arthas/FibonacciGenerator.java
Adding a case study to show Arthas.
=> BAEL-3635 Intro to Alibaba Arthas

README.md, parent-kotlin/pom.xml
- Updated README.md as per the latest profile based segregation that we follow in this repository
=> JAVA-60 Mvn Clean Install Profile Issue - Github 8189

spring-reactive-kotlin/pom.xml, spring-reactive-kotlin/src/main/kotlin/com/baeldung/bootmicroservice/HealthTrackerApplication.kt, spring-reactive-kotlin/src/main/kotlin/com/baeldung/bootmicroservice/config/DBConfiguration.kt, spring-reactive-kotlin/src/main/kotlin/com/baeldung/bootmicroservice/controller/HealthRecordController.kt, spring-reactive-kotlin/src/main/kotlin/com/baeldung/bootmicroservice/controller/ProfileController.kt, spring-reactive-kotlin/src/main/kotlin/com/baeldung/bootmicroservice/model/AverageHealthStatus.kt, spring-reactive-kotlin/src/main/kotlin/com/baeldung/bootmicroservice/model/HealthRecord.kt, spring-reactive-kotlin/src/main/kotlin/com/baeldung/bootmicroservice/model/Profile.kt, spring-reactive-kotlin/src/main/kotlin/com/baeldung/bootmicroservice/repository/HealthRecordRepository.kt, spring-reactive-kotlin/src/main/kotlin/com/baeldung/bootmicroservice/repository/ProfileRepository.kt, spring-reactive-kotlin/src/main/resources/application.yml, spring-reactive-kotlin/src/test/kotlin/com/baeldung/bootmicroservice/controller/ProfileControllerTest.kt
Sample codes for Kotlin Microservice With Spring Boot
=> KTLN-18: Kotlin Microservice With Spring Boot

spring-thymeleaf-2/src/main/java/com/baeldung/thymeleaf/mvcdata/BeanConfig.java, spring-thymeleaf-2/src/main/java/com/baeldung/thymeleaf/mvcdata/EmailController.java, spring-thymeleaf-2/src/main/java/com/baeldung/thymeleaf/mvcdata/repository/EmailData.java, spring-thymeleaf-2/src/main/resources/templates/mvcdata/email-bean-data.html, spring-thymeleaf-2/src/main/resources/templates/mvcdata/email-model-attributes.html, spring-thymeleaf-2/src/main/resources/templates/mvcdata/email-request-parameters.html, spring-thymeleaf-2/src/main/resources/templates/mvcdata/email-servlet-context.html, spring-thymeleaf-2/src/main/resources/templates/mvcdata/email-session-attributes.html, spring-thymeleaf-2/src/test/java/com/baeldung/thymeleaf/mvcdata/EmailControllerUnitTest.java
- Code example for https://jira.baeldung.com/browse/BAEL-3011
=> [BAEL-3011] Accesing Spring MVC Data from Thymeleaf

jhipster-5/bookstore-monolith/pom.xml, jhipster-5/bookstore-monolith/src/test/java/com/baeldung/jhipster5/service/mapper/UserMapperIntegrationTest.java
* Migrate UserMapperUnitTest to UserMapperIntegrationTest as it uses
Spring and takes a lot of time to execute
=> [JAVA-1265] Review build time

spring-5-security/src/main/java/com/baeldung/manuallogout/BasicAuthController.java, spring-5-security/src/main/java/com/baeldung/manuallogout/ClearSiteDataController.java, spring-5-security/src/main/java/com/baeldung/manuallogout/ManualLogoutApplication.java, spring-5-security/src/main/java/com/baeldung/manuallogout/SimpleSecurityConfiguration.java, spring-5-security/src/test/java/com/baeldung/manuallogout/ManualLogoutIntegrationTest.java
- Basic manual logout
- logout with Clear Data Site Header
=> BAEL 3970 - Manual logout with Spring Security

testing-modules/mockito-2/src/main/java/com/baeldung/mockito/additionalanswers/BookRepository.java, testing-modules/mockito-2/src/main/java/com/baeldung/mockito/additionalanswers/BookService.java, testing-modules/mockito-2/src/test/java/com/baeldung/mockito/additionalanswers/BookServiceUnitTest.java
Following Kevin's suggestion and changing the repository method to a more realistic one
=> Belma Jakupovic - additional answers mockito

pom.xml
* JUnit version upgraded from 4.12 to 4.13
* Maven Surefire Plugin version upgraded from 2.21.0 to 2.22.2
=> [JAVA-109] Upgraded JUnit and Maven Surefire Plugin versions

mesos-marathon/README.md, mesos-marathon/pom.xml, mesos-marathon/src/test/java/com/baeldung/DemoApplicationIntegrationTest.java, persistence-modules/flyway/pom.xml, persistence-modules/flyway/src/main/resources/application.properties
Includes JAVA-921 (mesos-marathon) and JAVA-922 (flyway)
=> JAVA-913: migrate parent-boot-1 articles to parent-boot-2

spring-security-modules/spring-security-core/src/main/java/com/baeldung/app/controller/TaskController.java
Add examples of checking user roles in Java
=> BAEL-3972: check user roles in Java

patterns/solid/src/main/java/com/baeldung/s/TextManipulator.java, patterns/solid/src/main/java/com/baeldung/s/TextPrinter.java
Example code for http://jira.baeldung.com/browse/BAEL-4004
=> bjakupovic - single responsibility principle example

persistence-modules/redis/pom.xml, persistence-modules/redis/src/main/java/com/baeldung/spring/redis/configuration/RedisConfig.java, persistence-modules/redis/src/main/java/com/baeldung/spring/redis/configuration/SpringRedisConfigurationApplication.java, persistence-modules/redis/src/main/java/com/baeldung/spring/redis/configuration/controller/BooksController.java, persistence-modules/redis/src/main/java/com/baeldung/spring/redis/configuration/entity/Book.java, persistence-modules/redis/src/main/java/com/baeldung/spring/redis/configuration/repository/BooksRepository.java, persistence-modules/redis/src/main/resources/application.properties, persistence-modules/redis/src/test/java/com/baeldung/spring/redis/configuration/controller/BooksControllerUnitTest.java, persistence-modules/redis/src/test/java/com/baeldung/spring/redis/configuration/repository/BooksRepositoryUnitTest.java
Spring Boot example with tests
=> [BAEL-3614] - Spring Redis Configuration From application.properties File

spring-cloud/spring-cloud-gateway/pom.xml, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/webfilters/WebFilterGatewayApplication.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/webfilters/config/ModifyBodyRouteConfig.java, spring-cloud/spring-cloud-gateway/src/main/java/com/baeldung/springcloudgateway/webfilters/config/RequestRateLimiterResolverConfig.java, spring-cloud/spring-cloud-gateway/src/main/resources/application-webfilters.yml, spring-cloud/spring-cloud-gateway/src/test/java/com/baeldung/springcloudgateway/webfilters/RedisWebFilterFactoriesLiveTest.java, spring-cloud/spring-cloud-gateway/src/test/java/com/baeldung/springcloudgateway/webfilters/WebFilterFactoriesLiveTest.java, spring-cloud/spring-cloud-gateway/src/test/resources/logback-test.xml
- Add WebFilter Factories implementation
- Add Unit Testing
- Modify the pom to include Circuit Breaker dependencies and upgrade Spring Boot and Spring Cloud versions
=> BAEL-3312 Spring Cloud Gateway WebFilter Factories

java-collections-conversions/src/main/java/com/baeldung/convertlisttomap/ConvertListToMapService.java, java-collections-conversions/src/test/java/com/baeldung/convertcollectiontoarraylist/CollectionToArrayListUnitTest.java, java-collections-conversions/src/test/java/com/baeldung/convertiteratortolist/ConvertIteratorToListServiceUnitTest.java
Just tiny clean up and simplifications by function references and specialized assertions
=> Cleanup and function references

persistence-modules/java-mongodb/src/main/java/com/baeldung/bsontojson/Book.java, persistence-modules/java-mongodb/src/main/java/com/baeldung/bsontojson/Publisher.java, persistence-modules/java-mongodb/src/test/java/com/baeldung/bsontojson/BsonToJsonLiveTest.java
moving the BSON to JSON entities to dedicated package
=> BAEL-3943 fix package

core-kotlin-modules/core-kotlin-lang-2/src/main/kotlin/com/baeldung/ifelseexpression/IfElseExpressionExample.kt, core-kotlin-modules/core-kotlin-lang-2/src/test/kotlin/com/baeldung/ifelseexpression/IfElseExpressionExampleTest.kt
Kotlin if-else expression examples
=> KTLN-140 Kotlin if-else expressions

parent-kotlin/pom.xml, spring-boot-modules/spring-boot-mvc-2/pom.xml
- Removed spring milestone/snapshots repositories from modules
=> JAVA-991 Week 14 | Do we have any Spring Milestone/RC repos defined?

aws-app-sync/src/main/java/com/baeldung/awsappsync/AppSyncClientHelper.java, aws-app-sync/src/test/java/com/baeldung/awsappsync/AwsAppSyncApplicationTests.java, pom.xml
=> Bael-3893 - Fixed tests causing build to fail

spring-mvc-webflow/pom.xml
Added TomEE application server using `tomee-maven-plugin` that could quickly run application using `mvn tomee:run`.
=> Add embedded app server

testing-modules/testng/pom.xml
I have verified the existing code also works with 7.10
=> tested the code with latest testng version 7.1.0

spring-boot-modules/spring-boot-springdoc/pom.xml, spring-boot-modules/spring-boot-springdoc/src/main/java/com/baeldung/springdoc/controller/BookController.java, spring-boot-modules/spring-boot-springdoc/src/main/java/com/baeldung/springdoc/kotlin/Foo.kt, spring-boot-modules/spring-boot-springdoc/src/main/java/com/baeldung/springdoc/kotlin/FooController.kt, spring-boot-modules/spring-boot-springdoc/src/main/resources/application.properties
=> BAEL-3609: Improve article Documenting a Spring REST API Using OpenAPI

spring-boot-modules/spring-boot-properties/.dockerignore, spring-boot-modules/spring-boot-properties/Dockerfile, spring-boot-modules/spring-boot-properties/pom.xml, spring-boot-modules/spring-boot-properties/src/main/resources/application.yml, spring-boot-modules/spring-boot-properties/src/test/java/com/baeldung/yaml/YAMLDevIntegrationTest.java, spring-boot-modules/spring-boot-properties/src/test/java/com/baeldung/yaml/YAMLIntegrationTest.java
- Add Dockerfile and .dockerignore
- Modify the YAML application file to demonstration the deployment with Docker
- Modify the pom to run the YAML application
=> BAEL-3756-YAML-for-Spring-DevOps

spring-core-4/src/main/java/com/baeldung/importannotation/animal/AnimalConfiguration.java, spring-core-4/src/main/java/com/baeldung/importannotation/animal/AnimalScanConfiguration.java, spring-core-4/src/main/java/com/baeldung/importannotation/animal/Bird.java, spring-core-4/src/main/java/com/baeldung/importannotation/animal/BirdConfig.java, spring-core-4/src/main/java/com/baeldung/importannotation/animal/Bug.java, spring-core-4/src/main/java/com/baeldung/importannotation/animal/BugConfig.java, spring-core-4/src/main/java/com/baeldung/importannotation/animal/Cat.java, spring-core-4/src/main/java/com/baeldung/importannotation/animal/CatConfig.java, spring-core-4/src/main/java/com/baeldung/importannotation/animal/Dog.java, spring-core-4/src/main/java/com/baeldung/importannotation/animal/DogConfig.java, spring-core-4/src/main/java/com/baeldung/importannotation/animal/MammalConfiguration.java, spring-core-4/src/main/java/com/baeldung/importannotation/zoo/ZooApplication.java, spring-core-4/src/test/java/com/baeldung/importannotation/animal/AnimalConfigUnitTest.java, spring-core-4/src/test/java/com/baeldung/importannotation/animal/BugConfigUnitTest.java, spring-core-4/src/test/java/com/baeldung/importannotation/animal/ConfigUnitTest.java, spring-core-4/src/test/java/com/baeldung/importannotation/animal/MammalConfigUnitTest.java, spring-core-4/src/test/java/com/baeldung/importannotation/zoo/ZooApplicationUnitTest.java
Spring @Import Annotation article - initial version.
=>  Spring Import Annotation - initial commit

core-java-modules/core-java-exceptions-2/src/test/java/com/baeldung/exceptions/TooManyOpenFilesExceptionLiveTest.java
http://jira.baeldung.com/browse/BAEL-4154
=> BAEL-4154 IOException Too many open files

data-structures/src/main/java/com/baeldung/circularbuffer/CircularBuffer.java, data-structures/src/test/java/com/baeldung/circularbuffer/CircularBufferUnitTest.java, data-structures/src/test/java/com/baeldung/circularbuffer/ProducerConsumerLiveTest.java
http://jira.baeldung.com/browse/BAEL-4145
=> BAEL-4145 Circular Buffer

spring-security-modules/spring-security-mvc-boot-2/src/main/java/com/baeldung/loginredirect/LoginPageFilter.java, spring-security-modules/spring-security-mvc-boot-2/src/main/java/com/baeldung/loginredirect/LoginPageInterceptor.java, spring-security-modules/spring-security-mvc-boot-2/src/main/java/com/baeldung/loginredirect/LoginRedirectApplication.java, spring-security-modules/spring-security-mvc-boot-2/src/main/java/com/baeldung/loginredirect/LoginRedirectMvcConfig.java, spring-security-modules/spring-security-mvc-boot-2/src/main/java/com/baeldung/loginredirect/LoginRedirectSecurityConfig.java, spring-security-modules/spring-security-mvc-boot-2/src/main/java/com/baeldung/loginredirect/UsersController.java, spring-security-modules/spring-security-mvc-boot-2/src/main/resources/spring-security-login-redirect.xml, spring-security-modules/spring-security-mvc-boot-2/src/main/resources/templates/userMainPage.html
PR for [BAEL-4018](http://jira.baeldung.com/browse/BAEL-4018)
=> BAEL-4018 Spring Security - Already logged in user redirect from the login page

spring-boot-modules/pom.xml, spring-boot-modules/spring-boot-libraries/pom.xml, spring-boot-modules/spring-boot-mvc-2/pom.xml, spring-boot-modules/spring-boot-mvc-3/pom.xml, spring-boot-modules/spring-boot-mvc-birt/pom.xml, spring-boot-modules/spring-boot-mvc/pom.xml, spring-boot-modules/spring-boot-nashorn/pom.xml, spring-boot-modules/spring-boot-parent/pom.xml, spring-boot-modules/spring-boot-parent/spring-boot-with-custom-parent/pom.xml, spring-boot-modules/spring-boot-parent/spring-boot-with-starter-parent/pom.xml, spring-boot-modules/spring-boot-performance/pom.xml, spring-boot-modules/spring-boot-properties-2/pom.xml, spring-boot-modules/spring-boot-properties/pom.xml, spring-boot-modules/spring-boot-runtime/disabling-console-jul/pom.xml, spring-boot-modules/spring-boot-runtime/disabling-console-log4j2/pom.xml, spring-boot-modules/spring-boot-runtime/disabling-console-logback/pom.xml, spring-boot-modules/spring-boot-runtime/pom.xml, spring-boot-modules/spring-boot-security/pom.xml, spring-boot-modules/spring-boot-springdoc/pom.xml, spring-boot-modules/spring-boot-testing/pom.xml, spring-boot-modules/spring-boot-vue/pom.xml
Changed sub-modules inheritance (second batch)
* Imported junit bom before spring-boot-dependencies bom with correct version
* Changed spring-boot-libraries
* Changed spring-boot-mvc
* Changed spring-boot-mvc-2
* Added and changed spring-boot-mvc-3
* Changed spring-boot-mvc-birt
* Changed spring-boot-nashorn
* Changed spring-boot-parent and its submodules
* Changed spring-boot-performance
* Changed spring-boot-properties
* Changed spring-boot-properties-2
* Changed spring-boot-runtime and its sub-modules
* Changed spring-boot-security
* Changed spring-boot-springdoc
* Changed spring-boot-testing
* Changed spring-boot-vue
=> [JAVA-1670] Upgrade JUnit and Maven Surefire Plugin in spring-boot-modules

core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/localvariables/LocalAndLambda.java, core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/localvariables/LocalVariables.java
Added two small example for article about thread-safety for local variables.
=> [BAEL-4213] Why are local variables thread safe

core-java-modules/core-java-collections-3/pom.xml, core-java-modules/core-java-collections-3/src/main/java/com/baeldung/collections/convertarrayprimitives/ConvertPrimitivesArrayToList.java, core-java-modules/core-java-collections-3/src/test/java/com/baeldung/collections/convertarrayprimitives/ConvertPrimitivesArrayToListUnitTest.java
=> feat: Convert an array of primitives to a List

spring-boot-modules/spring-boot-client/pom.xml, spring-boot-modules/spring-boot-parent/spring-boot-with-starter-parent/pom.xml
* Removed junit-platform version overriding from spring-boot-client
* Removed junit version overriding from spring-boot-with-starter-parent
=> [JAVA-1670] Follow-up fixes

java-collections-conversions-2/src/main/java/com/baeldung/convertlisttomap/ListToMapConverter.java, java-collections-conversions-2/src/test/java/com/baeldung/convertlisttomap/ListToMapUnitTest.java
Article: List to Map Conversion With Java 8 Stream API
=> Leasy Zhang/shiwangzhihe@gmail.com

guava-modules/pom.xml
instead of inheriting from parent
=> JAVA-2154: Added guava dependency to module pom directly

json-2/src/test/java/com/baeldung/jsonld/deserialization/jsonldjava/jackson/JacksonDeserializationUnitTest.java, json-2/src/test/java/com/baeldung/jsonld/deserialization/jsonldjava/jackson/Person.java, json-2/src/test/java/com/baeldung/jsonld/serialization/hydrajsonld/HydraJsonldSerializationUnitTest.java, json-2/src/test/java/com/baeldung/jsonld/serialization/hydrajsonld/Person.java, json-2/src/test/java/com/baeldung/jsonld/serialization/jacksonjsonld/JacksonJsonLdSerializationUnitTest.java, json-2/src/test/java/com/baeldung/jsonld/serialization/jacksonjsonld/Person.java
After a fresh pair of eyes looked at the article, there were some changes requested.
=> BAEL-1488: JSON-LD

persistence-modules/core-java-persistence/src/main/java/com/baeldung/jdbcmetadata/DatabaseConfig.java, persistence-modules/core-java-persistence/src/main/java/com/baeldung/jdbcmetadata/JdbcMetadataApplication.java, persistence-modules/core-java-persistence/src/main/java/com/baeldung/jdbcmetadata/MetadataExtractor.java
http://jira.baeldung.com/browse/BAEL-4431
http://inprogress.baeldung.com/?p=222927&preview=true
http://inprogress.baeldung.com/wp-admin/post.php?post=222927&action=edit&classic-editor&classic-editor__forget
=> BAEL-4431-jdbcmetadata: Article about extracting metadata using JDBC

spring-cloud/spring-cloud-consul/pom.xml, spring-cloud/spring-cloud-consul/src/main/java/com/baeldung/spring/cloud/consul/discovery/DiscoveryClientApplication.java, spring-cloud/spring-cloud-consul/src/main/java/com/baeldung/spring/cloud/consul/leadership/LeadershipElection.java, spring-cloud/spring-cloud-consul/src/main/resources/application.yml
- Upgrade Spring Cloud Consul to the latest version
- Minor fixing
- Include Java example and configuration for Leadership Election with Consul
I followed [those guidelines](https://learn.hashicorp.com/consul/developer-configuration/elections) how Consul can help in the leadership election using sessions and K/V store
=> BAEL-3217 Leadership Election with Consul

spring-boot-modules/spring-boot-autoconfiguration/src/main/java/com/baeldung/conditionalonproperty/NotificationApplication.java, spring-boot-modules/spring-boot-autoconfiguration/src/main/java/com/baeldung/conditionalonproperty/config/NotificationConfig.java, spring-boot-modules/spring-boot-autoconfiguration/src/main/java/com/baeldung/conditionalonproperty/service/EmailNotification.java, spring-boot-modules/spring-boot-autoconfiguration/src/main/java/com/baeldung/conditionalonproperty/service/NotificationSender.java, spring-boot-modules/spring-boot-autoconfiguration/src/main/java/com/baeldung/conditionalonproperty/service/SmsNotification.java, spring-boot-modules/spring-boot-autoconfiguration/src/main/resources/application.properties, spring-boot-modules/spring-boot-autoconfiguration/src/test/java/com/baeldung/conditionalonproperty/NotificationUnitTest.java
=> BAEL-4244: What is purpose of @ConditionalOnProperty annotation?

core-java-modules/core-java-lang-math-2/src/main/java/com/baeldung/algorithms/largestpowerof2/LargestPowerOf2.java, core-java-modules/core-java-lang-math-2/src/test/java/com/baeldung/algorithms/largestpowerof2/LargestPowerOf2UnitTest.java
article: find the largest power of 2 that is less than the given number
=> BAEL-4523 - Added code example 

core-groovy-strings/README.md, core-groovy-strings/pom.xml, core-groovy-strings/src/test/groovy/com/baeldung/removeprefix/RemovePrefixTest.groovy, pom.xml
Remove prefix from string using groovy (BAEL-4104)
=> Remove prefix from string using groovy (BAEL-4104)

spring-mvc-basics-4/src/main/java/com/baeldung/jsonparams/config/JsonParamsConfig.java, spring-mvc-basics-4/src/main/java/com/baeldung/jsonparams/config/JsonParamsInit.java, spring-mvc-basics-4/src/main/java/com/baeldung/jsonparams/controller/ProductController.java, spring-mvc-basics-4/src/main/java/com/baeldung/jsonparams/model/Product.java, spring-mvc-basics-4/src/main/java/com/baeldung/jsonparams/propertyeditor/ProductEditor.java, spring-mvc-basics-4/src/test/java/com/baeldung/jsonparams/JsonParamsIntegrationTest.java
=> BAEL-4327: JSON Parameters with Spring MVC

core-java-modules/core-java-lang-oop-methods/src/main/java/com/baeldung/signature/OverloadingErrors.java, core-java-modules/core-java-lang-oop-methods/src/main/java/com/baeldung/signature/StaticBinding.java
BAEL-4156 Does a method's signature in Java include its return type?
=> BAEL-4156 Does a method's signature in Java include its return type?

core-java-modules/core-java-io-3/src/main/java/com/baeldung/lastmodifiedfile/LastModifiedFileApp.java, core-java-modules/core-java-io-3/src/test/java/com/baeldung/lastmodifiedfile/LastModifiedFileAppUnitTest.java
=> BAEL-4396: Find the last modified file in a directory with Java

core-java-modules/core-java-security-2/src/test/java/certificates/CertificatesUnitTest.java, core-java-modules/core-java-security-2/src/test/java/com/baeldung/trustedcert/CertificatesUnitTest.java
BAEL-4415 get a list of trusted certificates in Java
=> BAEL-4415 get a list of trusted certificates in Java

persistence-modules/spring-hibernate-5/README.md
Removed legacy hibernate-4-spring article
=> JAVA-2432 Move articles out of spring-hibernate4

spring-boot-modules/spring-boot-keycloak/pom.xml
JIRA: http://team.baeldung.com/browse/JAVA-3002
=> [JAVA-3002] updated Keycloak dependencies version to 11.0.2

core-kotlin-modules/core-kotlin-lang/src/main/kotlin/com/baeldung/inline/Inline.kt
=> Revert "KTLN-8: Non-Local Returns"

persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/states/Application.java, persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/states/UserEntity.java, persistence-modules/spring-boot-persistence-2/src/main/java/com/baeldung/states/UserEntityWithCascade.java, persistence-modules/spring-boot-persistence-2/src/test/java/com/baeldung/states/UserEntityIntegrationTest.java
JIRA: http://jira.baeldung.com/browse/BAEL-4565
Draft: https://drafts.baeldung.com/wp-admin/post.php?post=88294&action=edit
=> BAEL-4565 Object States in Hibernate's Session

persistence-modules/spring-data-jpa-crud/pom.xml
The project still builds.
All tests still run fine.
=> Eliminate duplicate dependency spring-boot-starter-web

vavr/src/test/java/com/baeldung/vavr/VavrUnitTest.java
I've added some examples for Vavr Tuple 
- How to update a tuple 
- Know the number of elements of a tuple
=> Add Vavr Tuple example

core-kotlin-modules/core-kotlin-concurrency/src/main/kotlin/com/baeldung/channles/BufferedChannel.kt, core-kotlin-modules/core-kotlin-concurrency/src/main/kotlin/com/baeldung/channles/ConflatedChannel.kt, core-kotlin-modules/core-kotlin-concurrency/src/main/kotlin/com/baeldung/channles/PizzaPipeline.kt, core-kotlin-modules/core-kotlin-concurrency/src/main/kotlin/com/baeldung/channles/ProducerConsumer.kt, core-kotlin-modules/core-kotlin-concurrency/src/main/kotlin/com/baeldung/channles/RendezvousChannel.kt, core-kotlin-modules/core-kotlin-concurrency/src/main/kotlin/com/baeldung/channles/SeveralProducersOneConsumer.kt, core-kotlin-modules/core-kotlin-concurrency/src/main/kotlin/com/baeldung/channles/SingleProducerSeveralConsumers.kt, core-kotlin-modules/core-kotlin-concurrency/src/main/kotlin/com/baeldung/channles/TickerChannel.kt, core-kotlin-modules/core-kotlin-concurrency/src/main/kotlin/com/baeldung/channles/UnlimitedChannel.kt, core-kotlin-modules/core-kotlin-concurrency/src/main/kotlin/com/baeldung/channles/logger.kt, core-kotlin-modules/core-kotlin-concurrency/src/test/kotlin/com/baeldung/channels/ChannelsTest.kt
This is for https://drafts.baeldung.com/wp-admin/post.php?post=90558&action=edit
=> Channels examples

core-java-modules/core-java-lang-3/src/main/java/com/baeldung/transientkw/Book.java, core-java-modules/core-java-lang-3/src/main/java/com/baeldung/transientkw/BookSerDe.java, core-java-modules/core-java-lang-3/src/test/java/com/baeldung/transientkw/TransientUnitTest.java
Added code and tests to showcase the behavior of transient keyword in Java
=> BAEL-4645|Transient keyword in Java

persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/removal/LineItem.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/removal/OrderRequest.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/removal/ShipmentInfo.java, persistence-modules/java-jpa-3/src/main/resources/META-INF/persistence.xml, persistence-modules/java-jpa-3/src/test/java/com/baeldung/jpa/removal/CascadeTypeRemoveIntegrationTest.java, persistence-modules/java-jpa-3/src/test/java/com/baeldung/jpa/removal/OrphanRemovalIntegrationTest.java
* Defines the Domain: ShipmentInfo, LineItem and OrderRequest entity
* Adds CascadeTypeRemoveIntegrationTest
* Adds OrphanRemovalIntegrationTest
=> BAEL-4643: JPA CascadeType.REMOVE vs orphanRemoval

docker/docker-internal-dto/pom.xml, docker/docker-internal-dto/src/main/java/com/baeldung/docker/VariableDto.java, docker/docker-internal-dto/src/main/java/com/baeldung/docker/dto/VariableDto.java, docker/docker-spring-boot/pom.xml, docker/docker-spring-boot/src/layers.xml, docker/docker-spring-boot/src/main/docker/Dockerfile, docker/docker-spring-boot/src/main/java/com/baeldung/docker/spring/DemoApplication.java, docker/docker-spring-boot/src/main/java/com/baeldung/docker/spring/HelloController.java, docker/pom.xml
- Add layers.xml configuration file
- Register the layers in the spring maven plugin
- Modify Dockerfile to copy the new internal layer
=> BAEL-4574 - Creating-Docker-Images-for-Spring-Boot-Microservices

persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/multiplebagfetchexception/Album.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/multiplebagfetchexception/Artist.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/multiplebagfetchexception/DummyEntity.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/multiplebagfetchexception/FavoriteSong.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/multiplebagfetchexception/Offer.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/multiplebagfetchexception/Playlist.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/multiplebagfetchexception/Song.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/multiplebagfetchexception/User.java, persistence-modules/java-jpa-3/src/main/resources/META-INF/persistence.xml, persistence-modules/java-jpa-3/src/test/java/com/baeldung/jpa/multiplebagfetchexception/MultipleBagFetchExceptionIntegrationTest.java
* Adds Domain Models
* Adds Integration Tests
=> [BAEL-4056] Guide to MultipleBagFetchException

spring-boot-modules/spring-boot-properties/src/main/java/com/baeldung/properties/reloading/configs/ReloadablePropertySource.java, spring-boot-modules/spring-boot-properties/src/main/resources/application.yml
JIRA: http://team.baeldung.com/browse/JAVA-3715
=> [JAVA-3715] Update articles for 2.4.0 -- spring-boot-properties

spring-boot-modules/spring-boot-crud/src/main/java/com/baeldung/crud/controllers/UserController.java, spring-boot-modules/spring-boot-crud/src/test/java/com/baeldung/crud/UserControllerUnitTest.java
**Issue**
On the [CRUD application example](https://www.baeldung.com/spring-boot-crud-thymeleaf), on `UserController` many functions are redirecting to index (redirect:/index) but the `/index` mapping does not exist.
**Solution**
* Added index mapping on *UserController*
* Refactoring the `findAll` query to make it only on index redirection
* Added unit test for new index mapping
=> Fixed Spring Boot CRUD Application example

spring-boot-modules/spring-boot-libraries/README.md, spring-boot-modules/spring-boot-libraries/src/main/java/com/baeldung/demo/DemoApplication.java, spring-boot-modules/spring-boot-libraries/src/main/java/com/baeldung/graphql/PostResolver.java, spring-boot-modules/spring-boot-libraries/src/main/resources/demo.yml, spring-boot-modules/spring-boot-libraries/src/main/resources/graphql/post.graphqls
- GraphQL schema files was missing -> added
- PostResolver contained a bug of making Author in Post optional -> fixed
- Security disabled for easier experimenting
- server port changed to 8081 for easier experimenting
- sample queries for faster results
=> GraphQL code fixes and sample queries

spring-boot-modules/spring-boot-properties/src/main/java/com/baeldung/properties/reloading/configs/ReloadablePropertySource.java
JIRA: http://team.baeldung.com/browse/JAVA-4134
=> [JAVA-4134] Fix test in spring-boot-properties

spring-boot-modules/spring-boot-properties-2/src/main/java/com/baeldung/properties/value/defaults/ValuesWithDefaultsApp.java, spring-boot-modules/spring-boot-properties-2/src/test/java/com/baeldung/properties/lists/ListsPropertiesUnitTest.java, spring-boot-modules/spring-boot-properties-2/src/test/java/com/baeldung/properties/yamllist/YamlComplexListsUnitTest.java, spring-boot-modules/spring-boot-properties-2/src/test/java/com/baeldung/properties/yamllist/YamlSimpleListUnitTest.java
JIRA: http://team.baeldung.com/browse/JAVA-3716
=> [JAVA-3716] Update articles for 2.4.0 - spring-boot-modules/spring-boot-properties2

persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/hibernateunproxy/CreditCardPayment.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/hibernateunproxy/Payment.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/hibernateunproxy/PaymentReceipt.java, persistence-modules/java-jpa-3/src/main/java/com/baeldung/jpa/hibernateunproxy/WebUser.java, persistence-modules/java-jpa-3/src/main/resources/META-INF/persistence.xml, persistence-modules/java-jpa-3/src/test/java/com/baeldung/jpa/hibernateunproxy/HibernateProxyIntegrationTest.java
* Adds Domain Models
* Adds Integration Tests
=> [BAEL-4601] How to convert a Hibernate proxy to a real entity object

spring-boot-modules/spring-boot-properties-3/src/main/resources/application.properties, spring-boot-modules/spring-boot-properties-3/src/main/resources/application.yml, spring-boot-modules/spring-boot-properties-3/src/test/java/com/baeldung/boot/properties/multidocument/IntegrationMultidocumentFilesIntegrationTest.java, spring-cloud/spring-cloud-config/client/pom.xml, spring-cloud/spring-cloud-config/pom.xml, spring-cloud/spring-cloud-config/server/pom.xml
JIRA: http://team.baeldung.com/browse/JAVA-3720
=> [JAVA-3720] Update articles for 2.4.0 - articles using spring.profiles.* properties -- part 1

spring-boot-modules/spring-boot/pom.xml, spring-security-modules/spring-security-web-boot-2/src/main/java/com/baeldung/loginredirect/LoginPageInterceptor.java
JIRA: http://team.baeldung.com/browse/JAVA-3721
=> [JAVA-3721] Update articles for 2.4.0 - modules using spring.profiles.* properties - part 2

spring-5-reactive/pom.xml, spring-5-reactive/src/main/java/com/baeldung/web/reactive/client/WebClientApplication.java, spring-5-reactive/src/main/java/com/baeldung/web/reactive/client/WebClientController.java, spring-5-reactive/src/test/java/com/baeldung/web/client/SpringContextTest.java, spring-5-reactive/src/test/java/com/baeldung/web/client/WebTestClientIntegrationTest.java
JIRA: http://team.baeldung.com/browse/JAVA-4284
=> [JAVA-4284] Fix issues in "Spring Webclient" article

spring-5-reactive/pom.xml, spring-5-reactive/src/main/java/com/baeldung/web/reactive/client/Foo.java, spring-5-reactive/src/main/java/com/baeldung/web/reactive/client/WebClientApplication.java, spring-5-reactive/src/main/java/com/baeldung/web/reactive/client/WebClientController.java, spring-5-reactive/src/test/java/com/baeldung/web/client/WebClientIntegrationTest.java
JIRA: http://team.baeldung.com/browse/JAVA-4311
=> [JAVA-4311] Improve "Spring Webclient" article

spring-web-modules/spring-resttemplate-2/src/main/java/com/baeldung/resttemplateexception/RestTemplateExceptionApplication.java, spring-web-modules/spring-resttemplate-2/src/main/java/com/baeldung/resttemplateexception/controller/ProductApi.java, spring-web-modules/spring-resttemplate-2/src/main/java/com/baeldung/resttemplateexception/model/Criterion.java, spring-web-modules/spring-resttemplate-2/src/main/java/com/baeldung/resttemplateexception/model/Product.java, spring-web-modules/spring-resttemplate-2/src/test/java/com/baeldung/resttemplateexception/RestTemplateExceptionLiveTest.java
=> BAEL-4739: Spring RestTemplate Exception

core-java-modules/core-java-collections-maps-3/src/test/java/com/baeldung/map/hashmap/loadfactor/HashMapLoadFactorUnitTest.java
[BAEL-4715] Java HashMap Load Factor
=> [BAEL-4715] Java HashMap Load Factor

pom.xml, spring-core-3/README.md, spring-core-4/README.md, spring-core-5/README.md, spring-core-5/pom.xml, spring-core-5/src/main/java/com/baeldung/component/inscope/AmbiguousBean.java, spring-core-5/src/main/java/com/baeldung/component/inscope/BeanExample.java, spring-core-5/src/main/java/com/baeldung/component/inscope/BeanImplA.java, spring-core-5/src/main/java/com/baeldung/component/inscope/BeanImplB.java, spring-core-5/src/main/java/com/baeldung/component/inscope/ComponentApplication.java, spring-core-5/src/main/java/com/baeldung/component/inscope/ComponentExample.java, spring-core-5/src/main/java/com/baeldung/component/inscope/ControllerExample.java, spring-core-5/src/main/java/com/baeldung/component/inscope/CustomComponent.java, spring-core-5/src/main/java/com/baeldung/component/inscope/CustomComponentExample.java, spring-core-5/src/main/java/com/baeldung/component/inscope/RepositoryExample.java, spring-core-5/src/main/java/com/baeldung/component/inscope/ServiceExample.java, spring-core-5/src/main/java/com/baeldung/component/outsidescope/OutsideScopeBeanExample.java, spring-core-5/src/main/java/com/baeldung/component/outsidescope/OutsideScopeExample.java, spring-core-5/src/main/java/com/baeldung/component/scannedscope/ScannedScopeExample.java, spring-core-5/src/main/resources/application.yml, spring-core-5/src/test/java/com/baeldung/component/inscope/ComponentUnitTest.java, spring-core-5/src/test/resources/application.yml
- New module (spring-core-5)
- Code examples for BAEL-4764
- Modification of other spring-core-x modules to add missing "next" links
=> Added a new module (spring-core-5) for the code examples of BAEL-4764.

spring-5-reactive/src/test/java/com/baeldung/web/client/WebClientIntegrationTest.java
JIRA: http://team.baeldung.com/browse/JAVA-4311
=> [JAVA-4311] Improve "Spring Webclient" article -- fix integration test failing on server

spring-boot-modules/spring-boot-data-2/src/main/java/com/baeldung/boot/noconverterfound/NoConverterFoundApplication.java, spring-boot-modules/spring-boot-data-2/src/main/java/com/baeldung/boot/noconverterfound/controller/StudentRestController.java, spring-boot-modules/spring-boot-data-2/src/main/java/com/baeldung/boot/noconverterfound/model/Student.java, spring-boot-modules/spring-boot-data-2/src/test/java/com/baeldung/boot/noconverterfound/NoConverterFoundIntegrationTest.java
=> BAEL-4168: No converter found for return value of type

spring-cloud/spring-cloud-openfeign/pom.xml, spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/config/FeignSupportConfig.java, spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/controller/FileController.java, spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/service/UploadClient.java, spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/service/UploadResource.java, spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/service/UploadService.java, spring-cloud/spring-cloud-openfeign/src/test/java/com/baeldung/cloud/openfeign/OpenFeignFileUploadLiveTest.java, spring-cloud/spring-cloud-openfeign/src/test/java/com/baeldung/cloud/openfeign/OpenFeignFileUploadUnitTest.java
Initial changes for Multipart file upload.
=> BAEL-3595: Initial change for Multipart file upload

spring-cloud/spring-cloud-openfeign/src/main/java/com/baeldung/cloud/openfeign/fileupload/config/FeignSupportConfig.java
=> Bael 4804 config update

spring-boot-rest/src/main/java/com/baeldung/web/config/MyCustomErrorAttributes.java, spring-boot-rest/src/main/java/com/baeldung/web/config/MyErrorController.java, spring-boot-rest/src/main/resources/application.properties
JIRA: http://team.baeldung.com/browse/JAVA-4511
=> [JAVA-4511] Update "Error Handling for REST" article

jmeter/src/test/java/com/baeldung/JmeterIntegrationTest.java
changed spacing to now use spaces instead of tabs
=> BAEL-4672 changed jmeter integration test

pom.xml
Refer to http://team.baeldung.com/browse/JAVA-4770
=> Comment out quarkus-extension

pom.xml
details- http://team.baeldung.com/browse/JAVA-4770
=> commenting broken module

core-java-modules/core-java-lang-oop-types/src/main/java/com/baeldung/classfile/Outer.java, core-java-modules/core-java-lang-oop-types/src/test/java/com/baeldung/classfile/OuterUnitTest.java
Java class file naming conventions
=> [BAEL-4208] Java compiled classes contain dollar signs

kubernetes/k8s-intro/pom.xml, kubernetes/k8s-intro/src/main/java/com/baeldung/kubernetes/intro/ApiInvoker.java, kubernetes/k8s-intro/src/main/java/com/baeldung/kubernetes/intro/AsyncHelper.java, kubernetes/k8s-intro/src/main/java/com/baeldung/kubernetes/intro/ListNodesAsync.java, kubernetes/k8s-intro/src/main/java/com/baeldung/kubernetes/intro/ListPodsPaged.java, kubernetes/k8s-intro/src/test/java/com/baeldung/kubernetes/intro/ListNodesAsyncLiveTest.java, kubernetes/k8s-intro/src/test/java/com/baeldung/kubernetes/intro/ListPodsPagedLiveTest.java, kubernetes/k8s-intro/src/test/resources/logback.xml
Article: https://drafts.baeldung.com/wp-admin/post.php?post=98368&action=edit
Jira: http://jira.baeldung.com/browse/BAEL-4849
=> [BAEL-4849] Article code

xml/src/main/java/com/baeldung/sax/SaxParserMain.java
I startet to implement an XML parser from this tutorial and ran into a problem with empty elements, e.g. `<elem></elem>`. I found this SO post (https://stackoverflow.com/questions/44570604/sax-parser-is-not-working-properly-when-xml-input-is-given-as-stream-and-some-xm) and realised, that characters(...) can be called zero or multiple times, so one should fixed it conceptually by using a StringBuffer or StringBuilder.
=> characters(...) fills StringBuilder instead of String

persistence-modules/spring-jooq/src/test/java/com/baeldung/jooq/introduction/CountQueryIntegrationTest.java
=> Bael 4798 count query

core-java-modules/core-java-streams-3/src/main/java/com/baeldung/streams/conversion/EnumerationSpliterator.java, core-java-modules/core-java-streams-3/src/main/java/com/baeldung/streams/conversion/EnumerationStreamConversion.java, core-java-modules/core-java-streams-3/src/test/java/com/baeldung/streams/conversion/EnumerationStreamConversionUnitTest.java
Convert a Java Enumeration into a Stream - BAEL-4877
=> code samples for issue BAEL-4877

core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/interrupt/CustomInterruptedException.java, core-java-modules/core-java-concurrency-basic-2/src/main/java/com/baeldung/concurrent/interrupt/InterruptExample.java, core-java-modules/core-java-concurrency-basic-2/src/test/java/com/baeldung/concurrent/interrupt/InterruptExampleUnitTest.java
[BAEL-4296] Handling InterruptedException in Java
=> [BAEL-4296] Handling InterruptedException in Java
