eugenp/tutorials

spring-all/src/main/java/org/baeldung/customannotation/CustomAnnotationConfiguration.java, spring-all/src/main/java/org/baeldung/customannotation/DataAccess.java, spring-all/src/main/java/org/baeldung/customannotation/DataAccessAnnotationProcessor.java, spring-all/src/main/java/org/baeldung/customannotation/DataAccessFieldCallback.java, spring-all/src/main/java/org/baeldung/customannotation/GenericDAO.java, spring-all/src/test/java/org/baeldung/customannotation/Account.java, spring-all/src/test/java/org/baeldung/customannotation/BeanWithGenericDAO.java, spring-all/src/test/java/org/baeldung/customannotation/DataAccessAnnotationTest.java, spring-all/src/test/java/org/baeldung/customannotation/DataAccessFieldCallbackTest.java, spring-all/src/test/java/org/baeldung/customannotation/Person.java
Initial commit for "Spring Custom Annotation with Dynamic Qualifier" article.
=> Initial commit for "Spring Custom Annotation with Dynamic Qualifier"

spring-mvc-java/pom.xml, spring-mvc-java/src/main/java/org/baeldung/aop/PerformanceAspect.java, spring-mvc-java/src/main/java/org/baeldung/dao/FooDao.java, spring-mvc-java/src/test/java/org/baeldung/aop/AopPerformanceTest.java, spring-mvc-java/src/test/java/org/baeldung/config/TestConfig.java, spring-mvc-java/src/test/resources/log4j.properties
- Use component scanning for loading bean definitions
- Use Spring stereotypes to define poincuts
=> Create example with Spring stereotype annotations

sockets/src/test/java/com/baeldung/socket/EchoMultiTest.java, sockets/src/test/java/com/baeldung/socket/EchoTest.java, sockets/src/test/java/com/baeldung/socket/GreetServerTest.java
Hey Eugen,
I think all the tests are now passing with ExecutorService, thanks for the pointers.
However, I am getting a binding exception in EchoMultiTest because am creating different clients, 1 in each test.
When I run with only one of the three tests i.e. the rest commented out, there is of course no exception.
I am not very well versed with ExecutorService, why do you think connecting to the server from different clients throws a binding exception, I was thinking that should happen when am trying to start different servers on the same port.
=> fixed failing tests

core-java-8/src/test/java/com/baeldung/functionalinterface/FunctionalInterfaceTest.java
Review fixes: added an example for Supplier lazy value generation, corrected the example with reduce function.
=> Added example for Supplier lazy generation, corrected the reduce example

autovalue-tutorial/pom.xml
Fixed configuration of compiler plugin to don't use incremental compilation to prevent build failure of *parent-modules*. Reformatted *pom.xml*.
=> Craedel autovalue tutorial/build fix

core-java-8/src/test/java/com/baeldung/encoderdecoder/EncoderDecoder.java
=> BAEL-276: Added encode-decode of url

spring-all/src/main/java/org/baeldung/taskscheduler/ThreadPoolTaskSchedulerConfig.java, spring-all/src/main/java/org/baeldung/taskscheduler/ThreadPoolTaskSchedulerExamples.java, spring-all/src/test/java/org/baeldung/taskscheduler/ThreadPoolTaskSchedulerTest.java
Introduction to spring scheduling using annotations.
One configuration class only annotation based for all needed beans.
One component ThreadPoolTaskSchedulerExamples to try and schedule all ThreadPoolTaskScheduler provided scheduling.
One Test class for running the component for some time
=> Spring scheduling beyond scheduled

spring-boot/pom.xml, spring-boot/src/main/java/com/baeldung/annotation/servletcomponentscan/JavaEEApp.java, spring-boot/src/main/java/com/baeldung/annotation/servletcomponentscan/SpringBootAnnotatedApp.java, spring-boot/src/main/java/com/baeldung/annotation/servletcomponentscan/SpringBootPlainApp.java, spring-boot/src/main/java/com/baeldung/annotation/servletcomponentscan/javaee/AttrListener.java, spring-boot/src/main/java/com/baeldung/annotation/servletcomponentscan/javaee/EchoServlet.java, spring-boot/src/main/java/com/baeldung/annotation/servletcomponentscan/javaee/HelloFilter.java, spring-boot/src/main/java/com/baeldung/annotation/servletcomponentscan/javaee/HelloServlet.java, spring-boot/src/main/java/com/baeldung/webjar/TestController.java, spring-boot/src/main/java/com/baeldung/webjar/WebjarsdemoApplication.java, spring-boot/src/main/java/org/baeldung/common/error/SpringHelloServletRegistrationBean.java, spring-boot/src/main/java/org/baeldung/common/properties/MyServletContainerCustomizationBean.java, spring-boot/src/test/java/com/baeldung/annotation/servletcomponentscan/JavaEEAppTest.java, spring-boot/src/test/java/com/baeldung/annotation/servletcomponentscan/SpringBootWithServletComponentTest.java, spring-boot/src/test/java/com/baeldung/annotation/servletcomponentscan/SpringBootWithoutServletComponentTest.java, spring-boot/src/test/java/com/baeldung/intro/AppLiveTest.java, spring-boot/src/test/java/com/baeldung/webjar/WebjarsdemoApplicationIntegrationTest.java, spring-boot/src/test/java/org/baeldung/SpringBootApplicationIntegrationTest.java, spring-boot/src/test/java/org/baeldung/SpringBootJPAIntegrationTest.java, spring-boot/src/test/java/org/baeldung/SpringBootMailIntegrationTest.java
1. add tests for #BAEL-100
2. update spring-boot version to 1.5.1.RELEASE (previously 1.4.2.RELEASE)
Major changes in the existing code:
- moved WebjarsdemoApplication and TestController to webjars package for a more clear package structure
- due to spring-boot version changes, the following import changes are made:
- according to [spring-boot-6524](https://github.com/spring-projects/spring-boot/issues/6524)
```diff
- import org.springframework.boot.context.embedded.ServletRegistrationBean;
+ import org.springframework.boot.web.servlet.ServletRegistrationBean;
```
- according to [spring-boot-6764](https://github.com/spring-projects/spring-boot/issues/6764)
```diff
- import org.springframework.boot.context.embedded.ErrorPage;
+ import org.springframework.boot.web.servlet.ErrorPage;
```
- …
=> #BAEL-100 tests and update spring boot to 1.5.1.RELEASE

mockito2/src/test/java/com/baeldung/mockito/java8/CustomAnswerWithLambdaUnitTest.java
Simplify the construction of a Stream by using the 'of()' method instead
of a 'builder'
Resolves: BAEL-632
=> refactor: Use 'of' instead of Stream 'builder'

jackson/src/test/java/com/baeldung/jackson/test/JacksonDateTest.java
Suddenly,  `1970-01-01T02:30:00.000+0000` is not a correct ISO 8601 date: it mix basic timezone format and extended date and time format.
Correct value looks like:
* `1970-01-01T02:30:00.000+00:00` (Extended format)
* `19700101T023000.000+0000` (Basic format)
=> Fix whenSerializingDateToISO8601_thenSerializedToText test

core-java/src/test/java/org/baeldung/java/io/JavaFilePathUnitTest.java
Add a unit test class to demonstrate the results of the three different methods to get filesystem path.
=> Add unit test for File path article - BAEL-827

aws/src/main/java/com/baeldung/s3/S3Application.java
Replaced manual handling of stream with apache commons FileUtils library.
=> BAEL-787 (updated) - AWS S3 with Java 

vavr/src/test/java/com/baeldung/vavr/collections/CollectionAPIUnitTest.java
=> Examples for BAEL-422

libraries/pom.xml, libraries/src/main/java/com/baeldung/mbassador/AckMessage.java, libraries/src/main/java/com/baeldung/mbassador/Message.java, libraries/src/main/java/com/baeldung/mbassador/RejectMessage.java, libraries/src/test/java/com/baeldung/mbassador/MBassadorAsyncDispatchTest.java, libraries/src/test/java/com/baeldung/mbassador/MBassadorAsyncInvocationTest.java, libraries/src/test/java/com/baeldung/mbassador/MBassadorBasicTest.java, libraries/src/test/java/com/baeldung/mbassador/MBassadorConfigurationTest.java, libraries/src/test/java/com/baeldung/mbassador/MBassadorFilterTest.java, libraries/src/test/java/com/baeldung/mbassador/MBassadorHierarchyTest.java
PR for Introduction to MBassador
=> BAEL-1018 - Introduction to MBassador

core-java/pom.xml, core-java/src/main/java/com/baeldung/numberofdigits/Benchmarking.java, core-java/src/main/java/com/baeldung/numberofdigits/NumberOfDigits.java, core-java/src/main/java/com/baeldung/numberofdigits/NumberOfDigitsDriver.java, core-java/src/test/java/com/baeldung/numberofdigits/NumberOfDigitsIntegrationTest.java
=> BAEL-1076 How to get a number of digits in an int? (Update)

libraries/src/main/java/com/baeldung/commons/io/FileMonitor.java, libraries/src/test/java/com/baeldung/commons/io/CommonsIOUnitTest.java, libraries/src/test/resources/ABC.txt, libraries/src/test/resources/aaa.txt, libraries/src/test/resources/fileTest.txt, libraries/src/test/resources/sample.txt
@kevin - Changes were made as per your request. Thanks.
=> BAEL-973 Apache Commons Commons IO

spring-cloud-cli/README.md, spring-cloud-cli/decrypt.sh, spring-cloud-cli/encrypt.sh, spring-cloud-cli/groovy.sh, spring-cloud-cli/groovy/eureka.groovy, spring-cloud-cli/groovy/restapi.groovy, spring-cloud-cli/install.sh, spring-cloud-cli/spring-cli-cmds.sh, spring-cloud-cli/yml/configserver.yml, spring-cloud-cli/yml/eureka.yml
Bash scripts, Groovy examples, etc.
=> BAEL-456: Introduction to Spring Cloud CLI - Bash Scripts

core-java/pom.xml, core-java/src/main/java/com/baeldung/javac/Positive.java, core-java/src/main/java/com/baeldung/javac/SampleJavacPlugin.java, core-java/src/main/resources/META-INF/services/com.sun.source.util.Plugin, core-java/src/test/java/com/baeldung/javac/SampleJavacPluginIntegrationTest.java, core-java/src/test/java/com/baeldung/javac/SimpleClassFile.java, core-java/src/test/java/com/baeldung/javac/SimpleFileManager.java, core-java/src/test/java/com/baeldung/javac/SimpleSourceFile.java, core-java/src/test/java/com/baeldung/javac/TestCompiler.java, core-java/src/test/java/com/baeldung/javac/TestRunner.java
* a sample Javac plugin
* a test framework for Javac plugins
* sample Javac plugin's tests
Note: a Javac plugin needs to have *JDK*'s *tools.jar*, that's why a *system* dependency to the target file was added. It assumes that *JDK* is correctly configured in the target environment. Please double-check that that doesn't cause problems in environments like *CI*.
=> BAEL-1290 Creating a Java Compiler Plugin

spring-boot/src/main/java/org/baeldung/dsrouting/ClientDatabase.java, spring-boot/src/test/java/org/baeldung/dsrouting/DataSourceRoutingTestConfiguration.java, spring-boot/src/test/java/org/baeldung/dsrouting/DataSourceRoutingTests.java
Updates example to use plainer names for client database context and changes example to use 2 contexts instead of 3.
=> rename client databases and switch from 3 to 2 of them

guava-modules/guava-18/pom.xml, guava-modules/guava-19/pom.xml, guava-modules/guava-21/pom.xml, logging-modules/log-mdc/pom.xml, logging-modules/log4j/pom.xml, logging-modules/log4j2/pom.xml, persistence-modules/java-cassandra/pom.xml, persistence-modules/java-mongodb/pom.xml, persistence-modules/liquibase/pom.xml, persistence-modules/querydsl/pom.xml, persistence-modules/redis/pom.xml, persistence-modules/solr/pom.xml, persistence-modules/spring-data-cassandra/pom.xml, persistence-modules/spring-data-gemfire/pom.xml, persistence-modules/spring-data-neo4j/pom.xml, persistence-modules/spring-data-redis/pom.xml, persistence-modules/spring-data-solr/pom.xml, persistence-modules/spring-hibernate-3/pom.xml, persistence-modules/spring-hibernate-5/pom.xml, testing-modules/groovy-spock/pom.xml, testing-modules/junit-5/pom.xml, testing-modules/mockito-2/pom.xml, testing-modules/mockito/pom.xml, testing-modules/mocks/pom.xml, testing-modules/rest-assured/pom.xml, testing-modules/rest-testing/pom.xml, testing-modules/selenium-junit-testng/pom.xml, testing-modules/testing/pom.xml, testing-modules/testng/pom.xml
since some module have been moved to sub directories other than the root directory, pom.xml config should be adjusted accordingly.
=> fix parent.relativePath config for maven submodules in separate folders

core-java-8/src/main/java/com/baeldung/findanelement/FindElementInAList.java, core-java-8/src/test/java/com/baeldung/findanelement/FindAnElementTest.java
Pull request for BAEL-1584 by ankishagarwal8@gmail.com
=> Request for BAEL-1584

spring-rest/checkstyle.xml, spring-rest/pom.xml, spring-rest/src/main/java/org/baeldung/web/controller/HeavyResourceController.java, spring-rest/src/main/java/org/baeldung/web/controller/mediatypes/CustomMediaTypeController.java
Please review this commit for BAEL-1226. I have made it similar to Findbugs.
Regards,
Shreyash
=> BAEL-1226 Checkstyle introduction.

testing-modules/mockito/pom.xml, testing-modules/mockito/src/main/java/org/baeldung/hamcrest/custommatchers/IsDivisibleBy.java, testing-modules/mockito/src/main/java/org/baeldung/hamcrest/custommatchers/IsOnlyNumbers.java, testing-modules/mockito/src/main/java/org/baeldung/hamcrest/custommatchers/IsUppercase.java, testing-modules/mockito/src/test/java/org/baeldung/hamcrest/HamcrestCustomUnitTest.java
=> BAEL-1579: Hamcrest custom matchers.

libraries/pom.xml, libraries/src/test/java/com/baeldung/jets3t/JetS3tLiveTest.java
JetS3t tests. Live Test since connection requires S3 access keys.
=> BAEL-1595 - JetS3t for S3 storage.

rxjava/src/test/java/com/baeldung/rxjava/filters/RxJavaTimeFilteringOperatorsTest.java
Added TestScheduler to TimeFiltering operators test
=> BAEL-1512 Filtering Observables in RxJava

pom.xml, spring-data-keyvalue/pom.xml, spring-data-keyvalue/src/main/java/com/baeldung/spring/data/keyvalue/Configurations.java, spring-data-keyvalue/src/main/java/com/baeldung/spring/data/keyvalue/SpringDataKeyValueApplication.java, spring-data-keyvalue/src/main/java/com/baeldung/spring/data/keyvalue/repositories/EmployeeRepository.java, spring-data-keyvalue/src/main/java/com/baeldung/spring/data/keyvalue/services/EmployeeService.java, spring-data-keyvalue/src/main/java/com/baeldung/spring/data/keyvalue/services/impl/EmployeeServicesWithKeyValueTemplate.java, spring-data-keyvalue/src/main/java/com/baeldung/spring/data/keyvalue/services/impl/EmployeeServicesWithRepository.java, spring-data-keyvalue/src/main/java/com/baeldung/spring/data/keyvalue/vo/Employee.java, spring-data-keyvalue/src/test/java/com/baeldung/spring/data/keyvalue/services/test/EmployeeServicesWithKeyValueTemplateTest.java, spring-data-keyvalue/src/test/java/com/baeldung/spring/data/keyvalue/services/test/EmployeeServicesWithRepositoryTest.java
=> code samples for spring data key value

spring-rest-simple/pom.xml, spring-rest-simple/src/main/java/org/baeldung/config/WebConfig.java, spring-rest-simple/src/main/java/org/baeldung/web/exception/NotFoundException.java, spring-rest-simple/src/main/java/org/baeldung/web/handler/RestTemplateResponseErrorHandler.java, spring-rest-simple/src/main/java/org/baeldung/web/model/Bar.java, spring-rest-simple/src/main/java/org/baeldung/web/service/BarConsumerService.java, spring-rest-simple/src/test/java/org/baeldung/web/handler/RestTemplateResponseErrorHandlerIntegrationTest.java
Here is the code for Spring RestTemplate Exception Handling mini-article.
I had to correct 2 things in the pom.xml 
a) the first one is in the codehaus cargo configuration and not related at all to my project. It was causing an error in the commit. 
b) the seond one was directly impacting my project probably because the spring-boot-test entry was old a bit so I replaced with spring-boot-starter-test. That way, I had all required test annotations working.
Finally, an error poped in the global build from the spring-rest-query-language sub-project.
=> BAEL-1764 Code update for Spring RestTemplate Exception Handling article.

spring-5-reactive/pom.xml, spring-5-reactive/src/main/java/com/baeldung/reactive/webflux/Employee.java, spring-5-reactive/src/main/java/com/baeldung/reactive/webflux/EmployeeConfig.java, spring-5-reactive/src/main/java/com/baeldung/reactive/webflux/EmployeeController.java, spring-5-reactive/src/main/java/com/baeldung/reactive/webflux/EmployeeCreationEvent.java, spring-5-reactive/src/main/java/com/baeldung/reactive/webflux/EmployeeRepository.java, spring-5-reactive/src/main/java/com/baeldung/reactive/webflux/EmployeeSpringApplication.java, spring-5-reactive/src/main/java/com/baeldung/reactive/webflux/EmployeeWebClient.java, spring-5-reactive/src/main/java/com/baeldung/reactive/webflux/EmployeeWebSecurityConfig.java, spring-5-reactive/src/main/java/com/baeldung/reactive/webflux/EmployeeWebSocketClient.java, spring-5-reactive/src/main/java/com/baeldung/reactive/webflux/EmployeeWebSocketHandler.java, spring-5-reactive/src/test/java/com/baeldung/reactive/webflux/EmployeeControllerTest.java, spring-5-reactive/src/test/java/com/baeldung/reactive/webflux/EmployeeControllerUnitTest.java
-Added files for Employee reactive application
-Updated pom.xml for Spring Security
=> BAEL-1814 Guide to Spring Webflux

spring-5-reactive/src/main/java/com/baeldung/reactive/cors/annotated/CorsOnAnnotatedElementsApplication.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/annotated/controllers/CorsOnClassController.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/annotated/controllers/CorsOnMethodsController.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/global/CorsGlobalConfigApplication.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/global/config/CorsGlobalConfiguration.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/global/controllers/FurtherCorsConfigsController.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/global/controllers/RegularRestController.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/global/functional/handlers/FunctionalHandler.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/global/functional/routers/CorsRouterFunctions.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/webfilter/CorsWebFilterApplication.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/webfilter/config/CorsWebFilterConfig.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/webfilter/controllers/FurtherCorsConfigsController.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/webfilter/controllers/RegularRestController.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/webfilter/functional/handlers/CorsWithWebFilterHandler.java, spring-5-reactive/src/main/java/com/baeldung/reactive/cors/webfilter/functional/routers/CorsWithWebFilterRouterFunctions.java, spring-5-reactive/src/test/java/com/baeldung/reactive/cors/CorsOnAnnotatedElementsLiveTest.java, spring-5-reactive/src/test/java/com/baeldung/reactive/cors/CorsOnGlobalConfigLiveTest.java, spring-5-reactive/src/test/java/com/baeldung/reactive/cors/CorsOnWebFilterLiveTest.java
* Added changes for BAEL-1922 Enable CORS in Spring Webflux
IP: http://inprogress.baeldung.com/wp-admin/post.php?post=96356&action=edit
JIRA Ticket: http://jira.baeldung.com/browse/BAEL-1922
=> [BAEL-1922] spring-5-reactive | Enable CORS in Spring Webflux 

core-java-9/pom.xml, core-java-9/src/main/java/com/baeldung/java9/language/stream/StreamsGroupingCollectionFilter.java, core-java-9/src/test/java/com/baeldung/java9/language/stream/CollectionFilterUnitTest.java, core-java-collections/pom.xml, core-java-collections/src/main/java/com/baeldung/java/filtering/CollectionUtilsCollectionFilter.java, core-java-collections/src/main/java/com/baeldung/java/filtering/EclipseCollectionsCollectionFilter.java, core-java-collections/src/main/java/com/baeldung/java/filtering/GuavaCollectionFilter.java, core-java-collections/src/main/java/com/baeldung/java/filtering/StreamsCollectionFilter.java, core-java-collections/src/test/java/com/baeldung/java/filtering/CollectionFiltersUnitTest.java
Note: _mvn clean install_ FAILS (at least locally) in module 'core-java-9' due to PMD violations, the reason seems to be that it finds test classes that doesn't match the expected pattern (*UnitTest.java, *IntegrationTest.java,... )
Jira: http://jira.baeldung.com/browse/BAEL-2026
IP: http://inprogress.baeldung.com/wp-admin/post.php?post=98524&action=edit
=> [BAEL-2026] core-java-collections core-java-9 | find all items in collection that meet a condition

core-java/README.md
the link gives 404 and is also duplicate, so it can be removed.
=> remove duplicate and broken Java UUID tutorial link

spring-5-reactive-security/src/test/java/com/baeldung/reactive/webflux/EmployeeControllerIntegrationTest.java
Hi,
it seems that `com.baeldung.reactive.webflux.EmployeeControllerIntegrationTest` in the project `spring-5-reactive-security` is red at the moment:
```
cd spring-5-reactive-security
mvn test -Dtest=EmployeeControllerIntegrationTest -Dgib.enabled=false
```
=>
```
[ERROR] Failures: 
[ERROR]   EmployeeControllerIntegrationTest.givenEmployeeId_whenGetEmployeeById_thenCorrectEmployee:46 Status expected:<200> but was:<404>
...
[ERROR]   EmployeeControllerIntegrationTest.whenGetAllEmployees_thenCorrectEmployees:71 Status expected:<200> but was:<404>
```
Changing the `classes` property of the `@SpringBootTest` should fix it:
=>
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 28.8 s - in com.baeldung.reactive.webflux.EmployeeControllerIntegrationTest
```
=> spring-5-reactive-security: fixing EmployeeControllerIntegrationTest

java-numbers/src/test/java/com/baeldung/maths/MathSinUnitTest.java
- Fix assertion error - loss of precision was happening because double was being divided by an integer
=> BAEL-9683 Fix tutorials default-first build - ref# 156

ddd/pom.xml, ddd/src/main/java/com/baeldung/ddd/PersistingDddAggregatesApplication.java, ddd/src/main/java/com/baeldung/ddd/order/Order.java, ddd/src/main/java/com/baeldung/ddd/order/OrderLine.java, ddd/src/main/java/com/baeldung/ddd/order/Product.java, ddd/src/main/java/com/baeldung/ddd/order/jpa/JpaOrder.java, ddd/src/main/java/com/baeldung/ddd/order/jpa/JpaOrderLine.java, ddd/src/main/java/com/baeldung/ddd/order/jpa/JpaOrderRepository.java, ddd/src/main/java/com/baeldung/ddd/order/jpa/JpaProduct.java, ddd/src/main/java/com/baeldung/ddd/order/mongo/OrderMongoRepository.java, ddd/src/test/java/com/baeldung/ddd/order/OrderTest.java, ddd/src/test/java/com/baeldung/ddd/order/jpa/PersistOrderIntegrationTest.java, ddd/src/test/java/com/baeldung/ddd/order/jpa/ViolateOrderBusinessRulesTest.java, ddd/src/test/java/com/baeldung/ddd/order/mongo/OrderMongoIntegrationTest.java, pom.xml
Add persisting DDD aggregates examples (BAEL-2272). I created a completely new "ddd" module, which will contain all examples from the DDD series (BAEL-2271). I'm not really sure about the profiles in the parent module and the modules organization policy, so I simply used spring-boot parent. Let me know if that's acceptable.
=> Add BAEL-2272 persisting DDD aggregates examples

core-java/src/test/java/com/baeldung/abstractclasses/LowercaseFileReaderUnitTest.java, core-java/src/test/java/com/baeldung/abstractclasses/StandardFileReaderUnitTest.java, core-java/src/test/java/com/baeldung/abstractclasses/UppercaseFileReaderUnitTest.java, core-java/src/test/java/com/baeldung/simpledateformat/SimpleDateFormatUnitTest.java
Fixed:
* SimpleDateFormatUnitTest test, which formerly relied on the system locale to format a date.
* UppercaseFileReaderUnitTest, LowercaseFileReaderUnitTest and StandardFileReaderUnitTest, which were using an approach to generate a resource path that seems to be efficient only on Windows; on Linux it raises an exception when loading the resource. The new approach should be good for all cases, but we need further testing on a Windows environment
=> [BAEL-10301] core-java | fix unit tests

spring-boot/pom.xml, spring-boot/src/main/java/com/baeldung/dynamicvalidation/ContactInfoValidator.java, spring-boot/src/main/java/com/baeldung/dynamicvalidation/DynamicValidationApp.java, spring-boot/src/main/java/com/baeldung/dynamicvalidation/dao/ContactInfoExpressionRepository.java, spring-boot/src/main/java/com/baeldung/failureanalyzer/FailureAnalyzerApplication.java, spring-boot/src/main/java/com/baeldung/internationalization/InternationalizationApp.java, spring-boot/src/main/java/com/baeldung/rss/RssApp.java, spring-boot/src/main/java/com/baeldung/toggle/ToggleApplication.java, spring-boot/src/main/java/org/baeldung/session/exception/Application.java, spring-boot/src/main/java/org/baeldung/session/exception/repository/FooRepositoryImpl.java, spring-boot/src/main/resources/application.properties, spring-boot/src/test/java/com/baeldung/annotation/servletcomponentscan/SpringBootWithServletComponentIntegrationTest.java, spring-boot/src/test/java/com/baeldung/annotation/servletcomponentscan/SpringBootWithoutServletComponentIntegrationTest.java, spring-boot/src/test/java/com/baeldung/displayallbeans/DisplayBeanIntegrationTest.java, spring-boot/src/test/java/com/baeldung/git/CommitIdIntegrationTest.java, spring-boot/src/test/java/com/baeldung/intro/AppLiveTest.java, spring-boot/src/test/java/com/baeldung/kong/KongAdminAPILiveTest.java, spring-boot/src/test/java/com/baeldung/kong/KongLoadBalanceLiveTest.java, spring-boot/src/test/java/com/baeldung/mongodb/ManualEmbeddedMongoDbIntegrationTest.java, spring-boot/src/test/resources/application.properties, spring-boot/src/test/resources/exception.properties
JIRA: http://team.baeldung.com/browse/BAEL-9524
Fixed issues due to parent-boot-2 migration of module _spring-boot_ (migration to Spring-boot 2):
* Configured Hiberante 5 correctly
* Configured Git plugin correctly
* Changed hibernate methods to comply with new method naming conventions
* Removed and replaced deprecated properties
* Updated Actuator test to use new response structure and endpoint naming restrictions
* Using random port in Mongo integration test, to avoid clashing with a potential instance using the mongo default port
* Fixed Kong LiveTests configurations, project now using context path
**Integration tests** are now passing:
**LiveTests** are now passing:
And there are **no Unit Tests** in the project
=> [BAEL-9524] spring-boot | parent-boot-1 to parent-boot-2 for spring-boot

spring-boot/src/main/resources/META-INF/spring.factories, spring-boot/src/test/java/com/baeldung/failureanalyzer/FailureAnalyzerAppIntegrationTest.java, spring-boot/src/test/java/com/baeldung/failureanalyzer/utils/ListAppender.java, spring-boot/src/test/resources/logback-test.xml
JIRA: http://team.baeldung.com/browse/BAEL-9524
FailureAnalyzer Application was not working as expected, it was not actually reporting the failure with a description and an action.
Now it does:
Plus I added a test to validate the FailureAnalyzer is being configured in the context, that the report is being carried out (being logged).
=> [BAEL-9524] spring-boot | migrating to parent-boot-2 - further fixes

spring-thymeleaf/src/main/java/com/baeldung/thymeleaf/controller/BookController.java
Studying this tutorial code I noticed that it stores the current users request for a page of results in class static variables then reads those variables to render the page. If we get two concurrent requests we could have a second request clobber the first requests passed values and render the wrong page to the first user. 
If I try to make those values local variables the compiler says that "variable used in lamba expression should be final or effectively final". Intellij then suggests making them static, which is a concurrency bug, or atomic, and it performs the refactor to use local atomic variables which touches a lot of code to both declare, set and get the atomics. 
Using `orElse` to default the value is less code and does the job. Making them final also makes it clearer that they …
=> use of static variables is concurrency problem

spring-5-reactive/src/main/java/com/baeldung/debugging/consumer/chronjobs/ChronJobs.java, spring-5-reactive/src/main/java/com/baeldung/debugging/consumer/model/Foo.java, spring-5-reactive/src/main/java/com/baeldung/debugging/consumer/model/FooDto.java, spring-5-reactive/src/main/java/com/baeldung/debugging/consumer/service/FooService.java
Added cases using subscribeOn and publishOn when debuggin reactive streams, for analysis.
Checking a sample in the logs, with `log()` included to see whats happening behing the scene:
```
13:10:54.869 [five-single-starter-15] INFO  reactor.Flux.OnAssembly.5 - | onSubscribe([Fuseable] FluxOnAssembly.OnAssemblySubscriber)
13:10:54.870 [five-single-starter-15] INFO  reactor.Flux.OnAssembly.5 - | request(256)
13:10:55.005 [parallel-2] INFO  reactor.Flux.OnAssembly.5 - | onNext(com.baeldung.debugging.consumer.model.Foo@170944f)
13:10:55.007 [five-single-foo-14] INFO  c.b.d.consumer.service.FooReporter - Reporting for approach FIVE-SINGLE: Foo with id '0' name 'theFo' and quantity '0'
13:10:55.110 [parallel-3] INFO  reactor.Flux.OnAssembly.5 - | …
```
=> BAEL-2278 | spring-5-reactive | adding cases for publishOn different threads

core-java-io/src/main/java/com/baeldung/download/FileDownload.java
The output file stream is not closed, so it is still in use by the Java process after the code runs. I noticed this when trying to delete the output files right afterwards.
=> FileOutputStream is never closed

core-java-collections/src/test/java/org/baeldung/java/lists/ListJUnitTest.java
* adding a unit test where we determine the intersection of two lists
* applying the intersection for the same two lists in the other order as well
=> BAEL-2445: adding example for the intersection of two lists

spring-security-x509/keystore/Makefile
I add a Subject alternative name (SAN) parameter in all commands. This make the generated certificate work in Google Chrome. Before that change Chrome presents a ERR_CERT_COMMON_NAME_INVALID even when you had add the certificate as a know Authority.
=> Add Subject alternative name

testing-modules/load-testing-comparison/src/main/resources/scripts/JMeter/Test Plan.jmx
Hello,
Reading https://www.baeldung.com/gatling-jmeter-grinder-comparison, I noticed issues in the JMeter plan which highly impact performances of JMeter:
- In your IfController, you have changed default settings advised by JMeter (see Red warning in UI) from Checked "Interpret Condition as Variable Expression" to Unchecked which means Javascript will be used to interpret expression leading to issue. The correct way to do it is to use Check "Interpret Condition as Variable Expression"  and use ${__jexl3(${rwdId} == 0,)} as condition
- The Loop Controller is useless
- HTTP Header Manager does not set Accept-Encoding to gzip, deflate meaning server will return unzipped responses , is this realistic
This PR fixes those issues
Regards
Philippe M.
Co-Author of book Master Apache JMeter From …
=> Fix performance issues of JMeter Test Plan

core-java-8/src/test/java/com/baeldung/collectors/Java8CollectorsUnitTest.java
Added tests with a list with duplicate elements:
* toSet -> gets added only once
* toMap -> IllegalStateException
=> toSet, toMap: adding examples with duplicates

spring-boot-libraries/src/main/java/com/baeldung/boot/problem/advice/ExceptionHandler.java, spring-boot-libraries/src/main/java/com/baeldung/boot/problem/configuration/ProblemDemoConfiguration.java, spring-boot-libraries/src/test/java/com/baeldung/boot/problem/controller/ProblemDemoControllerIntegrationTest.java
Enable stack traces and causal chain of causes. Add a couple of tests to validate stack trace and cause are included in responses.
=> BAEL-2414 Stack traces and causal chain of causes samples

core-java-8/src/test/java/com/baeldung/collectors/Java8CollectorsUnitTest.java
Updated the test with toMap and binary operator
* using the `listWithDuplicates`
* renaming the temporary variables: i1, i2 -> item, identicalItem
* renaming the test method
=> BAEL-2548 updated the test with toMap and binary operator

core-java-12/pom.xml, core-java-12/src/test/java/com/baeldung/collectors/CollectorsUnitTest.java, pom.xml
Introducing a new module named `core-java-12`, which is commented in the modules section just like other 9+ versions.
Part of Beal-2786
=> Teeing Collector

spring-cloud/spring-cloud-archaius/additional-sources-simple/src/main/java/com/baeldung/spring/cloud/archaius/additionalsources/config/ApplicationPropertiesConfigurations.java, spring-cloud/spring-cloud-archaius/additional-sources-simple/src/test/java/com/baeldung/spring/cloud/archaius/additionalsources/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-aws/src/test/java/com/baeldung/spring/cloud/aws/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-config/server/src/test/java/com/baeldung/spring/cloud/config/server/SpringContextLiveTest.java, spring-cloud/spring-cloud-eureka/pom.xml, spring-cloud/spring-cloud-eureka/spring-cloud-eureka-client/pom.xml, spring-cloud/spring-cloud-eureka/spring-cloud-eureka-client/src/test/java/com/baeldung/spring/cloud/eureka/client/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-eureka/spring-cloud-eureka-feign-client/src/test/java/com/baeldung/spring/cloud/feign/client/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-eureka/spring-cloud-eureka-server/src/test/java/com/baeldung/spring/cloud/eureka/server/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-hystrix/feign-rest-consumer/src/test/java/com/baeldung/spring/cloud/hystrix/rest/consumer/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-hystrix/rest-consumer/pom.xml, spring-cloud/spring-cloud-hystrix/rest-consumer/src/test/java/com/baeldung/spring/cloud/hystrix/rest/consumer/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-hystrix/rest-producer/pom.xml, spring-cloud/spring-cloud-hystrix/rest-producer/src/test/java/com/baeldung/spring/cloud/hystrix/rest/producer/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-zuul-eureka-integration/eureka-client/pom.xml, spring-cloud/spring-cloud-zuul-eureka-integration/eureka-client/src/test/java/com/baeldung/spring/cloud/eureka/client/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-zuul-eureka-integration/eureka-server/pom.xml, spring-cloud/spring-cloud-zuul-eureka-integration/eureka-server/src/test/java/com/baeldung/spring/cloud/eureka/server/SpringContextIntegrationTest.java, spring-cloud/spring-cloud-zuul-eureka-integration/zuul-server/pom.xml, spring-cloud/spring-cloud-zuul-eureka-integration/zuul-server/src/test/java/com/baeldung/spring/cloud/zuul/config/SpringContextIntegrationTest.java
JIRA: http://team.baeldung.com/browse/BAEL-9493
Notes:
- I used the following command to run integration tests:
`mvn clean test -P integration-lite-first,integration-lite-second,integration-heavy`
- Some Spring-Boot versions are incompatible with the Mockito version that is specified in the parent-modules pom.
Normally, we'd leave it to the spring-boot dependency to specify what version is needed, but under these circumstances, we have to declare the Mockito version 'manually', which can be a problem when we upgrade the module's spring-boot version.
Maybe we want to reconsider constraining dependencies versions in the parent-modules pom??
- I've been analyzing the other projects under spring-cloud, and **apart** from the ones that would be coverend in …
=> [BAEL-9493] Fix/Add Context Integration Tests for modules named in ticket

libraries/pom.xml
Updated pom.xml to exclude log4j binding
=> BAEL-1959 Classpath contains multiple bindings

core-groovy/src/test/groovy/com/baeldung/strings/StringMatchingSpec.groovy
PR for http://jira.baeldung.com/browse/BAEL-2771.
I've added a corresponding Spock test to `core-groovy`.
=> BAEL-2771 Add String matching example to core-groovy

persistence-modules/spring-boot-persistence/src/main/java/com/baeldung/boot/config/H2JpaConfig.java, persistence-modules/spring-boot-persistence/src/test/java/com/baeldung/SpringBootProfileIntegrationTest.java, persistence-modules/spring-boot-persistence/src/test/java/com/baeldung/config/H2TestProfileJPAConfig.java
- profile-based integ test points at profile-based JPA config
- marked two JPA config classes at class level by profile, to prevent clashes in bean names at startup
=> corrected test to pull in profile-based config, fixe app context startup

spring-batch/src/main/java/org/baeldung/batch/App.java
In production environment there is always the need to execute a single job for multiple time. In this case, if we assume that we want to persist all the job execution meta-data (do not drop and create schema again), spring-batch has a interesting behavior. It prevents the job execution if you run it with the same parameters for multiple time. If you look at the generated meta-data, you can see that the job **EXIT_CODE** is **NOOP** and the exit message is "_All steps already completed or no steps configured for this job._".
To prevent this behavior it is a good practice to add current system time as a job parameter.
=> To enable multiple execution of a job with the same parameters

pom.xml
@maibin - this is a workaround for the issue, I think. The reason the original build passed was that we'd removed the Java-9 project from the list of modules - hoping it would be resolved in a JIRA ticket later (advice from @lor6 ). I've completely that workaround with this PR.
An alternative would be to put the `maven compiler` plugin into the module build to see if it can be coerced into building in Java 9 - at the moment the module build for `java-streams-2` defines `<properties>` for the Java 9 version, but that won't be enough.
=> Disabling Java Streams 2 in integration build as in main build

parent-kotlin/pom.xml, spring-mvc-kotlin/pom.xml, spring-mvc-kotlin/src/main/kotlin/com/baeldung/kotlin/mockmvc/MockMvcController.kt, spring-mvc-kotlin/src/main/kotlin/com/baeldung/kotlin/mockmvc/MockMvcModel.kt, spring-mvc-kotlin/src/test/kotlin/com/baeldung/kotlin/mockmvc/MockMvcControllerTest.kt
* configured spring repo in the 'parent-kotlin' model
to allow using spring's milestone artifacts
* configured jackson kotlin module in the 'parent-kotlin'
to allow easy use of kotlin data classes with jackson
* switched spring-mvc-kotlin from explicit spring
dependencies to spring-boot
* mockmvc dsl article's source and tests
=> BAEL-2910 MockMvc Kotlin DSL

quarkus/src/test/java/com/baeldung/quarkus/HelloResourceUnitTest.java, quarkus/src/test/java/com/baeldung/quarkus/NativeHelloResourceIT.java
Rename unit test to follow naming standards
=> Rename unit test to follow naming standards

metrics/pom.xml, metrics/src/main/java/com/baeldung/metrics/aspectj/MetricsAspectJMain.java, metrics/src/main/java/com/baeldung/metrics/aspectj/ObjectRunner.java
PR for the article: http://jira.baeldung.com/browse/BAEL-3050
=> Adding Metrics AspectJ article code changes

java-numbers-2/src/main/java/com/baeldung/lcm/BigIntegerLCM.java, java-numbers-2/src/main/java/com/baeldung/lcm/EuclideanAlgorithm.java, java-numbers-2/src/main/java/com/baeldung/lcm/PrimeFactorizationAlgorithm.java, java-numbers-2/src/main/java/com/baeldung/lcm/SimpleAlgorithm.java, java-numbers-2/src/test/java/com/baeldung/lcm/BigIntegerLCMUnitTest.java, java-numbers-2/src/test/java/com/baeldung/lcm/EuclideanAlgorithmUnitTest.java, java-numbers-2/src/test/java/com/baeldung/lcm/PrimeFactorizationAlgorithmUnitTest.java, java-numbers-2/src/test/java/com/baeldung/lcm/SimpleAlgorithmUnitTest.java
- Add a tutorial to implement algorithms used for computing
LCM of two numbers.
- List of approaches covered:
- Simple Method
- Prime Factorization Method
- Euclidean Algorithm
- BigInteger Class
- Lambda Implementation
- Reference: [BAEL-3116](http://jira.baeldung.com/browse/BAEL-3116)
=> BAEL-3116: Finding the Least Common Multiple in Java

core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGenerator.java, core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGeneratorUsingMonitor.java, core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGeneratorUsingReentrantLock.java, core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGeneratorUsingSemaphore.java, core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGeneratorUsingSynchronizedBlock.java, core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/mutex/SequenceGeneratorUsingSynchronizedMethod.java, core-java-modules/core-java-concurrency-basic/src/test/java/com/baeldung/concurrent/mutex/MutexUnitTest.java
Updated code example and test case for the mutex
Changes:
- Removed Thread.sleep from _getNextSequence_ method. It helped reducing time of execution of tests from 15s to 1s.
- Removed throws clause from _getNextSequence_ method.
- Changed the test case to increase the number of times _getNextSequence_ called to 1000.
- Also, improved the test case as added the test case in the article, as an example.
- Commented the test which verifies the race condition. As this test fails on Jenkins because of the unpredictable nature of multithreading behavior.
=> Updated code example and test case for mutex

core-java-modules/core-java/src/main/java/com/baeldung/uuid/UUIDGenerator.java
Computation of a SHA-1 hash will generate 20 bytes. Applying this PR will drop the last 4 (they are not used for generating the UUID). This will make the assertion in the `constructType5UUID`-method pass. Fixes #7598. Also fixes a wrong message for an exception.
=> Drop last 4 bytes of computed SHA-1 hash

core-java-modules/core-java-io-2/src/test/java/com/baeldung/filereader/FileReaderExampleUnitTest.java
- Simplify the demo: 
Change in unit-tests that currently uses `close()` method instead of try-with-resource
- Reference:
-  #7677 
- [BAEL-3215](http://jira.baeldung.com/browse/BAEL-3215)
=> BAEL-3215: Use try-with-resource in FileReader demo

spring-di/src/main/java/com/baeldung/sample/AppConfig.java
After the move, the 'ComponentScan' path was set wrongly in the AppConfig class.
=> [BAEL-17697] - Fixed integration tests

core-java-modules/core-java-concurrency-basic/src/main/java/com/baeldung/concurrent/semaphore/SemaPhoreDemo.java
tryAcquire() [already acquires a permit, if one is available](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Semaphore.html#tryAcquire--) (no need to call acquire() after it)
=> SemaPhoreDemo double acquire fix

java-dates/src/main/java/com/baeldung/datetime/UseDateTimeFormatter.java, java-dates/src/main/java/com/baeldung/datetime/UseLocalDate.java, java-dates/src/main/java/com/baeldung/datetime/UseLocalDateTime.java, java-dates/src/main/java/com/baeldung/datetime/UseLocalTime.java, java-dates/src/main/java/com/baeldung/datetime/UseOffsetDateTime.java, java-dates/src/main/java/com/baeldung/datetime/UseZonedDateTime.java, java-dates/src/test/java/com/baeldung/date/DateDiffUnitTest.java, java-dates/src/test/java/com/baeldung/date/comparison/Java8DateTimeApiGeneralComparisonsUnitTest.java, java-dates/src/test/java/com/baeldung/dateapi/JavaDurationUnitTest.java, java-dates/src/test/java/com/baeldung/dateapi/JavaPeriodUnitTest.java, java-dates/src/test/java/com/baeldung/datetime/UseDateTimeFormatterUnitTest.java, java-dates/src/test/java/com/baeldung/datetime/UseLocalDateTimeUnitTest.java, java-dates/src/test/java/com/baeldung/datetime/UseLocalDateUnitTest.java, java-dates/src/test/java/com/baeldung/datetime/UseLocalTimeUnitTest.java, java-dates/src/test/java/com/baeldung/datetime/UseOffsetDateTimeUnitTest.java, java-dates/src/test/java/com/baeldung/datetime/UseToInstantUnitTest.java, java-dates/src/test/java/com/baeldung/datetime/UseZonedDateTimeUnitTest.java
[BAEL-3315] Added missing code snippets from the Java 8 Date/Time article
Also:
- formatted changed files with Eclipse profile
- corrected failing test: givenTwoDatesInJava8_whenDifferentiating_thenWeGetSix
Please note that this project is excluded from the build:
```xml
```
But here is the output from running it locally:
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.baeldung:java-dates:jar:0.1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.version' for com.darwinsys:hirondelle-date4j:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 43, column 22
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] …
```
=> [BAEL-3315] Added missing code snippets from the Java 8 Date/Time article

spring-jooq/src/test/java/com/baeldung/jooq/introduction/ExceptionTranslator.java
- Updated SQLErrorCodeSQLExceptionTranslator to use dialect.thirdParty().springDbName()
=> BAEL-18143 Fix spring-jooq issue related to dialect

spring-mvc-simple-2/src/main/resources/application.properties
Wiser was listening to port 8025 but we didn't configure the Spring Boot to use it. Anyway, adding the required `spring.mail.*` properties fixed the problem.
=> BAEL-3409: Fixed the Broken Test

spring-boot/src/main/java/org/baeldung/model/User.java, spring-boot/src/main/java/org/baeldung/repository/UserRepository.java, spring-boot/src/test/java/org/baeldung/repository/UserRepositoryIntegrationTest.java
All these integration tests are failing because of a very weird mistake. Based on the directory structure, the User model should be in the `package org.baeldung.model` package, but instead it was in the `package org.baeldung.caching.model;` package.
=> BAEL-3410: Moved the User Model to its Package

logging-modules/logback/src/test/java/com/baeldung/logback/MapAppenderIntegrationTest.java, logging-modules/logback/src/test/resources/logback-test.xml
By introducing a new logger for the broken test.
=> Fixed the Concurrent Modifications on the Root Logger

persistence-modules/spring-data-redis/pom.xml, persistence-modules/spring-data-redis/src/test/java/com/baeldung/spring/data/reactive/redis/template/RedisKeyCommandsIntegrationTest.java, persistence-modules/spring-data-redis/src/test/java/com/baeldung/spring/data/reactive/redis/template/RedisTemplateListOpsIntegrationTest.java, persistence-modules/spring-data-redis/src/test/java/com/baeldung/spring/data/reactive/redis/template/RedisTemplateValueOpsIntegrationTest.java, persistence-modules/spring-data-redis/src/test/java/com/baeldung/spring/data/redis/RedisMessageListenerIntegrationTest.java, persistence-modules/spring-data-redis/src/test/java/com/baeldung/spring/data/redis/repo/StudentRepositoryIntegrationTest.java, persistence-modules/spring-data-redis/src/test/java/org/baeldung/SpringContextIntegrationTest.java
Fixed the following issues:
- There is no such configuration as `maxheap`.
- Can't fork and parallel since we can't let 10 Redis servers to listen to the same port. 
- The context test was failing to connect to the Redis server.
- Fixed a flaky pub-sub test
=> BAEL 3275: Fix the Integrations Tests in spring-data-redis

core-java-modules/core-java-string-operations/pom.xml, core-java-modules/core-java-string-operations/src/main/java/com/baeldung/isnumeric/Benchmarking.java, core-java-modules/core-java-string-operations/src/main/java/com/baeldung/isnumeric/IsNumeric.java, core-java-modules/core-java-string-operations/src/main/java/com/baeldung/isnumeric/IsNumericDriver.java, core-java-modules/core-java-string-operations/src/test/java/com/baeldung/isnumeric/CoreJavaIsNumericUnitTest.java, core-java-modules/core-java-string-operations/src/test/java/com/baeldung/isnumeric/RegularExpressionsUnitTest.java
* Perform a null-check instead of catching NPE's
* Use pre-compiled regular expressions and perform a null-check before testing it against the regex
* Made the test usable with two modes, one using a single values and another one using a more realistic workload.
* Upgraded the commons-lang version
=> [BAEL-3518] Some changes in the is-numeric

testing-modules/testing-libraries/src/test/java/com/baeldung/calculator/CalculatorIntegrationTest.java
The glue directory was incorrect in the Cucumber calculator tests. I have removed the explicit glue directory so that it defaults to the directory containing the integration tests (which is the correct directory in this case).
I have verified that the integration tests execute by running the following Maven command:
```
mvn clean install -P integration-heavy
```
=> BAEL-3444: Fixed calculator unit tests due to incorrect Cucumber glue directory

httpclient-simple/src/main/java/com/baeldung/basic/MyBasicAuthenticationEntryPoint.java, parent-spring-5/pom.xml, spring-security-modules/spring-security-mvc-login/src/main/resources/RedirectionWebSecurityConfig.xml, spring-security-modules/spring-security-mvc-login/src/main/resources/channelWebSecurityConfig.xml, spring-security-modules/spring-security-mvc-login/src/main/resources/webSecurityConfig.xml, spring-security-modules/spring-security-mvc-login/src/main/webapp/WEB-INF/mvc-servlet.xml, spring-security-modules/spring-security-mvc-login/src/test/resources/mvc-servlet.xml, spring-security-modules/spring-security-rest-basic-auth/src/main/java/org/baeldung/basic/MyBasicAuthenticationEntryPoint.java
Jira: 
http://team.baeldung.com/browse/BAEL-19382
Notes: 
1- ethereum:
There is a LiveTest failing (and probably, an indication that the code for the article is not working as expected) due to the reason I pointed out in BAEL-9518 (we're using parent-spring-5, but we're declaring a spring-boot-starter dependency using 1.5.x version).
2- persistence-modules/spring-data-elasticsearch:
I could never get the ManualTests to pass even before updating the spring version. We could take more time to analyze how to get it running correctly and write down the indications in the Test.
3- spring-security-modules/spring-security-rest
Service is not starting:
Exception starting filter [springSecurityFilterChain]:
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named …
=> [BAEL-19382] Upgrade parent-spring-5 to the latest version of Spring 5

spring-boot-testing/src/test/java/com/baeldung/autoconfig/exclude/ExcludeAutoConfig1IntegrationTest.java, spring-boot-testing/src/test/java/com/baeldung/autoconfig/exclude/ExcludeAutoConfig2IntegrationTest.java, spring-boot-testing/src/test/java/com/baeldung/autoconfig/exclude/ExcludeAutoConfig3IntegrationTest.java, spring-boot-testing/src/test/java/com/baeldung/autoconfig/exclude/ExcludeAutoConfig4IntegrationTest.java, spring-boot-testing/src/test/java/com/baeldung/boot/autoconfig/AutoConfigIntegrationTest.java, spring-boot-testing/src/test/java/com/baeldung/testloglevel/LogbackMultiProfileTestLogLevelIntegrationTest.java, spring-boot-testing/src/test/java/com/baeldung/testloglevel/LogbackTestLogLevelIntegrationTest.java, spring-boot-testing/src/test/java/com/baeldung/testloglevel/TestLogLevelWithProfileIntegrationTest.java
These tests are failing due to two completely different reasons:
1. A few of them are failing because all of them are trying to listen to port 8080 simultaneously.  Using a random port would fix the problem.
2. Another set is failing because of sharing one TestContext between three different test classes.
=> Fix the Integrations Tests in spring-boot-testing

core-java-modules/core-java-date-operations-2/src/test/java/com/baeldung/offsetdatetime/ConvertToOffsetDateTimeUnitTest.java
_Dates are tricky!_ When someone writes something like:
```java
Date date = new Date();
```
This would assign the current date and time in _UTC_ to the current variable, despite what `toString` might say. When you write:
```java
date.setHours(6);
date.setMinutes(30);
```
Those modifications would happen based on the `TimeZone.getDefault()` timezone, not _UTC_.  As the `TimeZone.getDefault()` is usually equal to the local timezone, **observing unexpected results is expected!**
For example, In my local timezone (Which btw is `+03:30`), the date variable is representing `06:30+03:30`. Therefore, the date vairable is already adjusted to my local timezone! When converting it to `Instant`, you would get the `03:00Z`. The final offset adjustment would get us back to `06:30+03:30` again!
Based on …
=> Fixing Yet Another Date & Time Problem

core-java-modules/core-java-concurrency-advanced-2/src/main/java/com/baeldung/threadlocalrandom/ThreadLocalRandomBenchMarkRunner.java, core-java-modules/core-java-concurrency-advanced-2/src/main/java/com/baeldung/threadlocalrandom/ThreadLocalRandomBenchMarker.java
Previous benchmark was measuring initialization of thread pools and
their shutdown, not really measuring Random.nextInt() with shared Random
instance and ThreadLocalRandom.current()
Example when run with 8 threads
```
Benchmark                                                         Mode  Cnt     Score     Error   Units
ThreadLocalRandomBenchMarker.randomValuesUsingRandom             thrpt   20     9.597 ±   0.475  ops/us
ThreadLocalRandomBenchMarker.randomValuesUsingThreadLocalRandom  thrpt   20  2195.178 ± 109.579  ops/us
```
This will require to change https://www.baeldung.com/java-thread-local-random#comparing-threadlocalrandom-and-random-using-jmh
=> Update ThreadLocalRandom benchmark to show issues with contention

parent-kotlin/pom.xml
- Updating the JCenter repository url as it has now moved from http to https
=> Jcenter URL update

spring-security-modules/spring-security-mvc-boot-1/src/main/java/org/baeldung/custom/Application.java, spring-security-modules/spring-security-mvc-boot-1/src/main/java/org/baeldung/custom/config/SecurityConfig.java, spring-security-modules/spring-security-mvc-boot-1/src/main/java/org/baeldung/ip/IpApplication.java, spring-security-modules/spring-security-mvc-boot-1/src/test/java/org/baeldung/web/ApplicationLiveTest.java, spring-security-modules/spring-security-mvc-boot-1/src/test/java/org/baeldung/web/IpLiveTest.java
CSRF was messing the test, and security config for that component was missing. Added csrf().disable() (as this was set for other components in the same module). I assume there is nothing to change in the related article.
=> BAEL-3900 Fixed ApplicationLiveTest.

persistence-modules/spring-data-neo4j/src/main/java/com/baeldung/spring/data/neo4j/config/MovieDatabaseNeo4jConfiguration.java
Instead of initializing a local variable first and then return it, you could directly return a new Builder instance.
-> `return new Builder().uri(URL).build();`
=> Redundant Variable 'config'

spring-5-reactive-2/src/test/java/com/baeldung/debugging/consumer/ConsumerFooServiceIntegrationTest.java, spring-5-reactive-2/src/test/java/com/baeldung/debugging/consumer/ConsumerFooServiceLiveTest.java
The previous test was making an assertion on Logback suppressed exceptions messages. I suspect with the upgrade to Spring Boot (and Logback), these are now empty messages. Im not sure of the utility of this assertion, but I kept it and compared the exception class instead of the message.
=> BAEL-3806 Fixed integration test

spring-jenkins-pipeline/scripted-pipeline-unix-nonunix
In order to launch the application, is necessary to remove "./"
=> fix launch run command for windows

testing-modules/testing-libraries/src/test/java/com/baeldung/mutation/PalindromeUnitTest.java
One of the test cases was not as described in the test method name.
Also corrected formatting in another test case.
=> Fix palindrome unit test

ddd-modules/infrastructure/pom.xml, ddd-modules/mainapp/pom.xml, ddd-modules/ordercontext/pom.xml, ddd-modules/pom.xml, ddd-modules/sharedkernel/pom.xml, ddd-modules/shippingcontext/pom.xml, ddd/pom.xml
* Upgraded Maven Surefire Plugin version to 2.22.2
* Upgraded JUnit version to 5.6.2
* Imported JUnit BOM before Spring Boot Dependencies BOM (as explained
[here](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/maven-plugin/reference/html/#using))
=> [JAVA-1659] Upgraded Maven Surefire Plugin and JUnit versions

algorithms-sorting-2/src/main/java/com/baeldung/algorithms/quicksort/DutchNationalFlagPartioning.java
- There's an inconsistency in the variable name of the input-array
- While the code snippet in the [article's section-4.3](https://www.baeldung.com/java-sorting-arrays-with-repeated-entries#dijkstra-approach) use `input` as the variable name, on the other hand, the code present in the Github repo use `a` as the variable name
- The variable name `input` makes more sense
- [BAEL-3484](http://jira.baeldung.com/browse/BAEL-3484)
- [Dutch National Flag Problem](https://www.baeldung.com/java-sorting-arrays-with-repeated-entries#dijkstra-approach)
=> Rename array variable name in DNF Partition method

core-java-modules/core-java-9-jigsaw/src/simple-modules/main.app/com/baeldung/modules/main/MainApp.java
In the "main-app" module, the `HelloInterface` service instance, `HelloModules`, was just being treated like an ordinary class that was exported from the "hello.modules" module. The code was not treating the class as a service class. This is not a good example of how services are used.
This pull request makes use of the `ServiceLoader` class, which provides access to the `HelloInterface` instance as defined in the "hello.modules" module. This serves as a better example for how services are used.
=> Use ServiceLoader class to obtain service instance

core-java-modules/core-java-nio-2/src/main/java/com/baeldung/selector/EchoServer.java
POISON_PILL is causing writing to closed client due to logic in code.
=> Fix exception when receiving POISON_PILL

testing-modules/load-testing-comparison/src/main/resources/scripts/Gatling/GatlingScenario.scala
The Gatling results in https://www.baeldung.com/gatling-jmeter-grinder-comparison are completely broken:
* dynamic parameter injection is incorrect, always the same value is injected, causing the application to actually crash because of the duplicates
* one of the response parameter capture (check) is incorrect and should be optional
* the test includes 1 second pauses between consecutive requests. The tests with the other tools don't have them. The result is that the Gatling throughput is artificially limited.
On my local machine, I get 4100 requests executed in ~3 seconds (instead of the 31s in your article), which give an average throughput of 1025 requests/second.
Generally speaking the performance figures in the article are very suspicious:
```
  | Successful Requests | Errors | …
```
=> Fix Gatling test used for https://www.baeldung.com/gatling-jmeter-grinder-comparison

testing-modules/load-testing-comparison/src/main/resources/scripts/Gatling/GatlingScenario.scala
Motivation:
Ids are numbers (Integers), not Strings.
Modifications:
Remove wrong wrapping double quotes.
Result:
Less parsing overhead on the server side.
=> Fix JSON payloads in the Gatling script

core-java-modules/core-java-security-2/src/main/java/com/baeldung/hashing/SHACommonUtils.java
Replace StringBuffer with StringBuilder and add initial  capacity.
StringBuilder is faster because it is not synchronized.
=> Replace StringBuffer with StringBuilder and add initial capacity

core-java-modules/core-java-9-jigsaw/src/modules/com.baeldung.student.service.dbimpl/com/baeldung/student/service/dbimpl/StudentDbService.java
Fixed typos.
There are same typos in this article:
https://www.baeldung.com/project-jigsaw-java-modularity
=> Fixed typos in core-java-9-jigsaw module

spring-boot-modules/spring-boot-springdoc/pom.xml, spring-boot-modules/spring-boot-springdoc/src/main/java/com/baeldung/springdoc/controller/BookController.java
Hi Team, 
Could you please upgrade to springdoc-openapi version 1.5.2.
For the [baeldung example](https://github.com/eugenp/tutorials/tree/master/spring-boot-modules/spring-boot-springdoc), there should be no breaking change by this upgrade.
There has been a lot of enhancements since version 1.3.2 (8 months now), mainly:
- The support of  spring-hateoas
- The support of spring-data-rest
- The support of Webflux and Webmvc.fn with a new functional DSL 
- [New properties](https://springdoc.org/#properties) added to make the library more customizable.
This PR, only covers the upgrade of the version and add the `@ParameterObject` annotation, which improves the support of Pageable in the swagger-ui.
You can let me know if you need any additional information.
=> upgrade to springdoc-openapi v1.5.2

spring-boot-modules/spring-boot-properties/pom.xml
JIRA: http://team.baeldung.com/browse/JAVA-3715
cleaned up boot version override in spring-boot-properties, since the parent-boot-2 module has been updated
=> [JAVA-3715] Update articles for 2.4.0 - spring-boot-modules/spring-boot-properties -- cleanup

spring-web-modules/spring-mvc-basics-3/src/main/java/com/baeldung/exclude_urls_filter/filter/HeaderValidatorFilter.java
Jira ticket:
[BAEL-4703](http://jira.baeldung.com/browse/BAEL-4703)
Summary:
The existing article uses an out-dated way is used to excluded filtering
for certain URLs, instead, `shouldNotFilter` should be used.
=> Use shouldNotFilter to exclude URLs for a Filter

core-java-modules/core-java-10/README.md, core-java-modules/core-java-10/src/test/java/com/baeldung/java10/streams/StreamToImmutableJava10UnitTest.java
I had to change the java version to 10 to support Collectors.toUnmodifiableList()
I also added an example of using Java 9's List.copyOf() which is not mentioned in the article. My intention with this was to follow the existing pattern, where there are more cases presented in the tests than in the article itself.
Besides these is the test that is included in the article, following the pattern of the existing tests.
=> BAEL-3938: Add new section on Java 10 Collectors.toUnmodifiableList()

spring-aop/pom.xml
This POM configuration change will resolve the integration test failures.
=> BAEL-4844: Prevent building the pointcutadvice code with the ajc.

axon/pom.xml
This pull request uses Axon Framework's new [BOM](https://github.com/AxonFramework/axon-bom) file instead of direct versions.
This ensures users will always use matching versions and hence is the current recommended process when starting an Axon project.
#BAEL-4947
=> [BAEL-4947] Update "A Guide to the Axon Framework"

core-java-modules/core-java-regex/src/test/java/com/baeldung/ignore/pattern/metacharacters/IgnoringPatternMetacharactersUnitTest.java
[BAEL-4881] Created a new IgnoringPatternMetacharactersUnitTest class inside a new com.baeldung.ignore.pattern.metacharacters package.
=> BAEL-4881 - Source code for 'Understanding the Pattern.quote method' article.

core-java-modules/core-java-regex/src/test/java/com/baeldung/regex/countdigits/CountDigitsUnitTest.java, core-java-modules/core-java-regex/src/test/java/com/baeldung/regex/findnumbers/FindNumbersUnitTest.java
Commits:
1. changed all instances of assertThat(...).contains(...) to containsExactly in FindingNumbersUnitTest
2. added tests for finding integers as Longs and decimal numbers as Doubles
3. added tests for finding Scientific Notation and Hexadecimal numbers
... these were added to previous code drafts for counting digits and finding numbers
=> [BAEL-4875] 1. contains -> containsExactly, 2. get number strings as Java types, 3. Sci Not. and Hex

testing-modules/testing-assertions/src/test/java/com/baeldung/junit/log/MemoryAppender.java
The above example only works when logging a string without using string interpolation. For example the following log statement: log.debug("This is a log from {}", "David"). This would result in event.getMessage() returning "This is a log from {}" while you would like to see the processed form "This is a log from David". The getMessage().toString() only returns the former while toString() on the event will return the latter. Furthermore the toString() method is redundant on getMessage() as it already is a string.
=> Also consider string interpolation

core-java-modules/core-java-string-operations-3/src/main/java/com/baeldung/doublequotesremoval/DoubleQuotesRemovalUtils.java, core-java-modules/core-java-string-operations-3/src/test/java/com/baeldung/doublequotesremoval/DoubleQuotesRemovalUtilsUnitTest.java
Examples for the BAEL-5153 "How to Remove Beginning and Ending Double Quotes from a String in Java" tutorial.
=> examples for BAEL-5153 - remove double quotes

jhipster-5/bookstore-monolith/pom.xml, libraries-security/pom.xml, patterns/clean-architecture/pom.xml, persistence-modules/spring-data-redis/pom.xml, persistence-modules/spring-jooq/pom.xml, spring-boot-modules/pom.xml, spring-boot-modules/spring-boot-environment/pom.xml, spring-boot-modules/spring-boot-flowable/pom.xml, spring-boot-modules/spring-boot-testing/pom.xml, spring-boot-modules/spring-boot/pom.xml, spring-cloud/spring-cloud-config/client/pom.xml, spring-cloud/spring-cloud-config/server/pom.xml, spring-cloud/spring-cloud-docker/docker-message-server/pom.xml, spring-cloud/spring-cloud-docker/docker-product-server/pom.xml, spring-cloud/spring-cloud-ribbon-retry/pom.xml, spring-web-modules/spring-rest-simple/pom.xml, spring-web-modules/spring-resttemplate/pom.xml, testing-modules/spring-testing-2/pom.xml, testing-modules/spring-testing/pom.xml
1. Removing redundant junit-jupiter and junit-vintage declaration. All the Junit dependencies should be inherited from parent-modules.
2. Updating surefire version to 2.22.2 in the parent-boot-2.
=> JAVA-1664: upgrading parent-boot-2 junit and surefire configurations

core-java-modules/core-java-11-2/pom.xml, core-java-modules/core-java-14/pom.xml, core-java-modules/core-java-15/pom.xml, core-java-modules/core-java-16/pom.xml, core-java-modules/core-java-17/pom.xml, core-java-modules/core-java-concurrency-2/pom.xml, core-java-modules/core-java-jndi/pom.xml, core-java-modules/core-java-jvm-2/pom.xml, core-java-modules/core-java-jvm/pom.xml, core-java-modules/core-java-networking-3/pom.xml, core-java-modules/core-java-os/pom.xml, core-java-modules/core-java-streams-2/pom.xml, core-java-modules/core-java-string-algorithms-3/pom.xml, core-java-modules/core-java-string-conversions-2/pom.xml, core-java-modules/core-java-time-measurements/pom.xml, core-java-modules/pom.xml, guava-modules/guava-collections-list/pom.xml, guava-modules/guava-collections-map/pom.xml, guava-modules/guava-collections-set/pom.xml, guava-modules/guava-collections/pom.xml, guava-modules/guava-io/pom.xml, guava-modules/guava-utilities/pom.xml, guava-modules/pom.xml, jackson-modules/pom.xml, jackson-simple/pom.xml, java-collections-conversions-2/pom.xml, parent-java/pom.xml, testing-modules/parallel-tests-junit/math-test-functions/pom.xml, testing-modules/parallel-tests-junit/string-test-functions/pom.xml, testing-modules/testing-assertions/pom.xml
1. Removing redundant junit-jupiter and junit-vintage declaration. All the Junit dependencies should be inherited from parent-modules.
2. Updating surefire version to 2.22.2 in the parent-java.
=> JAVA-1665: updated parent-java's junit and surefire configurations

spring-boot-modules/spring-boot-environment/src/main/java/com/baeldung/prefix/PrefixController.java
use the environment to get properties to avoid exception in case property do not exists
=> fix: [ BAEL-5109 ] Environment Variable Prefixes in Spring Boot 2.5 

spring-boot-modules/spring-boot-mvc/src/main/resources/application.properties, spring-boot-modules/spring-boot-springdoc/pom.xml, spring-boot-modules/spring-boot-springdoc/src/main/resources/application.properties, spring-web-modules/spring-mvc-basics-5/src/main/java/com/baeldung/spring/web/config/WebConfig.java, spring-web-modules/spring-mvc-basics-5/src/main/resources/application.properties, spring-web-modules/spring-mvc-basics/src/main/java/com/baeldung/spring/web/config/WebConfig.java, spring-web-modules/spring-mvc-basics/src/main/resources/application.properties, spring-web-modules/spring-mvc-basics/src/test/java/com/baeldung/web/controller/EmployeeControllerContentNegotiationIntegrationTest.java
**spring-boot-mvc**
- This module uses springfox which is not yet compatible with 2.6.1 PathPatternParser until this issue is resolved. https://github.com/springfox/springfox/issues/3462
- Also, I've modified ant_path_matcher to ant-path-matcher (dashes instead of underscores). That's what the release notes says and I've verified it as well.
**spring-boot-springdoc**
- Updated spring doc version to 1.6.4 which has the fix to make it compatible with the new matcher and removed the property. 
- Article update: http://staging37.baeldung.com/spring-rest-openapi-documentation
**spring-mvc-basics**
- Fixed the resource handler pattern in WebMvcConfig and removed the property.
- Removed the usage of ContentNegotiationConfigurer.favorPathExtension which is deprecated and not compatible with …
=> JAVA:8981: verify spring.mvc.pathmatch.matching-strategy property usage

spring-boot-modules/spring-boot-swagger/src/main/java/com/baeldung/swaggerconf/SpringBootSwaggerConfApplication.java, spring-boot-modules/spring-boot-swagger/src/main/java/com/baeldung/swaggerconf/configuration/SwaggerConfiguration.java, spring-boot-modules/spring-boot-swagger/src/main/java/com/baeldung/swaggerconf/controller/ErrorControllerExcludedForAnnotation.java, spring-boot-modules/spring-boot-swagger/src/main/java/com/baeldung/swaggerconf/controller/ErrorControllerExcludedForApiIgnore.java, spring-boot-modules/spring-boot-swagger/src/main/java/com/baeldung/swaggerconf/controller/ErrorControllerExcludedForPath.java, spring-boot-modules/spring-boot-swagger/src/main/java/com/baeldung/swaggerconf/controller/RegularRestController.java, spring-boot-modules/spring-boot-swagger/src/main/java/com/baeldung/swaggerconf/excluded/ErrorControllerExcludedForPackage.java, spring-boot-modules/spring-boot-swagger/src/main/resources/application.properties, spring-boot-modules/spring-boot-swagger/src/test/java/com/baeldung/swaggerconf/SwaggerConfExcludeErrorControllerIntegrationTest.java, spring-boot-modules/spring-boot-swagger/src/test/java/com/baeldung/swaggerconf/SwaggerConfExcludeErrorControllerTest.java
Notes: 
I had to add inside the _application.properties_ this line:
`spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER`
Otherwise applications in the folder "spring-modules/spring-boot-swagger" couldn't start.
=> BAEL-5319 - Remove Basic Error Controller in Swagger

spring-boot-modules/spring-boot-testing-2/README.md, spring-boot-modules/spring-boot-testing/README.md
Moved https://www.baeldung.com/spring-junit-failed-to-load-applicationcontext to spring-boot-testing-2
=> Updated README.md on spring-boot-testing and spring-boot-testing-2

spring-state-machine/pom.xml
Update spring-statemachine-core version 1.2.3.RELEASE to 3.1.0
=> BAEL-5432: Update spring-statemachine-core version 1.2.3.RELEASE to 3.1.0

spring-state-machine/pom.xml, spring-state-machine/src/main/java/com/baeldung/spring/statemachine/config/SimpleStateMachineConfiguration.java, spring-state-machine/src/test/java/com/baeldung/spring/statemachine/StateMachineIntegrationTest.java
I have upgraded the test to Junit5 in order to use the order functionality provided by Junit5. Also upgraded the spring-test.version as SpringExtension.class required by Junit5 is present in newer versions only.
=>  JAVA-9808 Fix integration test in spring-state-machine

spring-kafka/src/main/resources/application.properties
The placeholder is mentioned in the kafkaConsumer.java but didn't defined in the applications.prop. So we need to defined that.
Current exception is as follow.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaConsumer' defined in file [/Users/mac/Library/Mobile Documents/com~apple~CloudDocs/development/kafka-poc/producer/target/classes/com/ef/kafka/embedded/KafkaConsumer.class]: Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'test.topic' in value "${test.topic}"
=> Add placeholder

testing-modules/junit5-migration/src/test/java/com/baeldung/junit5vsjunit4assertions/Junit4AssertionsUnitTest.java, testing-modules/junit5-migration/src/test/java/com/baeldung/junit5vsjunit4assertions/Junit5AssertionsUnitTest.java
- [Let's start reviewing the assertions available also in JUnit 4](https://www.baeldung.com/junit-assertions#:~:text=Let%27s%20start%20reviewing%20the%20assertions%20available%20also%20in%20JUnit%204.). Its under Junit 5 thus should be Junit **5**
- [blacklisted exception](https://www.baeldung.com/junit-assertions#:~:text=blacklisted%20exception). Is marked [deprecated](https://junit.org/junit5/docs/current/user-guide/#:~:text=7.3.-,Deprecated%20APIs,-The%20following%20table) according to Junit5 docs
- [fast-forward marker](https://www.baeldung.com/junit-assertions#:~:text=expected%20line%20is%20a-,fast%2Dforward%20marker,-.%20If%20yes%20apply). Example should be given
A valid fast-forward marker is a string that starts and ends with >> and contains at least four characters. Any character …
=> Assertions in JUnit 4 and JUnit 5 suggestions

persistence-modules/java-cassandra/src/main/java/com/baeldung/cassandra/batch/repository/ProductRepository.java, persistence-modules/java-cassandra/src/main/java/com/baeldung/cassandra/java/client/repository/KeyspaceRepository.java
* Fix naming mismatch in Javadocs and typo in `com.baeldung.cassandra.batch.repository.ProductRepository` and `com.baeldung.cassandra.java.client.repository.KeyspaceRepository` classes.
=> Fix naming of parameters in documentation

core-java-modules/core-java-streams-2/src/test/java/com/baeldung/streams/StreamAddUnitTest.java
New version works with infinite streams and has constant space/time complexity. I'm not sure if this implementation is idiomatic. Fixes the non-website aspect of #10931 (I'm not sure how/where to update the website).
=> Improve `insertInStream`

vavr-modules/vavr/src/test/java/com/baeldung/vavr/VavrUnitTest.java
Fixing bug where any value other than `3` will result in "unknown" being assigned to `output`.
https://www.baeldung.com/vavr-pattern-matching should also be updated with the same changes.
=> bug fix to avoid fallthrough

deeplearning4j/src/main/java/com/baeldung/logreg/MnistClassifier.java
The classifier started producing NaN values for the probabilities due to the neural network configuration change caused by using another version Deeplearning4j library.
In this commit, the configuration has been restored for the currently used version of the Deeplearning4j library.
=> Fix the NaN issues

spring-security-modules/spring-security-web-boot-1/pom.xml, spring-security-modules/spring-security-web-boot-1/src/main/resources/application.properties, spring-security-modules/spring-security-web-boot-1/src/test/java/com/baeldung/roles/web/ApplicationLiveTest.java
The first error was "Unable to locate the default servlet for serving static content" in the spring-security-web-boot-1 module fixed by adding the following line to the application.properties file: server.servlet.register-default-servlet=true
The second error was the failure of the specific test "givenDisabledSecurityExpression_whenGetFooByName_thenError" in the ApplicationLiveTest method named givenDisabledSecurityExpression_whenGetFooByName_thenError(). It was failing the second assertion at line 56. If you look at the console log I see the error "java.lang.RuntimeException: method hasAuthority() not allowed". This message does not seem to get passed down to the testing framework if I look at response.toString() I see the {"timestamp":1670178149282,"status":500,"error":"Internal Server …
=> Master java 15108

core-java-modules/core-java-concurrency-collections-2/src/test/java/com/baeldung/concurrenthashmap/ConcurrentHashMapUnitTest.java
You're supposed to use value provided as lambda's parameter and not fetch it yourself using `get()`
=> Fix givenOneThreadIsWriting_whenAnotherThreadWritesAtSameKey_thenWaitAndGetCorrectValue

kubernetes-modules/pom.xml
- Removed kubernete-spring from the parent pom of kubernetes-modules since it is a JDK11 module
=> JAVA-16779 Removed kubernetes-spring from the kubernetes-modules

core-java-modules/core-java-security-3/src/main/java/com/baeldung/crypto/exception/BadPaddingExamples.java
ISO10126Padding has an element of randomness, which means that the code can occasionally "fluke" a result that does not throw an exception (which causes the associated tests to fail).
I have therefore replaced it with PKCS5Padding, which will work every time.
Tested by running the tests in a loop 100000 times and it passes each time.
=> BAEL-4487 remove padding that causes non-deterministic behaviour

core-java-modules/core-java-collections-2/README.md
Currently, "prev" points to "/core-java-modules/core-java-collections-1" which is not a valid relative directory in repository.
=> Fix link to the previous article in README.md

spring-reactive-modules/spring-reactive/src/main/java/com/baeldung/reactive/webflux/annotation/EmployeeController.java
Changing endpoints visibility to `public`.
Based on email feedback:
```
I would like to point out a something interesting in the following article : https://www.baeldung.com/spring-webflux.
The access specifiers mentioned in the controller methods are private, by far the my understanding is the methods should be public instead unless there is a specific reason to. Though the example works well in normal use cases, there can be instances when the application can show unexpected behaviours. To be honest I have learned a lot of concepts from the website and I am sure this is profound name among Java developers, 
You comments are welcome in this regard, mentioning the sections and one of github file I've identified.
Sections :
https://www.baeldung.com/spring-webflux#1-single-resource …
```
=> BAEL0-1814 - Guide to Spring 5 WebFlux - quick fix

spring-boot-modules/spring-boot-testing-2/pom.xml, spring-boot-modules/spring-boot-testing-2/src/test/java/com/baeldung/redistestcontainers/service/ProductServiceDynamicPropertyManualTest.java
- Add the [junit-jupiter](https://central.sonatype.com/artifact/org.testcontainers/junit-jupiter/1.17.6) and [testcontainers-redis-junit-jupiter](https://central.sonatype.com/artifact/com.redis.testcontainers/testcontainers-redis-junit-jupiter/1.4.6) dependencies in the project’s pom.xml
- Configure the Redis container using the `@DynamicPropertySource` annotation
- Add a test to validate that the container is running and available in the test methods
- Add the test methods from `ProductServiceManualTest` file in `ProductServiceDynamicPropertyManualTest` file
- Tests are passing
[BAEL-5721](https://jira.baeldung.com/browse/BAEL-5721)
=> BAEL-5721: Configure Redis Container Using DynamicPropertySource Annotation

spring-boot-rest/src/main/java/com/baeldung/springpagination/repository/PostRepository.java
`JpaRepository` already extends `PagingAndSortingRepository` and the project uses `getOne()` from `JpaRepository`.
=> PostRepository - removing redundant interface

spring-boot-rest/pom.xml
Hi, I found that **_com.baeldung.web: spring-boot-rest: 0.0.1-SNAPSHOT_**’s pom file introduced **_145_** dependencies. However, among them, **_8_** libraries (**_6%_** have not been used by this module), the redundant dependencies are listed below.
More importantly, **_5_** redundant  libraries have not been maintained by developers for more than **_3_** years (outdated dependencies).
Reducing these unused dependencies can help prevent introducing bugs/vulnerabilities from outdated dependencies. Meanwhile, it can minimize the project size. To safely remove redundant dependencies, I constructed a complete call graph (resolved most of Java reflection and dynamic binding), and validated that they have not been used by the client code.
This PR **_com.baeldung.web: spring-boot-rest: …
=> Could com.baeldung.web: spring-boot-rest: 0.0.1-SNAPSHOT drop off redundant dependencies?

persistence-modules/hibernate-mapping/src/main/java/com/baeldung/hibernate/arraymapping/CustomIntegerArrayType.java, persistence-modules/hibernate-mapping/src/main/java/com/baeldung/hibernate/arraymapping/CustomStringArrayType.java
`a.length` causes NPE when `null` is provided as a value
=> Prevent NPE when trying to create a deep copy

core-java-modules/core-java-collections-maps/src/test/java/com/baeldung/map/ImmutableMapUnitTest.java
+ Format the code
+ Add 4 test cases
++ givenGuavaImmutableMapFromOfEntriesMethodwhenModifyEntry_thenThrowUnsupportedOperationException()
++ givenGuavaImmutableMapFromOfEntriesMethodwhenEntryKeyExists_thenThrowIllegalArgumentException()
++ givenGuavaImmutableMapFromOfEntriesMethodwhenEntryKeyIsNull_thenThrowNullPointerException()
++ givenGuavaImmutableMapFromOfEntriesMethodwhenEntryValueIsNull_thenThrowNullPointerException()
+ Remove public from the test class/methods
=> BAEL-6313: Supporting ImmutableMap.ofEntries in Guava

core-java-modules/core-java-nio-2/src/main/java/com/baeldung/selector/EchoServer.java
The scenario is reproducible by running `EchoServer` and `NioEchoLiveTest`. After the test finishes, `answerWithEcho()` will be continuously called in the loop.
=> BAEL-322 - quick fix - echo server loop

jackson-modules/jackson-conversions/src/test/java/com/baeldung/jackson/map/MapWithJsonKeyValueUnitTest.java
Sometimes the test may fail as the order of the keys can vary. The fix is to use LinkedHashMap.
[BAEL-6307](https://jira.baeldung.com/browse/BAEL-6307)
=> BAEL-6307: Use LinkedHashMap to fix order of keys during serialization

core-java-modules/core-java-io-conversions-2/src/test/java/com/baeldung/inputstreamtostring/JavaInputStreamToXUnitTest.java
little point in taking the StandardCharset.UTF_8 and trying to build a new Charset instance from it
=> simplify StandardCharsets use

core-java-modules/core-java-string-operations-5/src/main/java/com/baeldung/firstchardigit/FirstCharDigit.java, core-java-modules/core-java-string-operations-5/src/test/java/com/baeldung/firstchardigit/FirstCharDigitUnitTest.java
+ Add methods to check whether the first character of a given string is a number (Java and Guava)
+ Add a test class to test our methods
=> BAEL-6352: Check if the First Letter of a String is a Number

persistence-modules/pom.xml
This pull request removes the spring-jooq module from persistence-modules. parent-boot-2 is the parent of the spring-jooq module, which uses the JDK 8.
=> JAVA-16946: comment spring-jooq module from persistence-modules.

core-java-modules/pom.xml
To upgrade H2 version, it is necessary to remove test.mv.db from Jenkins. Therefore, unit tests shouldn't be running for core-java-lang-oop-modifiers module. After deletion, this change will be rolled back, and a .db file will be initiated.
=> JAVA-16946: disable unit test for core-java-lang-oop-modifiers module

core-java-modules/core-java-regex-2/src/test/java/com/baeldung/regex/z_regexp/ZRegularExpressionUnitTest.java
Hello,
This commit related to the article entitled "Regular Expression: \z vs \Z Anchors in Java"
=> Title: Regular Expression: \z vs \Z Anchors in Java

core-java-modules/core-java-lang-oop-patterns/src/main/java/com/baeldung/interfacesingleimpl/Animal.java, core-java-modules/core-java-lang-oop-patterns/src/main/java/com/baeldung/interfacesingleimpl/AnimalCare.java, core-java-modules/core-java-lang-oop-patterns/src/main/java/com/baeldung/interfacesingleimpl/Cat.java, core-java-modules/core-java-lang-oop-patterns/src/main/java/com/baeldung/interfacesingleimpl/Dog.java, core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/interfacesingleimpl/InterfaceSingleImplUnitTest.java, core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/interfacesingleimpl/MockAnimal.java
This PR's main goal is to explore whether to create an interface for a single implementing class in Java. By providing examples and unit tests, we aim to demonstrate the advantages and disadvantages of using interfaces in different scenarios.
This pull request introduces an Animal interface along with its implementing class Dog, a non-interface class Cat, and classes AnimalCare and CatCare that work with the respective Animal and Cat classes. A MockAnimal class is also provided for testing purposes.
**Key changes:**
1. Add `Animal` interface, `Dog` and `MockAnimal` classes
2. Add `Cat`, `AnimalCare`, and `CatCare` classes
3. Include unit tests with AssertJ
This example helps developers understand when to use interfaces for single implementing classes in their projects.
=> Add java interface single implementation examples

pom.xml, spring-reactive-modules/spring-reactor/pom.xml, spring-reactive-modules/spring-webflux-amqp/pom.xml
When I was trying to run the parent pom.xml file `mvn clean install -Pintegration-jdk9-and-above,default-jdk9-and-above
`, I realized that it was failing. It turned out two spring reactive modules had incorrect parents. Since it's small change (03a7952f93125ca9280ccf9f8106919793a80508), I fixed it in the scope of this work.
=> JAVA-20631 move Jetbrains module to *-jdk9-and-above profiles

core-java-modules/core-java-collections-maps-6/pom.xml, core-java-modules/core-java-collections-maps-6/src/test/java/com/baeldung/maptojson/MapToJsonUnitTest.java
This commit is related to the article entitled "Convert Hashmap to JSON object in Java"
=> Convert Hashmap to JSON object in Java

core-java-modules/core-java-collections-5/src/main/java/com/baeldung/arrayandlistperformance/ArrayAndArrayListPerformance.java
This commit is related to the article entitled "Array vs List Performance in Java"
=> Array vs List Performance in Java

core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/scanner/NextVsNextLineUnitTest.java
=> BAEL-6461: What's the difference between Scanner next() and nextLine() methods?

patterns-modules/cqrs-es/src/main/java/com/baeldung/patterns/es/service/UserUtility.java
As the events are geting replayed, it should recreate  the user with the ID as it is provided on the UserCreatedEvent, otherwise it will generate a new ID for each read request.
=> Event Sourcing - Recreate user with id from the UserCreatedEvent instead of creating a new one

spring-web-modules/spring-thymeleaf-attributes/accessing-session-attributes/pom.xml, spring-web-modules/spring-thymeleaf-attributes/pom.xml
Remove 'modules' from spring-thymeleaf-attributes article in the context of aligning modules name.
=> JAVA-20405 Remove 'modules' from spring-thymeleaf-attributes

javaxval-2/pom.xml, javaxval-2/src/main/java/com/baeldung/javaxval/hibernate/validator/ap/Message.java, javaxval-2/src/main/java/com/baeldung/javaxval/messageinterpolator/Person.java, javaxval-2/src/main/java/com/baeldung/javaxval/methodvalidation/constraints/ConsistentDateParameterValidator.java, javaxval-2/src/main/java/com/baeldung/javaxval/methodvalidation/constraints/ConsistentDateParameters.java, javaxval-2/src/main/java/com/baeldung/javaxval/methodvalidation/constraints/ValidReservation.java, javaxval-2/src/main/java/com/baeldung/javaxval/methodvalidation/constraints/ValidReservationValidator.java, javaxval-2/src/main/java/com/baeldung/javaxval/methodvalidation/model/Customer.java, javaxval-2/src/main/java/com/baeldung/javaxval/methodvalidation/model/Reservation.java, javaxval-2/src/main/java/com/baeldung/javaxval/methodvalidation/model/ReservationManagement.java, javaxval-2/src/main/java/com/baeldung/javaxval/notnull/NotNullMethodParameter.java, javaxval-2/src/main/java/com/baeldung/javaxval/notnull/ValidatingComponent.java, javaxval-2/src/test/java/com/baeldung/javaxval/messageinterpolator/ParameterMessageInterpolaterIntegrationTest.java, javaxval-2/src/test/java/com/baeldung/javaxval/methodvalidation/ContainerValidationIntegrationTest.java, javaxval-2/src/test/java/com/baeldung/javaxval/methodvalidation/ValidationIntegrationTest.java, javaxval-2/src/test/java/com/baeldung/javaxval/notnull/ValidatingComponentIntegrationTest.java
Upgraded spring-boot and removed hybernate-validator explicit dependency to use 8.0.0.Final version of the spring-boot 3 transitive dependency. Changed javax with jakarta.
=> JAVA-22499 | Using Hibernate Validator 8.0.0.Final

core-java-modules/core-java-arrays-convert/src/test/java/com/baeldung/array/conversions/PrimitiveIntArrayToHashSetUnitTest.java
- Add multiple approaches to convert an int[] Array to HashSet<Integer>
[BAEL-6831](https://jira.baeldung.com/browse/BAEL-6831)
=> BAEL-6831: Convert an int[] Array to HashSet in Java

web-modules/javax-servlets-2/src/test/java/com/baeldung/setparam/LanguageServletLiveTest.java, web-modules/javax-servlets-2/src/test/java/com/baeldung/setparam/SanitizeParametersRequestLiveTest.java, web-modules/javax-servlets-2/src/test/java/com/baeldung/setparam/SanitizeParametersRequestWrapperUnitTest.java, web-modules/javax-servlets-2/src/test/java/com/baeldung/setparam/SetParameterRequestWrapperUnitTest.java, web-modules/javax-servlets-2/src/test/java/com/baeldung/setparam/UnsanitizedParametersRequestLiveTest.java
=> BAEL-6848: Set a Parameter in a HttpServletRequest in Java

.github/ISSUE_TEMPLATE/issue_report.md, CONTRIBUTING.md
This includes:
* A `CONTRIBUTING.md` file with guidelines on how to open issues.
* A `.github/ISSUE_TEMPLATE/issue_report.md` file that will appear as a template option when opening new issues.
=> JAVA-25303 Create contribution guidelines for tutorials repository

xml-2/src/test/java/com/baeldung/xml/xml2document/XMLStringToDocumentObjectUnitTest.java
This commit aims to add a test class "XMLStringToDocumentObjectUnitTest.java" that provides a test method to convert XML string into a Document object in Java.
=> This commit is related to the article BAEL-7084

core-java-modules/core-java-lang-6/src/main/java/com/baeldung/stopexecution/InterruptThread.java
Based on a comment:
Section 6 should be headlined with “Using System.exit()” since that’s what stops code execution, not the boolean variable (this is just a means to decide that execution should be stopped, like the negative array element in section 4.
Also it’s unclear why we’d need the “if (isInterrupted())” statement in the while loop of the 8th section: how should isInterrupted() be true one line after we’ve checked in the while loop header that it’s false? Admittedly there’s a little chance that the interrupt status changed between these 2 lines, but this if statement would make much more sense somewhere in the business logic code where more time has passed since the evaluation of “while (!isInterrupted())”… and if that business code doesn’t have that complexity/length, one should …
=> BAEL-6481 - Remove `isInterrupted()` check

persistence-modules/spring-boot-persistence-mongodb-3/src/test/java/com/baeldung/boot/hashmap/MongoDbHashMapLiveTest.java
Prevent integration tests from failing after Spring Boot upgrade.
* drop collection after each test;
* change multiple collection names to a single one;
* static `COLLECTION_NAME`;
* specifying specific class in `@SpringBootTest`.
=> MongoDbHashMapIntegrationTest - Changing to LiveTest

core-java-modules/core-java-datetime-conversion/src/test/java/com/baeldung/timestamptolocaldatetime/TimeToLocalDateTimeUnitTest.java
This PR adds a new test class "TimeToLocalDateTimeUnitTest" that shows how to convert a long timestamp into a LocalDateTime object.
=> This PR is related to the article BAEL-7232

core-java-modules/core-java-concurrency-advanced-5/src/main/java/com/baeldung/wait_synchronization/ConditionChecker.java
Changing `Boolean` to primitive.
Based on a comment.
=> BAEL-7022 Why wait must be called in a synchronized block - quick fix

spring-security-modules/spring-security-core/pom.xml, spring-security-modules/spring-security-core/src/main/java/com/baeldung/app/App.java, spring-security-modules/spring-security-core/src/main/java/com/baeldung/app/auditing/ExposeAttemptedPathAuthorizationAuditListener.java, spring-security-modules/spring-security-core/src/main/java/com/baeldung/app/config/WebSecurityConfig.java, spring-security-modules/spring-security-core/src/main/java/com/baeldung/app/controller/TaskController.java, spring-security-modules/spring-security-core/src/main/java/com/baeldung/app/entity/Task.java, spring-security-modules/spring-security-core/src/main/java/com/baeldung/app/filter/CustomFilter.java, spring-security-modules/spring-security-core/src/main/java/com/baeldung/checkrolejava/UserController.java, spring-security-modules/spring-security-core/src/main/java/com/baeldung/denyonmissing/CustomPermissionAllowedMethodSecurityMetadataSource.java, spring-security-modules/spring-security-core/src/main/java/com/baeldung/filterresponse/config/AppConfig.java, spring-security-modules/spring-security-core/src/main/java/com/baeldung/methodsecurity/service/UserRoleService.java, spring-security-modules/spring-security-core/src/test/java/com/baeldung/denyonmissing/DenyOnMissingControllerIntegrationTest.java, spring-security-modules/spring-security-core/src/test/java/com/baeldung/filterresponse/SpringSecurityJsonViewIntegrationTest.java
Made changes to upgrade to Boot 3.
Changed Parent POM as spring-security-modules is using spring boot 2 and a lot of other modules depend on it.  
ExpectedException is also now deprecated using Junit 5 based assertions to do the same.
=> 29171 - Upgrade spring-security-core to Spring Boot 3

core-java-modules/core-java-8-datetime-2/src/test/java/com/baeldung/zoneoffsetandzoneidof/ZoneOffSetAndZoneIdOfUnitTest.java
Difference between ZoneOffset.UTC and ZoneId.of("UTC")
=> baeldung-articles : BAEL - 6592

spring-cloud-modules/spring-cloud-eureka/spring-cloud-eureka-client-profiles/pom.xml, spring-cloud-modules/spring-cloud-eureka/spring-cloud-eureka-client/pom.xml, spring-cloud-modules/spring-cloud-eureka/spring-cloud-eureka-feign-client-integration-test/pom.xml, spring-cloud-modules/spring-cloud-eureka/spring-cloud-eureka-feign-client/pom.xml, spring-cloud-modules/spring-cloud-eureka/spring-cloud-eureka-server/pom.xml
Parent pom names were misplaced hence there was an error while starting Eureka.
=> JAVA-31205 :- Fix parent pom names.

core-groovy-modules/core-groovy-2/pom.xml, core-java-modules/core-java-jpms/service-loader-api-pattern/pom.xml, core-java-modules/core-java-jpms/service-provider-factory-pattern/pom.xml, ethereum/pom.xml, image-compressing/pom.xml, java-panama/pom.xml, jhipster-modules/jhipster-uaa/gateway/pom.xml, jhipster-modules/jhipster-uaa/quotes/pom.xml, jhipster-modules/jhipster-uaa/uaa/pom.xml, kubernetes-modules/k8s-intro/pom.xml, kubernetes-modules/k8s-java-heap-dump/pom.xml, maven-modules/compiler-plugin-java-9/pom.xml, maven-modules/multimodulemavenproject/pom.xml, microservices-modules/micronaut/pom.xml, patterns-modules/ddd-contexts/pom.xml, performance-tests/pom.xml, persistence-modules/jnosql/jnosql-artemis/pom.xml, persistence-modules/sirix/pom.xml, persistence-modules/spring-data-cassandra-2/pom.xml, quarkus-modules/quarkus-funqy/pom.xml, quarkus-modules/quarkus-virtual-threads/pom.xml, quarkus-modules/quarkus-vs-springboot/quarkus-project/pom.xml, spring-roo/pom.xml, spring-swagger-codegen/spring-openapi-generator-api-client/pom.xml, testing-modules/testng-command-line/pom.xml, web-modules/jooby/pom.xml, web-modules/ninja/pom.xml
Updates maven-compiler-plugin version for all modules specifying a version earlier than the latest (3.12.1 at time of PR).
=> JAVA-31644 Update maven-compiler-plugin to 3.12.1

spring-activiti/pom.xml, spring-activiti/src/main/java/com/baeldung/activiti/security/config/MvcConfig.java, spring-activiti/src/main/java/com/baeldung/activiti/security/withspring/SecurityConfig.java, spring-activiti/src/main/resources/templates/homepage.html
Upgrades the module to Spring Boot 3 including updating now deprecated Spring Security code.
Also adds homepage.html so that the example security application takes you somewhere after logging in to improve the example.
Uses Activiti 8.0.0 as later versions seem incompatible with Java 17.
=> JAVA-28947 Update Spring Activiti module to Spring Boot 3

testing-modules/spring-testing/pom.xml
This will work when the parent pom is reverted to Boot 3.2.2 as one of the tests needs features present in Spring Core 6.1X which doesnt come with Boot 3.15.
=> JAVA-31814 :- Make sure all tests pass with Spring boot 3.2.2

spring-boot-modules/spring-boot-keycloak/src/main/java/com/baeldung/keycloak/SecurityConfig.java
If anyone uses frontend to call the request with access token, the browsers will first try to send the OPTIONS preflight request. This update will allow them to get the 200 response and continue with actual request.
=> [Spring-Boot-Keycloak example] Allows preflight requests from browser

core-java-modules/core-java-string-operations-8/pom.xml, core-java-modules/core-java-string-operations-8/src/test/java/com/baeldung/EOLNormalizer/EOLNormalizerUnitTest.java
Normalizing the EOL Character in Java
=> baeldung-articles : BAEL-6402

persistence-modules/hibernate-jpa/src/main/java/com/baeldung/hibernate/struct/entities/StructDepartment.java, persistence-modules/hibernate-jpa/src/main/java/com/baeldung/hibernate/struct/entities/StructManager.java, persistence-modules/hibernate-jpa/src/test/java/com/baeldung/hibernate/struct/HibernateStructUnitTest.java, persistence-modules/hibernate-jpa/src/test/resources/hibernate-derby.properties
StructDepartment.java
StructManager.java - (contains the @Struct annotation which is the annotation the ticket is about. HibernateStructUnitTest.java - Struct unit test class. No unit test present because the hibernate dialect: org.hibernate.dialect.DerbyDialect does not support the @Struct annotation despite the fact that Apache Derby has support for CREATE TYPE (https://db.apache.org/derby/docs/10.17/ref/rrefsqljcreatetype.html) ddls. hibernate-derby.properties - properties file, just for reference, not being used in unit tests.
=> Code added for ticket: BAEL-7621

gradle-modules/gradle-5/cmd-line-args/src/main/java/com/baeldung/cmd/MainClass.java, pom.xml
This version is not the latest, but the last one that doesn't introduce breaking changes.
=> JAVA-31765: Upgrade gitflow-incremental-builder to version 4.5.3

azure/pom.xml, azure/src/main/java/com/baeldung/springboot/azure/User.java
The addition of the javax.xml.bind dependency isn't strictly necessary but means we get useful error messages if we provide an invalid Azure username/password
=> JAVA-27821 Upgrade Azure to Spring Boot 3

libraries-data/pom.xml
Have to upgrade Ignite to make it work with JDK 21. Checked by using JDK 21 SDK and setting maven version for JDK to 21. But for now set it to 17 to be compatible.
=> JAVA-28831 :- Fix libraries data for JDK 21.

core-java-modules/core-java-collections-list-6/src/main/java/com/baeldung/sublistindexoutofboundsexception/SubListUtils.java, core-java-modules/core-java-collections-list-6/src/test/java/com/baeldung/sublistindexoutofboundsexception/SubListIndexOutOfBoundsExceptionUnitTest.java
+ Create a safe alternative of subList method to avoid IndexOutOfBoundsException
=> BAEL-6333: Avoiding the IndexOutOfBoundsException in subList in Java

core-java-modules/core-java-datetime-conversion-2/src/test/java/com/baeldung/unsupportedtemporaltypeexception/UnsupportedTemporalTypeExceptionUnitTest.java
+ Add test cases to illustrate how to reproduce and fix _UnsupportedTemporalTypeException: Unsupported field: InstantSeconds_
=> BAEL-7999: How to fix UnsupportedTemporalTypeException: Unsupported field: InstantSeconds

maven-modules/dependency-ordering/pom.xml, maven-modules/dependency-ordering/src/test/java/com/baeldung/dependency/ordering/DependencyOrderingUnitTest.java, maven-modules/pom.xml
- add module with Apache POI and OpenCSV dependencies that use different versions of Apache Commons Collections
- add test that fails in case the order of those dependencies is changed
=> [BAEL-6373] Why the Order of Maven Dependencies is Important

lombok-modules/lombok/src/main/java/com/baeldung/lombok/builder/ClassWithExcludedFields.java, lombok-modules/lombok/src/test/java/com/baeldung/lombok/builder/BuilderUnitTest.java
+ Add a new class _ClassWithExcludedFields_
+ Add test cases to showcase how to exclude fields from Lombok builder
=> Bael 8138: Exclude Property from Lombok @Builder Annotation

core-java-modules/core-java-arrays-guides/src/test/java/com/baeldung/nullandemptyarray/NullAndEmptyArrayTests.java, core-java-modules/core-java-arrays-guides/src/test/java/com/baeldung/nullandemptyarray/NullAndEmptyArrayUnitTests.java
Hey David Martinez,
I have created a new pull request due to some difficulties with the previous one. The previous PR had issues that were compounded by my current computer's performance, so I decided to start fresh. Here are the key changes and updates:
Moved the code from the `core-java-numbers-8` module to the `core-java-arrays-guides` module as per your feedback.
Reverted the `pom.xml` file to its original state to remove any unnecessary modifications.
Removed the `EmptyArray` and `NullArray` classes which were not needed. 
Added a new test file in the `core-java-arrays-guides` module.
Please review the changes and let me know if there is anything else that needs to be updated.
Thanks,
Philip Nyankena
=> Move code to core-java-arrays-guides module and add tests for null and empty arrays

testing-modules/selenium-2/pom.xml, testing-modules/selenium-2/src/test/java/com/baeldung/selenium/generatePDF/GeneratePDFsUnitTests.java, testing-modules/selenium-2/src/test/java/com/baeldung/selenium/generatepdf/GeneratePDFsUnitTests.java
1. Added `GeneratePDFsUnitTests.java` to demonstrate PDF generation using the` print()` method in Selenium, including customization options with PrintOptions.
2. Updated` pom.xml` to include the necessary dependencies for Selenium and WebDriverManager.
Draft:  [How to Generate PDF With Selenium](https://drafts.baeldung.com/?p=211550&preview=true)
=> Add PDF Generation Unit Tests and Update Dependencies

libraries-io/src/test/java/com/baeldung/java/io/JavaDirectoryDeleteUnitTest.java
`File.walk` is a common source of memory leaks in my corporate job.  So much so that it has caused outages a few times now.
```
The returned stream encapsulates one or more DirectoryStreams. If timely disposal of file system resources is required, the try-with-resources construct should be used to ensure that the stream's close method is invoked after the stream operations are completed. Operating on a closed stream will result in an IllegalStateException.
```
[source](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#walk-java.nio.file.Path-java.nio.file.FileVisitOption...-)
Ideally you'd update your article too 😅 I suspect that is where most folks are going to grab this code.
I realize this is just a unit-test, so who cares but realistically your example will be used in …
=> Update JavaDirectoryDeleteUnitTest.java 

core-java-modules/core-java-string-operations-10/README.md, core-java-modules/core-java-string-operations-10/src/main/java/com/baeldung/insertnewlineinstringbuilder/NewlineUsingFormat.java, core-java-modules/core-java-string-operations-10/src/main/java/com/baeldung/insertnewlineinstringbuilder/NewlineUsingLineSeparator.java, core-java-modules/core-java-string-operations-10/src/main/java/com/baeldung/insertnewlineinstringbuilder/NewlineUsingN.java, core-java-modules/core-java-string-operations-10/src/main/java/com/baeldung/insertnewlineinstringbuilder/NewlineUsingProperty.java, core-java-modules/core-java-string-operations-10/src/main/java/com/baeldung/insertnewlineinstringbuilder/StringBuilderHelper.java, core-java-modules/core-java-string-operations-10/src/test/java/com/baeldung/insertnewlineinstringbuilder/NewlineUsingFormatTest.java, core-java-modules/core-java-string-operations-10/src/test/java/com/baeldung/insertnewlineinstringbuilder/NewlineUsingLineSeparatorTest.java, core-java-modules/core-java-string-operations-10/src/test/java/com/baeldung/insertnewlineinstringbuilder/NewlineUsingNTest.java, core-java-modules/core-java-string-operations-10/src/test/java/com/baeldung/insertnewlineinstringbuilder/NewlineUsingPropertyTest.java, core-java-modules/core-java-string-operations-10/src/test/java/com/baeldung/insertnewlineinstringbuilder/StringBuilderHelperTest.java
**Key Updates:**
- **Handling Platform-Dependent Newlines:** Explored various methods to manage newlines across different operating systems.
- **Platform-Independent Solutions:** Demonstrated using System.lineSeparator(), System.getProperty("line.separator"), and String.format("%n").
- **Helper Class:** Introduced StringBuilderHelper for simplified newline management and method chaining.
- **Testing:** Verified newline handling and functionality with relevant test cases.
=> How to append a newline to stringbuilder

persistence-modules/hibernate-annotations-2/src/main/java/com/baeldung/hibernate/mapsid/Address.java, persistence-modules/hibernate-annotations-2/src/main/java/com/baeldung/hibernate/mapsid/HibernateConfigUtils.java, persistence-modules/hibernate-annotations-2/src/main/java/com/baeldung/hibernate/mapsid/Person.java, persistence-modules/hibernate-annotations-2/src/test/java/com/baeldung/hibernate/mapsid/MapsIdAnnotationIntegrationTest.java
+ Add two Hibernate entities: _Person_ and _Address_
+ Add a test case to showcase how _@MapsId_ helps to implement shared primary key mapping
=> BAEL-8470: @MapsId Annotation in Hibernate

parent-boot-2/pom.xml, testing-modules/spring-testing-2/src/test/resources/application-hsql.properties
* Switched the database configuration to use an in-memory HSQLDB instance instead of creating a file-based database. This change addresses permission issues encountered during CI/CD, where file creation rights were not permitted.
=> BAEL-8160-Fix: Use in-memory HSQLDB to avoid file creation issues in CI/CD

reactor-core-2/src/test/java/com/baeldung/reactor/fromcallable/justempty/FromCallableJustEmptyUnitTest.java
1) Add Test Cases for fromCallable use cases.
2) Add Test Cases for justOrEmpty use cases.
=> BAEL-7538 - Mono.fromCallable vs Mono.justOrEmpty in Spring Reactive

text-processing-libraries-modules/pdf/src/test/java/com/baeldung/addheaderfooterpdf/AddHeaderFooterToPDFUnitTest.java, text-processing-libraries-modules/pdf/src/test/java/com/baeldung/pdfreadertest/ReadPdfFileUnitTest.java
AddHeaderFooterToPDFUnitTest - added @Order annotation to enforce tests to run in the specific order.
ReadPdfFileUnitTest- added Line separator to make this a platform independent.
=> Fixed test added anotation and line seperator

spring-ai-2/pom.xml, spring-ai-2/src/main/java/com/baeldung/spring/ai/om/OrderManagementAIAssistant.java, spring-ai-2/src/main/java/com/baeldung/spring/ai/om/OrderManagementApplication.java, spring-ai-2/src/main/java/com/baeldung/springai/chromadb/Application.java, spring-ai-2/src/main/java/com/baeldung/springai/huggingface/Application.java, spring-ai-2/src/main/resources/application-aiassistant.properties, spring-ai-2/src/test/java/com/baeldung/spring/ai/om/AiOrderManagementLiveTest.java, spring-ai-2/src/test/java/com/baeldung/springai/chromadb/SemanticSearchLiveTest.java, spring-ai-2/src/test/java/com/baeldung/springai/evaluator/LLMResponseEvaluatorLiveTest.java
This PR upgrades `spring-ai` to the latest `1.0.0-M6` version in the `spring-ai-2` module.
It fixes the compilation and startup failures.
Only the methods removed in the latest version are replaced by their counterparts, the methods/classes that are deprecated but are still present in the library have not been replaced.
=> upgrade/spring-ai-version/module/spring-ai-2 [BAEL-9132]

core-java-modules/core-java-concurrency-advanced-6/src/main/java/com/baeldung/atomic/AtomicLoadBalancer.java
Quote:
```
I believe there is a mistake in the code in Section 6 of the article https://www.baeldung.com/java-atomicinteger-load-balancer
Specifically, the current code is:
public String getServer() {
int index = counter.get() % serverList.size();
counter.incrementAndGet();
return serverList.get(index);
}
But I believe the correct code should be:
public String getServer() {
int index = counter.getAndIncrement() % serverList.size();
return serverList.get(index);
}
In the current code of the article, several threads could be calling getServer() at the same time, execute counter.get() in sequence, all get the same server number (index), before each incrementing the counter. This would mean one server gets more uses, and other servers are skipped, breaking a fair round-robin strategy.
```
=> bael-8622 getAndIncrement - fix based on email feedback

core-java-modules/core-java-streams-7/README.md, core-java-modules/core-java-streams-7/pom.xml, core-java-modules/core-java-streams-7/src/main/java/com/baeldung/streams/NestedLoopsToStreamsConverter.java, core-java-modules/core-java-streams-7/src/test/java/com/baeldung/streams/NestedLoopsToStreamsConverterUnitTest.java, core-java-modules/pom.xml
BAEL-9176 Code and Unit Tests for Converting Nested Loops to Streams in Java
- Added a new streams-7 module.
- Implements the solution showcasing three use-cases: looping through all the elements, lopping through elements and using a filter, looping through elements and short-circuiting.
- Provides unit tests for each of the implemented use-cases.
=> BAEL-9176 Code and Unit Tests for Converting Nested Loops to Streams in Java

core-java-modules/core-java-reflection-2/src/test/java/com/baeldung/reflection/access/privatemethods/InvokePrivateMethodsUnitTest.java
Based on email feedback:
Good evening,
I just noticed a discrepancy between two of your articles. In https://www.baeldung.com/java-call-private-method, section 3.3 states that to call a static method using reflection, one needs to pass the reference to the class object as the first parameter to the Method.invoke() method. In https://www.baeldung.com/java-invoke-static-method-reflection however, section 3 states that under the same circumstances one needs to pass a null to the same method. This likely means that the first parameter of this method call is ignored for static methods in the current JRE implementation.
However, according to a note in the article on Oracle web site https://docs.oracle.com/javase/tutorial/reflect/member/methodInvocation.html the first parameter should be null. …
=> bael-4384 - passing null instead of class

spring-boot-modules/spring-boot-keycloak/README.md, spring-boot-modules/spring-boot-keycloak/spring-boot-resource-server/src/main/java/com/baeldung/boot/keycloak/resourceserver/SecurityConfig.java
The article says this:
```
Because of generics type erasure in the JVM and because there could be many Converter beans with different inputs and outputs in an application context, this AuthoritiesConverter interface can be a useful tip for the bean factory when it searches for a Converter<Map<String, Object>, Collection<GrantedAuthority>> bean.
```
Then it never uses the interface for the authenticationConverter.
=> Have authenticationConverter use the interface AuthoritiesConverter

json-modules/json-2/src/main/java/com/baeldung/jsongetvaluewithkeyset/JSONGetValueWithKeySet.java, json-modules/json-2/src/test/java/com/baeldung/jsongetvaluewithkeyset/JSONGetValueWithKeySetUnitTest.java
BAEL-9249 Code and Unit Tests for Extracting Keys from a JSONObject Using keySet()
- Implements the solution showcasing two scenarios: 
extracting keys from a flat json and from a nested json object.
- Provides unit tests for each of the implemented scenarios.
=> BAEL-9249 Code and Unit Tests for Extracting Keys from a JSONObject Using keySet()

maven-modules/maven-custom-plugin/counter-maven-plugin/pom.xml
Since https://issues.apache.org/jira/browse/MPLUGIN-467 a dedicated plugin has to be used for report generation.
The previous setup here was already failing, but maybe it was not noticed because CI does not run `mvn site` for it?
> [!IMPORTANT]\
> The code snippets on https://www.baeldung.com/maven-plugin#documentation have to be updated as well.
=> Fix report generation for custom Maven plugin

libraries-testing-2/pom.xml, libraries-testing-2/src/main/java/com/baeldung/vmlens/AtomicBankAccount.java, libraries-testing-2/src/main/java/com/baeldung/vmlens/RegularFieldBankAccount.java, libraries-testing-2/src/main/java/com/baeldung/vmlens/VolatileFieldBankAccount.java, libraries-testing-2/src/test/java/com/baeldung/vmlens/BankAccountTest.java
This is the example code for the blog article Unit Tests for Concurrent Java with VMLens
=> examples for the blog article Unit Tests for Concurrent Java with VMLens
